### ISSUE TITLE
Crashes on Server Startup

### ISSUE THREAD

**Issue by Saincrad95** [qouteall/ImmersivePortalsMod#10]
I tried adding this mod and crashes with a class not found exception for version 0.6 and 0.7.
Will link logs for both.

https://drive.google.com/open?id=13ieRMsrmL9B-8zhOtIt36DGo20OfU_vr

Thanks for the help

**Comment by qouteall** [comment]
test 0.8 version and see whether this issue still exist

**Comment by Saincrad95** [comment]
Ver 0.8 works on both server and client side thanks.
Next issue would be the a crash with optifine when that chunk is loaded.
The Crash-Log in the the initial google drive link.
Other than that I played it without shaders for a bit and loved the mod
