### ISSUE TITLE
all issues seen so far with iris, major and minor

### ISSUE THREAD

**Issue by Redd56** [qouteall/ImmersivePortalsMod#1004]
level of severity  |     what the issue is, explanation and what happens  |     equipment (hardware) and tested versions    
major or minor   |                                                                                    |    my hardware: radeon wx5100 on mesa 21.2.6 drivers
                                                                                                               |     ryzen9 5950x. java 17 azul jdk
                                                                                                               | version for test 1:  fabric api 0.46.4   indium 1.0.2-alpha2
                                                                                                               | sodium 0.4.0 alpha 6 build 14,      iris 1.2.0-pre, 
                                                                                                               | immersive portals: 1.2.5

minor                  |  portal overlay (vanilla texture thingy)                         |    see specs above
                              doesnt render when shaders are on

minor                  | shadows dont properly propagate through portals     |   see specs above

**Comment by qouteall** [comment]
The iris compat issues has been descibed in the wiki https://qouteall.fun/immptl/wiki/Miscellaneous#iris-compatibility

About the cross-portal-shadow: it's not being considered because it's hard to implement.

**Comment by Redd56** [comment]
perfect we got it all in the wiki
