### ISSUE TITLE
Maps become invisible when going through a portal

### ISSUE THREAD

**Issue by Speedgoergo** [qouteall/ImmersivePortalsMod#1006]
A small issue I noticed while playing survival. Maps created in the overworld will become invisible when walking through a portal. Alternatively, walking back into the overworld will display all the contents again.
The main issue was when I stored the overworld maps in a chest in the Nether and logged back into the world. The maps would instead show in the Nether, but become invisible when going into the overworld. A relog fixes this issue.

**Comment by qouteall** [comment]
Should be fixed
