### ISSUE TITLE
i cant light anymore portals on my minecraft world

### ISSUE THREAD

**Issue by squendan998** [qouteall/ImmersivePortalsMod#1010]
its not letting me light anymore  portals on my minecraft world

**Comment by qouteall** [comment]
Does this issue occur with only Immersive Portals and Fabric API? (It's recommended to test it in a new world)

**Comment by squendan998** [comment]
wait do you mean with only those 2 mods?

**Comment by squendan998** [comment]
i have like 74 mods

**Comment by squendan998** [comment]
but it normaly works

**Comment by ImSpaceLover** [comment]
Test it again but with just Immersive Portals and Fabric API

**Comment by squendan998** [comment]
everything works fine when i switch to 1.18.1 version

**Comment by squendan998** [comment]
its working normal now

**Comment by qouteall** [comment]
Did you get this issue in 1.18.2?

**Comment by squendan998** [comment]
no it was on 1.17.1

**Comment by qouteall** [comment]
You said that it works fine in 1.18.1. I am not interested in support old versions unless severe issue occurs (this is probably a mod compatibility issue which is not deemed severe) so I will close the issue.
