### ISSUE TITLE
Iris Compatibility Borken with AMD videocard?

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#1015]

**Comment by ghost** [comment]
I'm using an amd card, but with or without iris I have the problem of my items disappearing when I go near a portal or look at one. they're still there they just stop rendering. I'm not sure if it sodium related though.

**Comment by qouteall** [comment]
@viruspro Does this issue occur with only immptl and fabric api (test it in another world)?

**Comment by ghost** [comment]
i will test it in a bit

**Comment by ghost** [comment]
yes it happens with just immptl and fabric api
![image](https://user-images.githubusercontent.com/12817965/160031450-ca76f51e-81d1-4a60-87ee-f6d6ff6991f2.png)
![image](https://user-images.githubusercontent.com/12817965/160031461-46821d83-f10b-44da-bf6e-c31fbc3c7f6e.png)
![image](https://user-images.githubusercontent.com/12817965/160031514-2de539ac-a6db-4834-9a89-c840803f8cca.png)

the flint and steel disappears along with a bunch of items in my inventory as long as im standing with the portal in view

**Comment by qouteall** [comment]
@viruspro Are you using intel videocard?

**Comment by qouteall** [comment]
@viruspro Maybe that issue will be fixed in this version https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v1.3.4-1.18  (I am not sure)

**Comment by ghost** [comment]
I am using a amd videocard, radeon rx 580

**Comment by ghost** [comment]
i will test it later today

**Comment by ghost** [comment]
i cannot test it as i and my server are running minecraft 1.18.1 not 1.18.2

**Comment by Redd56** [comment]
> i cannot test it as i and my server are running minecraft 1.18.1 not 1.18.2

Can you test in singleplayer on 1.18.2

**Comment by ghost** [comment]
Yeah, that fixed it on 1.18.2, is it possible to make a 1.18.1 version with the fix?
