### ISSUE TITLE
Fixing bedrock replacement of the nether [Enhancement]

### ISSUE THREAD

**Issue by FloridaMen** [qouteall/ImmersivePortalsMod#1016]
It'd be nice to have a single layer of bedrock as an extra dimension. Let's say you want to put the nether under the overworld. You'd likely replace bedrock for netherrack, meaning the player can now fall into the void if they mine too deep in the nether. 
Two ways to fix this would be as follows:
1) adding a basic dimension that is only a single layer of bedrock, to allow the player to place it where they like (though this could cause considerable lag, as well as unnecessary complications)
2) allowing for only eliminating bedrock above or below a specific y-level.

**Comment by FloridaMen** [comment]
I forgot to elaborate this: while it is possible to create a datapack to add this dimension layer, it must be at least 16 blocks in height. Whether this is a limitation of minecraft's engine or of datapacks I do not know. However (if i could get it to work) this is a hypothetical workaround.

**Comment by qouteall** [comment]
You can use commands to manually change the connecting portals https://qouteall.fun/immptl/wiki/Commands-Reference#portal-global-connect_floor-dimensiona-dimensionb
(Althought the command does not support rotation and scale)

**Comment by FloridaMen** [comment]
After spending some time on this issue I found a decent workaround for the bedrock issue. You can create a datapack that replaces the bedrock, and load it in with paxi in order to remove only the nether floor or ceiling.
