### ISSUE TITLE
Unable to launch with sodium installed

### ISSUE THREAD

**Issue by cootshk** [qouteall/ImmersivePortalsMod#1021]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* Provide instructions for how to reproduce the issue. Include the Minecraft version and mod version.
* Forge version issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues
* If it's a mod compatibility issue, post that mod's link and open another issue on that mod
the game doesn't start
mod is [CaffeineMC/sodium-fabric](https://github.com/CaffeineMC/sodium-fabric)
apparently, it doesn't allow sodium
crash report: 
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Immersive Portals' (immersive_portals) 1.2.5 with any version that is compatible with:
		 - sodium 0.4.1+build.15
Unmet dependency listing:
	 - Mod 'Immersive Portals' (immersive_portals) 1.2.5 is incompatible with any version before 0.4.0-alpha6 or any version after 0.4.0-alpha6 of mod 'Sodium' (sodium), but a matching version is present: 0.4.1+build.15!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by qouteall** [comment]
use sodium 0.4.1

**Comment by cootshk** [comment]
I am using the latest 1.18.1 version of sodium

**Comment by qouteall** [comment]
It's recommended to use 1.18.2. In 1.18.1, the compatible sodium version is 0.4.0-alpha6
