### ISSUE TITLE
Stuck on loading terrain screen when leaving the end.

### ISSUE THREAD

**Issue by Nate-NG** [qouteall/ImmersivePortalsMod#1022]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version:
 Version Used: immersive-portals-1.3.3-mc1.18.2-fabric

* Provide instructions for how to reproduce the issue. Include the Minecraft version and mod version:
In addition to the Immersive portals mod I am running;
      - fabric-api-0.48.0+1.18.2
      - litematica-fabric-1.18.2-0.11.1
      - malilib-fabric-1.18.2-0.12.1
      - minihud-fabric-1.18.2-0.22.0
      - sodium-fabric-mc1.18.2-0.4.1+build.15
 Enter end portal from the overworld. Leave end portal from the end. Sit and wait in the "Loading Terrain" screen forever. Get back into the game by crashing Minecraft. You load back where leaving the end should have put. 
* Forge version issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues
* If it's a mod compatibility issue, post that mod's link and open another issue on that mod
- I have tested yet if it is related to the other mods, however, if I remove immersive portals the issue goes away.
![1022-settings](https://user-images.githubusercontent.com/90462237/160106182-489e3a33-b55d-49f4-b393-48075c025998.JPG)

**Comment by qouteall** [comment]
Does this issue occur with only Immersive Portals and Fabric API? (It's recommended to test it in a new world)

**Comment by Nate-NG** [comment]
> Does this issue occur with only Immersive Portals and Fabric API? (It's recommended to test it in a new world)

Yes I just ran that test on a new world with just the api and immersive portals. I have also updated the ticket with a screenshot of my settings.

**Comment by qouteall** [comment]
I cannot reproduce this issue on my side. To diagnose this issue, I need you to post the log (`.minecraft/logs/latest.log`)

**Comment by Nate-NG** [comment]
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/8350037/latest.log)

**Comment by qouteall** [comment]
In the log the client accidentally stops the main loop and the server closes. But it does not show any exception. It's weird.

I tested using the same fabric api version and cannot reproduce the issue.

**Comment by Nate-NG** [comment]
That could be me crashing the game when it gets stuck on the loading screen. Happy to hop on a discord call or something to see what we can do if that helps.

**Comment by qouteall** [comment]
It does not stuck on loading screen when immptl is not present, right?

**Comment by Nate-NG** [comment]
No. I tested it without immptl but with my other mods and it worked. I also tested without any mods and it worked all before I made the ticket.

**Comment by qouteall** [comment]
Can you show a video about how to reproduce the issue?

**Comment by qouteall** [comment]
nevermind, I can reproduce the issue now

**Comment by Nate-NG** [comment]
Let me know if you still want a video or anything on my end.

**Comment by qouteall** [comment]
The real reason of this issue: the position sync system has issues, the client player is not in the correct position, and the client player's chunk is not loaded, so the loading screen is not closed.

**Comment by Nate-NG** [comment]
Is there a quick fix?

**Comment by qouteall** [comment]
This version should fix the issue https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v1.3.5-1.18

**Comment by Redd56** [comment]
This moght fix my issue as well, i will test

**Comment by qouteall** [comment]
Seems that many people are still using 1.18.1. I readded the fix into 1.18.1 https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v1.2.7-1.18
