### ISSUE TITLE
CommandsOnTeleported bug

### ISSUE THREAD

**Issue by Someone-193** [qouteall/ImmersivePortalsMod#1025]
I have been trying to get a portal to execute a command upon teleportation with the commandsOnTeleported NBT tag. The command I wanted to run was "   /kill @a[nbt={SelectedItem:{id:"minecraft:tripwire_hook",Count:1b}}]  " but because of the quotation marks in the kill command. The portal command wont accept it. Its not really bad or anything but you cant have a portal make someone run a command that has any quotation marks in it which is pretty annoying. As for how to re-create it? Load up a world and try to get a portal to run a command with quotation marks in it. (This is on 1.18.2)

**Comment by Razboy20** [comment]
You can escape the quotes by using backslashes, ex. `/kill @a[nbt={SelectedItem:{id:\"minecraft:tripwire_hook\",Count:1b}}]`.
