### ISSUE TITLE
pehkui mod on minecraft doesent have the portal blocks

### ISSUE THREAD

**Issue by zackackree** [qouteall/ImmersivePortalsMod#1028]
basically when i download pehkui on curseforge and launch it, it works but when i create  a world and look through the creative inventory there is no portal block. the commands for pehkui work though, so i know its not just vanilla minecraft and i tried all kinds of versions and forge or fabric but it just doesent do anything.

**Comment by qouteall** [comment]
This mod is not Phekui. Did you install immersive portals mod? Are you using the latest 1.18.2 version?
