### ISSUE TITLE
[ENHANCEMENT] Portal Culling Option

### ISSUE THREAD

**Issue by FloridaMen** [qouteall/ImmersivePortalsMod#1030]
Unsure if this would better performance, but for global portals, maybe it would help to stop rendering the portal on clientside if the player does not have direct line of sight to it? Even at a small loss to performance, having this option would be nice for say, a portal connecting the nether and overworld, to eliminate the overworld's bright blue skybox rendering in the nether.

**Comment by qouteall** [comment]
This optimization is already present.

**Comment by qouteall** [comment]
Are you using Iris? In normal cases the overworld sky is not rendered in nether because the portal is fuse view. But fuse view does not work with iris currently

**Comment by FloridaMen** [comment]
Ah, thank you, I was. Makes sense
