### ISSUE TITLE
Doors don't work

### ISSUE THREAD

**Issue by TomtomFH** [qouteall/ImmersivePortalsMod#1032]
if you go through the portal and open doors right after it will open but you can't see that it changed.
I don't know if this a because of another mod.

**Comment by Razboy20** [comment]
Can you elaborate on what you mean by "you can't see that it changed"?

**Comment by qouteall** [comment]
Can you show a video about the issue?

**Comment by TomtomFH** [comment]
for some reason i cant reproduce it now but when i opened a door it looked like before but i was able to walk through it (i installed optifine and sodium after that bug)
