### ISSUE TITLE
Block visuals won't update after I broke portal

### ISSUE THREAD

**Issue by NebbyOtt** [qouteall/ImmersivePortalsMod#1033]
I created a standard portal, went through and build a few blocks, came back out and broke an obsidian to break the portal, obsidian didn't disappear but the portal broke, couldn't relight it until I realized that the obsidian wasn't actually there, it was only there visually I went and broke other blocks around the portal and they broke, but they remained visually there, I placed a grass block where a wood block was, looked like a wood block, heard a grass sound when I broke it, its like things were updating, just not visually. Re-establishing the portal fixed the problem

**Comment by qouteall** [comment]
Are you using the latest version of immptl in 1.18.2? Does this issue occur with only immptl and fabric api?
