### ISSUE TITLE
Hard Crash when portal with durationTicks other than 10 is set to look at a different dimension

### ISSUE THREAD

**Issue by KMorris29** [qouteall/ImmersivePortalsMod#1034]
Version immersive-portals-1.3.5-mc1.18.2-fabric.jar
Create a portal looking nearby.  Do /portal set_portal_nbt {animation:{durationTicks:500}} then do /portal set_portal_destination minecraft:nether ~ ~ ~. Crashes out of game, even out of launcher.

Only other mods are Pehkui, Worldedit, NotEnoughCrashes (which fails to prevent this crash), and the new fork of GravityChanger.

Relevant section of crashlog: https://pastebin.com/LrYU2E1E

**Comment by qouteall** [comment]
Fixed in 1.3.6
