### ISSUE TITLE
Search Forceloaded Chunks for Matching Frames in Custom Portals

### ISSUE THREAD

**Issue by jmdev91** [qouteall/ImmersivePortalsMod#1037]
I've tried with both /forceload and the chunkloader built into FTB Maps, but I can't get my custom portals to match up with distant frames. Could we please get some "fallback" logic to check through forceloaded chunks if no match can be made nearby?

**Comment by qouteall** [comment]
This is not easy to implement. It has to handle the matching on the edge of the forceload region.
And implementing it will make nether portal linking more confusing.

You can use portal helpers and commands to edit the portal.

**Comment by jmdev91** [comment]
I just assumed the bounds of the forceload region would be the limit. If you're building a teleport room back at your survival base, for instance, you should expect to have to keep the portal you're making within the forceloaded chunk(s).

On the Nether portal issue, perhaps it could be a different linking/generation case distinguished by a boolean option or special value for the scale options it would, by definition, be mutually exclusive with. Not sure if that still makes it especially confusing or not though.

**Comment by qouteall** [comment]
I am going to design a new way of creating portal other than portal helper. That would solve the problem.
