### ISSUE TITLE
Immersive portals breaking rendering + mekanism

### ISSUE THREAD

**Issue by wakkytabbaky** [qouteall/ImmersivePortalsMod#104]
immersive-portals-0.4(for mc 1.15 with forge)
Mekanism-1.15.2-9.9.14.406

using immersive portals and mekanism creates a rendering bug for item pipes etc

https://imgur.com/a/uN48Rx9

the mekanism stuff still works fine its just rendering which is broken , the rendering issue only happens when you leave render distance / chunk the item pipes are in when there is a portal nearby. confirmed to be immersive portals breaking the rendering so thought id post it here instead of the mekanism github

client log with errors https://pastebin.com/261cXQva

**Comment by Jarfeh** [comment]
this is the github page for the fabric version of immersive portals

**Comment by wakkytabbaky** [comment]
oh did not realise there was 2 my bad.
