### ISSUE TITLE
 i can't play with immersive portals mod with optifabric the optifabric is 1.18.2 1.13.0 and the immersive portals mod is 1.3.6

### ISSUE THREAD

**Issue by MrDeathKMGamer** [qouteall/ImmersivePortalsMod#1044]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* Provide instructions for how to reproduce the issue. Include the minecraft version and mod version.
* Forge version issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues
* If it's a mod compatibility issue, post that mod's link and open another issue on that mod

**Comment by Classified3939** [comment]
Optifine/Optifabric is not supported by Immersive Portals. Optifine is closed-source, which means mod compatibility is very difficult to achieve. Use the supported mods Sodium for lag prevention and Iris for shaders (most shaders that work with optifine also work with Iris).

**Comment by qouteall** [comment]
https://qouteall.fun/immptl/wiki/Miscellaneous#optifine-compatibility
