### ISSUE TITLE
If you have sodium and immersive portals loaded, when you start to load a world the game crashes. Please make it compatible with Sodium.

### ISSUE THREAD

**Issue by 2009johan** [qouteall/ImmersivePortalsMod#1045]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* Provide instructions for how to reproduce the issue. Include the minecraft version and mod version.
* Forge version issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues
* If it's a mod compatibility issue, post that mod's link and open another issue on that mod

**Comment by qouteall** [comment]
which mc version? which immptl version? which sodium version? post the crash report
