### ISSUE TITLE
Graphical Issues 

### ISSUE THREAD

**Issue by weaz12** [qouteall/ImmersivePortalsMod#1048]
I am assuming this issue is related to running Sodium/Iris, however even in compatibility mode the issues remain. I have tried toggling almost every setting.  In each of these images I have compatibility mode turned on.

immersive-portals-1.2.5-mc1.18.1
sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14
iris-mc1.18.1-1.2.0-pre

![2022-05-13_21 34 03](https://user-images.githubusercontent.com/11304445/168409220-2ae0e6dc-b036-49c0-9594-9988e8042748.png)
![2022-05-13_21 33 51](https://user-images.githubusercontent.com/11304445/168409224-4ea77435-47e9-4439-9439-f0438b8e6396.png)
![2022-05-13_21 30 15](https://user-images.githubusercontent.com/11304445/168409282-da34de2c-d22b-49fd-bbe9-da154ffe983c.png)

**Comment by qouteall** [comment]
Does the issue occur with BSL shader? Have you tried turning off motion blur?
