### ISSUE TITLE
incompatible with chunk loaders

### ISSUE THREAD

**Issue by systemshaper** [qouteall/ImmersivePortalsMod#105]
I have tested immersive portals (both 1.14 and 1.15 versions) with a number of chunk loaders (simple chunk loader, chunknogobyebye, Plain Chunk Loader) and in each case the chunk loaders stop working correctly when combined with Immersive Portals. Is this a known incompatibility? Or should it theoretically be possible to still use chunk loading mods with this one?

**Comment by qouteall** [comment]
Being compatible with chunk loader mods is theoretically possible but very hard.

**Comment by systemshaper** [comment]
Ok thanks. Was just hoping to have my cake and eat it too.

**Comment by qouteall** [comment]
As this compatibility issue is hard to fix, I am planning to add similar chunk loader things into immersive portals.

**Comment by systemshaper** [comment]
That would be awesome! My server decided to give up our cool immersive portals because we needed chunk loaders, but we would love to have both. Hope it works out.

**Comment by qouteall** [comment]
Fixed. It will be in the next version

**Comment by systemshaper** [comment]
Fantastic, thank you!

**Comment by qouteall** [comment]
should be fixed in the latest version

**Comment by systemshaper** [comment]
Is this fix likely to be applied for 1.14 as well at some point?
