### ISSUE TITLE
The view through the Portal only renders on the right side

### ISSUE THREAD

**Issue by SahKriaan** [qouteall/ImmersivePortalsMod#1053]
The view through the portal renders, but only on the right half of the view window, split directly in line with the crosshairs. Using F5, it continues to do it relative to the camera as well. Tried breaking and relighting the portal in the overworld, lighting from the Nether, restarting the game, and reinstalling the mod both manually and through CurseForge.

![2022-05-19_21 39 18](https://user-images.githubusercontent.com/60028349/169438394-185c9a7c-1645-41f2-8100-b02fa026d149.png)
![2022-05-19_21 39 57](https://user-images.githubusercontent.com/60028349/169438412-47c1020d-040d-4bef-a8c8-2175414eeae5.png)

**Comment by froyo4u** [comment]
have you tried without shaders?

**Comment by qouteall** [comment]
Does the issue occur without iris and sodium?

**Comment by SahKriaan** [comment]
Turning off shaders did fix it. I tried with a few different shaders and they all had similar problems. Sometimes half the screen, sometimes a odd square in the middle.
As for Iris and Sodium, they are installed but I get an error saying that Sodium is not installed when the portal mod is active. Also, the game does not start with Iris uninstalled.
