### ISSUE TITLE
Immersive Portals breaks Minecraft's depth buffer clearing when using IrisPortalRenderer

### ISSUE THREAD

**Issue by coderbot16** [qouteall/ImmersivePortalsMod#1055]
This unbindWrite call happens right before RenderSystem#clear in LevelRenderer. This breaks with the upcoming Iris 1.2.5 update:

https://github.com/qouteall/ImmersivePortalsMod/blob/0f894149e81d5c6079d2b8e555edb551b02d43ff/imm_ptl_core/src/main/java/qouteall/imm_ptl/core/compat/iris_compatibility/IrisPortalRenderer.java#L93

**Comment by qouteall** [comment]
Can you explain how does Iris change the way of binding framebuffer and clearing?

**Comment by coderbot16** [comment]
Iris 1.2.5 uses the Minecraft depth buffer from the main render target and expects it to be cleared normally in LevelRenderer, but it clears its own color buffers separately after Minecraft's buffer clearing has taken place. Notably, Iris only explicitly clears the shader color buffers.

Previously this problem was hidden because Iris used its own depth buffer and cleared it, but this is no longer the case, which exposed the issue in this Iris-specific code path in immersive portals.

**Comment by coderbot16** [comment]
The Iris framebuffers use the depth attachment from Minecraft's main render target along with Iris's own shader color attachments.

**Comment by qouteall** [comment]
So all I need is to re-bind the vanilla framebuffer, so vanilla clearing will work, right?

**Comment by coderbot16** [comment]
Yep, I believe that should work.
