### ISSUE TITLE
Custom Portal Genration Issue

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#1060]
From ParasiticSquid

So here's a weird issue: I made a custom datapack that adds a portal to the bumblezone dimension. Now, apparently I did it right because it works perfectly even when generating a portal on the other side and even works in reverse.. yet, if I make the portal scaled suddenly it refuses to generate or sometimes even connect to the other side. Sometimes when I check the side it's suppose to be making the portal on I see it has generated a bunch of empty frames but no portal. Or no portal as in linked but seems to sometimes create some blank portal entity that breaks when I break the frame.

Im not sure if this is just a weird normal issue with scaled portals or if it's what im trying to do with it that is causing these issues. Basically, I have the portal using "from_length": 1 and "to_length": 4 with 4 being the bumblezone side. That way a player normal size in the bumblezone will be small when they exit through the portal into another dimension like the overworld. Basically bee sized player from the bee world for a bee based origins playthrough. A neat bonus was the fact 1x1 portals apparently exist so normal sized players who didn't shrink coming from the bumblezone or weren't already scaled down can't access the portal and be giant in the dimension unless it's vertical or they have a method to crawl with a hotkey like the crawl mod. Even the trapdoor trick doesn't work since it just causes you to fall into the portal frame due to standing up since your unable to place blocks inside the breakable portal entity unlike normal portals.

Im honestly at a loss. Sometimes it works randomly but most of the time it doesn't which is annoying. Anyways on another note the wiki doesn't mention any way to create a datapack portal that changes player gravity so is that not implemented or am I blind?

**Comment by ParasiticSquid** [comment]
Well, here it is. As far as ive seen and read on your wiki it should in theory work but I may of screwed something up. First time making a datapack myself

`{
  "schema_version": "imm_ptl:v1",
  "from": [
    "minecraft:overworld"
  ],
  "reversible": true,
  "to": "the_bumblezone:the_bumblezone",
  "form": {
    "type": "imm_ptl:scaling_square",
    "from_frame_block": "minecraft:honeycomb_block",
    "to_frame_block": "minecraft:honeycomb_block",
    "area_block": "minecraft:air",
	"from_length": 1,
	"to_length": 4,
    "generate_frame_if_not_found": true
  },
  "trigger": {
    "type": "imm_ptl:use_item",
    "item": "minecraft:honey_bottle"
  }
}`

**Comment by qouteall** [comment]
I can reproduce this issue now

**Comment by qouteall** [comment]
Should be fixed in the next version

**Comment by qouteall** [comment]
should be fixed in this version https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v1.4.0-1.18

**Comment by ParasiticSquid** [comment]
Fixed it from what I can tell after a couple days of testing
