### ISSUE TITLE
Stick doesnt move both portal entities 

### ISSUE THREAD

**Issue by Katooaton** [qouteall/ImmersivePortalsMod#1065]
When I use the sticks to move the portal, only one part of the portal moves. The portal also doesnt move forward in a smooth motion, it teleports .5 forward/backward ect. 
![Screenshot 2022-05-31 121909](https://user-images.githubusercontent.com/74023027/171223099-55869cb3-ad42-4d0a-be83-7f73568a965e.png)

Also its a 1.17.1 server with the immersive portals version .39 (new one as of when I wrote post)
mods are fabric api
image2map
worldedit

**Comment by qouteall** [comment]
The portal animation feature and bind cluster feature was introduced in 1.18. Unfotunately I won't do backporting because maintaining one version is already a huge work. Only fixes of important issues will be backported.

It's recommended to use 1.18.2 now.
