### ISSUE TITLE
Chests and some other gui based blocks don't work through portals

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#1066]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* Load a world with Immersive Portals, create a semi far away portal or a portal in another dimension that has a chest on one side, try to open it, it will close the gui.

**Comment by qouteall** [comment]
I know the issue exists. Don't make duplicate issues.
https://github.com/qouteall/ImmersivePortalsMod/issues/198
