### ISSUE TITLE
Immersive Portals is incompatible with anything before sodium 0.4.1 even though i have 0.4.2 and crashes

### ISSUE THREAD

**Issue by epicyeeto** [qouteall/ImmersivePortalsMod#1073]
hello all
i have this error where i can play even though i have everything correct
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'LambDynamicLights' (lambdynlights) 2.1.2+1.19 with any version that is compatible with:
		 - fabric 0.55.2+1.19
	 - Replace mod 'Immersive Portals' (immersive_portals) 2.0.0 with any version that is compatible with:
		 - sodium 0.4.2+build.16
Unmet dependency listing:
	 - Mod 'Immersive Portals' (immersive_portals) 2.0.0 is incompatible with any version before 0.4.1+build.15 or any version after 0.4.1+build.15 of mod 'Sodium' (sodium), but a matching version is present: 0.4.2+build.16!
	 - Mod 'LambDynamicLights' (lambdynlights) 2.1.2+1.19 requires version 0.55.3+1.19 or later of mod 'Fabric API' (fabric), but only the wrong version is present: 0.55.2+1.19!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
here is the error

**Comment by qouteall** [comment]
It says "or any version after 0.4.1+build.15 of mod 'Sodium' (sodium)". 2.0.0 is not yet compatible with sodium
2.0.0 is not yet stable and only published for testing
