### ISSUE TITLE
1.19 unstable version

### ISSUE THREAD

**Issue by MadnessMyth** [qouteall/ImmersivePortalsMod#1074]
TNT's can be rendered in half sometimes when inside a portal (TNT Entity)
Arrows or projectiles such as snow can go through the obsidian from the portal
Water doesn't break portals (Vanilla portals break if water interacts with them)
Throwable potions break on impact of portal instead of going through the portal.
Sculk sensors don't detect any sound when you go inside the portal. (If sensor is not in same dimension)
TNT's or explosives do not deal damage through portals.
Mobs and entities have glitchy rendering when going through the portal
Hostile mobs forget who they were attacking when attacker goes through a portal
Damage animations for a mob or player stop when going through a portal
Zombies and husks do not attack villagers when they are not in the same dimension
Iron golems do not attack the hostile mobs when they are not in the same dimension
Villagers are not scared of zombies when they are not in the same dimension
Zombies do not go after villagers if they are not in the same dimension.
Leads act very strangely when you change dimensions.
Cobweb and Powdered snow is ignored when inside a portal.

All the bugs i know.

**Comment by qouteall** [comment]
As I tested, the nether portal can be break by water bucket by using it on the obsidian frame. Are you using other mods?

**Comment by qouteall** [comment]
Going to split this issue into separate issues.

**Comment by qouteall** [comment]
https://github.com/qouteall/ImmersivePortalsMod/issues/931

**Comment by qouteall** [comment]
What do you mean by "Damage animations for a mob or player stop when going through a portal"?
