### ISSUE TITLE
Incompatible with JourneyMap

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#1088]
It displays both nether and overworld at the same time.

**Comment by qouteall** [comment]
JourneyMap seem to be close-sourced so this cannot be fixed on ImmPtl's side. https://github.com/TeamJM/journeymap

**Comment by qouteall** [comment]
https://github.com/TeamJM/journeymap/issues/457

**Comment by mysticdrew** [comment]
This is fixed with the latest IP and journeymap 5.9.0
