### ISSUE TITLE
portal only work sometimes

### ISSUE THREAD

**Issue by Zagrec1** [qouteall/ImmersivePortalsMod#1095]
(1.18.2, fabric loader 0.14.8-1.18.2) most of the time when i go through a portal does it actually work other times you go through it like it's an illusion

**Comment by qouteall** [comment]
Are you using other mods? Can you show a video about when it does not work?

**Comment by Zagrec1** [comment]
> Are you using other mods? Can you show a video about when it does not work?

im using:
- ChiselsBits-fabric-1.18.2-1.2.90
- fabric-api-0.56.1+1.18.2
- immersive-portals-1.4.0-mc1.18.2-fabric
- Pehkui-3.3.2+1.14.4-1.19
- worldedit-mod-7.2.10

i can't show a video because the recording software crashes minecraft but it's as if one second the portal is there, but the next it disappears

**Comment by Zagrec1** [comment]
![2022-06-22_12 30 50](https://user-images.githubusercontent.com/102463962/175008772-febf5292-7d06-4209-9167-7a05255144dc.png)

**Comment by qouteall** [comment]
Is that portal very big? If the portal is more than 20 blocks wide then you should make it a global portal

**Comment by Zagrec1** [comment]
this worked thanks!
