### ISSUE TITLE
Unusual error on Fabric 1.18.2

### ISSUE THREAD

**Issue by Sunconure11** [qouteall/ImmersivePortalsMod#1096]
https://bytebin.lucko.me/T2XLATvZRP

I really couldn't give you tips on how to reproduce it, even if I wanted to. But it seems to be poking at something you are using.

I'm trying to solve whatever is causing this when I make a new world:

https://cdn.discordapp.com/attachments/407858842995785728/988850848253755392/unknown.png

But it seems that when I enter a world after making it, I crash, either with Immersive Portals, or Twilight Forest.

The Twilight Forest crash can be seen here:

https://bytebin.lucko.me/hg7iyfJbtJ

https://bytebin.lucko.me/EnwAXQ08LK

**Comment by Sunconure11** [comment]
https://gist.github.com/Sunconure11/70930d32f3bd2f1f80ce5f55c921b3ab

Here's an associated log of this.

Ignore that I have 700+ mods, nested dependencies are one hell of a drug.

Of note is that I tried downgrading just to see what would happen, and nothing changed.

**Comment by qouteall** [comment]
If I don't know which specific mod is incompatible with ImmPtl then I cannot fix this. You can try to remove half of the mods until it does not crash with ImmPtl

**Comment by Sunconure11** [comment]
I do not believe it to be Immersive Portals. I think this was just a red herring thrown by the true cause.
