### ISSUE TITLE
server not launching due to many mod class exceptions(1.14.4 fabric)

### ISSUE THREAD

**Issue by SDUBZ** [qouteall/ImmersivePortalsMod#11]
this the issue gist i made with log and mod list etc due to many class conflicts https://gist.github.com/SDUBZ/8a121bddf045e26d7234afb321140f29

**Comment by qouteall** [comment]
test 0.8 version and see whether this issue still exist

**Comment by SDUBZ** [comment]
0.8 seems to work but hard to tell when one is stopping me joining it but atleast it got to launching world and stuff

**Comment by qouteall** [comment]
Maybe it's a mod compatibility issue. Try to remove half of the mods and try again, until you find which mod it's incompatible with

**Comment by qouteall** [comment]
And show the server log

**Comment by SDUBZ** [comment]
http://puu.sh/E5m1s/2ccd8cb08e.log
