### ISSUE TITLE
Portal incompatibility with other dimensions

### ISSUE THREAD

**Issue by nodogsleft** [qouteall/ImmersivePortalsMod#111]
When modifying the portal's destination to dimensions other than vanilla dimensions or alternate dimensions, the portal will only display the sky box of the destination. Teleportation occurs as expected, but as stated, the world won't load through the entry portal. Creating a two-way portal also does not create a portal in the opposite dimension. 

It's notable that I'm using the latest 1.14 forge version of the mod. I couldn't find any issues pertaining to this, so I assumed it hadn't been addressed. 

![2020-03-13_16 48 04](https://user-images.githubusercontent.com/61568402/76661861-76013f80-654a-11ea-9a3b-4fa234dd3976.png)
Midnight and Ultra Amplified mods used as examples

**Comment by qouteall** [comment]
Are you playing multiplayer? Show the log

**Comment by nodogsleft** [comment]
Singleplayer, and here: https://pastebin.com/E4zax7w1

Dimensions that didn't load included The Midnight, Blue Skies, and Ultra Amplified
![2020-03-14_20 14 22](https://user-images.githubusercontent.com/61568402/76693396-3ada3b80-6632-11ea-8518-94efa30e5e6a.png)
![2020-03-14_20 18 04](https://user-images.githubusercontent.com/61568402/76693397-3b72d200-6632-11ea-8c92-e531ca5b5c8e.png)
![2020-03-14_20 11 17](https://user-images.githubusercontent.com/61568402/76693398-3c0b6880-6632-11ea-9da5-ec0e6a483789.png)
![2020-03-14_20 11 57](https://user-images.githubusercontent.com/61568402/76693399-3ca3ff00-6632-11ea-9744-efb67a30dc8f.png)
![2020-03-14_20 12 26](https://user-images.githubusercontent.com/61568402/76693400-3d3c9580-6632-11ea-88a9-4e186c857120.png)
![2020-03-14_20 12 49](https://user-images.githubusercontent.com/61568402/76693401-3e6dc280-6632-11ea-96bd-fe06f74b398e.png)
![2020-03-14_20 13 17](https://user-images.githubusercontent.com/61568402/76693402-3f065900-6632-11ea-95d3-a02f92cd05e7.png)
![2020-03-14_20 13 51](https://user-images.githubusercontent.com/61568402/76693403-3f9eef80-6632-11ea-9cc8-da3770058ac0.png)

Unrelated, and may require its own issue:
![2020-03-14_20 10 27](https://user-images.githubusercontent.com/61568402/76693405-4ded0b80-6632-11ea-949b-9fbbeef5ff8d.png)

As expected, portals native to Blue Skies don't utilise the functions of Immersive Portals.

(I'd also really appreciate a reply to my question on the curseforge page!)

**Comment by qouteall** [comment]
Close due to the version being outdated.
