### ISSUE TITLE
[SUGGESTION] Blocks through portals

### ISSUE THREAD

**Issue by rdrpenguin04** [qouteall/ImmersivePortalsMod#1114]
My friend and I were coming up with ideas for unique nether hubs using flying machines and portals, just for the heck of it. I immediately checked to see if it was possible, and it isn't, for very reasonable reasons: the portal is a block.

But what if block movement was emulated across the border?

If a block would displace a portal block, that portal block instead becomes a metadata clone of the pushed block on both sides, copying redstone signals and other properties across. This could also apply to flowing liquids across portal boundaries.

This seems like a difficult idea, but it also seems like it could be possible. How does that sound to you?

**Comment by ImSpaceLover** [comment]
https://qouteall.fun/immptl/wiki/Miscellaneous.html#can-fluid-redstone-and-light-work-across-a-portal

**Comment by Classified3939** [comment]
Portals are not blocks, portals are entities. The portal helper blocks create a portal entity, but you can also create one with commands at places and rotations not aligned to the grid. For this reason, it is VERY non-trivial to have piston movement thru portals.
And before you ask, the portals created with the helper blocks are the same kind of portal, so they can be moved and rotated with commands as well, meaning having blocks move thru "just" helper-block portals is still a non-starter.

**Comment by rdrpenguin04** [comment]
Alright; I was mostly asking about doing it through vanilla-style portals, but I can understand that also being a bit of a non-starter because of inconsistency.

I'll close this until I come up with some MVP, if I ever end up doing that. Thank you for the links!
