### ISSUE TITLE
Mirrors not rendering through portals

### ISSUE THREAD

**Issue by The-Professor123** [qouteall/ImmersivePortalsMod#1115]
* v2.0.2
*Expected behavior: Mirror to render thru the portal.
*actual behavior: flat black color, though mirror renders after stepping through
![2022-06-26_23 31 09](https://user-images.githubusercontent.com/92767299/175875081-6c4a2a31-55b4-48eb-bc46-add6441f8475.png)

**Comment by qouteall** [comment]
This mod has a "lag attack proof" mode that make max portal layer to be 1 when the client is laggy. Try to disable the lag attack proof in the config. (the config can be changed via modmenu)
