### ISSUE TITLE
sound bug

### ISSUE THREAD

**Issue by BarbaricLadder** [qouteall/ImmersivePortalsMod#1119]
### Does the issue occur with only Immersive Portals mod and Farbic API? (Backup the world before testing this.)

No

### What happened?

after creating a portal, entering, then leaving and walking away, i can hear these invisible pigmen near me. it also happens with other nether npcs and entities.

**Comment by qouteall** [comment]
You said that this issue does not occur with only immptl, so it's a compatibility issue, please find which exact mod it's incompatible with.

**Comment by qouteall** [comment]
Updated the issue template to make it clear. It does not ask whether you are using other mods. I need you to test whether this issue occur without other mods.

**Comment by qouteall** [comment]
Are you using dimension stack? There is a known issue that mobs may spawn on top of nether in dimension stack.

I cannot reproduce the issue.

You can disable cross portal sound for now

**Comment by BarbaricLadder** [comment]
yeah im an idiot sorry turns out i had a bug with a audio reverb mod sorry
