### ISSUE TITLE
Incompatible with alternate current and modern glass doors mods when running in a quilt server

### ISSUE THREAD

**Issue by ChristopherHaws** [qouteall/ImmersivePortalsMod#1122]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

No

### Describe the issue

The steps to reproduce the issue are:
1) Install immersive portals, [alternate current](https://www.curseforge.com/minecraft/mc-mods/alternate-current), and [modern glass doors](https://www.curseforge.com/minecraft/mc-mods/modern-glass-doors) on a Quilt 1.19 server
2) Light a portal and the portal will show up as portal helper blocks
![image](https://user-images.githubusercontent.com/5934505/177249033-8fdbc14b-740b-421d-a713-a3d29659d1ff.png)

With the portal still lit, uninstall the alternate current mod and the blocks will turn into oak_glassdoor blocks:
![image](https://user-images.githubusercontent.com/5934505/177249417-ed1ff716-89b6-474e-8396-51c9d30e68c0.png)

Notes:
- If you light the portal and uninstall both of these mods, the game will crash when trying to connect since it can't find the glass door block
- If you don't install the alternate current mod and try to light the portal, it will spawn the glass door blocks instead of the portal helper blocks
- If you don't install the modern glass doors mod and try to light the portal, it will still spawn the portal helper blocks
- This issue doesn't happen on a fabric server, only on a quilt server

**Comment by qouteall** [comment]
Seem to be a registry sync issue of QSL

**Comment by ChristopherHaws** [comment]
For anyone interested, I asked around in the Quilt discord and the fix is to install this mod: https://modrinth.com/mod/polymer
