### ISSUE TITLE
i cant make portals why does this happen

### ISSUE THREAD

**Issue by squendan998** [qouteall/ImmersivePortalsMod#1126]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

https://user-images.githubusercontent.com/101436804/177440014-9b160c7c-2e22-4ad4-8eb8-d390a735fc5c.mp4

**Comment by qouteall** [comment]
I need more information. Do you mean nether portal or portal helper? Can you show the video of lighting the portals?

**Comment by qouteall** [comment]
Close because outdated.
