### ISSUE TITLE
If a portal is slightly behind the block surface, the player can slowly go through the block

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#1129]

**Comment by Siorinex** [comment]
Pls, back this at options for portal! I and more people`s use this "bug" on map`s!

**Comment by qouteall** [comment]
@Siorinex It's being considered https://github.com/qouteall/ImmersivePortalsMod/issues/1146

**Comment by qouteall** [comment]
@Siorinex I am going to make that a portal can be marked invisible. If it's invisible it still can do teleportation and cross portal collision. You can put a invisible portal slightly in front of a wall.
