### ISSUE TITLE
Serious FPS dips when portal is in view

### ISSUE THREAD

**Issue by purejosh** [qouteall/ImmersivePortalsMod#1135]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

I get serious FPS performance issues when looking at a portal that's linked with immersive. I'm running a 3090 kingpin, so this shouldn't be an issue for me. The frametimes increase significantly when looking at a portal, too. My frames will hover around 30FPS when looking at one. 

I know that we're technically rendering two dimensions when this is in view, but there shouldn't be such a performance loss. Some performance loss is expected.

**Comment by froyo4u** [comment]
Are you using shaders?

**Comment by purejosh** [comment]
I've tried with shaders, and without. Both have the same effect. I'm playing in 4k, if that's any help.

**Comment by froyo4u** [comment]
What's your frames when not looking at a portal?

**Comment by purejosh** [comment]
A solid 60FPS, frame times are nearing 20ms IIRC. I use vsync, can test without if needed.

**Comment by froyo4u** [comment]
Try without vsync, also as a general rule of thumb, don't use vsync like ever

**Comment by purejosh** [comment]
Vsync improves choppy behavior on most if not all games I play on, to be fair.

**Comment by purejosh** [comment]
240FPS without vsync and not looking at portal, 40-50FPS when looking at portal.

**Comment by froyo4u** [comment]
Jeez, idk what is wrong with your game, I have a GTX 1060 and my fps doesn't dip like that

**Comment by purejosh** [comment]
Will having sodium and iris installed affect FPS by that much? I mean they're both designed to increase perf and are included in pretty much every modpack, but there's "incompat" messages with them installed.

**Comment by purejosh** [comment]
Also, are there settings I can change to limit rendering distance on the other side of the portal? Maybe I can tweak it so there's only a few chunks loaded until I actually pass through the portal...

**Comment by froyo4u** [comment]
> Will having sodium and iris installed affect FPS by that much? I mean they're both designed to increase perf and are included in pretty much every modpack, but there's "incompat" messages with them installed. 
> 
> 

Wdym there's incompat messages

**Comment by purejosh** [comment]
![image](https://user-images.githubusercontent.com/70633949/178328930-db1f3398-aec0-4635-9e36-63b7daacc8e9.png)

**Comment by froyo4u** [comment]
Oh you're fine you won't really notice anything, just click disable warnings

**Comment by purejosh** [comment]
Alright. What can be done to improve the FPS here? Anything from the mod's end?

**Comment by purejosh** [comment]
I see that there's a distance to portal render option. If it were possible, it would be cool to see an option that controls the render distance on the other side of the portal.

**Comment by qouteall** [comment]
What's your render distance? Have you tried 12?

**Comment by qouteall** [comment]
I cannot reproduce this issue. Does this issue occur in every world or only a specific world? Does this issue occur with render distance 12? Have you changed other config related with rendering? Have you changed any option of immptl (if so try to reset all the settings)? What's your screen resolution?
