### ISSUE TITLE
exit code -805306369

### ISSUE THREAD

**Issue by SingendPfeil2** [qouteall/ImmersivePortalsMod#1138]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

No

### Describe the issue

I somehow get lower and lower to the moment that
 im looked like dinnerbone than my mc crashed with the error -805306369
It was on an server.

### Post the log here

```shell
Minecraft latest [latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/9103265/latest.log)
Server crash 2[Server-crash2.txt](https://github.com/qouteall/ImmersivePortalsMod/files/9103312/Server-crash2.txt)
Server crash 1 [Server-crash1.txt](https://github.com/qouteall/ImmersivePortalsMod/files/9103322/Server-crash1.txt)
Server crash 3[Server-crash3.txt](https://github.com/qouteall/ImmersivePortalsMod/files/9103327/Server-crash3.txt)
Server-latest [Server-latest.txt](https://github.com/qouteall/ImmersivePortalsMod/files/9103335/Server-latest.txt)
```

**Comment by ImSpaceLover** [comment]
Looks like you're describing pehkui and not Immersive Portals, try to submit this issue to pehkui github repository instead

**Comment by qouteall** [comment]
Try to use the latest version of immptl. It's currently 1.4.9
