### ISSUE TITLE
Nether Portal Search Range not working

### ISSUE THREAD

**Issue by ChristopherHaws** [qouteall/ImmersivePortalsMod#1141]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

No

### Describe the issue

Breaking a portal and recreating it a few blocks away is causing a new nether portal to be created instead of using the existing one even though my search radius is set to 128 (the default). 

In this picture, you can see the old nether portal is still there, but Immersive Portals created a new portal 2 blocks away when it should have used the existing portal.
![image](https://user-images.githubusercontent.com/5934505/179374440-5b74df78-2ae2-44a6-8e63-4bf9b17c43f4.png)

NOTE: I am using Quilt

**Comment by qouteall** [comment]
Are you sure that the frame size matches?

**Comment by ChristopherHaws** [comment]
After some trial and error, I found that it was because the original portal I made in the overworld was missing it's 4 corners, but the one that generates in the nether spawns with all 4 corners. Because of this, when I tried to re-light it, it didn't link properly. Maybe the fix would be to not include the 4 corners of the portal in the search for a portal to link to?

**Comment by qouteall** [comment]
The corner block does not count.

**Comment by qouteall** [comment]
Can you show a video about this?
