### ISSUE TITLE
My portal doesn't turn on 

### ISSUE THREAD

**Issue by Moxxie22** [qouteall/ImmersivePortalsMod#1149]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

No

### Describe the issue

Well, the problem was that at the beginning it did work.
But then the next day I saw that the nether portal was not on, so I assumed that I had to turn it on again, but I couldn't because there were some invisible blocks inside the portal, I removed them with a pickaxe and tried to turn the portal on again, but nothing happened.
I tried removing all the mods and just leaving the immersive portals and the fabric API and the problem continued, even removing the immersive portal mod, my nether portal did not work.
![2022-07-25_15 59 32](https://user-images.githubusercontent.com/109934621/180873755-8696f7eb-ac28-4511-bb8f-da1dfaf2d623.png)

**Comment by qouteall** [comment]
Seems that the nether gets unregistered. Try typing `/execute in ` command and it will show the dimension list. Is nether in the list?

Did you uninstall any mod before the nether portal become abnormal? Or did you use vanilla to open the world?

**Comment by Moxxie22** [comment]
My world from the beginning had only 3 mods: Fabric API, Fabric and Sodium.
Then I installed the others that are in the image of the list of mods, but he: "oh the biomes you'll go" was outdated because when I entered the world I got a message that it was unstable, then I removed it and put the updated and until then the portal worked, but when I closed the Minecraft there began the problem with the portal.
In my world, I set that no commands could be used, and I had to open the "LAN" to be able to use the commands.
![Mods](https://user-images.githubusercontent.com/109934621/181080113-25a7629d-59aa-4464-9e67-87cdc9705cb4.png)
![Minecraft issue](https://user-images.githubusercontent.com/109934621/181080125-5689410d-c299-4b0a-900e-63cf15091958.png)

**Comment by qouteall** [comment]
To fix the world, you can do:
1. use `/seed` command to know the seed
2. create another world with the same name, world generation and seed
3. use the new world's `level.dat` file to replace the `level.dat` of the broken world (don't forge to backup the broken world's `level.dat`)

Can you test installing "oh the biomes you'll go" in a new world and then uninstall "oh the biomes you'll go" and check the dimension list by typing command `/execute in `?

**Comment by Moxxie22** [comment]
I did what you said, but the world resets and I only keep my items that I have in my inventory.
And I did the thing about creating a new world and deleting the mod, oh the biomes you'll go and yes that is what is causing neither the nether and the end to work.
Sorry for taking up your time, as apparently the problem is not to do with the immersive portals mod.

**Comment by qouteall** [comment]
I mean that use the new world's `level.dat` to replace the old world's, the blocks and entities will still remain. Maybe the inventory is stored in `level.dat` so you can put inventory to a chest before that
