### ISSUE TITLE
Alternate 3/4 can generate random game block sections so big they crash the server

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#1155]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

In cursed alternate worlds there is that "biome" with all blocks in the game, and if this one generates too big, an issue arises - when having this structure loaded, the server lags to death. This may be due to water streams flowing onto it and making a lot of dropped items, but as a person more knowlegable than me said,

> having all kinds of random blocks like that seems to really fuck with the chunk decoder

Whatever the laggy part of this is, I ask you to decrease the max size this structire may generate. ~~i'm going to run a server on alternate 3/4, after all.~~
![javaw 2022-07-31 20-11-34](https://user-images.githubusercontent.com/85982640/182041125-bb1e9f57-bf38-4430-b62c-b7d3372f7e11.png)
(they should not be able to generate that big)

**Comment by ghost** [comment]
oh and there is a spark report taken right before the server almost crashes :skull: https://spark.lucko.me/omEv1a4bbR

**Comment by ghost** [comment]
~~i should really never have thought using these worlds as the main world on a production server was a good idea, not backing out now~~

**Comment by qouteall** [comment]
If it lags like that I will remove this kind of random block generation.

**Comment by ghost** [comment]
> If it lags like that I will remove this kind of random block generation.

Please don't remove it, just make it generate smaller. There were 2 smaller structures of this kind on the server and it was all fine.
![image](https://user-images.githubusercontent.com/85982640/182094249-88b1b816-beef-4b65-9b0d-969d11f3309a.png)
In this size they still look cool and don't cause any lag.

**Comment by ghost** [comment]
@qouteall any news on this? i'd like this fix sooner than later

**Comment by qouteall** [comment]
I made it only generate between y=0 and y=32 and built a quick release (not yet tested, it may crash)

[immersive-portals-2.1.2-mc1.19.1-fabric.jar.zip](https://github.com/qouteall/ImmersivePortalsMod/files/9251668/immersive-portals-2.1.2-mc1.19.1-fabric.jar.zip)

**Comment by ghost** [comment]
> I made it only generate between y=0 and y=32 and built a quick release (not yet tested, it may crash)
> 
> [immersive-portals-2.1.2-mc1.19.1-fabric.jar.zip](https://github.com/qouteall/ImmersivePortalsMod/files/9251668/immersive-portals-2.1.2-mc1.19.1-fabric.jar.zip)

Is it tied to world height or do you mean the height of the structure? Anyway, thanks a lot for the build.

**Comment by ghost** [comment]
I booted up the server with the new build, went to the place the big structure would have generated, and there is totally no structure of this kind there, at all. Guess the generation is very different in this version. Gotta find another one.

**Comment by ghost** [comment]
I think you straight up removed those/i'm unlucky, i have went like 2k blocks in a straight line and found none of those XD

**Comment by qouteall** [comment]
I didn't remove that. It's just rare.

**Comment by ghost** [comment]
> I didn't remove that. It's just rare.

then i'll just have to keep grinding, but i think the way you capped their height made them 5 times rarer.

**Comment by ghost** [comment]
![javaw 2022-08-04 09-21-12](https://user-images.githubusercontent.com/85982640/182780068-a6b77a4c-4b67-4ea8-a44b-5cd1406fba0c.png)
![javaw 2022-08-04 09-38-15](https://user-images.githubusercontent.com/85982640/182780135-9d9752ee-6d1e-4d9b-875c-5a5bbd059a5c.png)
![javaw 2022-08-04 09-28-50](https://user-images.githubusercontent.com/85982640/182780124-49c9b422-4bb2-48a2-9cd6-94d9948c4811.png),
![javaw 2022-08-04 09-29-40](https://user-images.githubusercontent.com/85982640/182780128-b025a068-f47f-417f-a2d3-b5b8d6239761.png)
![javaw 2022-08-04 09-30-02](https://user-images.githubusercontent.com/85982640/182780130-08159122-70be-494e-a4e5-0a5dfafd93b0.png)
Just as i told that to you, i found 5 of those, none being too extreme.

**Comment by ghost** [comment]
@qouteall is the change live in the latest 1.19.2 release?

**Comment by qouteall** [comment]
@HyperSoop yes

**Comment by qouteall** [comment]
So this is considered fixed right? Closing.
