### ISSUE TITLE
Unwrap cube command (Suggestion)

### ISSUE THREAD

**Issue by JoeTheOrangeCat** [qouteall/ImmersivePortalsMod#1157]
It would be cool to add a command that could "unwrap" a cube,
It would unwrap it by putting a portal on the edge that changes gravity that then leads to another edge, this will make it feel like the cube is flattened.
![2022-08-05_16 00 09](https://user-images.githubusercontent.com/110697200/183184268-f6aa3d63-820f-42d7-9c92-54b9c87d3b35.png)

The commands syntax could be like this "/portal unwrapcube x1 y1 z1 x2 y2 z2 height"

The height would be the height of each portal that is made.

![2022-08-05_16 11 20](https://user-images.githubusercontent.com/110697200/183192838-5f7e58ff-fcad-4429-8c6f-e6597d7c292d.png)

**Comment by qouteall** [comment]
It's being considered.

**Comment by qouteall** [comment]
The feature has been added, will be in 2.2.0

**Comment by JoeTheOrangeCat** [comment]
Thank you!
