### ISSUE TITLE
Suggestion: Make a 1.18.2 version compatible with Gravity API

### ISSUE THREAD

**Issue by Hedwig7s** [qouteall/ImmersivePortalsMod#1160]
Why? The GravityChanger 1.18.2 port is really unstable and has broken compatibility with more things than ImmersivePortals

**Comment by qouteall** [comment]
The gravity API and gravity changer has different API and changing it would break existing users that use gravity changer (there cannot be two kinds of compatibility in immptl). Unfotunately this is not being considered.

**Comment by Hedwig7s** [comment]
> The gravity API and gravity changer has different API and changing it would break existing users that use gravity changer (there cannot be two kinds of compatibility in immptl). Unfotunately this is not being considered.

People don't have to update their mod the the Gravity API version y'know
