### ISSUE TITLE
Cannot enter a portal whilst crawling

### ISSUE THREAD

**Issue by TheSnugget** [qouteall/ImmersivePortalsMod#1161]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

Entering a portal whilst crawling (shoved into a 1 block space by trapdoor, piston, or otherwise) causing a constant flicker between crawling and standing, and phasing the player through the portal if they persist.

### Post the log here

```shell
log is not relevant
```

**Comment by qouteall** [comment]
Is the portal horizontal or vertical? How is the trapdoor being placed? How is the portal being placed? Is it nether portal or custom portal? Can you show a screenshot or video about the issue?

**Comment by ScoutTheSaneless** [comment]
I can shed some light on the subject, it has to deal w standing portals as the player crawls through it, and the method of entering the crawl state is irrelevant

**Comment by TheSnugget** [comment]
hi, sorry for the late reply. Here's a video showcasing the issue. The effect described previously only applies to portals on the edge of a block, sorry for not clarifying

https://user-images.githubusercontent.com/103380745/185723747-b6ab54b3-1f4a-4d9e-86f1-def5faacd900.mp4

.

**Comment by qouteall** [comment]
Already fixed.

**Comment by Pladrassil** [comment]
Any plans to fix this for the 1.19 version of the mod?

**Comment by qouteall** [comment]
@Pladrassil No. It's recommended to use 1.19.3.
