### ISSUE TITLE
Items keep disappearing when thrown through a global portal.

### ISSUE THREAD

**Issue by ABadMinecraftPlayer** [qouteall/ImmersivePortalsMod#1165]
When i throw an item through a global portal it kind of disappears.

https://user-images.githubusercontent.com/112104688/186709603-0ff40323-1b3e-4d2f-9efe-07e63c332fde.mp4

The video shows what happened to the item.

**Comment by qouteall** [comment]
This does not affect the dimension stack portals. Only the global portals converted from normal portals have this issue

**Comment by qouteall** [comment]
Fixed in the next version
