### ISSUE TITLE
[SUGGESTION] Immersive portals linking worlds in different servers

### ISSUE THREAD

**Issue by omixann** [qouteall/ImmersivePortalsMod#1169]
I know it would be a nightmare to code and keeping player state in sync between two servers wanting to be the ground truth at the same time sounds really complicated, but being able to seamlessly link my world to my friend's world would be miraculous.

**Comment by qouteall** [comment]
https://qouteall.fun/immptl/wiki/Miscellaneous.html#could-a-portal-link-to-another-server

**Comment by omixann** [comment]
Oh so I haven't been the first one to think about that... probably won't be the last one either.

Sorry for the noise!
