### ISSUE TITLE
Water renders twice outside of portal if a portal is rendering.

### ISSUE THREAD

**Issue by TwistedZero** [qouteall/ImmersivePortalsMod#118]
Without portal:
![2020-03-26_01 52 44](https://user-images.githubusercontent.com/51268715/77602518-a01d0f00-6f05-11ea-98ab-68e600f3b23b.png)
With portal:
![2020-03-26_01 52 53](https://user-images.githubusercontent.com/51268715/77602570-bc20b080-6f05-11ea-84cf-f0ee9db71098.png)

I am using the following versions (as reported by MultiMC):
Minecraft: 20w12a
Fabric Loader: 0.7.8+build.189
Fabric API: 0.5.5+build.311-1.16
ImmersivePortals: 0.4

**Comment by OpenSauce04** [comment]
I can confirm that this still happens in 20w17a

**Comment by qouteall** [comment]
should be fixed
