### ISSUE TITLE
[BUG] Portal-in-portal not rendering w. Nether Portal Overlay enabled

### ISSUE THREAD

**Issue by Shazuli** [qouteall/ImmersivePortalsMod#1181]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

With `netherPortalOverlay` enabled other portals are not rendered through portals:

![2022-10-01_18 15 19](https://user-images.githubusercontent.com/9884180/193418540-7a98121e-d3b7-49d0-81b8-2c9954b3ad50.png)
![2022-10-01_18 15 22](https://user-images.githubusercontent.com/9884180/193418547-e7819106-60b6-409f-8ab7-d8d710257de5.png)

**Comment by qouteall** [comment]
Will be fixed in the next version
