### ISSUE TITLE
crazy console spam upon entering back into overworld from nether(1.14.4-frabric-immersive-portals-0.9)

### ISSUE THREAD

**Issue by SDUBZ** [qouteall/ImmersivePortalsMod#12]
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/3511836/latest.log)
immersive-portals-0.9

**Comment by qouteall** [comment]
It's a mod compatibility issue. Which mod you installed is correlated to beds?

**Comment by SDUBZ** [comment]
umm the only thing to do with beds is bettersleeping as far as i know off top of my head

**Comment by qouteall** [comment]
It seems not this mod.

**Comment by qouteall** [comment]
That mod mixins getSleepingDirection method
