### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by ItsZer0here** [qouteall/ImmersivePortalsMod#1206]
I can't use the gravity function in 1.19.2, so could you add support for Up and down and all around?

**Comment by qouteall** [comment]
Use this https://modrinth.com/mod/gravity-api

**Comment by ItsZer0here** [comment]
when i try to use it in 1.19.2, it crashes before opening

**Comment by ItsZer0here** [comment]
it seems gravity api isn't compatible with versions newer than 1.19

**Comment by ghost** [comment]
it is

**Comment by ItsZer0here** [comment]
rly?

**Comment by ItsZer0here** [comment]
i just switched to quilt, and apparentyl it supports fabric mods so all fixed
