### ISSUE TITLE
Cannot exit Dimension Stack

### ISSUE THREAD

**Issue by Eli-Eli-Oh** [qouteall/ImmersivePortalsMod#1208]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

No

### Describe the issue

Whenever I try to click finish to exit the menu, it just brings up the prompt to add dimensions, making it impossible to leave. The issue also occurs when I press esc. This literally just makes it so I cannot leave the dimension stack menu, meaning I cannot use dimension stacking until this is fixed.

**Comment by VexianEmpire** [comment]
If this doesn't happen with only Immersive Portals and Fabric API installed, can you post the full mod list?

**Comment by qouteall** [comment]
Does this issue occur with only Immersive Portals and Fabric API?

**Comment by Sluss21** [comment]
Hello, I'm having the same issue and perhaps this would help. Whenever I try to exit it takes me to the add dimension page but only has the default three. The Minecraft log also says 
[04:46:51] [Render thread/INFO]: Getting the dimension list 
[04:46:51] [Render thread/ERROR]: Null registry access
 [04:46:51] [Render thread/ERROR]: Null WorldGen settings
 
 Also, I was able to use the in-game command to set up dimension stacking. This bug has only affected world creation so far.

**Comment by qouteall** [comment]
@Sluss21 Are you using the Forge version? If so, upgrade the mod version.
