### ISSUE TITLE
immersive portals is acting like it isn't downloaded

### ISSUE THREAD

**Issue by Boombox96** [qouteall/ImmersivePortalsMod#1211]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

Immersive portals is acting like it isn't downloaded when I have the fabric api and fabric itself

**Comment by Redd56** [comment]
?

**Comment by qouteall** [comment]
Install mod menu to check whether you successfully installed the mod.

**Comment by Boombox96** [comment]
it work weeks ago but now when i open it it dosent

**Comment by qouteall** [comment]
Does this mod show up in the mod menu?
