### ISSUE TITLE
[Enhancement] Easier way to create custom portals

### ISSUE THREAD

**Issue by emoandproud** [qouteall/ImmersivePortalsMod#1215]
What if there was an item similar to the debug stick, but used to make portals?

It could be used like this:

1. Click on 4 corners with the stick
2. The stick saves those coordinates
3. Click on 4 other corners
4. Two linked portals are created

It could also be used for things like configuring where a portal leads to, by clicking on one portal, and then another, you could link them together.

**Comment by qouteall** [comment]
It's being considered

**Comment by TheSnugget** [comment]
would be helpful for large portals

**Comment by qouteall** [comment]
Already implemented by portal wand.
