### ISSUE TITLE
I uninstalled Immersive Portals and now the game crashes when I go through portals

### ISSUE THREAD

**Issue by Fireheart318** [qouteall/ImmersivePortalsMod#1216]
I'm on a 1.19.2 server running Fabric. If I enter a nether portal from either direction, the game tries to load the dimension and then black-screen crashes. Exit Code: 1. When I load the game up again, I'm on the other side of the portal (like I should be) and everything is fine until I use a portal again, when the cycle repeats.
I only had the mod installed bc we were using it on a modded server. After a bit, we convinced the admin to get rid of IP and I uninstalled the mod. It was then that this issue started. I'm now on our vanilla server and I'm still experiencing the issue.
Crash report - https://pastebin.com/9MJ615Df
Mod list - https://imgur.com/a/09YMP80

**Comment by qouteall** [comment]
The JVM crash is related to rendering. Someone experienced similar issue and avoided the issue by installing sodium. You can try installing sodium. Imgur is down now so I can't see the mod list.

**Comment by qouteall** [comment]
I need to know whether it's a world file corruption. Does it crash when loading that world without any mod (backup the world before testing)? If not, this is an issue of other mods, not immptl, because you said that it crashes without immptl.

**Comment by Fireheart318** [comment]
It's a server. Nobody else has issues like I have. This exact mod list doesn't have issues on my other computer.
Would reinstalling MC fix it? What landmines could I step on when reinstalling? Keybinds? Video settings?

**Comment by Lolothepro** [comment]
https://github.com/CaffeineMC/sodium-fabric/issues/1486 ?

**Comment by qouteall** [comment]
It seem to be an issue related to videocard or videocard driver. This is probably not an issue of ImmPtl.

**Comment by qouteall** [comment]
Nvidia driver issue. Install Sodium to workaround.
