### ISSUE TITLE
Game crashes when i enter my world with sodium

### ISSUE THREAD

**Issue by Whatares** [qouteall/ImmersivePortalsMod#1217]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

No

### Describe the issue

When i enter my world, it loads to 100% then crashes the world with sodium on. It loads fine without sodium but with it, it crashes.
(im laggy without sodium so i need it. doesnt work with optifabric)

**Comment by Lolothepro** [comment]
crash report?
