### ISSUE TITLE
Collision incorrect with the portal that have rotating transformation

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#122]

**Comment by LoganDark** [comment]
lovely gif showing me phasing through the walls next to a portal with rotating transformation

![](https://user-images.githubusercontent.com/4723091/79850655-1718bc80-8379-11ea-9003-cc0d7202666e.gif)

**Comment by deli73** [comment]
have experienced this even when there's the same wall on both sides of the portal. also occasionally found ourselves slipping into the floor when moving quickly.

**Comment by qouteall** [comment]
Fixed
