### ISSUE TITLE
Portal does (not) exist

### ISSUE THREAD

**Issue by i-rember** [qouteall/ImmersivePortalsMod#1227]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

The portal does not exist but it also does.
Edit: For more clarification: I can see through the portal, but not enter it.

**Comment by qouteall** [comment]
What do you mean by "cannot enter it"? Crash when entering?

**Comment by TeraByte-Official** [comment]
Well, if I try to enter it, the

**Comment by i-rember** [comment]
If I try to enter it, I just go to the other face of the portal.

**Comment by qouteall** [comment]
Does it happen to all nether portals? Does it happen to end portals?

**Comment by qouteall** [comment]
Close because no reply.
