### ISSUE TITLE
The sky seems to act weird with vanilla settings? (Fabric 1.15.2)

### ISSUE THREAD

**Issue by Bambuzl-Byte** [qouteall/ImmersivePortalsMod#123]
![2020-03-27_10 31 53](https://user-images.githubusercontent.com/62759540/77773028-08a7e100-7017-11ea-80c4-a120530389df.png)

**Comment by CraftyPotatoes** [comment]
1.15.2 Latest Fabric

**Comment by qouteall** [comment]
Are you using dimension stack?

**Comment by Jarfeh** [comment]
I have the same problem as him, using optifabric beta 7 and optifine 1.15.2 G1 pre10. I can say that I am using dimension stack

**Comment by qouteall** [comment]
I changed the global portal area rendering so that this is less likely to show up
