### ISSUE TITLE
euler commands can only take integer sizes, and dont work with decimel

### ISSUE THREAD

**Issue by Vexxen1** [qouteall/ImmersivePortalsMod#1232]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

When you use the command:
/portal euler make_portal ~ ~ ~ ~ ~ 1.25 2.5 1
The command errors, and says that the size is the issue.
When you do this:
/portal euler make_portal ~ ~ ~ ~ ~ 1 2 1
It works.

**Comment by Vexxen1** [comment]
Sorry for the issue spam, put it all into 1 issue, you can delete this post:
https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1236

**Comment by qouteall** [comment]
Going to fix in the next version

**Comment by qouteall** [comment]
fixed
