### ISSUE TITLE
euler make_portal does not use nbt imputed

### ISSUE THREAD

**Issue by Vexxen1** [qouteall/ImmersivePortalsMod#1233]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

`/portal euler make_portal ~ ~ ~ ~ ~ 1 2 1 {Tags:["test"]}`
summons a portal without the nbt imputed.

**Comment by Vexxen1** [comment]
Sorry for the issue spam, put it all into 1 issue, you can delete this post:
https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1236

**Comment by qouteall** [comment]
Currently it only controls portal-specific nbts. Going to make it control all entity nbt in the next version.

**Comment by qouteall** [comment]
fixed
