### ISSUE TITLE
"/portal euler set_other_side" sets portals upsidedown

### ISSUE THREAD

**Issue by Vexxen1** [qouteall/ImmersivePortalsMod#1235]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

Run the command:
`/execute as @e[type=immersive_portals:portal,sort=nearest,limit=1] run portal euler set_other_side ~ ~ ~ ~ ~`
it will set the rotation upside down.

**Comment by Vexxen1** [comment]
Sorry for the issue spam, put it all into 1 issue, you can delete this post:
https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1236

**Comment by qouteall** [comment]
~~Currently the euler angle rotation correspond to the other side's facing rotation. You want it to be the opposite?~~

**Comment by qouteall** [comment]
I see what do you mean by upside down now.

**Comment by qouteall** [comment]
The upside-down issue is caused by the mod's reverse portal entity linking rule. ImmPtl currently flips axisH to create the flipped and reverse portal. Changing it to axisW will fix the upside-down issue, but also change existing portal linking status and may break the portals of existing worlds.

**Comment by qouteall** [comment]
fixed
