### ISSUE TITLE
Euler Command Issues

### ISSUE THREAD

**Issue by Vexxen1** [qouteall/ImmersivePortalsMod#1236]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes, this was done using version 
[v2.4.3-mc1.19.3](https://github.com/iPortalTeam/ImmersivePortalsMod/releases/tag/v2.4.3-mc1.19.3)
In minecraft 1.19.3

### Describe the issue

A video Showing all the issues, much better then in text form.
https://www.youtube.com/watch?v=ehEiGFc7mvY

**Comment by Vexxen1** [comment]
The test world i used, with a rig to make sure it works:
https://www.dropbox.com/s/2nm0u06njihbprq/Euler%20Tests.zip?dl=0

**Comment by Vexxen1** [comment]
You may need to see what happens for the y rot as well, make sure that works.

**Comment by qouteall** [comment]
The design that the destination is 10 blocks above the portal is to make the portal not invisible. If the portal destination is the same as origin, the portal is almost invisible and may cause confusion. As you proabably want to set the destination after summoning the portal, the initial destination doesn't matter.

**Comment by qouteall** [comment]
I changed the portal linking rule. Going to test how much it affects.

**Comment by qouteall** [comment]
I made some fixes in preview version 2.4.4

https://github.com/iPortalTeam/ImmersivePortalsMod/releases/tag/v2.4.4-mc1.19.3
