### ISSUE TITLE
Incompatible with Sodium 4.8 and Iris 1.5.1 !!!

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [qouteall/ImmersivePortalsMod#1238]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

No

### Describe the issue

When in install these versions of fabric api, Immersive Portals, Iris and Sodium:

Immersive Portals: 2.4.4
Iris: 1.5.1
Fabric API: 0.72.0
Sodium: 4.8 build 22
Fabric Loader: 0.14.12

![image](https://user-images.githubusercontent.com/88291316/210978096-1d0bf1b7-bb4c-4617-b639-3b9f72b49f10.png)

### Post the log here

```shell
https://mclo.gs/JLQhrT0
```
Minecraft process ID: 172

[11:02:23] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[11:02:23] [main/WARN]: Mod resolution failed
[11:02:23] [main/INFO]: Immediate reason: [NEG_HARD_DEP immersive_portals 2.4.4 {breaks iris @ [<1.5.0 || >1.5.0]}, ROOT_FORCELOAD_SINGLE immersive_portals 2.4.4, ROOT_FORCELOAD_SINGLE iris 1.5.1]
[11:02:23] [main/INFO]: Reason: [NEG_HARD_DEP immersive_portals 2.4.4 {breaks iris @ [<1.5.0 || >1.5.0]}, NEG_HARD_DEP immersive_portals 2.4.4 {breaks sodium @ [<0.4.7 || >0.4.7]}]
[11:02:23] [main/INFO]: Fix: add [], remove [iris 1.5.1], replace [[immersive_portals 2.4.4] -> add:immersive_portals 1 ([(-∞,∞)])]
[11:02:23] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'Iris' (iris) 1.5.1 (/home/booba/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.19.3/.minecraft/mods/iris-mc1.19.3-1.5.1.jar).
	 - Replace mod 'Immersive Portals' (immersive_portals) 2.4.4 with any version that is compatible with:
		 - sodium 0.4.8+build.22
Unmet dependency listing:
	 - Mod 'Immersive Portals' (immersive_portals) 2.4.4 is incompatible with any version before 1.5.0 or any version after 1.5.0 of mod 'Iris' (iris), but a matching version is present: 1.5.1!
	 - Mod 'Immersive Portals' (immersive_portals) 2.4.4 is incompatible with any version before 0.4.7 or any version after 0.4.7 of mod 'Sodium' (sodium), but a matching version is present: 0.4.8+build.22!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[?:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[?:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[?:?]
Process exited with code 1.

**Comment by Enoratato** [comment]
+1

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'Iris' (iris) 1.5.1 (/home/enora/.local/share/PrismLauncher/instances/1.19.3(1)/.minecraft/mods/iris-mc1.19.3-1.5.1.jar).
	 - Replace mod 'Immersive Portals' (immersive_portals) 2.4.4 with any version that is compatible with:
		 - sodium 0.4.8+build.22
Unmet dependency listing:
	 - Mod 'Immersive Portals' (immersive_portals) 2.4.4 is incompatible with any version before 1.5.0 or any version after 1.5.0 of mod 'Iris' (iris), but a matching version is present: 1.5.1!
	 - Mod 'Immersive Portals' (immersive_portals) 2.4.4 is incompatible with any version before 0.4.7 or any version after 0.4.7 of mod 'Sodium' (sodium), but a matching version is present: 0.4.8+build.22!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

**Comment by Schweeeeeeeeeeeeeeee** [comment]
I just edited some text in the mod file from 1.5.0 to 1.5.1 and from 4.7 to 4.8 it now seems to work, though i dont qurantee anything for the time you  can use the edited mod if you want until this really gets resolved.

heres what i changed:
![image](https://user-images.githubusercontent.com/88291316/211018348-a76c9b1d-cc83-46fb-b673-469f594c6694.png)
you can download it here:
https://cdn.discordapp.com/attachments/887419980163973190/1060907866640367646/immersive-portals-2.4.4-mc1.19.3-fabric.jar

**Comment by Schweeeeeeeeeeeeeeee** [comment]
> +1
> 
> Incompatible mod set! net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set! A potential solution has been determined: - Remove mod 'Iris' (iris) 1.5.1 (/home/enora/.local/share/PrismLauncher/instances/1.19.3(1)/.minecraft/mods/iris-mc1.19.3-1.5.1.jar). - Replace mod 'Immersive Portals' (immersive_portals) 2.4.4 with any version that is compatible with: - sodium 0.4.8+build.22 Unmet dependency listing: - Mod 'Immersive Portals' (immersive_portals) 2.4.4 is incompatible with any version before 1.5.0 or any version after 1.5.0 of mod 'Iris' (iris), but a matching version is present: 1.5.1! - Mod 'Immersive Portals' (immersive_portals) 2.4.4 is incompatible with any version before 0.4.7 or any version after 0.4.7 of mod 'Sodium' (sodium), but a matching version is present: 0.4.8+build.22! at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

test

**Comment by Schweeeeeeeeeeeeeeee** [comment]
> +1
> 
> Incompatible mod set! net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set! A potential solution has been determined: - Remove mod 'Iris' (iris) 1.5.1 (/home/enora/.local/share/PrismLauncher/instances/1.19.3(1)/.minecraft/mods/iris-mc1.19.3-1.5.1.jar). - Replace mod 'Immersive Portals' (immersive_portals) 2.4.4 with any version that is compatible with: - sodium 0.4.8+build.22 Unmet dependency listing: - Mod 'Immersive Portals' (immersive_portals) 2.4.4 is incompatible with any version before 1.5.0 or any version after 1.5.0 of mod 'Iris' (iris), but a matching version is present: 1.5.1! - Mod 'Immersive Portals' (immersive_portals) 2.4.4 is incompatible with any version before 0.4.7 or any version after 0.4.7 of mod 'Sodium' (sodium), but a matching version is present: 0.4.8+build.22! at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

I just edited some text in the mod file from 1.5.0 to 1.5.1 and from 4.7 to 4.8 it now seems to work, though i dont qurantee anything for the time you  can use the edited mod if you want until this really gets resolved.

heres what i changed:
![image](https://user-images.githubusercontent.com/88291316/211018348-a76c9b1d-cc83-46fb-b673-469f594c6694.png)
you can download it here:
https://cdn.discordapp.com/attachments/887419980163973190/1060907866640367646/immersive-portals-2.4.4-mc1.19.3-fabric.jar

**Comment by Schweeeeeeeeeeeeeeee** [comment]
> +1
> 
> Incompatible mod set! net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set! A potential solution has been determined: - Remove mod 'Iris' (iris) 1.5.1 (/home/enora/.local/share/PrismLauncher/instances/1.19.3(1)/.minecraft/mods/iris-mc1.19.3-1.5.1.jar). - Replace mod 'Immersive Portals' (immersive_portals) 2.4.4 with any version that is compatible with: - sodium 0.4.8+build.22 Unmet dependency listing: - Mod 'Immersive Portals' (immersive_portals) 2.4.4 is incompatible with any version before 1.5.0 or any version after 1.5.0 of mod 'Iris' (iris), but a matching version is present: 1.5.1! - Mod 'Immersive Portals' (immersive_portals) 2.4.4 is incompatible with any version before 0.4.7 or any version after 0.4.7 of mod 'Sodium' (sodium), but a matching version is present: 0.4.8+build.22! at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

I just edited some text in the mod file from 1.5.0 to 1.5.1 and from 4.7 to 4.8 it now seems to work, though i dont qurantee anything for the time you  can use the edited mod if you want until this issue really gets resolved.

heres what i changed:
![image](https://user-images.githubusercontent.com/88291316/211018348-a76c9b1d-cc83-46fb-b673-469f594c6694.png)
you can download it here:
https://cdn.discordapp.com/attachments/887419980163973190/1060907866640367646/immersive-portals-2.4.4-mc1.19.3-fabric.jar

**Comment by Enoratato** [comment]
I'll back up my current minecraft then and use the edited jar you are using for now. I appreciate it a lot for you making a temporary fix.

**Comment by qouteall** [comment]
fixed in 2.4.5
