### ISSUE TITLE
Logging out while going through a portal seems to create a broken clone of the player.

### ISSUE THREAD

**Issue by DaveyL2013** [qouteall/ImmersivePortalsMod#124]
I was testing the glitches with shaders and this mod combined, and decided to relog while sprinting through a portal. When I logged back in I got jumpscared by a flashing copy of me teleporting up & down. Installed mods were this, the latest fabric api, and Optifabric. Breaking the portal did not fix the issue and neither did reloading the world again. Here is a screenshot of the glitch.
![2020-03-28_16 47 11](https://user-images.githubusercontent.com/20153257/77833586-edbb9680-7114-11ea-89fe-b38a33f6b220.png)
I will update if the glitch can occur without other mods.

**Comment by DaveyL2013** [comment]
I was able to reproduce the glitch without other mods, here is another screenshot and the log.
![2020-03-28_17 06 51](https://user-images.githubusercontent.com/20153257/77833853-c665c900-7116-11ea-91fa-c0eb3f69df4a.png)
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/4397895/latest.log)
It seems to be teleporting me right before I log out, and again when I log in. This could be related to the glitch.

**Comment by qouteall** [comment]
Fixed. It will be in the next version.
