### ISSUE TITLE
When using Dimension stacking, I crash when entering the new dimension.

### ISSUE THREAD

**Issue by TheOfficialNapp** [qouteall/ImmersivePortalsMod#1242]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

When I enable Dimension stacking for the nether underneath, I can enter the dimension up to about 5 blocks before crashing. I tried increasing RAM but I don't know how to do so for memory. Tried this bare with only Fabric Api and still have the same issue. 

Disabling the function ofc allows me to play as normal. Crash Log down below. 

[hs_err_pid4468.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/10367543/hs_err_pid4468.log)

Edit: Crash whilst around lit nether portal. Allocated 46% of ram so idk how this would be a mem issue.
Log: 
 
[crash-2023-01-08_04.22.39-client.txt](https://github.com/iPortalTeam/ImmersivePortalsMod/files/10368147/crash-2023-01-08_04.22.39-client.txt)

**Comment by qouteall** [comment]
It's probably a Nvidia driver bug. You can use MC 1.19.3 and install Sodium. Sodium contains a workaround of the driver bug.

https://github.com/CaffeineMC/sodium-fabric/issues/1486

**Comment by TheOfficialNapp** [comment]
> 
[crash-2023-01-08_20.11.03-client.txt](https://github.com/iPortalTeam/ImmersivePortalsMod/files/10369993/crash-2023-01-08_20.11.03-client.txt)
Updated to 1.19.3 Allocated 40% mem, updated driver.
Edit: Forgot you suggested using sodium. Trying now.

Edit2: I tried it and that works, I tried 1.19.2 with sodium and that works as well. Thank you
