### ISSUE TITLE
Portal rendering abnormal when seeing from under water

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#125]

**Comment by nobleRadical** [comment]
I'm experiencing this problem in 1.17. 
![2021-08-02_01 41 37](https://user-images.githubusercontent.com/88314680/127831655-c6bf7e96-f239-493a-bcaf-0355cf14ebc7.png)
![2021-08-02_01 42 29](https://user-images.githubusercontent.com/88314680/127831661-b6904f5f-cd29-467f-a419-889d2bc6250b.png)

The only mod conflict I could even see the possibility of would be Lamb's dynamic lights, so I don't think this is a conflict.

Modlist:
AdditionalEnchantedMiner-1.17-fabric-17.0.338
antiqueatlas-6.0.0-fabric-mc1.17.1 (API)
appleskin-fabric-mc1.17-2.1.1
architectury-2.3.22-fabric (API)
betterbiomeblend-1.17.0-1.2.7-fabric
Blur-2.2.1-1.17+fabric
cloth-config-5.0.34-fabric (API)
Croptopia-1.17-FABRIC-1.6.0
fabric-api-0.37.1+1.17 (API)
fabric-language-scala-1.1.0+scala.2.13.6-fat
IKnowWhatImDoing-3.1.0-fabric
immersive-portals-0.17-mc1.17.1-fabric
lambdynamiclights-2.0.2+1.17
modmenu-2.0.4
RoughlyEnoughItems-6.0.264-alpha-fabric

**Comment by qouteall** [comment]
Fixed https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.19-1.17
