### ISSUE TITLE
How about gravity changing in 1.19.3?

### ISSUE THREAD

**Issue by ItsZer0here** [qouteall/ImmersivePortalsMod#1253]
Do I have to ask the Gravity API devs to port it?

**Comment by qouteall** [comment]
I already ported it. https://github.com/qouteall/Gravity-Api/releases

**Comment by ItsZer0here** [comment]
thx

**Comment by ItsZer0here** [comment]
I tried it in Quilt not Fabric
Maybe that's why it gave me an error

**Comment by ItsZer0here** [comment]
like right now

**Comment by ItsZer0here** [comment]
What if I switch back to Fabric?
Mayeb that will solve the problem.

**Comment by ItsZer0here** [comment]
the problem I got right after I downloaded the 1.19.3 version of Gravity API

**Comment by ItsZer0here** [comment]
Downloaded it, installed it, didn't work, switched to Fabric, now will it work?
And it did.

**Comment by ItsZer0here** [comment]
(I was using Quilt so I also switched from QSL to Fabric API too)
