### ISSUE TITLE
Not compatible with Better MC

### ISSUE THREAD

**Issue by Adzeiros** [qouteall/ImmersivePortalsMod#1258]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

More of just letting you know it is not compatible with the Better MC modpack...

Which I find a little Odd as it is a Vanilla+ modpack, but I cant say what would be conflicting with it.

Fabric Version 0.14.12

Minecraft version 1.19.2

Immersive Portals Version(s) 2.2.5, 2.2.3, 2.2.0 (tested all that were compatible with 1.19.2)

### Post the log here

```shell
https://pastebin.com/RSJfH1eG

Couldn't paste here
```

**Comment by qouteall** [comment]
In 1.19.2, use iris 1.4.0
