### ISSUE TITLE
Question about compatibility with Smaller Nether Portals

### ISSUE THREAD

**Issue by vico93** [qouteall/ImmersivePortalsMod#1259]
Does Immersive Portals works with [Smaller Nether Portals](https://modrinth.com/mod/smaller-nether-portals)? I'm asking preemptively because mod compatibility in IP is complicated due to how it works.

Does it need any work on SNP side to get a compatibility to work (if not yet)?

Related issue i made on SNP side: https://github.com/ricksouth/serilum-mc-mods/issues/1581

**Comment by RemagOfficial** [comment]
IP supports making smaller portals itself

**Comment by vico93** [comment]
Sorry, didnt know about this information.
