### ISSUE TITLE
End Portal is invulnerable when removing the frames

### ISSUE THREAD

**Issue by FRBFStudios** [qouteall/ImmersivePortalsMod#1265]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

No

### Describe the issue

If you remove the frames of a lit portal, the portal blocks won't disappear because there aren't any, so you have an invulnerable End Portal that can only be removed by uninstalling the mod, loading the world and then reinstalling it. Please fix for my creative world!

**Comment by Nick1st** [comment]
Point at the portal, and use the command `/portal delete_portal`.

**Comment by FRBFStudios** [comment]
Ah thank you
