### ISSUE TITLE
My game crashes when I open the Nether Portal.

### ISSUE THREAD

**Issue by SUPPE228** [qouteall/ImmersivePortalsMod#1269]
it works can play it cnpletly Find until I open the nether Portal then my game crashes can please someone pls help?
Crash log:
[hs_err_pid1648.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/10609120/hs_err_pid1648.log)

**Comment by Lolothepro** [comment]
use Sodium with Immersive Portal

**Comment by qouteall** [comment]
A nvidia driver bug. https://github.com/CaffeineMC/sodium-fabric/issues/1486
Install Sodium to workaround this issue.
