### ISSUE TITLE
无法获取 miniScaled模组中的操作棒

### ISSUE THREAD

**Issue by soul-zym** [qouteall/ImmersivePortalsMod#1277]
![image](https://user-images.githubusercontent.com/52745365/218262697-62b5b92b-8ef3-40c9-ab22-28ed7e64acdb.png)
即使在创造模式中依然无法获取
-----
这是这个世界添加的全部模组
![image](https://user-images.githubusercontent.com/52745365/218262749-82704d9c-87b8-4b9e-8705-9241d9f3d042.png)
-----
游戏版本为1.19
使用的Java版本为
![image](https://user-images.githubusercontent.com/52745365/218262834-d71b43d5-28aa-48ba-9242-4ff5153211d3.png)

**Comment by qouteall** [comment]
这些功能是1.19.3版本的MiniScaled中才有的，建议用新版本

**Comment by soul-zym** [comment]
那如何才能在1.19版本内做到控制box的大小呢？32大小对我来说还是有点小了

**Comment by qouteall** [comment]
用那个物品对box右键一下就能扩展，用手右键就缩小
