### ISSUE TITLE
Random Crash When Loading World In Quilt

### ISSUE THREAD

**Issue by defautluser0** [qouteall/ImmersivePortalsMod#1280]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Fabric API?

No

### Describe the issue

When i try to open any world it crashes. Im using quilt, not fabric and with only quilted fabric api and immersive portals it does not crash.
[crash-2023-02-16_18.51.40-client.txt](https://github.com/iPortalTeam/ImmersivePortalsMod/files/10759050/crash-2023-02-16_18.51.40-client.txt)
[latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/10759053/latest.log)

**Comment by qouteall** [comment]
In MC1.19.2, the compatible Iris version is 1.4.0. Use Iris 1.4.0.

In Fabric it will not let the game launch with the wrong Iris version. But Quilt seems ignoring the Fabric mod incompatibility information.
