### ISSUE TITLE
World not loading properly with this mod

### ISSUE THREAD

**Issue by TheUntamed** [qouteall/ImmersivePortalsMod#129]
I have the issue, that my overworld is not loading properly if this mod is installed.
I'm playing on Mc 1.15.2 with Forge 31.1.30 and Immersive Portals v. 0.9

I'm playing a pack with other mods, but I could narrow the problem down to this mod. If I just disable this mod everything is loading fine. If I activate it the spawn is generated normally but if I start exploring, after a few chunks the world stops loading. No more chunks are generated. And I haven't even placed and activated a portal.

I tested this with biomes o plenty and TerraForge world generation. Both world generations worked fine without the mod and had the problems mentioned above when the mod was integrated.

I'm not using any shaders or texture packs.

**Comment by qouteall** [comment]
Open F3 and see the memory ussge. Is it always high?
Can you reproduce this issue when only this mod is installed?
