### ISSUE TITLE
Incompatible with Mine Cells mod.

### ISSUE THREAD

**Issue by Zarepheth** [qouteall/ImmersivePortalsMod#1290]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Fabric API?

No

### Describe the issue

After adding Immersive Portals to the Medieval MC (FABRIC) modpack, the game crashes on startup. Removing either Immersive Portals or Mine Cells will prevent the crash.

Running with just Fabric API, Mine Cells, and Immersive Portals will get far enough to attempt creation of a new world. However, the game will crash during world creation (or upon entering it).

Compatibility issue reported with [Mine Cells](https://github.com/mim1q/MineCells/issues/30), includes the log from the crash (_no crash report was generated - may have additional mod compatibility issues_).

Logs from testing just Fabric, Mine Cells, and Immersive Portals:

- [crash-2023-02-25_18.16.49-client.txt](https://github.com/iPortalTeam/ImmersivePortalsMod/files/10832603/crash-2023-02-25_18.16.49-client.txt)
- [latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/10832604/latest.log)

**Comment by qouteall** [comment]
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifySizeLimitWhenReadingPacket(I)I in imm_ptl.mixins.json:common.networking.MixinClientboundCustomPayloadPacket from mod imm_ptl_core failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap imm_ptl_core-refmap.json

```

**Comment by mim1q** [comment]
Hi, Mine Cells creator here, I'll try to get this fixed on my side :)

**Comment by Zarepheth** [comment]
@mim1q fixed the issue on their end.
