### ISSUE TITLE
doesnt work with optifabric

### ISSUE THREAD

**Issue by Artyx1** [qouteall/ImmersivePortalsMod#1291]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Fabric API?

Select One

### Describe the issue

when i try to launch immersive portals 2.3.1 with optifabric 1.13.16 it crashes

**Comment by SalTeyJek004** [comment]
the dev has stopped making the mod compatible with optifine, use the sodium mod for preformance, and the iris mod for shaders

**Comment by qouteall** [comment]
https://qouteall.fun/immptl/wiki/Miscellaneous.html#optifine-compatibility
