### ISSUE TITLE
How did i fix this?

### ISSUE THREAD

**Issue by montewyn** [qouteall/ImmersivePortalsMod#1295]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Fabric API?

Select One

### Describe the issue

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Immersive Portals' (immersive_portals) 2.5.1 with any version that is compatible with:
		 - sodium 0.4.8+build.22
Unmet dependency listing:
	 - Mod 'Immersive Portals' (immersive_portals) 2.5.1 is incompatible with any version before 0.4.9 or any version after 0.4.9 of mod 'Sodium' (sodium), but a matching version is present: 0.4.8+build.22!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by qouteall** [comment]
Use sodium 0.4.8

**Comment by qouteall** [comment]
Use sodium 0.4.9

**Comment by montewyn** [comment]
> Use sodium 0.4.9

ok, thanks
