### ISSUE TITLE
crash why exploring I.P: 0.10

### ISSUE THREAD

**Issue by SDUBZ** [qouteall/ImmersivePortalsMod#13]
[crash-2019-08-19_16.28.20-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/3514496/crash-2019-08-19_16.28.20-client.txt)

**Comment by qouteall** [comment]
show the log

**Comment by SDUBZ** [comment]
if i can trigger it again sorry forgot to get the log from when it happens
[2019-08-19-5.log](https://github.com/qouteall/ImmersivePortalsMod/files/3516187/2019-08-19-5.log)
i this is it seems closest time and date

**Comment by SDUBZ** [comment]
server:
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/3520429/latest.log)
[crash-2019-08-20_20.24.44-server.txt](https://github.com/qouteall/ImmersivePortalsMod/files/3520430/crash-2019-08-20_20.24.44-server.txt)
log and crash when it happend again
client:
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/3520436/latest.log)

**Comment by qouteall** [comment]
the first crash and the second crash seem to have different causes.
The second one is caused by the server too laggy. Try to put a redstone clock and see how it lags when you travel between dimension. And use /debug start /debug end to profile
