### ISSUE TITLE
Laggy Crash: Memory Acess Violation

### ISSUE THREAD

**Issue by nobleRadical** [qouteall/ImmersivePortalsMod#1303]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Fabric API?

Yes

### Describe the issue

After loading up a world on Fabric 1.19.2, setting a nether portal, and walking though it a few times, Minecraft got progressively laggier until it hardcrashed.

Looks like the JVM crashed, rather than just Minecraft.

This might be out of the scope of the mod; If so, I would love some insight into what might cause this error.

Minecraft 1.19.2
Fabric 0.14.14
Fabric API 0.75.1
Immersive Portals 2.3.1

[crash-report->hs_err_pid56880.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/10998952/hs_err_pid56880.log)
[latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/10998978/latest.log)

**Comment by Lolothepro** [comment]
NVIDIA driver bug

**Comment by qouteall** [comment]
Nvidia driver bug. Sodium contains a workaround to this bug. Try installing Sodium.

**Comment by nobleRadical** [comment]
Worked, thanks!
