### ISSUE TITLE
Rendering artifact with Sildur's Basic Shaders in Iris

### ISSUE THREAD

**Issue by Lolothepro** [qouteall/ImmersivePortalsMod#1306]
### According to your testing, does the issue occur with ONLY MiniScaled mod and Immersive Portals mod and Farbic API?

No

### Describe the issue
Currently, Sildur's Basic Shaders looks like this.

https://user-images.githubusercontent.com/68275908/226188003-a95f58fa-967e-4ea1-9731-04337f0d4173.mp4

**Comment by Cape-City** [comment]
Hi,

this also happens with the higher versions of sildur's shaders, i'm using right now the high variant.

MC Version 1.19.3
Fabric Loader: 0.14.18
Mod version: immersive-portals-2.5.4-mc1.19.3-fabric.jar

**Comment by qouteall** [comment]
Try turning off motion blur and TAA. If that does not help, reopen the issue.
