### ISSUE TITLE
Portals fail at build limit - Cannot target or delete

### ISSUE THREAD

**Issue by Yagarobe** [qouteall/ImmersivePortalsMod#1314]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Fabric API?

Yes

### Describe the issue

I wanted to link my base to the AFK platform of two of my nether farms. In both instances (i only figured out what was going on the second time) the portals I created could not be targeted after creation. They still function (i.e. I can still walk through them,) but i cannot use any commands on them, instead I get the error message "You are not pointing to any non-global portal. (This command cannot process global portals)" These aren't global portals either. 

When I use the F3 + b hotkey to see entity hit boxes, the portal hit box comes up, but i can still not target it. 

When i use the command "/portal  debug list_portals" The portal comes up as a client portal in the nether at the correct coordinates. I believe the system also gives it a number. the string for one of them is as follows:

Portal{83294,south,(minecraft:the_nether 296.5 256.5 8.5) ->(minecraft:the_nether 296.7 100.0 8.7)}

This one is a single way, single facing portal. My question is, is there any way that I can delete it without targeting it? It seems like 83294 is a unique ID for the portal. Is there a command I haven't found yet that will let me alter it without physically looking at it in game? I think because it is above the build limit the system can't "see" it. idk. Anyone got any ideas?

**Comment by qouteall** [comment]
I can confirm the issue.

**Comment by qouteall** [comment]
Fixed in the next version.

**Comment by qouteall** [comment]
Which MC version are you using?

**Comment by Yagarobe** [comment]
MC version: 1.19.3

Fabric Version: 0.14.14
