### ISSUE TITLE
when i turn on complementary shaders this mod crashes the game

### ISSUE THREAD

**Issue by Kotchilla** [qouteall/ImmersivePortalsMod#1315]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Fabric API?

Select One

### Describe the issue

Describe the issue.

**Comment by Kotchilla** [comment]
the game crashes when i turn on complementary shaders while this mod is installed

**Comment by Lolothepro** [comment]
minecraft version?

**Comment by qouteall** [comment]
Provide minecraft version and the mod list.

**Comment by soul514y3r** [comment]
I also crash, I use 1.19.2, and wonder if an update to support iris 1.5.2 will be coming to this version.

**Comment by erazare** [comment]
how are you running shaders if only one version of the mod only supports one version of sodium and hasnt supported optifine since 1.18? unless the info about the mod is inaccurate.
