### ISSUE TITLE
Incompatibility with the map item when it has a non-existent dimension

### ISSUE THREAD

**Issue by rebane2001** [qouteall/ImmersivePortalsMod#1317]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Fabric API?

No

### Describe the issue

When a map item has a custom dimension set that doesn't exist, the game crashes with the following stacktrace:

![image](https://user-images.githubusercontent.com/6316541/230186887-fae034a8-d483-4344-ac51-f724cb307f57.png)

In this specific example a map was generated with MapartCraft that uses a custom dimension to protect it from accidental overwrites/updates, but I imagine there might also be other scenarios where you'd need to load a world with this kind of a map item in it.

**Comment by qouteall** [comment]
You seem to be using MC 1.19. Unfortunately 1.19 is not being maintained because the development effort is limited, it's impossible to maintain every version. It's recommended to use 1.19.3 or 1.19.4 now. If the issue presists in MC 1.19.3 or 1.19.4, reopen the issue.
