### ISSUE TITLE
Feature Request: dimension stack serverconfigs file

### ISSUE THREAD

**Issue by son0fether** [qouteall/ImmersivePortalsMod#1318]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

43.2.8

### ImmersivePortals Version

2.3.4-mc1.19.2

### Latest Log

n/a

### Steps to Reproduce

The dimension stacking works really well, and I am enjoying it. 

However, I'm trying to make a modpack that includes a specific setup for dimension stacking. 

### What You Expected

I would expect the configs to be in a file in the serverconfigs folder in each save.

There's mechanisms for setting default serverconfig files for modpacks, so that would be how a modpack creator could provide that configuration.

### What Happened Instead

The configuration for the stacking seems to be set within the level.dat or other game files. This prevents setting the configuration for a modpack, given the current options.

I'm not aiming to create an adventure map, so distributing a pre-mades world is out. The only other current option seems to be asking players to do the dimension stacking themselves when creating their worlds. There are commands for setting dimensional floor and ceiling portals, but those don't include scaling or flipping options.

### Additional Details

Thanks again for making this mod. I'm having fun building a huge stack of dimensions.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
I'll transfer this to the fabric upstream repository, as this is a feature request.

**Comment by qouteall** [comment]
The latest version allows server-side dimension stack preset, inside ImmPtl config file.
