### ISSUE TITLE
Immersive portals breaking minecraft

### ISSUE THREAD

**Issue by Epicmerwowie** [qouteall/ImmersivePortalsMod#1327]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Fabric API?

Yes

### Describe the issue

So my friend is having a problem with ImmersivePortals were when he joins a world it get stuck on save and crashes. Is there nay way to fix this?

**Comment by qouteall** [comment]
Which mc version? Which mod version? Are the two people using the same mods?

**Comment by Epicmerwowie** [comment]
He tried with 1.18.2 and 1.16.5 fabric and forge. And the lates version that can be installed at the moment, and yes.

**Comment by qouteall** [comment]
Try using MC 1.19.4 Fabric. If it still crashes with the latest version of Immersive Portals, post the crash report.

**Comment by Epicmerwowie** [comment]
Ok

**Comment by Epicmerwowie** [comment]
Thanks it worked now hes not having problems!
