### ISSUE TITLE
Cross portal container block interaction broken?

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#1329]

**Comment by Nick1st** [comment]
I can confirm this in 1.18.2-1.19.2 Fabric. Didn't test 1.19.3/1.19.4, so not sure about those versions.

**Comment by ImSpaceLover** [comment]
Can confirm in 1.19.4 Quilt with latest versions of Quilt, QAPI, Immersive Portals

**Comment by qouteall** [comment]
Probably fixed in the next version (MC 1.19.4)
