### ISSUE TITLE
Clientsided crash with bonsaitrees mod

### ISSUE THREAD

**Issue by winnetrie83** [qouteall/ImmersivePortalsMod#133]
There is a clientsided crash that happens with bonsaitrees mod installed.
This crash only happens when client and server are 2 different instances.
Trying to reproduce this in singleplayer won't work.

What happens and how:

I create a nether portal in the owerworld and i also have somewhere near a bonsaipot.
I enter the nether and go exploring.
I return to my portal and as soon as i come in a certain range the client crashes.
After the client crashed, it will crash again as soon as it connects to the server.

I'm not saying this mod is the cause, but with this mod installed there happens to be several rendering issues too with other mods (just visual).

**Comment by qouteall** [comment]
show the crash report

**Comment by winnetrie83** [comment]
I don't have 1 atm, i deleted the profile on twitch where that crashlog was, because of updates.

**Comment by winnetrie83** [comment]
Well, i have to apologize. It seems to be fixed since IP 0.9. Can't reproduce it with 0.9 but easily with 0.8

**Comment by Kaaybi** [comment]
Hello guys, reopening this, I've got the same problem as well and here are two crash 
 reports:
[crash-2020-04-04_11.51.59-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/4431125/crash-2020-04-04_11.51.59-client.txt)
[crash-2020-04-04_11.50.35-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/4431127/crash-2020-04-04_11.50.35-client.txt)

**Comment by Kaaybi** [comment]
I'm in 0.8, I'm trying immediatly to update to 0.9 and report to you if this fixes it!

**Comment by Kaaybi** [comment]
Updated to 0.11 and works perfectly fine with bonsaitrees!
