### ISSUE TITLE
Front clipping not working with Iris

### ISSUE THREAD

**Issue by ZackNCheeseBB** [qouteall/ImmersivePortalsMod#1335]
### Is it a mod compatibility issue?

Select One

### Minecraft version

Select One

### Describe the issue
[https://www.reddit.com/r/ImmersivePortals/comments/132f2hd/having_an_issue_with_bsl_and_immersive_portals_on/](https://www.reddit.com/r/ImmersivePortals/comments/132f2hd/having_an_issue_with_bsl_and_immersive_portals_on/)

**Comment by qouteall** [comment]
Fixed in 2.6.6. (going to release)
