### ISSUE TITLE
Immersive Portals Compatible with C2ME (Extra: How to remove warning? C2ME = Concurrent Chunk Management Engine)

### ISSUE THREAD

**Issue by Rebel459** [qouteall/ImmersivePortalsMod#1339]
Hi, I’ve noticed, regardless of the warning, that Immersive Portals (2.2.5) has been working fine with C2ME (latest verson for 1.19.2 is alpha 9.9 at the time of this) in my 1.19.2 Fabric modpack (Enhanced Legacy on Modrinth). I was wondering if you could further investigate compatibility and/or provide a way to remove the warning popup, as it is quite annoying to have on a distributed modpack. Thanks

**Comment by qouteall** [comment]
Someone reported that sometimes lighting a nether portal cause it to stuck in loading chunks. it randomly happens. Are you sure that the two mods work fine?

**Comment by qouteall** [comment]
If you are sure that there is no incompatibility, I will remove that.

**Comment by Rebel459** [comment]
I've tested loading portals in very far away chunks a few times, haven't had an issue. If it's ok, I would like to request that if you release a version without the warning, you provide one for 2.2.5, which is compatible with iris and hence what my modpack uses, if it's not too much of a hassle. Could have something to do with hardware maybe, I have a fairly high-end setup but I'm pretty sure there isn't a problem after doing a few tests - it loaded no slower than if I didn't have C2ME installed.

**Comment by qouteall** [comment]
The warning of c2me has been removed for MC 1.19.2. (It checkes from github pages https://github.com/qouteall/immptl_info so no mod update is required)

**Comment by qouteall** [comment]
Because of this issue report, https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1348 , the warning has been re-added

**Comment by Rebel459** [comment]
Yeah, sorry about that. I can say that the issue isn’t random however. It seems to be related to when the portal you load is visible through another portal, as when I did my initial regular tests, there was a 100% success rate, and testing Portal-in-Portal in the Nether had a 100% failure rate, though it needs some more testing
