### ISSUE TITLE
Crash with imersive portals and physics mod

### ISSUE THREAD

**Issue by Mrgaton** [qouteall/ImmersivePortalsMod#1344]
### Is it a mod compatibility issue?

Yes

### Minecraft version

1.19.2

### Describe the issue

Minecraft crashes when entering between portals and sound is sometimes buggy and its not passed between dimensions

[latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/11451393/latest.log)

Oh and when the portal is charging i would put like an animation instead of leaving transparent all it would be just awesome

**Comment by qouteall** [comment]
Duplicate to https://github.com/iPortalTeam/ImmersivePortalsMod/issues/985
