### ISSUE TITLE
Nether Portal mode doesn't work.

### ISSUE THREAD

**Issue by allisnulll** [qouteall/ImmersivePortalsMod#1347]
### Is it a mod compatibility issue?
No

### Minecraft version
1.19.3/1.19.4

### Describe the issue

I want to use other features of the mod besides the immersive nether and end portals. I went to the mod settings and set the portal modes to vanilla assuming it would work for both but it only worked for one. All of the different modes seem to change how the end portals work but the nether portals always stay the same. I can make vanilla portals through crouching but I don't want to crouch everytime I make a portal. I have tried this on both 1.19.3 and 1.19.4 with only sodium, mod menu, and fabric api installed.

**Comment by ImSpaceLover** [comment]
Nether Portal mode and End Portal Mode are separate settings. You need to change both.

**Comment by qouteall** [comment]
Fixed. Will be in the next version (in MC 1.19.4).

**Comment by allisnulll** [comment]
The nether portal mode and end portal mode were the settings I was talking about. Will the next version be compatible with 1.19.3? Is there a way to make it work in the current version? 
I feel annoyed that I can place a regular portal by crouching and that there is a setting right there for what I need, but it just doesn't work. Otherwise, Immersive Portals is a great mod!

**Comment by qouteall** [comment]
built a version for 1.19.3. haven't tested, not sure whether it works. https://github.com/iPortalTeam/ImmersivePortalsMod/releases/tag/v2.5.5-mc1.19.3
