### ISSUE TITLE
C2ME Portal In Portal Issue

### ISSUE THREAD

**Issue by Rebel459** [qouteall/ImmersivePortalsMod#1348]
### Is it a mod compatibility issue?

Yes

### Minecraft version

1.19.2

### Describe the issue

Fabric 1.19.2 with C2ME and Immersive Portals. Stuck loading infinitely, but only when Portal-in-Portal is attempted. Fixed when reloading the world after destroying conflicting portals, until Portal in Portal is attempted again. Needs further testing to verify the exact cause.

**Comment by qouteall** [comment]
Same as https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1036
