### ISSUE TITLE
"...encountered an error during the load_registries event phase" for 1.15.2

### ISSUE THREAD

**Issue by Glowbomb12** [qouteall/ImmersivePortalsMod#135]
Error occurs for both "immersive-portals-0.10(forMc1.15withForge)" and the newer .11 version. I get the error even with the mod loaded by itself.

[latest.txt](https://github.com/qouteall/ImmersivePortalsMod/files/4427768/latest.txt)

**Comment by qouteall** [comment]
Did you install MixinBootstrap?
