### ISSUE TITLE
Using portal wand in multiplayer cause getting kicked

### ISSUE THREAD

**Issue by yeeman236427** [qouteall/ImmersivePortalsMod#1357]
### Is it a mod compatibility issue?

No

### Minecraft version

1.19.4

### Describe the issue

i have a yt video: https://youtu.be/qrHaz0gdD-Y

**Comment by yeeman236427** [comment]
ill add that its two portals in general  not two at the same time as shown in the video,
and after making the second portal any more portals ever made instantly kicks you (unless your the host).
also its any portal not just ones made by the portal stick.

**Comment by qouteall** [comment]
~~Are you using other mods? Such as c2me or essential?~~

**Comment by qouteall** [comment]
It seem to be an issue of portal wand.

**Comment by qouteall** [comment]
The server and client should both use the latest version of the mod. Does the issue still occur when the server and client are both using the latest?
