### ISSUE TITLE
Incompatable with Iris Shaders 1.6.2

### ISSUE THREAD

**Issue by Murphmario** [qouteall/ImmersivePortalsMod#1360]
### Is it a mod compatibility issue?

Yes

### Minecraft version

1.19.2

### Describe the issue

Game crashed upon startup, tested with Iris Shaders 1.6.2 and Immersive Portals 2.3.2 on a fresh Fabric 0.14.21 install.
[latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/11583964/latest.log)

**Comment by qouteall** [comment]
just use iris 1.4.1
