### ISSUE TITLE
does anyone know how to fix this?

### ISSUE THREAD

**Issue by montewyn** [qouteall/ImmersivePortalsMod#1364]
### Is it a mod compatibility issue?

No

### Minecraft version

1.19

### Describe the issue

![2023-05-31_16 43 10](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/112774231/be2925d0-b1a5-467b-ac38-cc3f9978c4f8)

**Comment by qouteall** [comment]
Turn off fabulous mode. Could also be mod compatibility issue.
