### ISSUE TITLE
Blocks in front of target plane get rendered if far away from portal

### ISSUE THREAD

**Issue by QuImUfu** [qouteall/ImmersivePortalsMod#1369]
### Is it a mod compatibility issue?

No

### Minecraft version

1.20

### Describe the issue

If you place a thin block in front of the remote location (e.g. Trapdoor), then move quite far away from the portal, the block will appear in front of the current Portal. 

I debugged it a bit, and always setting `doCompensate` to `false` in `qouteall.imm_ptl.core.render.FrontClipping.getClipEquationInner(…)` seems to fix the issue.  
I imagine there is some reason that flag exists, but it does cause these rendering issues. Especially annoying with my Colourful Portals Reimagined mod, where, after a short (~8 blocks) distance, the plane gets rendered twice, making it look half as transparent.

**Comment by qouteall** [comment]
The doCompensate is originally used for avoiding z-fighting of world wrapping portal which is aligned to block grid.

Can you provide screenshots?

**Comment by QuImUfu** [comment]
Close, rendered correctly:  
![close (correct)](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/9885301/9dfc73fe-1893-493b-b969-c7c3edf09472)
~8 blocks away, planes start rendering (twice):  
![medium distance (plans bugged)](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/9885301/172800b1-e5d3-4ad3-b638-71b4df3850f2)
~105 blocks away, trapdoor starts rendering through portal:  
![far away (zoomed, trapdoor bugged)](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/9885301/7a8424ce-c937-4246-96a9-6524e1b52ac9)

**Comment by qouteall** [comment]
I made the clipping compensation always 0.01. This should fix the issue.

**Comment by QuImUfu** [comment]
That fixes the issue.  
Thank you!
