### ISSUE TITLE
Crash with Create

### ISSUE THREAD

**Issue by aratuluc** [qouteall/ImmersivePortalsMod#1371]
### Is it a mod compatibility issue?

Yes

### Minecraft version

1.19.2

### Describe the issue

After spawning to a world whenever I go through a nether portal it crashes my game and my friend's games also crash when they go through portals.

https://hastebin.com/share/bikuvejaqo.ruby - Crash Report
https://hastebin.com/share/kuzerejoci.makefile - latest log

**Comment by qouteall** [comment]
It seem to be the nvidia driver bug. Install sodium to workaround.

**Comment by aratuluc** [comment]
That worked, thanks!
