### ISSUE TITLE
Player cannot go through portal when riding

### ISSUE THREAD

**Issue by xhoneybear** [qouteall/ImmersivePortalsMod#1372]
### Is it a mod compatibility issue?

No

### Minecraft version

1.20

### Describe the issue

Tested on Quilt and Fabric with and without Iris (and other mods) on two separate computers. Only tried Nether portals so far.

Pandas just passed to the other side of the portal frame in the same dimension, riding a horse also made the player stay in the same dimension instead of passing through to another one.

I remember 1.18.2 having no issues with mobs passing through portals. Is it disabled for now due to rendering (or other) issues or is it a bug?

**Comment by qouteall** [comment]
The issue of teleporting while riding an entity will be fixed in the next version.

**Comment by xhoneybear** [comment]
Just tried 1.20.1 with ImmPtl 3.1.0, it works seamlessly now. Riding a horse through portals works well, mobs alone can pass them no problem, too. Thank you! :heart:
