### ISSUE TITLE
Visual glitch at the shared edge of 2 portals

### ISSUE THREAD

**Issue by ImSpaceLover** [qouteall/ImmersivePortalsMod#1377]
### Is it a mod compatibility issue?

No

### Minecraft version

1.20.1

### Describe the issue

When portals are placed in a certain way a weird black line appears between them.
How to replicate:
![2023-06-24_16 42 36](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/64267797/e2ceb091-4ecb-4238-91df-ec9bf6322b48)
Make a structure "1" (orange) appear inside of a structure "2" blue
1) Create the first portal in-front of the structure "1" like this: 
![2023-06-24_16 43 04](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/64267797/16e1d71e-649e-4bd6-9b36-c8ceb9cfd9be)
2) Create the second portal at one of the sides
![2023-06-24_16 50 04](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/64267797/2ff94626-3e60-4d6f-a8fa-3e9c03b06377)
3) Observe the black line 
![2023-06-24_16 43 53](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/64267797/677a0462-e0a3-447b-97b2-aa15feed665b)
![2023-06-24_16 44 05](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/64267797/9d7b70e5-4de3-45e5-a011-65dd1bed69a3)
(The black line doesn't appear when these portals don't "overlap" from the viewer's perspective) 
![2023-06-24_16 44 00](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/64267797/54e3c89f-6e1d-4ad2-a780-dcf3d5de9756)

The glitch appears with fabric-loader-0.14.21-1.20.1, fabric-api-0.83.1+1.20.1, immersive-portals-3.1.0, Minecraft 1.20.1. Also appears with sodium installed.

**Comment by qouteall** [comment]
Probably fixed in the next version.
