### ISSUE TITLE
"/portal wiki" loses connection to the world

### ISSUE THREAD

**Issue by CrazyMusicBoy44** [qouteall/ImmersivePortalsMod#1389]
### Is it a mod compatibility issue?

No

### Minecraft version

1.20.1

### Describe the issue

Using the "Check Immersive Portals Wiki" stick (or running `/portal wiki`) loses connection to server (in singleplayer), closing the world, and going to the multiplayer connection screen. The message it shows is below:

Connection Lost
Internal Exception: java.lang.RuntimeException: Cannot find class qouteall.imm_ptl.peripheral.guide.IPGuide.RemoteCallables

It happens with no mods as well as with mods, to test it just right click the stick or run the command (`/portal wiki`)

I apologize if this report is lacking, this is the first time that I have reported a bug.

**Comment by qouteall** [comment]
Fixed, will be in the next version.
