### ISSUE TITLE
incompatible with gravity api (quilt)

### ISSUE THREAD

**Issue by baconlover209** [qouteall/ImmersivePortalsMod#1397]
### Is it a mod compatibility issue?

Yes

### Minecraft version

1.20.1

### Describe the issue

game cannot open due to a "complex solver error"
only happens on quilt
[2023-07-24-7.log.gz](https://github.com/iPortalTeam/ImmersivePortalsMod/files/12155910/2023-07-24-7.log.gz)

**Comment by qouteall** [comment]
The latest version of Immptl is compatible with my fork of gravity api https://modrinth.com/mod/gravity-api-fork
It is not compatible with the gravity api on quilt because a fabric mod cannot depend on a quilt mod.
