### ISSUE TITLE
Mobs spawn on top of the nether in dimension stack worlds

### ISSUE THREAD

**Issue by LeeSpork** [qouteall/ImmersivePortalsMod#140]
In vanilla Minecraft, the reason that mobs do not spawn on top of the nether is that mobs do not spawn on bedrock. The stacked dimensions world option however replaces this bedrock with obsidian, thus ghasts will spawn on top of the nether and make really annoying sounds, with the player not even being able to reach them due to the ceiling portal thing.

**Comment by qouteall** [comment]
To solve this I am going to make it compatible with https://www.curseforge.com/minecraft/mc-mods/netherhigher

**Comment by qouteall** [comment]
Another solution is to generate one more bedrock layer on top

**Comment by qouteall** [comment]
I made it compatible with netherHigher but unfortunately even if the nether is 256 high mobs can still spawn on top

**Comment by qouteall** [comment]
fixed
