### ISSUE TITLE
Custom maps don't render correctly

### ISSUE THREAD

**Issue by ArztKlein** [qouteall/ImmersivePortalsMod#1400]
### Is it a mod compatibility issue?

No

### Minecraft version

1.18.x

### Describe the issue

Creating custom maps using a map.dat file (for 1.18.2, Fabric) doesn't work. They just don't render at all.
It is something to do with the Immersive Portals mod because these maps work on vanilla 1.18.2. For reference, the maps were generated using [MapartCraft](https://rebane2001.com/mapartcraft/).

![javaw_zPIZWx1YjF](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/52363453/3de0ca6f-0a4a-4ea0-8203-21aeb824da5c)

**Comment by qouteall** [comment]
Does the same issue exist in the latest version for MC 1.20.1?

**Comment by ArztKlein** [comment]
> Does the same issue exist in the latest version for MC 1.20.1?

Yes. I also tried in vanilla 1.20.1, and the maps correctly render.

**Comment by qouteall** [comment]
The reason is that, in the map data that MapartCraft, the dimension is `minecraft:mapartcraft`. ImmPtl does special handling to map data's dimension.

**Comment by qouteall** [comment]
Will be fixed in the next version of ImmPtl.

**Comment by tadhgmister** [comment]
did the fix also fix twillight forest magic maps? I'm playing 19.2 on forge and assume the fix wasn't backported but because what ever the fix was wasn't referenced from this issue I'm not sure how to find it and try to backport it myself.
