### ISSUE TITLE
Compatibility with Entity Culling?

### ISSUE THREAD

**Issue by Briscuit** [qouteall/ImmersivePortalsMod#1401]
### Is it a mod compatibility issue?

Yes

### Minecraft version

1.20.1

### Describe the issue

When I booted a world, it said that it was not compatible with Entity Culling, but its working just fine for me
That's all

**Comment by qouteall** [comment]
You are sure that the entity render works normally when looking at nether portals, same-dimension portals and portal-in-portal?

**Comment by Briscuit** [comment]
> You are sure that the entity render works normally when looking at nether portals, same-dimension portals and portal-in-portal?

As far as I am aware, everything worked normal, and I had no issues with it what so ever.

**Comment by qouteall** [comment]
I changed the incompatibility message to mild and can be disabled.
