### ISSUE TITLE
my mod immersive to error and map even more non eucliden

### ISSUE THREAD

**Issue by ghandikan** [qouteall/ImmersivePortalsMod#1411]
### Is it a mod compatibility issue?

Select One

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

imeersive portal 1.20.1

### Minecraft version

1.20.1

### Describe the issue

error to map even more non ecluden

**Comment by qouteall** [comment]
What do you mean by "error to map even more non ecluden"?

**Comment by qouteall** [comment]
Close because no reply.
