### ISSUE TITLE
How is this incompatible with Krypton and Sound Physics Remaster?

### ISSUE THREAD

**Issue by makumaku1974** [qouteall/ImmersivePortalsMod#1419]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

https://modrinth.com/mod/krypton

https://modrinth.com/mod/sound-physics-remastered

### Minecraft version

1.20.1

### Describe the issue

![2023-08-12_18 36 56](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/129804277/affd4835-d705-4247-a25e-22bcd538c864)

**Comment by qouteall** [comment]
The krypton warning has been removed.

About sound physics remastered, someone reported having no issue with it, so I made its warning disable-able.
