### ISSUE TITLE
Immersive Portals dont work with shaders anymore

### ISSUE THREAD

**Issue by RikkHardi** [qouteall/ImmersivePortalsMod#1420]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

https://modrinth.com/mod/iris
https://modrinth.com/shader/bsl-shaders
https://modrinth.com/shader/rethinking-voxels
https://modrinth.com/shader/complementary-reimagined
https://modrinth.com/shader/super-duper-vanilla
https://modrinth.com/shader/astralex
https://modrinth.com/shader/solas-shader
https://modrinth.com/shader/kappa-shader

### Minecraft version

1.20.1

### Describe the issue

NOTE: It was tested after I had updated lots of my mods and downloaded 84 new ones, so the issue might be related to one of those. Mods downloaded were mostly world generation, alternate dimensions and added mobs. Before those Immersive Portals worked completely fine.

Portal transportation works fine. Problem is, when shaders are enabled, it doesnt render the other side of the portals. When shaders are turned off portals render just fine.

Log file from my latest test: https://mclo.gs/IzvYf5Z

All the mods it warns about in game were previously present and worked fine with only minor issues.

**Comment by LokeYourC3PH** [comment]
Iris & Sodium (and Indium) just updated again very recently. Immersive Portals has not updated for the release yet.

**Comment by qouteall** [comment]
Does the shader work with only Immersive Portals, sodium, iris and fabric api in a new world?

**Comment by LokeYourC3PH** [comment]
> Does the shader work with only Immersive Portals, sodium, iris and fabric api in a new world?

It's once again just an incompatibility with the newest update of Sodium 0.5.2.
