### ISSUE TITLE
I cant use sodium with immersive portals mod  

### ISSUE THREAD

**Issue by cclandry** [qouteall/ImmersivePortalsMod#1421]
### Is it a mod compatibility issue?

Yes

### Minecraft version

1.20.1

### Describe the issue

When ever I try to play Minecraft with sodium and immersive portals I get a error code saying immersive portals is not compatible with sodium 0.5.0 but is compatibles with sodium 0.5.1 but I have sodium 0.5.1

**Comment by cclandry** [comment]
Could some one pls respond

**Comment by Lolothepro** [comment]
just wait...

**Comment by cclandry** [comment]
Ok

**Comment by qouteall** [comment]
Use sodium 0.5.0 for now.
