### ISSUE TITLE
Incompatible with the latest version of Iris

### ISSUE THREAD

**Issue by Aabaddon** [qouteall/ImmersivePortalsMod#1423]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

https://modrinth.com/mod/iris
[2023-08-18-6.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/12384081/2023-08-18-6.log)

### Minecraft version

1.20.1

### Describe the issue

Simple incompatibility with newer versions of iris, i tried downgrading iris and sodium but it caused more incompatibility issues with a lot more mods than immersive portals

**Comment by qouteall** [comment]
Updated in 3.2.6
