### ISSUE TITLE
nvoglv64.dll crash on staring at a portal funny or making changes too quick

### ISSUE THREAD

**Issue by zemuffinnman** [qouteall/ImmersivePortalsMod#1425]
### Is it a mod compatibility issue?

No

### Minecraft version

Other (specify below)

### Describe the issue

happens on versions 1.18.1 to 1.19.2 from what i have experimented with

crash log attached below

[hs_err_pid8756.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/12403109/hs_err_pid8756.log)

**Comment by zemuffinnman** [comment]
version info in crashlog is modifed from some silly regedit stuff. windows version is actually the latest build number. 19041 is inaccurate

**Comment by zemuffinnman** [comment]
> version info in crashlog is modifed from some silly regedit stuff. windows version is actually the latest build number. 19041 is inaccurate

but windows 10 is correct

**Comment by qouteall** [comment]
Seem to be the nvidia driver bug https://github.com/CaffeineMC/sodium-fabric/issues/1486

Sodium contains a workaround of this bug. It's recommended to use 1.20.1 and the latest version of this mod and the latest version of this mod. Older versions of Sodium contains a workaround to it, but it seems that nvidia made that workaround not working in later versions of driver, so Sodium changed a way of workarounding it.
