### ISSUE TITLE
Exiting crawl mode when you shouldn't

### ISSUE THREAD

**Issue by abacussssss** [qouteall/ImmersivePortalsMod#1431]
### Is it a mod compatibility issue?

No

### Minecraft version

1.20.1

### Describe the issue

The collision box for determining whether the player should be crawling, sneaking, or standing is 0.1 blocks smaller in all directions than the player's hitbox.

So, if the player is crawling and goes under a sideways chain elevated 1 block from the ground, they start sneaking and clip into the chain. The player also starts standing from inside a crawlspace if they're on the outermost 0.1 blocks, clipping into the ceiling.
![2023-08-29_18 07 55](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/143558044/b002202e-7633-47bd-aed6-9df252d30c9b)

**Comment by qouteall** [comment]
Fixed in the next version.
