### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Szilard2011** [qouteall/ImmersivePortalsMod#1437]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

when i want to click a lever or open a door from side to another side, game will crash

### Minecraft version

1.20

### Describe the issue

i create a portal, and i open a door from side to another side, minecraft just crashed for no reason

**Comment by zemuffinnman** [comment]
post crash log

**Comment by qouteall** [comment]
Post the crash report to help diagnose the issue

**Comment by qouteall** [comment]
Issue closed because the issue opener haven't provided requested information for a long time.
