### ISSUE TITLE
When entering end portal, feather falling effect is too short.

### ISSUE THREAD

**Issue by eyepopper** [qouteall/ImmersivePortalsMod#1446]
### Is it a mod compatibility issue?

No

### Minecraft version

1.20.1

### Describe the issue

If your end portal settings are set to normal, then you enter the portal with 7 hearts, you will die of fall damage.

**Comment by qouteall** [comment]
Fixed in the next version.

~~In old MC versions it used to be enough, possibly because that old MC versions does not reset velocity when applying feather falling effect so that the player will fall quicker.~~

**Comment by qouteall** [comment]
The velocity reset is made by ImmPtl. The velocity reset was introduced for scale box end portal. Now it will not reset velocity for non-scale-box end portal.
