### ISSUE TITLE
Dimension stacking with custom heights

### ISSUE THREAD

**Issue by ZolaKluke** [qouteall/ImmersivePortalsMod#1449]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

https://www.curseforge.com/minecraft/mc-mods/betternether

### Minecraft version

1.20.1

### Describe the issue

Using the BetterNether mod there is an option to allow the nether to generate up to Y 256 however this area is inaccesible when using dimension stacking and placing the Nether below the Overworld

**Comment by qouteall** [comment]
In the dimension stack window, you can set top Y to 256 for the nether dimension

https://qouteall.fun/immptl/wiki/Dimension-Stack.html#per-dimension-options

**Comment by qouteall** [comment]
ImmPtl uses min_y + logical_height as the top Y value by default. It may be an issue of BetterNether not updating the dimension type's logical_height.
