### ISSUE TITLE
Connector/Iris/Oculus Incompatiblity

### ISSUE THREAD

**Issue by Its-Just-Luci** [qouteall/ImmersivePortalsMod#1451]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

https://modrinth.com/mod/connector
https://modrinth.com/mod/oculus

### Minecraft version

1.20.1

### Describe the issue

Simple crash, forgified fabric api is suggesting I-
"- Replace mod 'Immersive Portals' (immersive_portals) 3.2.6 with any version that is compatible with:
		 - iris 1.6.9
		 - sodium 0.5.3"
		 
[latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/12739426/latest.log)
[debug.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/12739427/debug.log)

**Comment by Its-Just-Luci** [comment]
Got these mods working, however still having an unknown crash upon creating or loading a world:

[debug.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/12753967/debug.log)
[latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/12753968/latest.log)

**Comment by Its-Just-Luci** [comment]
it was an issue with serene seasons, my b

**Comment by Cyberwolf606** [comment]
Hey, what did you do to get them working?
