### ISSUE TITLE
Cannot connect to server when using essential?

### ISSUE THREAD

**Issue by FlyingToilet** [qouteall/ImmersivePortalsMod#1459]
### Is it a mod compatibility issue?

No

### Minecraft version

Other (specify below)

### Describe the issue

Made sure ALL mods are on MC version 1.20.2 and everything works, but when I add your mod, it then tells me to add it to the server files(even tho im running SP only) No idea whats going on.
![javaw_kt41qlWA0y](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/6323856/30f6f0b5-c548-4aae-89b1-2d327eb7795f)

**Comment by qouteall** [comment]
Are you using bad packets mod? Bad packets mod could cause this issue. https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1456

If not, to know whether it's a mod compatibility issue, backup your world and test it with only Fabric API and Immersive Portals mod.

**Comment by FlyingToilet** [comment]
Don't I need badpackets for it to run? And sure I can do that. Let me test that out and get back to you.

**Comment by qouteall** [comment]
No, I mean that someone reported having similar issue when using Bad Packets mod. ImmPtl does not require bad packets.

**Comment by qouteall** [comment]
Update: someone reported that similar issue also occurs with essential https://discord.com/channels/662271867431682058/671895714527182920/1162676318228447374

Are you using essential?

**Comment by qouteall** [comment]
ImmPtl uses Fabric API's functionality to check whether the client has ImmPtl. Seems that essential mod or other mod breaks this. If you get this issue with essential, you can report this issue to essential.

In 4.0.2 https://github.com/iPortalTeam/ImmersivePortalsMod/releases/tag/v4.0.2-mc1.20.2 you can disable the check from the server side by setting the server side's `serverRejectClientWithoutImmPtl` to `false` in the config file `config/immersive_portals.json` .
