### ISSUE TITLE
add compatibility to iris 1.6.10+1.20.1 to immersivePortals and portal guns in 1.20.1

### ISSUE THREAD

**Issue by Steame090** [qouteall/ImmersivePortalsMod#1463]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

add compatibility to iris 1.6.10+1.20.1 to immersivePortals and portal guns in 1.20.1
https://modrinth.com/mod/iris/version/DsjYuGMO
https://modrinth.com/mod/iris/version/DsjYuGMO
https://modrinth.com/mod/iris/version/DsjYuGMO
https://modrinth.com/mod/iris/version/DsjYuGMO
https://modrinth.com/mod/iris/version/DsjYuGMO

### Minecraft version

1.20.1

### Describe the issue

add compatibility to iris 1.6.10+1.20.1 to immersivePortals and portal guns in 1.20.1

**Comment by Mysterious-Wrangler** [comment]
Same issue, not compatible. 
Edit: Nevermind the new alpha version 3.3.4 works. Curseforge said all mods were up to date while it actually wasnt. TY.
