### ISSUE TITLE
Crashes game when trying to use immersive portals with Pehkui

### ISSUE THREAD

**Issue by Noahbloxian** [qouteall/ImmersivePortalsMod#1464]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

https://www.curseforge.com/minecraft/mc-mods/pehkui

### Minecraft version

1.20.2

### Describe the issue

It tried to put immersive portals and Pehkui in the same folder but it crashed when I booted up minecraft and it's clearly the mod because I renamed the installation to immersive portals

**Comment by qouteall** [comment]
Pehkui does not support 1.20.2 and it crashes in 1.20.2 without ImmPtl https://github.com/Virtuoel/Pehkui/issues/455
It's not an issue of ImmPtl.
