### ISSUE TITLE
Mirror rendering is broken

### ISSUE THREAD

**Issue by Alceris** [qouteall/ImmersivePortalsMod#1486]
### Is it a mod compatibility issue?

No

### Minecraft version

1.20.2

### Describe the issue

Mirrors appear to lack any draw distance and are strangely rendering the blocks they're made from. See video for more information: https://cdn.discordapp.com/attachments/190944839183892481/1185933335009165322/mirrorbroke.mp4

**Comment by qouteall** [comment]
Does this issue occur with the mirrors that are created via flint-and-steel naturally? (In the video the mirror seems modified by commands.)

**Comment by Alceris** [comment]
I initially created it naturally using flint and steel, I only modified the destination to provide more information about the issue.

**Comment by Alceris** [comment]
Additionally, the same thing happens with portals that have been turned into 'fake enterable mirrors,' it happens with all mirrors no matter how they're created or edited, but it does not happen with normal portals that have simply been turned around 180 degrees. https://cdn.discordapp.com/attachments/190944839183892481/1186118722562297926/allmirrorbroke.mp4

**Comment by ImSpaceLover** [comment]
Does this happen with no other mods installed? (Such as Figura and other mods like it)

**Comment by Alceris** [comment]
Yes.

**Comment by Alceris** [comment]
Interestingly, mirror rendering appears to function perfectly fine in Minecraft version 1.20.1, in Forge with Sinytra Connector. I have not tested it in Fabric 1.20.1.

**Comment by qouteall** [comment]
I can reproduce the issue. Going to fix.

**Comment by qouteall** [comment]
Should be fixed in 4.1.3
