### ISSUE TITLE
Incompatible with Iris Shaders mod

### ISSUE THREAD

**Issue by nikolodeon** [qouteall/ImmersivePortalsMod#1488]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

https://modrinth.com/mod/iris

### Minecraft version

1.20.2

### Describe the issue

the game doesnt load but gives me a error message saying that the version of Iris Shaders and Immersive Portals are incompatible with eachother. However i have tried to choose the versions of the mods that are suppose to be compatible, but the error still comes.

This is the error that  i get:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Remove mod 'Iris' (iris) 1.6.14 (C:\Users\footb\AppData\Roaming\com.modrinth.theseus\profiles\Fabulously Optimized\mods\iris-mc1.20.2-1.6.14.jar).
More details:
	 - Mod 'Immersive Portals' (immersive_portals) 4.1.3 is incompatible with any version before 1.6.13 or any version after 1.6.13 of mod 'Iris' (iris), but a matching version is present: 1.6.14!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by qouteall** [comment]
Use iris 1.6.13 for now or use dependency override https://qouteall.fun/immptl/wiki/Miscellaneous.html#remove-the-sodium-iris-version-lock

**Comment by ShrikerChestTree** [comment]
> Use iris 1.6.13 for now or use dependency override https://qouteall.fun/immptl/wiki/Miscellaneous.html#remove-the-sodium-iris-version-lock

This person helped me solve the problem thank you!
