### ISSUE TITLE
GUI bugs when viewing Portal with shaders

### ISSUE THREAD

**Issue by RowanSkie** [qouteall/ImmersivePortalsMod#149]
The GUI creates a "shadow" based on the light of the main dimension and light color when viewing a portal with Immersive Portal and Optifine active. Other versions also render only the portal it leads to.

Mod: 
* Immersive Portals 0.24
* Optifine preview 13

Shader: BeyondBelief Vanilla Reborn
![2020-04-08_18 55 50](https://user-images.githubusercontent.com/11764533/78777473-2d636780-79cc-11ea-8cad-5cf22582a8ef.png)

Shader: Chocapic13_V8_Ultra
![2020-04-08_19 09 12](https://user-images.githubusercontent.com/11764533/78777723-a2cf3800-79cc-11ea-8c1d-38a8ee1bf0e7.png)

Shader: SEUS Renewed 1.0.1
![2020-04-08_19 10 04](https://user-images.githubusercontent.com/11764533/78777752-b37fae00-79cc-11ea-8c10-40fa439865c1.png)

And, as a bonus, a path-tracing shader pack called MollyVXE
![2020-04-08_19 11 48](https://user-images.githubusercontent.com/11764533/78777863-e3c74c80-79cc-11ea-9fd5-e6b4247f7786.png)

**Comment by qouteall** [comment]
Fixed in 0.25
