### ISSUE TITLE
immersive portals mod requiring   *0.28.1 fabric API*

### ISSUE THREAD

**Issue by NoobDefault111** [qouteall/ImmersivePortalsMod#1490]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

![Screenshot 2023-12-28 160852](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/155045418/101ee283-2e60-4e4a-b5c4-eaca8aca634e)
![image](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/155045418/0cbb0a25-f38e-432b-98fb-3673b20006a9)

 https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod/files/4945515
https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod/files/4973659

### Minecraft version

1.20.2

### Describe the issue

i've tried repeatedly downloading the immersive portals mod multiple times on latest minecraft fabric API but everytome i download the mod the same error screen appears showing that the mod is incompatible with the fabric launcher requiring fabric API ver 0.28.1    even though the latest fabric launcher is ver 0.15.3

( ps , im not sure why there is a mod called QMiscUtil is on the error list even though the immersive portals mod is the only mod in the mod file and that the fabric loader works finely without the immersive portals mod even thought i want to try out the immersive portal mod ,BTW could you devs mind updating the forge version for immersive portals for minecraft ver 1.20)

**Comment by ImSpaceLover** [comment]
Install Fabric API, it's a separate mod
