### ISSUE TITLE
Mirrors Are Super Buggy

### ISSUE THREAD

**Issue by DaRealNoteed** [qouteall/ImmersivePortalsMod#1495]
### Is it a mod compatibility issue?

No

### Minecraft version

1.20.2

### Describe the issue

I was testing out the Immersive Portals mod and all went well until I tried a mirror. The mirror was super buggy and it only showed some blocks zoomed in if I went like 20 blocks away from it. Otherwise, it kinda just showed more glass frames inside of the mirror. I tried removing all mods (WorldEdit, Gravity API, Pekuhi, Continuity, LambDynamicLights, and those mods' APIs) so that only Gecolib, Fabric API, Mod Menu, and Immersive Portals remained and the issue persisted. I also messed with the Immersive Portals config but that didn't fix it. All of the command sticks work, and the portals work fine. I don't know what to do. If it helps, I'm using a Ventura Mac and I know sometimes the Apple operating systems have a hard time with mods but I remember the mirrors working in a different world I deleted. I also have tried switching worlds if you're wondering.
![2023-12-23_06 55 38](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/110487810/e3abd7fc-be44-4c14-b004-30cfd53e90ef)
Mirror Example after and before removing all other mods and changing worlds

**Comment by qouteall** [comment]
This issue has been fixed in the latest version. https://modrinth.com/mod/immersiveportals/version/v4.1.4-mc1.20.2
