### ISSUE TITLE
Ticking entities when making nested scale boxes 

### ISSUE THREAD

**Issue by ImSpaceLover** [qouteall/ImmersivePortalsMod#1498]
### According to your testing, does the issue occur with ONLY MiniScaled mod and Immersive Portals mod and Farbic API?

Yes

### Describe the issue

When I try to make a scale box inside another scale box inside another scale box ticking entities randomly appear
[latest.log](https://github.com/iPortalTeam/MiniScaledMod/files/13829005/latest.log)
[crash-2024-01-04_13.20.55-client.txt](https://github.com/iPortalTeam/MiniScaledMod/files/13829007/crash-2024-01-04_13.20.55-client.txt)
[crash-2024-01-04_13.20.53-server.txt](https://github.com/iPortalTeam/MiniScaledMod/files/13829008/crash-2024-01-04_13.20.53-server.txt)

**Comment by qouteall** [comment]
Probably fixed in 5.0.3
