### ISSUE TITLE
Render issues with Portal with specific shaders (1.15.2)

### ISSUE THREAD

**Issue by RowanSkie** [qouteall/ImmersivePortalsMod#150]
I don't know if this is also fixed in 0.25, but I get weird render bugs with two shaders: Raspberry and MollyVX. Both are made by rutherin.

Raspberry: (Notice that my design are enlarged and possibly mirrored)
![2020-04-08_20 15 24](https://user-images.githubusercontent.com/11764533/78783841-da42e200-79d6-11ea-9f7e-fb0b9d0eca71.png)
![2020-04-08_20 19 10](https://user-images.githubusercontent.com/11764533/78783852-ddd66900-79d6-11ea-8715-d85ab55c74bf.png)
![2020-04-08_20 19 15](https://user-images.githubusercontent.com/11764533/78783864-e0d15980-79d6-11ea-9ca1-a42a218c5aef.png)
![2020-04-08_20 19 19](https://user-images.githubusercontent.com/11764533/78783869-e333b380-79d6-11ea-8e7c-29035b073b48.png)

MollyVX: (Same thing, the lighting is actually an Optifine problem)
![2020-04-08_20 19 45](https://user-images.githubusercontent.com/11764533/78784014-2857e580-79d7-11ea-8577-90d1c7e9926b.png)
![2020-04-08_20 19 49](https://user-images.githubusercontent.com/11764533/78784019-2beb6c80-79d7-11ea-93e4-74bc7696171a.png)
![2020-04-08_20 19 52](https://user-images.githubusercontent.com/11764533/78784023-2e4dc680-79d7-11ea-8c65-87e8f542b6a7.png)

**Comment by qouteall** [comment]
MollyVX is path tracing and is hard to be compatible with.
