### ISSUE TITLE
Not compatible with sodium and iris mods

### ISSUE THREAD

**Issue by 0Dominik0** [qouteall/ImmersivePortalsMod#1502]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

Iris shader : https://irisshaders.dev/download
Sodium mod: https://modrinth.com/mod/sodium

### Minecraft version

1.20.4

### Describe the issue

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Remove mod 'Iris' (iris) 1.6.13 (D:\Users\User\AppData\Roaming\.minecraft\mods\iris-mc1.20.4-1.6.13.jar).
	 - Remove mod 'Sodium' (sodium) 0.5.4 (D:\Users\User\AppData\Roaming\.minecraft\mods\sodium-fabric-mc1.20.3-0.5.4.jar).
More details:
	 - Mod 'Immersive Portals' (immersive_portals) 5.1.1 is incompatible with any version before 1.6.14 or any version after 1.6.14 of mod 'Iris' (iris), but a matching version is present: 1.6.13!
	 - Mod 'Immersive Portals' (immersive_portals) 5.1.1 is incompatible with any version before 0.5.5 or any version after 0.5.5 of mod 'Sodium' (sodium), but a matching version is present: 0.5.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Lolothepro** [comment]
update Sodium & Iris

**Comment by 0Dominik0** [comment]
thank you.
