### ISSUE TITLE
can't even run install file?

### ISSUE THREAD

**Issue by ijo-amali** [qouteall/ImmersivePortalsMod#1503]
### Is it a mod compatibility issue?

No

### Minecraft version

1.20.2

### Describe the issue

I can't even run the installation file, `immersive-portals-4.1.4-mc1.20.2-fabric.jar`. If I double-click and click past the warning from Windows, nothing happens. If I run it in the terminal, like so: `java -jar .\immersive-portals-4.1.4-mc1.20.2-fabric.jar`, I get this error:
`no main manifest attribute, in .\immersive-portals-4.1.4-mc1.20.2-fabric.jar`
I'm definitely missing something obvious here, thank you

**Comment by ImSpaceLover** [comment]
search how to install fabric mods, you don't need to open the jar files, you need to put them in the mods folder

**Comment by ijo-amali** [comment]
apologies, i've never installed a fabric mod before! thank you
