### ISSUE TITLE
i look in the portal and i get crash and my save gets delete

### ISSUE THREAD

**Issue by ghost323245** [qouteall/ImmersivePortalsMod#1504]
### Is it a mod compatibility issue?

Yes

### Minecraft version

1.20.1
fabric
### Describe the issue

i look in the custom portal and i get crash and my save gets delete

**Comment by qouteall** [comment]
Post the crash report because you didn't provide any useful information for diagnosing the issue.

This is probably a mod compatibility issue. This mod does NOT delete the world saving.

**Comment by qouteall** [comment]
Information to whom experience "missing world" issue: if the world's `level.dat` file gets broken, then the world will not be shown in world list in game, but in that case the world saving is not deleted. To fix that, create a new world with the same seed and setting, then use the new world's `level.dat` file to override the broken one.

Immersive portals mod does not delete world saving. Mod incompatibility may cause the game to fail to save world correctly.

**Comment by qouteall** [comment]
Close for now. Will reopen if more information provided.
