### ISSUE TITLE
Nether side replacing view when looking at the general area of portal (1.15)

### ISSUE THREAD

**Issue by RowanSkie** [qouteall/ImmersivePortalsMod#151]
Version 0.25 with Chocoapic shader

Evidence:
Within the house, portal not in view
![2020-04-09_18 54 00](https://user-images.githubusercontent.com/11764533/78890718-bba51f80-7a98-11ea-952d-7d66a837b4c2.png)
Within the house, portal hit by field of view
![2020-04-09_18 54 01](https://user-images.githubusercontent.com/11764533/78890725-be077980-7a98-11ea-90d0-3d13a54c695e.png)

**Comment by qouteall** [comment]
fixed. it will be in the next version

**Comment by qouteall** [comment]
possibly fixed in 0.26
