### ISSUE TITLE
BIgger portals wont connect

### ISSUE THREAD

**Issue by adavzg** [qouteall/ImmersivePortalsMod#1512]
### Is it a mod compatibility issue?

No

### Minecraft version

1.19.3

### Describe the issue

So lets say, I want a 19x19 portal connect to a 1x3 portal. And when I ignite the portal, they dont connect. It does it for other people but not me. Is there anything I have to modify to connect big and small portals?

**Comment by qouteall** [comment]
By default, the nether portal will only link to same-shaped same-sized same-direction frame. You can change nether portal mode to `adaptive` to make it link to other sizes with compatible shape.
