### ISSUE TITLE
Won’t work

### ISSUE THREAD

**Issue by ExiledNinja** [qouteall/ImmersivePortalsMod#1516]
### Is it a mod compatibility issue?

No

### Minecraft version

1.20.1

### Describe the issue

It won’t work so I’ll go into the game and it will say that I don’t have the mod and it doesn’t give me anything from the mod.

**Comment by qouteall** [comment]
Requires details explanation.

**Comment by qouteall** [comment]
Issue closed because the issue opener haven't provided requested information for a long time.
