### ISSUE TITLE
Missing capability for UUID after using Immersive portals mod nether portal - kick from the server

### ISSUE THREAD

**Issue by luk4k0** [qouteall/ImmersivePortalsMod#1517]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

LuckPerms Version 5.4.102
Probably also Curios API in a slightly different way. https://github.com/Sinytra/Connector/issues/564

### Minecraft version

1.20.1

### Describe the issue

After I use nether portal for once with Immersive Portals mod, any command, or typing into the chat causes kick from the server with error missing capability for my UUID. After reconnection it works again until I use the portal again. When I delete Luckperms from the server, the problem stops. Server log doesn't show much, it is in the end of the log
[latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/14193941/latest.log)

Reproduction Steps:
Connect to the server.
Type anything in the chat - works fine.
Go through the nether portal (Immersive portals) to the nether (or vice-versa)
Again type anything in the chat ---> kicked out of the server

Actually, when I type a command, /tp , /spawn etc. it does nothing and its like ignored, like a ping lag, when I type message into to the chat, it kicks me out....

Similar issue is happening with curios API, when the portal is used, Curios items start to disappear or double, and then player gets potentially kicked from the server. - Link above. (not sure if those issues are related, just in case, to provide more info) 

It needs to be said that I run Immersive portals through the Sinytra connector and I also created an issue report there. 

Thank you for any help.

**Comment by qouteall** [comment]
Unfortunately, the usage of iPortal via Sinytra Connector is not being supported. iPortal Fabric version is not designed for Connector and does not work well normally on Sinytra Connector. It's recommended to wait for the Forge version.
