### ISSUE TITLE
Save Corruption

### ISSUE THREAD

**Issue by Rikipalooza** [qouteall/ImmersivePortalsMod#1521]
### Is it a mod compatibility issue?

No

### Minecraft version

1.20.1

### Describe the issue

I'm running a heavily modded minecraft version with both forge and fabric. I decided to try and add Immersive Portals, just to test if it'd work. 

When joining the world it said to install Sodium to go around a Nvidia driver bug, that I use many mods, that its incompatible with Bobby and compatibility issues with nvidium. So without even taking a step, I closed the world, and removed the mod. 

And now my save is corrupted.

 I didn't do anything other than open the save. As soon as I saw the erros, I read them, closed it, removed the mod. And now I can only open the world if I reinstall immersive portals but due to its compatibility issues, I want to remove it. Help me, please.

**Comment by qouteall** [comment]
Explain what do you mean by "now I can only open the world if I reinstall immersive portals"? Did it crash or show any error message without iPortal?

**Comment by qouteall** [comment]
Old versions of iPortal adds dimensions. It's recommended to install Fabric API and open the world once without dimension mods, to clear the dimension data in `level.dat` so that vanilla MC can open the world.

**Comment by Rikipalooza** [comment]
When I removed the Immersive Portals mod and tried to open the world it says there's problem with resource packs and gives me the option to use Safe Mode or go back to Title Screen. If I try to use Safe Mode it crashes. If I go back to the title screen i can enter any world which I didn't open with Immersive Portals. By reinstalling Immersive Portals there's no problem when entering the said world, but it stops other mods of mine of working.

If by open the world without dimension mods you mean without any mods that create or change dimensions, Immersive Portals was the only one I've had, and opening said world without it, isn't allowed as I mentioned above.

**Comment by qouteall** [comment]
Are you using the latest version of Fabric API in 1.20.1? If so, provide the log and screenshot when not being able to open the world.

**Comment by qouteall** [comment]
I cannot reproduce that issue in 1.20.1.

**Comment by Rikipalooza** [comment]
Nevermind. I didn't know you'd need an NBTeditor to alter the level.dat to remove the mod completely. After turning my search for answers more general instead of related to immersivePortals I found the answer. I thought since I hadn't used any of the mod, no files like that would've been created, but I was wrong

**Comment by qouteall** [comment]
Are you using Sinytra Connector in Forge? Fabric API already have the functionality of removing invalid data from `level.dat` but Forge maybe doesn't yet support that.

**Comment by Rikipalooza** [comment]
I am. I see, then that might be the cause of the trouble!
