### ISSUE TITLE
Iris 1.6.15-1.6.17 support

### ISSUE THREAD

**Issue by ShrikerChestTree** [qouteall/ImmersivePortalsMod#1522]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

Iris 1.6.17 https://modrinth.com/mod/iris/version/1.6.17+1.20.4
Iris 1.6.15-1.6.16 in Discord Server

### Minecraft version

1.20.4

### Describe the issue

When I locked the error with unsupported mods Iris 1.6.17 and Sodium 0.5.8 I render portals began to not work and began to make a clipping. (Tested also on Iris 1.6.15).

**Comment by qouteall** [comment]
The latest version moved iris compat https://github.com/iPortalTeam/ImmersivePortalsMod/releases/tag/v5.1.6-mc1.20.4

**Comment by ShrikerChestTree** [comment]
> The latest version moved iris compat https://github.com/iPortalTeam/ImmersivePortalsMod/releases/tag/v5.1.6-mc1.20.4

Thank you!

**Comment by ShrikerChestTree** [comment]
Oh, no, you didn't fix it(
![2024-02-16_13 04 35](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/107254774/14d8ebfb-9ab1-453f-8230-3db7c79f15a0)
