### ISSUE TITLE
Crashing with Personal Player Dimensions

### ISSUE THREAD

**Issue by ScriptAero** [qouteall/ImmersivePortalsMod#1533]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

https://www.curseforge.com/minecraft/mc-mods/personal-player-dimensions

### Minecraft version

1.20.1

### Describe the issue

We have been using Immersive Portals now for a while for our pack without any major issues rising up in the version 1.20.1.
With a new addition of the above linked mod of "Personal Player Dimensions" we now can no longer use it alongside it.
The reason is a crash due to the ID of the dimension, as Immersive Portals seemingly doesn't accept that.
We believe the issue is on this side and would ask for a simple fix.
Admittedly we are using Forge with Sinytra Connector, but this our only option of a functioning and immersive world stacking mod we have available.
We hope you at least consider it.

These are the versions we're using:
MC: 1.20.1
Forge: 47.2.0
Sinytra: Connector-1.0.0-beta37+1.20.1
Forgified Fabric API : fabric-api-0.92.0+1.11.3+1.20.1
Immersive Portals: immersive-portals-3.3.9-mc1.20.1

[latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/14514598/latest.log)
[crash-2024-03-06_14.27.09-server.txt](https://github.com/iPortalTeam/ImmersivePortalsMod/files/14514606/crash-2024-03-06_14.27.09-server.txt)

**Comment by qouteall** [comment]
Unfortunately usage with sinytra connector is not being supported. It's recommended to wait for the Forge version.
