### ISSUE TITLE
Friend keeps having lag issues/being kicked when using Immersive Portals (1.20.4)

### ISSUE THREAD

**Issue by Badger505** [qouteall/ImmersivePortalsMod#1539]
### Is it a mod compatibility issue?

No

### Minecraft version

1.20.4

### Describe the issue

We've used Immersive Portals for a while now, and recently updated to 1.20.4. Anyone who joins the server is able to play fine, but one of my friends keeps having issues with immense lag, despite his internet running completely fine. After some time, he is kicked with the error "Internal Exception: java.net.SocketException: cCnnection reset" but does not crash.
We've troubleshooted and found that it has something to do with the immersive portals mod, but no one else has had the issue (I myself, along with 4 others, have joined and not had issues).
Whenever he joins when the server has other mods, or is a vanilla world, he runs fine. It is only this world in particular that has this happen with the mod.

**Comment by qouteall** [comment]
What is that friend's hardware spec? Does that friend allocate the game with more than 2GB RAM? Does that friend install a mod that other people does not install?

If I cannot reproduce the issue, then I cannot diagnose the issue and fix it.

**Comment by Badger505** [comment]
Apologies, it turns out he has memory issues and has ordered more memory in hopes of fixing the issue
