### ISSUE TITLE
Immersive Portal is incompatible with Sodium & Iris

### ISSUE THREAD

**Issue by nekoniyah** [qouteall/ImmersivePortalsMod#1540]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

https://www.curseforge.com/minecraft/mc-mods/irisshaders
https://www.curseforge.com/minecraft/mc-mods/sodium

### Minecraft version

1.20.1

### Describe the issue

![javaw_znhXkTkKNo](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/114854571/0bf7e07c-66cd-45ef-a469-8b499e9ae83e)

And it was working before updating all my mods (idk if immersive portal was updated or if it's the other mods)

**Comment by Phinwing** [comment]
first of all, get rid of Iris.

**Comment by qouteall** [comment]
It says to use Sodium 0.5.3 and iris 1.6.11

**Comment by Mrgaton** [comment]
but those versions doesn't support distant horizons + they are very outdated

**Comment by HydronBlaster** [comment]
The Author's solution worked, albeit requiring me to disable Sodium Extras because it crashes when opening video settings

**Comment by HydronBlaster** [comment]
nvm it crashes when playing a world

**Comment by HydronBlaster** [comment]
I won't die until Immersive Portals is compatible with Sodium 0.5.11 and Iris 1.7.6

**Comment by RXTransit** [comment]
using dependecy override I can get Sodium 0.5.13 working but not Iris 1.7.6 without a crash
