### ISSUE TITLE
[Crash, Fabric] Seeing a CC Turtle through an Immersive Portal crashes the game

### ISSUE THREAD

**Issue by Flexico** [qouteall/ImmersivePortalsMod#1546]
### Is it a mod compatibility issue?
Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)
https://tweaked.cc/

**Version Info**
- Minecraft, 1.20.1
- CC:Tweaked 1.110.1 Fabric
- Immersive Portals 3.3.9 Fabric

**Are you using OptiFine?:** No

**Steps to Reproduce**
Place a turtle,
Set up portals so that you can see the turtle  from beyond the render distance
Look through portal
Minecraft go boom

**Crash report (~/logs/latest.log)**
https://pastebin.com/02FNRPq4

**Comment by Alicev3** [comment]
Patch notes for the latest version of cc:tweaked (1.110.2) mark this as fixed, testing results match this
