### ISSUE TITLE
Incompatibility Iris 1.7.0+mc1.20.4!

### ISSUE THREAD

**Issue by sourdemon** [qouteall/ImmersivePortalsMod#1552]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

https://www.curseforge.com/minecraft/mc-mods/irisshaders/files/all?page=1&pageSize=20&version=1.20.4&gameVersionTypeId=4

### Minecraft version

1.20.4

### Describe the issue

The mod requires the minimum version of **Iris 1.6.17**
but I have the version of **Iris 1.7.0+mc1.20.4**!

**Comment by qouteall** [comment]
Probably fixed in 5.1.8
