### ISSUE TITLE
v5.1.8-mc1.20.4 is incompatible with Iris 1.7.0

### ISSUE THREAD

**Issue by Klous666** [qouteall/ImmersivePortalsMod#1554]
### Is it a mod compatibility issue?

Yes

### Minecraft version

1.20.4

### Describe the issue

Changelog for this version says compatibility was moved to Irs 1.7.0.  But an error is shown when using Iris 1.7.0

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Remove mod 'Iris' (iris) 1.7.0-snapshot+mc1.20.4-6bad887-dirty (C:\MineCraft-DistantHorizons\mods\iris-1.7.0-snapshot+mc1.20.4-6bad887-dirty.jar).
More details:
	 - Mod 'Immersive Portals' (immersive_portals) 5.1.8 is incompatible with any version before 1.7.0 or any version after 1.7.0 of mod 'Iris' (iris), but a matching version is present: 1.7.0-snapshot+mc1.20.4-6bad887-dirty!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by qouteall** [comment]
The iris version that you are using is `1.7.0-snapshot+mc1.20.4-6bad887-dirty` which is not `1.7.0`. If you want the game to launch, use dependency override as described in https://qouteall.fun/immptl/wiki/Miscellaneous.html#remove-the-sodium-iris-version-lock
