### ISSUE TITLE
Will not render terrain in Forge with Sinytra Connector, Embeddium, and Oculus

### ISSUE THREAD

**Issue by Cyberwolf606** [qouteall/ImmersivePortalsMod#1564]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

Sinytra Connector: https://github.com/Sinytra/Connector
Oculus: https://github.com/Asek3/Oculus
Embeddium: https://github.com/embeddedt/embeddium
(Also using:
Forgified Fabric API: https://github.com/Sinytra/ForgifiedFabricAPI)

### Minecraft version

1.20.1

### Describe the issue

Using Immersive Portals v3.3.2 as it's the only one that seems to work with any other versions of Oculus available (Later versions of 1.20.1 versions of Immersive Portals use 1.6.10, or versions before 1.6.9, and Oculus' earliest available version is 1.6.9), terrain will not render, but the skybox and the skyboxes of other dimensions will render. Also using Embeddium 0.3.0 as it works with Oculus 1.6.9, and Sinytra Connector 1.0.0-beta.43 with Forgified Fabric API 0.92.2+1.11.8 in order to get Immersive Portals to run on Forge 1.20.1.

Works fine when using Immersive Portals alone with Sinytra and FFAPI, but Embeddium and Oculus cause issues. I have tried other Sodium ports but they don't seem to fix the issue.

![GzlVkZO - Imgur](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/99134959/a6608da2-594f-4068-b8e9-7e8f45d0bc98)

[latest.log](https://github.com/user-attachments/files/15781624/latest.log)

[debug.log](https://github.com/user-attachments/files/15781627/debug.log)

**Comment by Su5eD** [comment]
Please don't report Connector issues to mod authors!

**Comment by Cyberwolf606** [comment]
Oh man, woops! I'm so sorry about that I forgot. I'll close this as not planned then I believe. Sorry!
