### ISSUE TITLE
1.20.5-1.21 PLS

### ISSUE THREAD

**Issue by vishualizze** [qouteall/ImmersivePortalsMod#1574]
### Suggestion

pls do 1.20.5-1.21 i want to use this mod SOOO bad

**Comment by SalTeyJek004** [comment]
![Patience fans](https://github.com/user-attachments/assets/e9a2a46c-6128-4871-9f11-6650d5b62812)

**Comment by Nick1st** [comment]
It will probably happen one day. Please stop spamming the issue tracker. Thanks
