### ISSUE TITLE
Update For Minecraft 1.21 PLZ?

### ISSUE THREAD

**Issue by LiuQiYu671** [qouteall/ImmersivePortalsMod#1577]
### Suggestion

An plans? Im waiting for it.

**Comment by SalTeyJek004** [comment]
![Patience fans](https://github.com/user-attachments/assets/57585800-fdf2-4f8a-80b0-e5ac590dcd71)

**Comment by Nick1st** [comment]
It will probably happen one day. Please stop spamming the issue tracker. Thanks
