### ISSUE TITLE
WE NEED 1.21 FABRIC

### ISSUE THREAD

**Issue by BinaryHarbinger** [qouteall/ImmersivePortalsMod#1581]
### Is it a mod compatibility issue?

Select One

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

WE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRIC

### Minecraft version

Other (specify below)

### Describe the issue

WE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRICWE NEED 1.21 FABRIC

**Comment by SalTeyJek004** [comment]
im going to fill your shoes with human teeth.
![Patience fans](https://github.com/user-attachments/assets/95e6da74-613b-43ce-97e4-a235f527e373)

**Comment by SalTeyJek004** [comment]
in the discord server the dev has said its being worked on, but will take some time due to burn out.
if you want it done asap, you would get better results by helping the dev than just demanding.

**Comment by LeandroTheDev** [comment]
the less insane arch user

**Comment by Nick1st** [comment]
It will probably happen one day. Please stop spamming the issue tracker. Thanks
