### ISSUE TITLE
Immersive Portal incompatibility with sodium and Iris

### ISSUE THREAD

**Issue by 3Caspro** [qouteall/ImmersivePortalsMod#1589]
### Is it a mod compatibility issue?

Yes

### Minecraft version

1.20.1

### Describe the issue

I have the right version of every mod that it's said, but it crash.
![Immagine 2024-08-09 193851](https://github.com/user-attachments/assets/3aa0e984-2e63-49ec-a918-baf30429f303)

**Comment by Mortycio** [comment]
up

**Comment by qouteall** [comment]
Duplicate to https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1536
