### ISSUE TITLE
Sculpt Command Crashing Game

### ISSUE THREAD

**Issue by coledamon** [qouteall/ImmersivePortalsMod#1590]
### Is it a mod compatibility issue?

No

### Minecraft version

1.20.4

### Describe the issue

[crash-2024-08-09_18.46.06-server.txt](https://github.com/user-attachments/files/16568112/crash-2024-08-09_18.46.06-server.txt)
[latest.log](https://github.com/user-attachments/files/16568114/latest.log)

1.20.4 Fabric version. Tested with other mods, then tested alone, crashed both times, indicating an issue solely with iPortal.

Steps to reproduce:
1) Place a cauldron
2) Create a 1x1 portal that has one side touching the top face of the cauldron (creation method doesn't seem to matter).
3) While looking at the top-of-the-cauldron portal, attempt to sculpt it.
4) Crash (The game crashed whilst ticking entity Error: java.lang.IllegalArgumentException: The validated expression is false)

Attempted also with a 3x3 portal that was touching the top of the portal and it worked fine, so it might just be something with the portal starting as 1x1 and being reduced to <1x1? Before crashing, it seems that the portal was successfully sculpted as a chat message was output (Portal Sculpted. Area Reduced: 0.4375  Area Before: 1.0000  Area After: 0.5625), so it might be something in some checks somewhere after the sculpt itself.

This might just be a "hey just don't do that" kind of error, but figured it would be best to report anyways (the goal was to create a false/portal-bottomed cauldron for a fun secret passage)

**Comment by coledamon** [comment]
Tested a bit more, same error happens with: 
Composter (on top face)
[Compostercrash-2024-08-10_14.18.14-server.txt](https://github.com/user-attachments/files/16570922/Compostercrash-2024-08-10_14.18.14-server.txt)
[Composterlatest.log](https://github.com/user-attachments/files/16570923/Composterlatest.log)

Stairs (halfway in from left/right): (tested with oak, but guessing it work work with any)
[Stairscrash-2024-08-10_14.46.35-server.txt](https://github.com/user-attachments/files/16570951/Stairscrash-2024-08-10_14.46.35-server.txt)
[Stairslatest.log](https://github.com/user-attachments/files/16570950/Stairslatest.log)

Anvil (halfway in from front): (Error message different for this one: "The game crashed whilst ticking entity Error: java.lang.IllegalArgumentException: triangle 264 not found in quad tree")
[Anvilcrash-2024-08-10_14.31.49-server.txt](https://github.com/user-attachments/files/16570926/Anvilcrash-2024-08-10_14.31.49-server.txt)
[Anvillatest.log](https://github.com/user-attachments/files/16570925/Anvillatest.log)


(Just in case it's important, other odd geometry blocks tested that didn't crash: Bed (right side), Chest (front), Grindstone (halfway in from front), Lectern (halfway in from front), Flower Pot (halfway in from front, top), Fence (halfway in from front))

**Comment by qouteall** [comment]
Should be fixed in 5.1.9
