### ISSUE TITLE
Incompatible with Sodium

### ISSUE THREAD

**Issue by Mortycio** [qouteall/ImmersivePortalsMod#1594]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

[Immersive Portals Continued](https://modrinth.com/mod/immersive-portals-continued)

[Sodium](https://modrinth.com/mod/sodium)

### Minecraft version

1.20.1

### Describe the issue

![image](https://github.com/user-attachments/assets/02b1b252-9fe4-45c1-88ca-a184852660a4)

https://mclo.gs/15ob3R7

immersive portals continued version: 3.4.0-iris1.8
sodium version: 0.5.11 + mc1.20.1
minecraft version: 1.20.1
fabric loader: 0.16.0
java version: 17.0.12

**Comment by qouteall** [comment]
Duplicate to https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1536
