### ISSUE TITLE
Underwater graphical bugs with shaders - bright pink

### ISSUE THREAD

**Issue by MayliSong** [qouteall/ImmersivePortalsMod#161]
Using Fabric for 1.15 and projectLUMA shaders, some odd things happen if you attempt to build a nether portal underwater, which I acknowledge is a pretty niche problem. Being underwater with the shaders on, you can't see the nether through the portal.
![Screenshot_8](https://user-images.githubusercontent.com/63749441/79520184-ecda9e00-800a-11ea-8bd1-518bb3f384d2.png)
 Which itself is not a terrible problem, but then being underwater and looking at any part not under the water/where you can see through causes everything else to turn pink.
![Screenshot_9](https://user-images.githubusercontent.com/63749441/79520233-15629800-800b-11ea-8ca9-2f95cb91ca37.png)
![Screenshot_10](https://user-images.githubusercontent.com/63749441/79520278-388d4780-800b-11ea-9091-a23fb3a67b56.png)

**Comment by qouteall** [comment]
Maybe it's fixed in 0.26
