### ISSUE TITLE
Mobs don't teleport through portals?

### ISSUE THREAD

**Issue by LoganDark** [qouteall/ImmersivePortalsMod#165]
Hit a creeper through a portal, it will not teleport. It will just clip through the portal.

MC 1.15.2 Forge 31.1.46 `immersive-portals-0.13(forMc1.15withForge)` (from CurseForge)

**Comment by qouteall** [comment]
The mob should teleport through. Does this happen with only this mod and mixinbootstrap installed?

**Comment by LoganDark** [comment]
Arrows teleport but only at very low speeds.

So I believe the entity teleporting code is somewhere but kind of weird.

I have Controlling, JEI, Mouse Tweaks, Inventory Tweaks, ReAuth, and RandomPatches. I think only the last one could possibly cause this behavior, if the mod usually works perfectly

**Comment by qouteall** [comment]
Try to remove randomPatches and try again?

**Comment by LoganDark** [comment]
I'll let you know if that fixes the issue. In the meantime if randompatches is the culprit, maybe you should check it out and see if you can improve compatibility.

**Comment by LoganDark** [comment]
I restarted MC without RandomPatches and things like dropped items, fast arrows, creepers etc. all do not teleport through any portals.

**Comment by qouteall** [comment]
Then remove all other mods

**Comment by LoganDark** [comment]
The issue persists with NO mods except for MixinBootstrap and ImmersivePortals.

Please just test it out and see if you can reproduce the bug.

**Comment by qouteall** [comment]
I cannot reproduce this.

**Comment by LoganDark** [comment]
I'm using OpenJDK as well. Let me see if running HotSpot fixes the issue.

**Comment by LoganDark** [comment]
Running Java jdk1.8.0_212 doesn't seem to fix the issue. I'm not really sure what else the problem could be. Do you have any ideas?

The issue still occurs on a new world, still using HotSpot VM.

**Comment by LoganDark** [comment]
I just noticed I'm using 0.13 and the latest version is 0.26. Mega oof.

Where can I get 0.26 for Forge? Is it just the jar in releases?

**Comment by LoganDark** [comment]
@qouteall Would you be willing to upload a Forge version of 0.26 to CurseForge?

**Comment by LoganDark** [comment]
ok so it seems dropped items, mobs, and arrows work cross-dimension, but not through portals leading to the same dimension (short range teleport in overworld for example)

Fast moving arrows still bypass both portals tho
