### ISSUE TITLE
Traveler's Backpack Incompatibility 1.20.1 Forge 

### ISSUE THREAD

**Issue by Nebula434** [qouteall/ImmersivePortalsMod#1668]
Currently have been playing a long playthrough with this mod, noticed that whenever I go through a nether portal ( most other portals too) I lose access to my backpack entirely. Forcing the user to re-join to get access back. This problem extends further when the user tries to put on the backpack after entering the new dimension, it entirely disappears. When u reload, it's entirely gone as well. Not sure if it is a Immersive Portals issue or a backpack issue but I thought i'd make it known!

**Comment by Nick1st** [comment]
There is no 1.20.1 Forge version. I suspect this is a connector "issue". (They can't really do anything against it either.)

**Comment by Nebula434** [comment]
Ah alright, thank you for the quick response bro!
