### ISSUE TITLE
aiming at a portal's skybox makes you aim at blocks behind the portal entity

### ISSUE THREAD

**Issue by LoganDark** [qouteall/ImmersivePortalsMod#167]
With creative mode's far reach, this can be annoying (and destructive)

![image](https://user-images.githubusercontent.com/4723091/79721996-28d66300-8298-11ea-861b-90944c703fc8.png)

**Comment by qouteall** [comment]
fixed. it will be in the next version

**Comment by qouteall** [comment]
Oh, after fixing it the cross portal block manipulation is mega broken.

**Comment by LoganDark** [comment]
Man, you don't test before you release do you? :P

Dude, just send the jar to me before release, I'll find every issue there is and then some. Just look at how many issues I opened when I discovered this mod.

If you have Discord we could talk on there and, you know, be more productive together? :P

**Comment by qouteall** [comment]
there is a discord. see the home page of wiki

**Comment by LoganDark** [comment]
I meant adding you specifically and not joining a server but I'll check it out.

**Comment by qouteall** [comment]
emergently released 0.16 to fix it

**Comment by LoganDark** [comment]
did you regression test 0.16 this time?
