### ISSUE TITLE
Add Bedrock 1.21 Support

### ISSUE THREAD

**Issue by Jaw7829** [qouteall/ImmersivePortalsMod#1672]
Could You Make A Bedrock Version Of This Mod? I’m Being 100% Serious Right Now. I’ve Been Looking For Bedrock Ports Of This Mod For A Long Time. This Is My Only Other Choice. Can You Please Add Bedrock Support?🫤😭🫥

**Comment by Jaw7829** [comment]
🥹

**Comment by Nick1st** [comment]
It's simply not possible, sorry.

**Comment by Jaw7829** [comment]
😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭
