### ISSUE TITLE
portals don't display your character intersecting with them correctly

### ISSUE THREAD

**Issue by LoganDark** [qouteall/ImmersivePortalsMod#179]
screenshot explanation

![image](https://user-images.githubusercontent.com/4723091/79858315-176a8500-8384-11ea-9285-cfa4d6a90612.png)

**Comment by LoganDark** [comment]
in f5 mode
![image](https://user-images.githubusercontent.com/4723091/79858558-75976800-8384-11ea-8737-c46723ae0e81.png)

I know f5 isn't really supported in this mod (would be cool if it was - raycast from your head to your camera and if it passes through a portal offset it) but this issue isn't f5 specific, f5 just lets me put my camera in a place that triggers the issue

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/79858723-b68f7c80-8384-11ea-8592-7f037da4a2c9.png)
also this (still in f5, my character just disappears)

**Comment by qouteall** [comment]
Probably fixed
