### ISSUE TITLE
portal clipping pyramid doesn't work all the time

### ISSUE THREAD

**Issue by LoganDark** [qouteall/ImmersivePortalsMod#180]
![portal clipping](https://user-images.githubusercontent.com/4723091/79859089-4cc3a280-8385-11ea-9b3e-da70038e8682.gif)

I have no descriptive title for this issue, please advise lol

**Comment by LoganDark** [comment]
that might be unavoidable as well as this
![image](https://user-images.githubusercontent.com/4723091/79881084-a50a9c80-83a5-11ea-819b-9127712121fe.png)

**Comment by qouteall** [comment]
Fixed. Now it enables GL_DEPTH_CLAMP
