### ISSUE TITLE
Render Distance is cut in half when viewing through portals.

### ISSUE THREAD

**Issue by Bambuzl-Byte** [qouteall/ImmersivePortalsMod#182]
I thought it was just a mod restraint, but now I may be wrong... Portals are cutting the render distance in half
![2020-04-21_13 35 20](https://user-images.githubusercontent.com/62759540/79901702-d602c580-83d5-11ea-81e0-25413f604153.png)
"Two portals side-by-side in the same chunk, with one portal face missing. Render distance is set to two chunks. The cow is 'floating' in the right portal."
https://youtu.be/niTbzww-e7M
So far, this has been for ALL portals.

**Comment by qouteall** [comment]
Turn graphic option from fast to fancy
https://github.com/qouteall/ImmersivePortalsMod/wiki/Config-Options

**Comment by Bambuzl-Byte** [comment]
thanbks
