### ISSUE TITLE
Player gets rendered through the wrong portal

### ISSUE THREAD

**Issue by Bambuzl-Byte** [qouteall/ImmersivePortalsMod#183]
https://youtu.be/MN2agZzZ4fQ
![2020-04-21_19 13 11](https://user-images.githubusercontent.com/62759540/79927155-7ff94680-8404-11ea-8600-f55888348f0e.png)

**Comment by LoganDark** [comment]
I think this is #181 except for player entities as well

**Comment by qouteall** [comment]
Cannot reproduce in the latest version
