### ISSUE TITLE
move_portal_destination

### ISSUE THREAD

**Issue by LoganDark** [qouteall/ImmersivePortalsMod#184]
man imagine nudging around the portal destination visually instead of using coordinates PLEASE ADD

can't add it myself because it would need some rotation calculations and for anything more complex than copy/paste I need an IDE to test in but I don't have one D:

**Comment by Bambuzl-Byte** [comment]
Long way:
1. Move the entrance portal physically (move_portal)
2. Reload the connected portals from the entrance (complete_bi_way_bi_faced (can exclude bi_faced))
3. Move the exit portal physically (move_portal)
4. Reload the connected portals from the exit (complete_bi_way_bi_faced (can exclude bi_faced))

Short way: add the command

**Comment by qouteall** [comment]
yes, firstly complete bi way portal, go to other side, remove connected portals, move portal then complete bi way portal again

**Comment by LoganDark** [comment]
Yes, that's what I'm doing.

remove_connected_portals
complete_bi_way_portal
go to other side
remove_connected_portals
nudge
complete_bi_way_portal
done

but it's slow and this will be faster and easier :P

**Comment by LoganDark** [comment]
If this feature were to be added, should it be relative to the axes of the destination (as seen through the portal), or the axes of the world?

Like, if you were in this situation:

![image](https://user-images.githubusercontent.com/4723091/79932147-abc6fd00-8401-11ea-8040-e659112c354c.png)

should it nudge the destination this way? (world axis)
![image](https://user-images.githubusercontent.com/4723091/79932302-0d876700-8402-11ea-9e3b-66c8628ddff3.png)

or this way? (destination axis)
![image](https://user-images.githubusercontent.com/4723091/79932251-ed57a800-8401-11ea-96fe-daabcbc1da22.png)

personally leaning towards world axis since that makes the most sense imho

**Comment by Bambuzl-Byte** [comment]
BTW you don't have to remove the portal each time, since moving the portal only changes the entities current position instead of the target. When you use /complete..., it auto-deletes the others for you.

**Comment by LoganDark** [comment]
> moving the portal only changes the entities current position instead of the target

I know that

> When you use /complete..., it auto-deletes the others for you.

Didn't know that, but I don't trust it so I'm going to keep using my method.

---

Rather than discussing workarounds I would like to discuss the feature request instead, see my post above

**Comment by qouteall** [comment]
The command has been added
