### ISSUE TITLE
advanced chunk culling bad

### ISSUE THREAD

**Issue by LoganDark** [qouteall/ImmersivePortalsMod#187]
![](https://cdn.discordapp.com/attachments/702367639237951538/702411285429485590/unknown.png)

why is the chunk the portal is in being unloaded when the portal is visible

world: https://logandark.net/files/S56056S3-O82505O4-S5N500ON-74QRRR3Q/e7d9fc678fb146ca.zip

**Comment by qouteall** [comment]
fixed
