### ISSUE TITLE
Dosen't let me join servers

### ISSUE THREAD

**Issue by WellGoblin** [qouteall/ImmersivePortalsMod#189]
Whenever i tried to join a server it would just kick me out

**Comment by LoganDark** [comment]
Does the server also have Immersive Portals installed?

**Comment by WellGoblin** [comment]
no it doesnt

**Comment by LoganDark** [comment]
Then the mod won't work on that server.

**Comment by WellGoblin** [comment]
ok thanks lol. makes sense :/

**Comment by LoganDark** [comment]
Close your issue please
