### ISSUE TITLE
End Portal not disappearing when frame is broken (1.14.4)

### ISSUE THREAD

**Issue by shredderslash** [qouteall/ImmersivePortalsMod#197]
![2020-04-25_08 50 22](https://user-images.githubusercontent.com/8062717/80283003-e666b900-86d1-11ea-85e7-88d9e3aae5eb.png)

**Comment by LoganDark** [comment]
??? why close it

**Comment by shredderslash** [comment]
Meant to put it on the Immersive Portals Mod For Forge page not sure how i wound up on the main

**Comment by LoganDark** [comment]
But this isn't forge specific. This applies to both versions, I just tested it on fabric and it has the same bug.
![image](https://user-images.githubusercontent.com/4723091/80283307-676e8200-86cb-11ea-86df-d3826a7221dc.png)

**Comment by qouteall** [comment]
This is vanilla behavior

**Comment by shredderslash** [comment]
So it is, but breaking the portal blocks (not the frame the actual portal blocks) doesn't work either. The only way I've found to remove an end portal once placed was to uninstall the mod, run the world without it, then reinstall

**Comment by sunsetbear** [comment]
> So it is, but breaking the portal blocks (not the frame the actual portal blocks) doesn't work either. The only way I've found to remove an end portal once placed was to uninstall the mod, run the world without it, then reinstall

/portal delete_portal

**Comment by LoganDark** [comment]
> /portal delete_portal

Doesn't exist in 1.14 afaik.

**Comment by muzikbike** [comment]
That "vanilla behaviour" is a bug: https://bugs.mojang.com/browse/MC-1174
