### ISSUE TITLE
Cannot open block GUI through portal

### ISSUE THREAD

**Issue by LoganDark** [qouteall/ImmersivePortalsMod#198]
The server denies the request because you're too far from the chest

Will need to mix into the code that checks if you're close enough to the chest, and scan for nearby portals that allow you to reach that chest.

**Comment by VexianEmpire** [comment]
Also applies to other blocks that have a GUI (e.g. Lecterns, Looms, Droppers) and beds

Does not apply to blocks that can be interacted with without using a GUI (excluding beds) (e.g. Levers, Doors, Comparators)

Now that I think about it this is probably obvious but I'm going to say it anyway

**Comment by LoganDark** [comment]
Yeah. Many GUIs have a range limit and since the server doesn't know that you can be closer relatively than you are absolutely (i.e. portal), it assumes you're too far and kicks you out.

I'm going to mix into this in the future and make the server consider nearby portals.

**Comment by ghost** [comment]
Anyone got a solution lol? And yes ik this post is 2 years old but still tho

**Comment by qouteall** [comment]
Fixed
