### ISSUE TITLE
Seems to require javafx

### ISSUE THREAD

**Issue by Scotsguy** [qouteall/ImmersivePortalsMod#2]
This mod constistently crashed for me when loading / shortly after loading when JavaFX was not installed. I installed java8-openjfx from the Arch repos and lo and behold, it works just fine.
Here's a log when JavaFX isn't installed: https://paste.ee/p/wOCrG
Maybe add this requirement to the Curseforge description?

Some info on my system:
OS: Arch Linux
Java Version: 1.8.0_222, OpenJDK
JavaFX Version: 8.u202-3, OpenJFX
Graphics Card: GTX 970

**Comment by Juuxel** [comment]
I think the usages of JavaFX's Pair can be replaced with Minecraft's Pair.

**Comment by Scotsguy** [comment]
> I think the usages of JavaFX's Pair can be replaced with Minecraft's Pair.

See #5
