### ISSUE TITLE
Crash when lighting nether portal on server

### ISSUE THREAD

**Issue by Littleownage** [qouteall/ImmersivePortalsMod#20]
My server crashes when I try to light a nether portal with flint and steel. 
Mod works as intended on my single player world. Client has optifine, optifabric, hwyla, voxelmap, orderly, roughlyenoughitems, and autofish installed as well. I can link versions of any of those if needed.

Here is my crash report: [crash-2019-08-29_04.32.21-server.txt](https://github.com/qouteall/ImmersivePortalsMod/files/3554939/crash-2019-08-29_04.32.21-server.txt)

Here is my server log: [2019-08-29-7.log.gz](https://github.com/qouteall/ImmersivePortalsMod/files/3554965/2019-08-29-7.log.gz)

Thank you for any help!

**Comment by scoobert19** [comment]
I also have this issue. Portal lights, I can see the default red fog on the other side, and then the server crashes. No chunks load before the server fails.

**Comment by qouteall** [comment]
Try 0.15 version and see whether this issue still exists
