### ISSUE TITLE
Non-Player, non-item entities are trapped in between teleportation.

### ISSUE THREAD

**Issue by Bambuzl-Byte** [qouteall/ImmersivePortalsMod#201]
The cow is stuck in limbo. It would usually just lag a bit to the other side.
![Minecraft_ 20w17a - Singleplayer 2020-04-28 16-05-30_Moment](https://user-images.githubusercontent.com/62759540/80537937-7aeb4880-896a-11ea-87c8-7d4798b22557.jpg)
https://youtu.be/OKORgrmrlII

**Comment by qouteall** [comment]
How did you make it?

**Comment by Bambuzl-Byte** [comment]
I punched the cow, and it ran through the portal, but it got stuck somewhere during teleportation.

**Comment by qouteall** [comment]
Close because outdated.
