### ISSUE TITLE
Mipmap level decreased to 0

### ISSUE THREAD

**Issue by benfah** [qouteall/ImmersivePortalsMod#202]
The mipmap level of Minecraft gets decreased to 0 because of the weird Portal Helper resolution. If you want to keep the portal helper texture you could just downsample the image to 256x256 or 128x128 :D

**Comment by LoganDark** [comment]
But the Portal Helper is beautiful!

**Comment by benfah** [comment]
Welp, you can still downsample the texture :p

**Comment by LoganDark** [comment]
Welp, I was going to add a commit that closes this issue without comment but you were too fast. Maybe in the future I'll wait an hour before replying.

**Comment by benfah** [comment]
Gotta go fast

**Comment by LoganDark** [comment]
Confirm that this build of Immersive Portals 0.28 for Fabric fixes your issue?

(Sorry, was delayed 5 minutes by an unexpected interruption)

[immersive-portals-0.28.jar.zip](https://github.com/qouteall/ImmersivePortalsMod/files/4553485/immersive-portals-0.28.jar.zip)

**Comment by benfah** [comment]
Yep, thanks!

**Comment by LoganDark** [comment]
I'm letting the PR merge close the issue
