### ISSUE TITLE
Map on item frame are not being rendered on mirrors

### ISSUE THREAD

**Issue by lebonq** [qouteall/ImmersivePortalsMod#209]
Minecraft 20w18a
Fabric 0.8.2 build 194
FabricAPI 0.10.1 build 336
Immersive Portals 0.9

![2020-05-01_22 06 47](https://user-images.githubusercontent.com/57987762/80838638-cc5d3700-8bf9-11ea-974f-495ab88297ec.png)
![2020-05-01_22 06 53](https://user-images.githubusercontent.com/57987762/80838640-cd8e6400-8bf9-11ea-959f-7eeb030cbb07.png)

**Comment by LoganDark** [comment]
are they being rendered backwards? (visible from the other side)

**Comment by lebonq** [comment]
I checked it in singleplayer and it's look like the front texture of the item of the item frame is not being rendered.
![2020-05-01_22 52 07](https://user-images.githubusercontent.com/57987762/80840828-750d9580-8bfe-11ea-86e9-91cc4c860154.png)
![2020-05-01_22 52 15](https://user-images.githubusercontent.com/57987762/80840829-750d9580-8bfe-11ea-98c2-422dbfc68107.png)
![2020-05-01_22 52 19](https://user-images.githubusercontent.com/57987762/80840830-75a62c00-8bfe-11ea-806b-9880c2b3fcc0.png)
