### ISSUE TITLE
Aiming problem with mirrors

### ISSUE THREAD

**Issue by lebonq** [qouteall/ImmersivePortalsMod#210]
Minecraft 20w18a
Fabric 0.8.2 build 194
FabricAPI 0.10.1 build 336
Immersive Portals 0.9

It's also happen in creative, and in singleplayer.
Also I cannot interact with fire which is on the mirror.

![2020-05-02 11-42-40_1_1](https://user-images.githubusercontent.com/57987762/80861004-ffd8a980-8c6b-11ea-919e-15ec5cd3be1e.gif)

**Comment by LoganDark** [comment]
You should provide an image or gif in the issue itself for convenience

**Comment by lebonq** [comment]
All my gif are higher than 10MB how can i do ?

Edit : I did it
