### ISSUE TITLE
A solution to the problem that players will be trapped in the air when using transfer commands to other worlds

### ISSUE THREAD

**Issue by flycat233** [qouteall/ImmersivePortalsMod#213]
When using the portal, when using the teleport command to other world, the character will be stuck in the air, unable to act, and prompt "player changed world without us noticing. Did some third party mod do something weight", and cause the server to crash. How can I solve this problem?

**Comment by qouteall** [comment]
It's probably a mod compatibility issue. Showing the full log may help to find that

**Comment by qouteall** [comment]
Close due to not having complete information to diagnose the issue.
