### ISSUE TITLE
Question: Using ImmersiveMod functionality (API) without having to use nether and end functionality

### ISSUE THREAD

**Issue by mainrs** [qouteall/ImmersivePortalsMod#216]
Hi!
My goal is to implement a new portal that appears in the sky and provides a small "preview" of the dimension that lies behind it. I am not sure if it is possible to use this mod for it. I know that you provide an API to allow custom portals but I do not want to force players to use your version of the nether and end portal. Is it somehow possible to deactivate those immersive portals? 

I guess I am asking/looking for a way to use the underlying rendering logic without having to use the already implemented immersive portals for the nether and end. However, if people want to use those, they should be able to add this mod and it would work for them.

**Comment by LoganDark** [comment]
> Is it somehow possible to deactivate those immersive portals?

Not yet. Imho, I think this mod could be separated out into two mods: one is the portal entity itself with rendering and teleportation and such, and the other is the stuff like alternate dimensions and nether portal conversion.

But that would be a _massive_ undertaking and I don't know if @qouteall would approve.

**Comment by mainrs** [comment]
I guess even a small split-off of the end and nether implementation would be enough to make it work. But yes, the optimal solution would be to split it off into `base` and `api` or something similar.

**Comment by qouteall** [comment]
Why don't you want to force player to use this mod's nether and end portal? Because it's laggier?
Splitting it is possible.

**Comment by mainrs** [comment]
Mainly yes. I mean, I have nothing against it but I'd like to give players the option to disable the preview in my mod as well if their pc isn't powerful enough. 

Would you be open to splitting it up? If so I'd give it a try and create a wip pr.

**Comment by qouteall** [comment]
You can make it an optional dependency that if the player does not install IP the preview will not show and if the player installs IP it will show preview

**Comment by mainrs** [comment]
Oh, that is another option as well! Thanks for pointing this out

**Comment by LoganDark** [comment]
I'll be willing to do the split if @qouteall approves.
