### ISSUE TITLE
Major FPS drops with dimension stack enabled.

### ISSUE THREAD

**Issue by MagmaSlime123** [qouteall/ImmersivePortalsMod#217]
Title says all. I'm getting 20-30 FPS while Dimension Stacking is Enabled. 

20 in the Nether and 30 on the surface.

**Comment by qouteall** [comment]
Try to install OptiFine or reduce render distance?

**Comment by MagmaSlime123** [comment]
> Try to install OptiFine or reduce render distance?

Optifine isn't available in 1.16.

**Comment by Physuo** [comment]
It is now, you can get it for 1.16.(whatever version)
