### ISSUE TITLE
Floor portals don't render when player is more than 4 blocks above it.

### ISSUE THREAD

**Issue by Bambuzl-Byte** [qouteall/ImmersivePortalsMod#218]
They render fine on the same level, but not above.

4 Blocks:
![2020-05-04_12 13 54](https://user-images.githubusercontent.com/62759540/80993598-f46ab700-8e00-11ea-9a3c-5e7c0d0697ed.png)

5 Blocks:
![2020-05-04_12 13 57](https://user-images.githubusercontent.com/62759540/80993622-fe8cb580-8e00-11ea-8e7d-83c2b5a14827.png)

**Comment by qouteall** [comment]
That black portal is player covering it?

**Comment by Bambuzl-Byte** [comment]
wym?

**Comment by qouteall** [comment]
nevermind.
Is it 1.15 or 1.16?
And try to increase render distance?

**Comment by Bambuzl-Byte** [comment]
MC 1.16 Mod Fabric v0.8

I think it only seems to bug out when you rotate the portal 180 degrees. Leaving it normal (top in -> bottom out) makes it act normal.

**Comment by qouteall** [comment]
Close because outdated.
