### ISSUE TITLE
1.15.2 Crashes before game opens

### ISSUE THREAD

**Issue by VexianEmpire** [qouteall/ImmersivePortalsMod#219]
[Here is the log](https://github.com/qouteall/ImmersivePortalsModForForge/files/4578641/latest.log), as I couldn't find the crash report

I disabled all mods except for FabricAPI and ImmersivePortals

I'm kinda new to Fabric to please correct any mistakes I make

**Comment by VexianEmpire** [comment]
The reason the log is on the Forge version's files is because I uploaded it there when I almost accidentally posted this issue there

**Comment by qouteall** [comment]
Seems that you used 1.14 version of the mod?

**Comment by qouteall** [comment]
The loader, IP, fabric api should all be 1.15.2

**Comment by VexianEmpire** [comment]
Thank you that fixed it
