### ISSUE TITLE
Make command /portal make_portal usable for command block

### ISSUE THREAD

**Issue by ImSpaceLover** [qouteall/ImmersivePortalsMod#224]

**Comment by qouteall** [comment]
You can create a template portal somewhere and use cb_set_portal_destination and cb_complete_bi_way_portal to create the portal

**Comment by ImSpaceLover** [comment]
![image](https://user-images.githubusercontent.com/64267797/87412289-89441a80-c5d1-11ea-9fde-929daf171ce7.png)
