### ISSUE TITLE
Blocks in other dimension do not render when nearing portal boundary

### ISSUE THREAD

**Issue by Quizer9O8** [qouteall/ImmersivePortalsMod#228]
How to reproduce:
1. Stack the Dimensions Nether -> Overworld -> Skylands -> Void -> End
2. go between dimensions
![2020-05-06_19 12 22](https://user-images.githubusercontent.com/19509275/81207232-8a533d00-8fcd-11ea-91a4-89417c112724.png)
3. reload chunks to reverse the effects in current dimension
![2020-05-06_19 13 13](https://user-images.githubusercontent.com/19509275/81207300-a7880b80-8fcd-11ea-983a-867559e88466.png)

**Comment by qouteall** [comment]
Fabric or forge? Did you install optifine?

**Comment by qouteall** [comment]
Close due to not having complete information to diagnose the issue.
