### ISSUE TITLE
Underwater rendering broken in all versions

### ISSUE THREAD

**Issue by Thaums** [qouteall/ImmersivePortalsMod#24]
![immersive portals](https://user-images.githubusercontent.com/21028062/64876916-45356180-d61e-11e9-8042-caa61cecaf1d.png)
![immersive portals 2](https://user-images.githubusercontent.com/21028062/64876929-4a92ac00-d61e-11e9-873d-5d88cc9b9b15.png)
Underwater fog appears to not render at all, same with lava

Modlist:
fabric-api-0.3.2+build.226-1.14
immersive-portals-0.18

Fabric version: fabric-loader-0.6.1+build.165-1.14.4

I tested this on the very first version of the mod uploaded, still happens
Occurs with or without a portal active

**Comment by qouteall** [comment]
This has been fixed. You will see it in 0.19 version
