### ISSUE TITLE
Glass and water rendering is not correct when the portal is nearby (same with a mirror)

### ISSUE THREAD

**Issue by ImSpaceLover** [qouteall/ImmersivePortalsMod#243]
![2020-05-09_15 18 25](https://user-images.githubusercontent.com/64267797/81473646-8eb76a00-9208-11ea-8fda-a3c5c034efea.png)
![2020-05-09_15 19 00](https://user-images.githubusercontent.com/64267797/81473647-8fe89700-9208-11ea-875e-13c017b8be65.png)

**Comment by qouteall** [comment]
Fixed. It will be in the next version

**Comment by ImSpaceLover** [comment]
Same issue but with mirrors https://youtu.be/NeM91KX3X3E
