### ISSUE TITLE
I can’t set the portal rotation on two axes at the same time

### ISSUE THREAD

**Issue by ImSpaceLover** [qouteall/ImmersivePortalsMod#244]
For example: I need to make a horizontal portal that teleport you to a vertical surface. (like at the first pic)
![2020-05-09_15 58 56](https://user-images.githubusercontent.com/64267797/81474483-60d52400-920e-11ea-96a6-e8de19be7271.png)

But I built my house (or something else) contrariwise and I need to see the view from first pic from the other side
![2020-05-09_15 59 05](https://user-images.githubusercontent.com/64267797/81474632-79920980-920f-11ea-9959-2bd37d4dd74c.png)

**Comment by LoganDark** [comment]
> contrariwise

LOL

I think any rotation is possible with set_portal_rotation. Just try stuff until you get what you want? might need to type some square roots and things into google

**Comment by qouteall** [comment]
If the reverse portal is generated by complete_bi_way_portal, it will use the inverse rotation to make space "connect". If not the teleportation will not be seamless

**Comment by LoganDark** [comment]
have you tried actually rotating the portal body around the Y axis? As in, rotate portal body, not set rotation

**Comment by ImSpaceLover** [comment]
> have you tried actually rotating the portal body around the Y axis? As in, rotate portal body, not set rotation

It do nothing

**Comment by LoganDark** [comment]
whoops, forgot rotating the portal body doesn't actually rotate anything else xD
uhh... maybe I could add a new command `add_portal_rotation`

**Comment by ImSpaceLover** [comment]
Okay, I'll wait

**Comment by LoganDark** [comment]
this is a valid issue

**Comment by ImSpaceLover** [comment]
Oh, okay

**Comment by ImSpaceLover** [comment]
So, I think rotate_portal_rotation can help me now
