### ISSUE TITLE
Micro stutters when placing/destroying blocks.

### ISSUE THREAD

**Issue by TheAlcoholicDuck** [qouteall/ImmersivePortalsMod#246]
When the mod is installed (both fabric and forge) I get frame time spikes when destroying or placing blocks. Version: 1.15.2

Edit: This seems to happen in other versions as well.

**Comment by qouteall** [comment]
Try to install optifine

**Comment by TheAlcoholicDuck** [comment]
> Try to install optifine

That changes nothing. I've tried everything that doesn't require coding skills.

**Comment by qouteall** [comment]
Does it stutter without this mod?

**Comment by TheAlcoholicDuck** [comment]
> Does it stutter without this mod?

No.

**Comment by TheAlcoholicDuck** [comment]
I don't know if this helps, but it seems to be caused by chunk updates.

**Comment by qouteall** [comment]
Fixed in the latest version
