### ISSUE TITLE
Add a way to create vanilla nether portal

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#247]

**Comment by VexianEmpire** [comment]
When you light a portal there could be a GUI of which type of portal you want to create

Maybe there could be custom settings for what the portal looks like (e.g. red only, green only, blue only, fisheye, swirl, hue shift, distort, glitch, refraction, etc. (note that these are only suggestions and are not mandatory))

**Comment by OpenSauce04** [comment]
I think that a config option would be a better approach, a gui would break the immersion too much

**Comment by LoganDark** [comment]
Imagine getting ready to create your nether portal, and you right click with a flint and steel to light it, and then... "Are you sure you want to do that? Would you like to create a vanilla portal instead? Which one do you want?"

**Comment by VexianEmpire** [comment]
`/portal make_vanilla_portal` Make vanilla portal
`/portal make_portal 3 3 minecraft:overworld 100.5 70.5 100.5 {PortalColorFilter:"FF0000"}` Make red portal

**Comment by LoganDark** [comment]
> PortalColorFilter:"FF0000"

Ooo, dunno if that is possible.

I should add NBT argument to the make_portal command

**Comment by VexianEmpire** [comment]
`PortalColorFilter` Only allow specific color to go through portal
`PortalColorOverlay` Overlay specific color on top of portal

**Comment by LoganDark** [comment]
> `PortalColorFilter` Only allow specific color to go through portal
> `PortalColorOverlay` Overlay specific color on top of portal

Still don't know if that is possible. Definitely will need a shader, and you won't see the color after you pass through. I don't think @qouteall would be willing to add it

This is the wrong issue, make a new one if you want to discuss this.

**Comment by qouteall** [comment]
Implemented
