### ISSUE TITLE
Immersive Portals doesn't work with Continuum 2.1

### ISSUE THREAD

**Issue by Tammell** [qouteall/ImmersivePortalsMod#252]
I have Continuum 2.1 shaders but when I installed immersive portals I get errors and everything doesn't render properly. Some blocks are white and grass looks weird just as an example. I tried it with both fabric and forge but get the same errors.

[Shaders] Error: Invalid program "gbuffers_textured"
[Shaders] Error: Invalid program "gbuffers_terrain"
[Shaders] Error: Invalid program "gbuffers_block"
[Shaders] Error: Invalid program "gbuffers_entities"

When I remove Immersive Portals the errors stop.

**Comment by qouteall** [comment]
Fixed. Will be in the next version
