### ISSUE TITLE
Immersive Portals is incompatible with Sodium

### ISSUE THREAD

**Issue by Neubulae** [qouteall/ImmersivePortalsMod#254]
https://github.com/jellysquid3/sodium-fabric
[crash-2020-05-12_00.36.07-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/4610902/crash-2020-05-12_00.36.07-client.txt)

**Comment by LoganDark** [comment]
Highlight:
> `Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_761::redirectGetTranslucent with priority 1000 cannot inject into net/minecraft/class_761::method_3251(Lnet/minecraft/class_1921;Lnet/minecraft/class_4587;DDD)V merged by me.jellysquid.mods.sodium.mixin.chunk_rendering.MixinWorldRenderer with priority 1000 [PREINJECT Applicator Phase -> immersive_portals.mixins_client.json:MixinWorldRenderer -> Prepare Injections ->  -> redirect$dle000$redirectGetTranslucent()Lnet/minecraft/class_1921; -> Prepare]`

**Comment by qouteall** [comment]
Sodium's injection is more invasive than OptiFine, so making it compatible is non-trivial work.

**Comment by qouteall** [comment]
And I will start investigating it after sodium's first release

**Comment by Jarfeh** [comment]
I noticed that you've since closed the pull request under sodium for compatibility. Has the compatibility issue been resolved?

**Comment by qouteall** [comment]
@Jarfeh I added another pr. Because sodium switched development branch for 2 times.

**Comment by Jarfeh** [comment]
Ah, I see

**Comment by Linkspeedrunner** [comment]
sodium 0.5.11 is incompatible with any version of immersive portals
