### ISSUE TITLE
Player ghosts in portals instead of actual player

### ISSUE THREAD

**Issue by rapus95** [qouteall/ImmersivePortalsMod#26]
Here is my friend's ghost after he entered the nether 1 min ago:
![2019-09-15_22 15 40](https://user-images.githubusercontent.com/5960902/64927218-2b577280-d808-11e9-800a-3b7608a2dd62.png)
And here is his screen at the same moment:
![photo_2019-09-15_22-30-40](https://user-images.githubusercontent.com/5960902/64927240-7e312a00-d808-11e9-898b-e21a83d653b1.jpg)

You can also see that we cannot see each other at the actual positions.

**Comment by rapus95** [comment]
Oh and as I see right now, the name of him is clipped by the portal. Maybe you know where that comes from and can fix it 👼

**Comment by qouteall** [comment]
Fixed in 0.19
