### ISSUE TITLE
[1.15.2] Mod causes entities in chunks that are unloaded after a players death to remain frozen on the client when returning to the chunk.

### ISSUE THREAD

**Issue by lizfinite** [qouteall/ImmersivePortalsMod#260]
The issue can be reproduced:

1. Create a new world  (I did superflat for ease of testing)
2. Choose a direction, and fly until you're sure the spawn chunk is unloaded. Open F3 if you want to use Coords.
3. Do /kill, then wait until all the mob sounds/movements have stopped before respawning.
4. Fly back in exactly the same direction to where you died.
5. The entities in the area should be frozen and reloading the save will make them disappear.

This occurs with just the mod itself, as well as dependencies, on the lastest Fabric Loader and API versions. (0.8.3+build196 and 0.10.8+build.310-1.15 respectively.)

**Comment by VexianEmpire** [comment]
This happened on the IP server but I thought it was a problem with Minecraft itself

**Comment by LoganDark** [comment]
Does it look kind of like this when the entities freeze?

![](https://cdn.discordapp.com/attachments/707163597888946176/707170622429462558/unknown.png)

**Comment by LoganDark** [comment]
This is the Fabric repository, no need for the loader version in the title.

**Comment by qouteall** [comment]
Looks like a severe issue

**Comment by lizfinite** [comment]
Yep, exactly like that. Worse still is that the client won't let you occupy the same space as the frozen entities. They'll push you out either direction; but you can't move them like normal entities that are just standing still.

**Comment by LoganDark** [comment]
> Yep, exactly like that.

Spinning too?

**Comment by lizfinite** [comment]
No spin. Just frozen immovable soundless husks.

**Comment by qouteall** [comment]
Fixed in the latest version
