### ISSUE TITLE
(Suggestion) Portal Commands and NBT

### ISSUE THREAD

**Issue by VexianEmpire** [qouteall/ImmersivePortalsMod#264]
- [x] `/portal make_vanilla_portal` #247 (See [here](https://github.com/qouteall/ImmersivePortalsMod/issues/264#issuecomment-698882064))
- [ ] `/portal make_portal 3 3 minecraft:overworld 100.5 70.5 100.5 {NBTDATA}`
### Color
- [ ] `PortalColorFilter`
`[Red, Green, Blue]`
Only allow specific color to go through portal
- [ ] `PortalColorOverlay`
`[Red, Green, Blue, Alpha]`
Overlay specific color on top of the portal (See [here](https://github.com/qouteall/ImmersivePortalsMod/issues/264#issuecomment-698882064))
### Camera
~~`CameraRotationMultiplier`
`[X, Y, Z]`
The rotation of the camera (the player's viewpoint of the portal) will be multiplied by the specified value for a refraction effect
![image](https://user-images.githubusercontent.com/64798986/82170460-1a289f00-988a-11ea-82bc-dcb6a41f8849.png)
`CameraFOVMultiplier`
`[X, Y, Z]`
The FOV of the camera (the player's viewpoint of the portal) will be multiplied by the specified value for a refraction effect
`CameraFOVAdder`
`[X, Y, Z]`
The FOV of the camera (the player's viewpoint of the portal) will be added with(?) the specified value for a refraction effect~~ (See [here](https://github.com/qouteall/ImmersivePortalsMod/issues/264#issuecomment-698882064))
### Gravity
**Gravity cannot be done right now because the only gravity mods are in Forge 1.12.2 or under.**
- [ ] `PortalAffectsGravity`
The gravity of the player will be shifted to the rotation of the destination portal from the perspective of the (rotation of) the portal body from the perspective of the (rotation of) the player.
- [ ] `AdditionalGravityRotation`
`[X, Y, Z]`
The gravity of the player will be shifted by the specified value, on top of the rotation of the portal itself.
### Basic Filters
- [ ] Fisheye
- [ ] Swirl
- [ ] Hue shift
~~Distort~~ (See [here](https://github.com/qouteall/ImmersivePortalsMod/issues/264#issuecomment-698882064))
- [ ] Glitch

etc.

**Comment by LoganDark** [comment]
> /portal make_portal 3 3 minecraft:overworld 100.5 70.5 100.5 {NBTDATA}

Already planned
> /portal make_vanilla_portal

More detail needed (how it will work, etc) - this is complicated because there needs to be an unbiased way for this command to work.

Perhaps you build the portal frame out of obsidian, and then run that command to light it as vanilla. That would be unbiased.
> PortalColorFilter
> [Red,Green,Blue,FilterIntensity]

What's the need for FilterIntensity if you can simply use a lighter color to subtract less color?

> CameraRotationMultiplier
> [X,Y,Z]
> The rotation of the camera (the player's viewpoint of the portal" will be multiplied by the > specified integer for a refraction effect

The... rotation of the camera will be multiplied? I don't know what you mean by this.

**Comment by VexianEmpire** [comment]
> More detail needed (how it will work, etc) - this is complicated because there needs to be an unbiased way for this command to work

`/portal make_vanilla_portal 3 3 100.5 70.5 100.5`?

Can the destination dimension of vanilla portals be modified?

> The... rotation of the camera will be multiplied? I don't know what you mean by this.

![image](https://user-images.githubusercontent.com/64798986/82170460-1a289f00-988a-11ea-82bc-dcb6a41f8849.png)

**Comment by LoganDark** [comment]
> `/portal make_vanilla_portal 3 3 100.5 70.5 100.5`?

Blocks can't be placed on fractional coordinates so this would have to be biased. I think I better support the lighting idea, where you build a frame yourself and run a command to simulate a fire being started without triggering Immersive Portals' overrides.

**Comment by qouteall** [comment]
About the color overlay, this can be done by putting transparent blocks in front of the portal.
Refraction is out of this mod's scope (some optifine shaders have approximate refraction rendering).
About make vanilla portal, the nether portal mode can be configured now.
About distort, this mod's portal rendering mechanic does not allow that

**Comment by qouteall** [comment]
Gravity change is implemented now. The hue shift and distortion is theoretically achievable via the gui portal feature
