### ISSUE TITLE
Worldstacking only goes 11k blocks

### ISSUE THREAD

**Issue by AutoCADEng** [qouteall/ImmersivePortalsMod#267]
I was attempting to use portals and world stacking to travel to the far lands. Utilizing the 8:1 nether ratio. I made it to -11600 before I found a point that  allowed me to get onto the nether roof, rather than the overworld.

![image](https://user-images.githubusercontent.com/53391942/82303861-db682580-99fe-11ea-83a9-57a4599ffc67.png)

**Comment by LoganDark** [comment]
Are you using Forge?

**Comment by qouteall** [comment]
The vertical connecting portal's width is 233333. I can change it to bigger

**Comment by AutoCADEng** [comment]
Yes, I'm running this specific jar file.
immersive-portals-0.18(forMc1.15withForge)

**Comment by LoganDark** [comment]
> The vertical connecting portal's width is 233333. I can change it to bigger

you could change it to follow the player's position so that they can never reach the edge

**Comment by AutoCADEng** [comment]
There would need to be a portal per player in that case. I'm not sure what would happen if two or more portals overlapped.

**Comment by LoganDark** [comment]
> There would need to be a portal per player in that case. I'm not sure what would happen if two or more portals overlapped.

not exactly, but maybe it would be less complicated to just use a much bigger size, like `1000000000` (Minecraft worlds are usually about 30 million blocks in either direction)

**Comment by AutoCADEng** [comment]
Worth a shot. It'd take at least, 60,000,001
I'm not sure what'd happen if you cross the 30 million limit.

**Comment by LoganDark** [comment]
> I'm not sure what'd happen if you cross the 30 million limit.

Nothing. That's just the default world border but Minecraft worlds are infinite.

**Comment by LoganDark** [comment]
@qouteall perhaps you could automatically use the size of the world border?
