### ISSUE TITLE
What about command /portal turn_portal_into_mirror?

### ISSUE THREAD

**Issue by ImSpaceLover** [qouteall/ImmersivePortalsMod#270]
Idk why but this can be cool feature

**Comment by LoganDark** [comment]
why close?

**Comment by ImSpaceLover** [comment]
I suggested this because i wanted rotatable mirrors but i found out that i already can rotate mirrors. 
But yeah, this is not such a bad idea

**Comment by qouteall** [comment]
This feature has already been implemented. `/portal turn_info_fake_enterable_mirror`
