### ISSUE TITLE
Startup crash with most recent Optifine

### ISSUE THREAD

**Issue by Lunalunata** [qouteall/ImmersivePortalsMod#276]
When OptiFine 1.15.2 HD U G1 pre18 is used with Immersive Portals (forge) and Mixin, then it will crash during start-up.

**Comment by qouteall** [comment]
what's the crash report?

**Comment by Buic** [comment]
I have had the same issue, however my game freezes instead of crashing.
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/4796112/latest.log)
