### ISSUE TITLE
Make a same verb for all commands

### ISSUE THREAD

**Issue by ImSpaceLover** [qouteall/ImmersivePortalsMod#278]
Why is it "make" here
![image](https://user-images.githubusercontent.com/64267797/82981680-444e2f80-9ff5-11ea-9b9b-dbc8c1bcbc00.png)
but "add" here?
![image](https://user-images.githubusercontent.com/64267797/82981734-63e55800-9ff5-11ea-8584-cf424f7c6077.png)

I suggest replacing these verbs with the verb "create".

**Comment by LoganDark** [comment]
make_portal sounds better than create_portal :D

and add wrapping is better than create wrapping or make wrapping

**Comment by LoganDark** [comment]
?

**Comment by LoganDark** [comment]
Do you mean using the same verb for just the wrapping commands? Since in that case, I would not mind if make_small_inward_wrapping was changed to add_small_inward_wrapping and etc.

**Comment by qouteall** [comment]
I am considering changing them to "create" except for "make_portal"

**Comment by ImSpaceLover** [comment]
Yes
