### ISSUE TITLE
You can get kicked for flying if you are standing on a block through a portal

### ISSUE THREAD

**Issue by LoganDark** [qouteall/ImmersivePortalsMod#280]

**Comment by qouteall** [comment]
https://media.discordapp.net/attachments/707163597888946176/715339568995631124/portals.png?width=1136&height=613

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/83086421-95851000-a043-11ea-8185-259bd3312de7.png)
image version

**Comment by qouteall** [comment]
Close because outdated.
