### ISSUE TITLE
place block through dimension stack

### ISSUE THREAD

**Issue by LoganDark** [qouteall/ImmersivePortalsMod#281]
1. Alternate2 on top of overworld
2. Pillar to the top of overworld
3. You can place a block on the pillar and it will be placed on Y 0 in alternate2

**Comment by qouteall** [comment]
I tested and the block placing works normally as you described. What do you mean "pillar"?

**Comment by LoganDark** [comment]
@qouteall if there is a block at y level 255 and you try to place a block on top, it says the build limit is 256... unless I'm wrong and you actually implemented this

**Comment by LoganDark** [comment]
Closed because already implemented
