### ISSUE TITLE
Storing portals in a minecraft compatible manner

### ISSUE THREAD

**Issue by rapus95** [qouteall/ImmersivePortalsMod#29]
When removing the mod, every portal is unlinked and reactivating a portal connects to a new location. Thus it seems you don't use the minecraft algorithm of determining the portal to link to or to spawn. It would be nice if you could change the algorithm to the minecraft way (because we had floating portals several times aswell)

**Comment by qouteall** [comment]
There are invisible blocks filling portal area. Maybe these blocks in the other dimension are not deleted when removing the mod. If the portal filling block still remains, the obsidian frame will be regarded as empty and will not be linked.
And I will decrease the possibility of generating floating portal.

**Comment by qouteall** [comment]
If you remove the mod you should go to nether and the portal filling blocks should vanish.

**Comment by rapus95** [comment]
> If you remove the mod you should go to nether and the portal filling blocks should vanish.

Yep, though as the chunks of the other portals weren't loaded in the other dimension, I have to go through every portal to remove these blocks. And since you use another placing mechanic than vanilla, it places the portal not next to it but rather radomly far away. Every time you use a portal the first time when the chunk in the other dimension hasn't been loaded.

As an idea:
a) Change vanilla portal blocks such that when the mod is removed every portal is actual vanilla portal block
b) only save the portal blocks as vanilla portals and replace them again when loading
That way the saves will always contain valid portals

**Comment by rapus95** [comment]
Order of activation: Left one, right one
![2019-09-19_16 11 16](https://user-images.githubusercontent.com/5960902/65251775-3821e200-daf8-11e9-8443-8e2ef163afd7.png)
Left Entry:
![2019-09-19_16 11 30](https://user-images.githubusercontent.com/5960902/65251932-70c1bb80-daf8-11e9-8432-e4287c17262b.png)
Right Entry:
![2019-09-19_16 11 21](https://user-images.githubusercontent.com/5960902/65251987-80d99b00-daf8-11e9-8d40-18e3f3835200.png)

Watch the huge difference between coordinates. Shouldn't they connect to the same portal in nether?

I found out, that when swapping the order in which I activate the portals, the endpoints in nether are swapped too (now the nether fortress is left):
![2019-09-19_16 16 12](https://user-images.githubusercontent.com/5960902/65252208-d9109d00-daf8-11e9-8e7c-3f99743194d6.png)

**Comment by rapus95** [comment]
Update: activating the second one produces that error:
```
[16:17:48] [Server thread/ERROR]: [Portal] Cannot find the reverse portal. Nether portal may not be removed normally.
```

**Comment by qouteall** [comment]
It will search for big lava lake, this could make portal generate far from its corresponding position.
This mod is not intended to work when the mod was removed and added again. It's hard to store information without this mod installed.
The "Cannot find the reverse portal" is an issue and I am trying to fix it.

**Comment by rapus95** [comment]
Btw why does it look for a big lava lake? Especially where vanilla minecraft rather tries to prevent spawning midair above a lava lake :/
