### ISSUE TITLE
Not able to open minecraft

### ISSUE THREAD

**Issue by orangemn6** [qouteall/ImmersivePortalsMod#298]
I think it might be a problem with optifine, but here is the pastebin. https://pastebin.com/JhCKkQUU

**Comment by CGNRYY** [comment]
How to use this thing

**Comment by qouteall** [comment]
Try to use optifine pre26

**Comment by orangemn6** [comment]
I use optifine pre26 with optifabric

**Comment by orangemn6** [comment]
Will pre29 or pre30 work better?

**Comment by qouteall** [comment]
last time I tested pre30 works

**Comment by orangemn6** [comment]
Yes pre30 works thank you!!!
