### ISSUE TITLE
Incompatible with Optifine Shaders

### ISSUE THREAD

**Issue by ClockwerkKaiser** [qouteall/ImmersivePortalsMod#3]
When Immersive Portals is installed, Shaders get very wonky. 

Attached are two screenshots. One without the mod, and one with the mod. 

![2019-07-26_13 45 28](https://user-images.githubusercontent.com/8023695/61971076-29152c80-afac-11e9-9e0d-7603537349e5.png)

![2019-07-26_13 47 34](https://user-images.githubusercontent.com/8023695/61971085-303c3a80-afac-11e9-85cb-554becd14a19.png)

**Comment by qouteall** [comment]
It's half compatible with shaders now. Now it can't render portal when the shader is present

**Comment by qouteall** [comment]
check 0.11 version

**Comment by VoxelCreatesStuff** [comment]
didnt get better untill now sadly
