### ISSUE TITLE
Requiem 1.0.0 and Immersive Portals 0.19 Bug

### ISSUE THREAD

**Issue by Kamalalshair** [qouteall/ImmersivePortalsMod#30]
I have not tested this on every mob, but with skeletons, when the portal renders, it renders the head of the Skeleton in first person mode which covers the camera.

**Comment by qouteall** [comment]
How to reproduce this bug?

**Comment by qouteall** [comment]
Requiem seems to have many rendering issues with this mod.

**Comment by Kamalalshair** [comment]
To reproduce this bug, simply possess a mob/skeleton and be near a portal. My particular setup had a two-way portal for a tunnel that collapsed a large distance into a smaller one when moving through it. I.E. going around the portal was 8 blocks, going through was one.
