### ISSUE TITLE
Cannot access nether/void after disabling plugin

### ISSUE THREAD

**Issue by Processhf** [qouteall/ImmersivePortalsMod#301]
There is no way to get into the nether or void on my server after disabling ImmersivePortals

**Comment by qouteall** [comment]
It's an issue related to DFU. I am planning to fix it.
But if you want to fix it now, you can create a new world with the same seed and level name, then use the new world's level.dat to replace the broken world's level.dat(I am not sure whether this will work.). Don't forget to backup the old level.dat before doing this. (And the player's item may be lost in this process, you need to put items into a chest in world before doing that)

**Comment by qouteall** [comment]
fixed
