### ISSUE TITLE
Registry remapping failed!

### ISSUE THREAD

**Issue by ardentcrest** [qouteall/ImmersivePortalsMod#303]
with new fabric server 1.16.1 and just this mod and fabric api I cant get in to newly created world.

**Comment by qouteall** [comment]
Where do you see "registry remapping failed"? post the full crash report

**Comment by ardentcrest** [comment]
this is with out portals in client https://paste.ee/p/v7APy
This is with portals in client https://paste.ee/p/jDF92

Also in single player all items in inventory are have the wrong icon. ie an arrow is blue dye and so on and only when mod is enabled on client

**Comment by qouteall** [comment]
Are you playing multiplayer when triggering this issue? If you are playing multiplayer your mod list should be consistent with the server's

**Comment by ardentcrest** [comment]
this is using fabric server and client. there is also  different error screen when using an un-modded  client 
![error1](https://user-images.githubusercontent.com/25410934/85724785-73d38300-b6ec-11ea-90fd-9bb9a9764aa4.gif)

**Comment by qouteall** [comment]
If you want to join a server the client mod list should be the same as the server's. For the client inventory issue, to know whether it's a mod compat issue, I need you to only enable this mod and fabric api and enter a new world and see whether the issue occurs

**Comment by qouteall** [comment]
Close because outdated.
