### ISSUE TITLE
NullPointers on Dedicated Servers (1.16.1 Fabric)

### ISSUE THREAD

**Issue by ArchieBeepBoop** [qouteall/ImmersivePortalsMod#305]
Using the latest version in curse. (v0.12)

https://pastebin.com/W1yWc6pm

Steps to repro:

Attempt to create a portal in a newly generated dedicated world
As soon as the loading finishes, attempt to step in.

**Comment by qouteall** [comment]
I cannot reproduce this. Are you using other mods?

**Comment by ArchieBeepBoop** [comment]
I'll try reproducing it again with my updated modlist and I'll send it over to you in a zip file if you wish, if it happens again that is.

**Comment by qouteall** [comment]
Close because outdated.
