### ISSUE TITLE
1.16.1 - Teleporting to the Overworld from a Vanilla Custom Dimension Causes Chunk Loading To Freeze

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#306]
Basically, when teleporting to the overworld from a vanilla custom dimension, the game freezes on chunk loading. The only way to get back to the world that I try to teleport to is to exit the world and re-enter (as in save and quit and then reload the world).

I've submitted a video to showcase the bug at https://youtu.be/feajI4hDwrY. Sorry about the length. I didn't realize the recording went on for 23 minutes. If needed, I can make a shorter video.

**Comment by qouteall** [comment]
It seems super laggy on your computer. This kind of lag is bug

**Comment by qouteall** [comment]
After profiling, the main lag cause after portal generation is light updates. You can try to install phosphor https://www.curseforge.com/minecraft/mc-mods/phosphor?__cf_chl_jschl_tk__=a84121efe39e375da66737c15874c826f859b4e4-1593147165-0-AUd7ZWwlbrE_DxYXzW3iQUGF8jGilgqqtS9PCfhskdGKv76-G7rQTPBsYmp00_OESeW29vIXvMfviRfEwzDmxk13PjTAnEe-H_PP7e65OA9FszNHO_DPUQJ0B0ve4beC5lzS-igaNTPg_qx-vUoCjrollo1iv482jpSXtwO6rbp7C_XuaeaaqH6ZMKU6UGOxWcZ61LOIiIJs1qeZBZeaicuByr13ZFAwscMug_tNq_xeXO9HL7L84VrjyQuubdH1hjWksKMs7RwxdS8DUVCZSf6zRQ9M5cZU7tWJS8Gn-1O5aEaPWk5qft2t4t_LCWTF-L3XHTsA4o_f5XF6FSq2Q6eNwaRJosTXtwu3sOHblztjnYNLxXCFel43fjjnB5SZTQ
And see whether it reduces lag

**Comment by qouteall** [comment]
Did you disable "actively load remote chunks"? I found that disabling it will cause many issues

**Comment by qouteall** [comment]
I seem to be able to reproduce this issue

**Comment by qouteall** [comment]
The chunk loading issue is fixed. I cannot reproduce the nether portal vanish issue.

**Comment by ghost** [comment]
This bug appears to have been fixed in the latest release on Curseforge.

Edit: Thanks for fixing this! :)
