### ISSUE TITLE
[Fabric 1.14.4, IP 0.20 and before] Portals floating

### ISSUE THREAD

**Issue by rapus95** [qouteall/ImmersivePortalsMod#31]
![2019-09-19_15 45 35](https://user-images.githubusercontent.com/5960902/65249721-c1371a00-daf4-11e9-96bf-679f7242ced3.png)
I'm not entirely sure what vanilla would do here, but it's quite unsatisfying.

**Comment by rapus95** [comment]
![2019-09-19_15 54 11](https://user-images.githubusercontent.com/5960902/65250368-c3e63f00-daf5-11e9-8938-851f88349838.png)
This is technically not floating but there is no block in front of the portal which IIRC is prevented by vanilla selection.

**Comment by qouteall** [comment]
The first one is normal, I intentionally made portal sometimes generate above lava lake. But the second one is a bug.

**Comment by qouteall** [comment]
The second one will probably not appear in 0.21

**Comment by qouteall** [comment]
And it's still possible to generate the portal above lava lake
