### ISSUE TITLE
Invisible Armor Stands Show Up In Mirrors

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#310]
Version: immersive-portals-0.13(forMc1.16.1withFabric).jar

2 Minute Video Demonstrating The Issue: https://youtu.be/p7BMzHYsRVg

**Comment by qouteall** [comment]
Because this mod renders portal "in spectator mode" and invisible armor stand is visible in spectator mode. This could be fixed

**Comment by qouteall** [comment]
Fixed. Will be in the next version
