### ISSUE TITLE
Rendering Bug on Global Wrapping (Inward and Outward)

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#311]
Version: immersive-portals-0.13(forMc1.16.1withFabric).jar

3 Minute Video Demonstrating The Issue: https://youtu.be/5jTK7gtfc7Y

Edit: Basically, the sides of blocks don't show up where terrain is covered in blocks on the other side of the portal.

**Comment by qouteall** [comment]
The wiki says:
After setting up the wrapping portals, you may see z-fighting or missing block faces on the edge. Use command /portal global clear_wrapping_border to clear all blocks in the outer border. (NOTE This operation cannot be undone. You should backup the world before trying this.)
