### ISSUE TITLE
When Creating a Vertical Global Portal, The Client Crashes

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#312]
Version: immersive-portals-0.13(forMc1.16.1withFabric).jar

1 Minute Video Demonstrating The Issue: https://youtu.be/8y9LF31Zb-A

Crash Report: https://paste.ee/p/Xis4q

This requires a world backup to be restored in order to access the world again.

**Comment by qouteall** [comment]
fixed in the latest version
