### ISSUE TITLE
Suggestion: Allow Entities to Create and Link Portals

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#313]
I'm trying to add support for Immersive Portals to my Custom Portals datapack. My datapack uses armor stands to dynamically pick the world the player is going to teleport to without making the server owner modify the datapack to mark the destination dimension.

However, I'm having trouble figuring out how to create an immersive portals' portal without explicitly specifying which dimension the portal needs to be created in. In vanilla, I just teleport the players to the armor stands that are setup during datapack install.

For immersive portals, I cannot get an entity other than a player to be able to generate a portal (using commands such as `/execute as @e[type=armor_stand, tag=test, limit=1] run ...command`. That's not even getting to the problem that I cannot set the destination to another entity's location.

My suggestion is to allow entities to be able to create portals and to be able to set the destination at a specified entity (with offsets being an option). This can be used to create a command block command such as `/portal cb_make_portal ...`

I've included the custom portals datapack so you can check what exactly I'm doing and perform tests yourself if you want to.

To setup the custom portals datapack, use `/function portals:marking/mark_main_side` on one world you want the portal to link to and `/function portals:marking/mark_other_side` on the other dimension. You can then create a portal in the same of a standard vanilla portal (the 10 block one as I don't have support for larger sizes yet), but with crying obsidian.

[Custom Portals.zip](https://github.com/qouteall/ImmersivePortalsMod/files/4839655/Custom.Portals.zip)
[Glass Dimension.zip](https://github.com/qouteall/ImmersivePortalsMod/files/4839656/Glass.Dimension.zip)

**Comment by qouteall** [comment]
this is being considered

**Comment by qouteall** [comment]
The command cb_make_portal has been added
