### ISSUE TITLE
Portal scanning linking portals seemingly randomly

### ISSUE THREAD

**Issue by Vortetty** [qouteall/ImmersivePortalsMod#319]
[video](https://streamable.com/ojil5a)
i have noticed chains of portals tend to link weirdly, causing falls longer than they should be. in the video i have a chain of portals and another portal about 100 blocks away, and it causes this fall, not sure why it does it like this but it does. (portal scan range set to 32)

**Comment by qouteall** [comment]
Should have been fixed
