### ISSUE TITLE
[Fabric 1.14.4, IP 0.20 and before] falling out of the portal

### ISSUE THREAD

**Issue by rapus95** [qouteall/ImmersivePortalsMod#32]
When moving through the portal I cannot use shift to stay at the border of the portal. Furthermore I am somewhat like  slipping off the border of the obsidian block where I would still have a solid stand in vanilla portals. In combination with #31 this is very annoying and usually ends in a death.

**Comment by qouteall** [comment]
fixed. you will see it in 0.21 version
