### ISSUE TITLE
portals in series render the nether not the second portal

### ISSUE THREAD

**Issue by Vortetty** [qouteall/ImmersivePortalsMod#320]
[video](https://streamable.com/itrq9w)
when looking through portals that are placed in series, the portal will only render the dimension on the other side, and does not render the second portal.

**Comment by qouteall** [comment]
The nether portal linking seems broken. Could be the same issue as https://github.com/qouteall/ImmersivePortalsMod/issues/319

**Comment by qouteall** [comment]
Did you disable "actively load remote chunks"?

**Comment by qouteall** [comment]
What did you do to trigger this?

**Comment by rullinoiz** [comment]
im also having this issue

**Comment by qouteall** [comment]
@rullinoiz What did you do to trigger this?

**Comment by rullinoiz** [comment]
> @rullinoiz What did you do to trigger this?

i didnt do anything, it just happens

**Comment by qouteall** [comment]
@rullinoiz How did you create and breake the nether portals to make this happen, showing a video would be good

**Comment by rullinoiz** [comment]
> @rullinoiz How did you create and breake the nether portals to make this happen, showing a video would be good

i made them the same way OP did, and im on a mac if that makes any difference. btw that part in my video where the portal disappears has never happened before 

[video](https://streamable.com/25nodo)

here are my mod options (ive tried everything default already)
![image](https://user-images.githubusercontent.com/46585763/88250642-0835f480-cc5d-11ea-8665-b0c69ac89a83.png)
![image](https://user-images.githubusercontent.com/46585763/88250656-1421b680-cc5d-11ea-8c0e-9d088220fa39.png)

it also does the same thing with regular portal frames made with the commands and portal helper blocks, so its not only nether portals having this problem

**Comment by Vortetty** [comment]
sorry for my not replying, hadnt realized this was replied to. @qouteall i just build a 2x2 floor portal. then i built a portal the same way a few blocks under it, and repeated this for a while.

**Comment by Vortetty** [comment]
this happens under all default settings except for i upped the max portal layer

**Comment by Vortetty** [comment]
oh misread what question this was, to do this i just made a portal in the overworld, then traveled through it. and then i made one in the nether, and traveled through it. the portals have no gap between them and that is most likely why the portal appears to just disappear

**Comment by qouteall** [comment]
The wrongly linked portals will automatically break with the latest version
