### ISSUE TITLE
will not link at all

### ISSUE THREAD

**Issue by djnugets** [qouteall/ImmersivePortalsMod#323]
im having issues linking my portals

**Comment by qouteall** [comment]
Did you disable actively load remote chunks option

**Comment by djnugets** [comment]
No but will try
Thank you

**Comment by qouteall** [comment]
oops I didn't mean that disabling can fix the issue. disabling it may cause issues. no need to disable it.

**Comment by qouteall** [comment]
are you using openjdk?

**Comment by djnugets** [comment]
I don’t think so

**Comment by qouteall** [comment]
I can reproduce the bug. It only happens when a nether portal to a newly generated region is being created. It thinks that the region is not generated and skip frame searching

**Comment by djnugets** [comment]
When I did it it said it was searching but just put a new one right above
the one I was trying to link to

**Comment by qouteall** [comment]
should be fixed in the latest version

**Comment by djnugets** [comment]
Ok thanks
