### ISSUE TITLE
Server bug | Chunk not loading.

### ISSUE THREAD

**Issue by timo1050** [qouteall/ImmersivePortalsMod#324]
On server (most frequently) some Chunk not loading. Even after F3 + Q.

**Comment by qouteall** [comment]
1.15 or 1.16? are you using the latest version of this mod?

**Comment by timo1050** [comment]
In 1.16, with the lastest version yes. Download in few hours (It was the same things for the 2 lastest version).
I prefer before to thank you for this mod :).
PS : I'm french. Sorry for my English

**Comment by qouteall** [comment]
I cannot reproduce this bug. Show the log (.minecraft/logs/latest.log). What other mods are you using?

**Comment by timo1050** [comment]
![Annotation 2020-07-04 112848](https://user-images.githubusercontent.com/8901731/86509624-a155b600-bde9-11ea-9929-41a3034c75e5.png)
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/4872382/latest.log)
I also give you an image of the bug. 
With the other mod, I have : fabric api :/ (what a surprise), iimmersive portal, worldedit, lithium fabric.

**Comment by timo1050** [comment]
And modmenu too. (I've forgotten).

**Comment by qouteall** [comment]
The log doesn't show anything useful.
What did you do before triggering the bug? Did you use teleport commands? Did you teleport between dimensions using `execute in run tp` command?

**Comment by qouteall** [comment]
I suspect it may be an incompatibility with lithium

**Comment by timo1050** [comment]
it seem that it work without lithium. Will see for a longest time.
Thank you very much. This mod is really great !

**Comment by qouteall** [comment]
Adding `mixin.world.player_chunk_tick=false` to lithium config can fix this
