### ISSUE TITLE
1.16 IllegalAccessError

### ISSUE THREAD

**Issue by LAROmega** [qouteall/ImmersivePortalsMod#325]
I was testing out mods on 1.16 and Immersive Portals is throwing an IllegalAccessError when I create an active portal. This is a fresh world, created in 1.16.1, in creative mode.

Given the location the exception is being thrown in I tried initializing the Nether first, but the exception was still thrown. Stack trace is attached.

[crash-2020-07-03_22.30.49-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/4872016/crash-2020-07-03_22.30.49-client.txt)

**Comment by LAROmega** [comment]
Just a quick clarification. I entered the nether without the mod installed to initialize the world.

**Comment by qouteall** [comment]
Try to upgrade to the latest fabric loader

**Comment by LAROmega** [comment]
This is a fresh install from tonight through the installer, so it should be latest. 

I was able to figure out the problem though, it's the 1.16 version of optifabric (beta2) that's causing the crash. I think it's their first 1.16 version and it was just released today, so I'm not surprised it's having a problem. Thanks for the quick reply.

**Comment by qouteall** [comment]
the compatibility with optifine should be fixed in the latest version

**Comment by LAROmega** [comment]
Looks like it's working, thanks for the fix!
