### ISSUE TITLE
Crash with bundled ModMenu [Minecraft v1.16.1, Fabric API v0.14.1]

### ISSUE THREAD

**Issue by nycki93** [qouteall/ImmersivePortalsMod#329]
I have a crash when using these mods:
- Borderless Mining v1.0.5+1.16
- Fabric API v0.14.1+build.372-1.16
- Immersive Portals v0.17

But there is no crash with these mods:
- Borderless Mining v1.0.5+1.16
- Fabric API v0.14.1+build.372-1.16
- Immersive Portals v0.17
- **Mod Menu v1.12.1+build.17**

I believe that ImmersivePortals may be shipping with an internal version of ModMenu which is outdated. Is it possible to remove this bundled ModMenu?

[crashlog](https://gist.github.com/nupanick/ff4e08404f3f8e081d128a6ad1e7769d)

**Comment by qouteall** [comment]
I bundle modmenu and cloth config to provide the config gui. I will update it
