### ISSUE TITLE
Sneak bug

### ISSUE THREAD

**Issue by cryum** [qouteall/ImmersivePortalsMod#33]
When traveling between dimensions, some player data is reset, in this case sneaking. But since the portal doesn't unlock sneaking until you're out of the portal itself, a portal that opens up over lava can't be avoided.

You can only do a running jump(and I assume elytra) to get through without falling. No sneak platforms, and it seems to push me a little bit as well so I can't just walk very carefully to place blocks under me.

**Comment by qouteall** [comment]
I tried sneaking both in singleplayer and in multiplayer and cannot reproduce this issue. Are you using 0.21 version? Do you player singleplayer or multiplayer? Is your network delay high? Does this issue happen without other mods?

**Comment by cryum** [comment]
version 0.19, singleplayer

Haven't tested without other mods, but I'll try updating first.

**Comment by cryum** [comment]
Works on 0.21, sorry for the trouble.
