### ISSUE TITLE
Incompatible with ClearSkies

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#332]
https://www.curseforge.com/minecraft/mc-mods/clear-skies

**Comment by Mariocraft95** [comment]
Let me help this issue out a little bit by posting an error log:

https://pastebin.com/9Ktza9bd
This is what I got when I ran Clear Skies, Immersive Portals, and the Fabric API. 

I was going to post about this, but you beat me to it.
