### ISSUE TITLE
Nether ambience sound is missing

### ISSUE THREAD

**Issue by POPTHREE** [qouteall/ImmersivePortalsMod#335]

**Comment by qouteall** [comment]
1.16?

**Comment by POPTHREE** [comment]
> 
> 
> 1.16?

yes

**Comment by qouteall** [comment]
I don't know which sound is ambient sound. As I tested the background music plays normally

**Comment by POPTHREE** [comment]
> I don't know which sound is ambient sound. As I tested the background music plays normally

https://minecraft.gamepedia.com/Ambience

**Comment by qouteall** [comment]
Fixed. will be in the next version
