### ISSUE TITLE
Rendering bug with Randomly Adding Anything

### ISSUE THREAD

**Issue by RViper80** [qouteall/ImmersivePortalsMod#34]
It seems when this mod and Randomly Adding Anything are loaded together, the block breaking overlay of the RAA ores is showing as a scrambled texture.

[Screenshot](https://steamuserimages-a.akamaihd.net/ugc/773981410545679326/4731B24B6A5851B7AE43CF43A03E369B3E3051DC/)

**Comment by qouteall** [comment]
Do you install optifabric?

**Comment by qouteall** [comment]
Randomly Adding Anything seems to be not open-sourced. It's hard to fix it without its source code.

**Comment by qouteall** [comment]
It may be a problem of post processing shaders.

**Comment by qouteall** [comment]
I installed that mod and explored in a new world and can not reproduce the bug

**Comment by qouteall** [comment]
Were you near a portal when triggering this?

**Comment by RViper80** [comment]
Sorry, busy at the moment, but nope, it happens in a new world, no portals built.  You have to look certain specific directions for it to show up.  Hmm...  Not sure if it is always the same direction (Always SE?  Not entirely sure, and unfortunately don't really have the time at the moment to test more)

If you aren't looking in just the right spot, then instead you just see nothing.  No block breaking overlay at all.  And no, I tried to reproduce this with minimal installed as possible, no optifabric or other shaders, just the RAA mod, One Probe, Journeymap, Immersive Portals, and Fabric API.

**Comment by RViper80** [comment]
Got a chance to test this more, Only mods loaded are RAA, One Probe, Journeymap, and Immersive Portals.  The graphical glitch seems to be while looking north or south, and looking upwards above horizontal.  

[2nd SS](https://steamcommunity.com/sharedfiles/filedetails/?id=1889893214)

**Comment by qouteall** [comment]
Raa seems to generate different things in every world. Does this issue happen when only raa and immersive portals are installed?

**Comment by qouteall** [comment]
If so, give me the world file

**Comment by RViper80** [comment]
[WorldTest.zip](https://github.com/qouteall/ImmersivePortalsMod/files/3737040/WorldTest.zip)

Yeah, still there with only Immersive Portals, Fabric API, and Randomly Adding Anything installed.  I have some floating ores at around X: 241, Z: 56.  Standing anywhere on the Diorite platform and trying to mine the ores should show the texture glitch.  Standing on the side without the Diorite shows no breaking texture at all.

**Comment by qouteall** [comment]
Outdated
