### ISSUE TITLE
When attempting to connect to the server I get an io.netty error: "Packet was larger than I expected, found 4 bytes extra whilst reading packet 53"

### ISSUE THREAD

**Issue by progenitor-amborella** [qouteall/ImmersivePortalsMod#343]
`internal exception: io.netty.handler.codec.DecoderEnxemption: java.ioException: Packet 0/53 (class_2708) was larger than I expected, found 4 bytes whilst reading packet 53`

The only other mods are 
`fabric-api-0.14.1`
`fabric-carpet-1.16`
`lithium-fabric-mc.1.16.1` (I did include the `mixin.world.player_chunk_tick=false` argument in `lithium.properties`)
`phosphor-fabric-mc-1.16.1`

I can provide more data if you need, but I'm genuinely not sure what other variables would be causing this as it's a fresh world, with no completed portals even.

**Comment by qouteall** [comment]
The server and client should both install this mod
