### ISSUE TITLE
The End spawn platform doesn't spawn

### ISSUE THREAD

**Issue by THEN00P** [qouteall/ImmersivePortalsMod#345]
This shouldn't be a problem but far out portals in the end cities teleport you to that location which can send you straight to the void.

**Comment by qouteall** [comment]
I remember that I fixed it before. It broke again?

**Comment by THEN00P** [comment]
Yup

**Comment by qouteall** [comment]
1.16 seems hardcoded the end platform coordinate. This should be fixed in the next version
