### ISSUE TITLE
Crash from skeleton arrow firing through portal?

### ISSUE THREAD

**Issue by CammiePone** [qouteall/ImmersivePortalsMod#346]
I wasn't able to reproduce it with just Immersive Portals in singleplayer, but a friend of mine was being chased by a skeleton on his server (dedicated) and he ran away through the portal, and was met with this crash shortly after.

Crash report:
https://pastebin.com/pe5wRyxZ

**Comment by qouteall** [comment]
I added the check. It probably won't crash in the next version
