### ISSUE TITLE
Ender pearls do not work if thrown into another dimension through a portal

### ISSUE THREAD

**Issue by muzikbike** [qouteall/ImmersivePortalsMod#348]
For example, ender pearls go through fine visually, but do nothing when colliding with blocks other than disappear - teleportation would be expected.

![2020-07-23_17 02 00](https://user-images.githubusercontent.com/52297970/88309885-e2fdc080-cd06-11ea-9889-d042f8ae030a.png)
![2020-07-23_17 04 41](https://user-images.githubusercontent.com/52297970/88309889-e4c78400-cd06-11ea-8607-19c5e7f1bf12.png)

**Comment by muzikbike** [comment]
from further testing it seems like they actually, do, it's just that the particles and sounds aren't displayed.

Ender pearls are still bugged in this regard though, since they should teleport the player anyway.

**Comment by scytail** [comment]
When running a server with this mod, throwing an ender pearl through a portal from the nether to the overworld causes the server to freeze completely before crashing.

**Comment by qouteall** [comment]
@scytail 1.16 or 1.17?

**Comment by scytail** [comment]
Sorry, Minecraft 1.16. I think 1.16.5? I haven't checked what exact version of the mod I'm using at this point. The pack I'm using is a create+ pack which features this mod alongside the create mod and the rats mod (running on forge), along with a few others. I can get you a full rundown of all the mods and datapacks I'm using later if you need them.

**Comment by qouteall** [comment]
Fixed in the latest version
