### ISSUE TITLE
Underwater Mirror Rendering Issue

### ISSUE THREAD

**Issue by ChloeDawn** [qouteall/ImmersivePortalsMod#35]
Mirrors do not render correctly underwater.

**Mod version:** [0.22](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod/files/2806496)
**Fabric API version:** [0.4.0 build 240](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/2798477)

![recording](https://giant.gfycat.com/ColdPepperyIsabellinewheatear.gif)

**Comment by qouteall** [comment]
It seems that the position of the mirror is changed. Maybe water flushed it?

**Comment by qouteall** [comment]
The third-person view mirror rendering issue fixed

**Comment by qouteall** [comment]
I can't reproduce the issue you showed
