### ISSUE TITLE
[Suggestion] Invert- versions of dimensions

### ISSUE THREAD

**Issue by muzikbike** [qouteall/ImmersivePortalsMod#350]
The mineup mod for 1.2.5 includes upside-down versions of the usual aboveground dimensions it adds:

![2020-07-23_16 21 51](https://user-images.githubusercontent.com/52297970/88305173-19384180-cd01-11ea-8e34-e0ce5a82e823.png)

In these upside-down dimensions, everything is vertically flipped (block models, fluid physics, entity physics, basically everything but the player) and the day-night cycle is also inverted.
![2020-07-23_16 28 13](https://user-images.githubusercontent.com/52297970/88305637-a380a580-cd01-11ea-8c3b-326b30845372.png)

Having these be added as potential immersive portals dimensions (as well as the three being there by default) would be fun since there's currently nothing but void below the nether.

![2020-07-23_16 31 34](https://user-images.githubusercontent.com/52297970/88305967-0d00b400-cd02-11ea-8056-a5ba6c030b0e.png)

**Comment by qouteall** [comment]
This mod does not have inverse gravity feature. However the portals can have rotating transformation.

**Comment by muzikbike** [comment]
Could be done if this is: https://github.com/Virtuoel/Pehkui/issues/20

**Comment by muzikbike** [comment]
...apparently that won't happen then

**Comment by muzikbike** [comment]
...apparently that won't happen then

**Comment by muzikbike** [comment]
Might be a possibility with Gravity Changer, now that it exists.

**Comment by qouteall** [comment]
It's already a thing. You can make a dimension flipped in dimension stack and enable gravity change. https://qouteall.fun/immptl/wiki/Dimension-Stack

**Comment by muzikbike** [comment]
How can I have something like an inverted nether alongside a normal nether?

**Comment by qouteall** [comment]
No, because dimension stack cannot clone a dimension. However you can use datapacks to add another nether dimension
