### ISSUE TITLE
Cannot create portals on the roof of Nether

### ISSUE THREAD

**Issue by kanzaki1201** [qouteall/ImmersivePortalsMod#359]
Portals cannot be created on the roof of Nether (above bedrock).
![2020-07-27_18 59 57](https://user-images.githubusercontent.com/6962263/88610499-5e000780-d076-11ea-9092-133bec2d2a15.png)

After trying to do so, the game freezes when you try to save.

Loader: Fabric 0.9.0 build 204
Fabric API version: 0.15.1 build 380
Immersive Portal Version: 0.20
Minecraft version: 1.6.1

**Comment by qouteall** [comment]
This has been fixed. Will be in the next version.

**Comment by qouteall** [comment]
fixed in 0.22
