### ISSUE TITLE
game crashes while loading world

### ISSUE THREAD

**Issue by som3rando** [qouteall/ImmersivePortalsMod#361]
game crashes when i try to load a world.
mod version:immersive-portals-0.23-mc1.16.1-fabric
crash report:The game crashed whilst exception in server tick loop
Error: java.lang.IllegalAccessError: tried to access field net.minecraft.class_3898.field_18242 from class com.qouteall.immersive_portals.chunk_loading.EntitySync
[crash-2020-07-28_18.09.07-server.txt](https://github.com/qouteall/ImmersivePortalsMod/files/4989645/crash-2020-07-28_18.09.07-server.txt)
fabric api:fabric-api-0.16.0+build.384-1.16.1
other mods:just optifine and optifabric

**Comment by qouteall** [comment]
Seems that optifine breaks with access widener again

**Comment by qouteall** [comment]
fixed in 0.24
