### ISSUE TITLE
Client crash in version 0.24

### ISSUE THREAD

**Issue by Tomas1506** [qouteall/ImmersivePortalsMod#363]
[crash-2020-07-30_10.30.31-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/5000389/crash-2020-07-30_10.30.31-client.txt)
I have everything installed from fabric, when i tried to install this mod it simply crashes on trying to start the game.
I will play without it until i find a way to make it work, and i tried with previous versions but it doesn't seem to work aswell

**Comment by qouteall** [comment]
Use the sodium version that's compatible with this mod. https://github.com/qouteall/sodium-fabric/releases/tag/ipc0.1.0.6
