### ISSUE TITLE
Suggestion: Allow custom block tags to be used in custom portals

### ISSUE THREAD

**Issue by Lionmeow** [qouteall/ImmersivePortalsMod#368]

**Comment by qouteall** [comment]
You can add "/portal cb_set_portal_nbt ..." in postInvokeCommands

**Comment by qouteall** [comment]
Wait do you mean block tag?

**Comment by Lionmeow** [comment]
Yeah, block tags. Sorry for the confusion!

**Comment by qouteall** [comment]
Vanilla has a weird way of resource loading. After debugging a while, I found that it supports datapack-provided tags, but in a strange way. For example you have `data/minecraft/tags/blocks/namespace/mytag.json` then the tag is `minecraft:namespace/mytag`
