### ISSUE TITLE
Crash when loading into a world with Optifine 1.16.1 G2

### ISSUE THREAD

**Issue by jhammerberg** [qouteall/ImmersivePortalsMod#369]
On Forge 32.0.98 with Optifine G2 and Immersive Portals 0.24 I crash when trying to load into a world.
[Forge Crash.txt](https://github.com/qouteall/ImmersivePortalsMod/files/5014307/Forge.Crash.txt)
I get roughly the same crash with Fabric 0.8.9, Immersive Portals 0.24, Optifabric 1.1.0  and Optifine G2
[crash-2020-08-03_14.16.05-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/5017602/crash-2020-08-03_14.16.05-client.txt) (New)

**Comment by Leo40Git** [comment]
OptiFine is incompatible with Immersive Portals.
The Fabric crash seems to be... completely unrelated to OptiFine, though?

**Comment by qouteall** [comment]
About the fabric version crash, try to upgrade the fabric loader to the latest version

**Comment by qouteall** [comment]
@Leo40Git As I tested Optifine g2 is compatible with this mod 0.24 fabric

**Comment by jhammerberg** [comment]
Sorry, I think I attached the wrong crash for Fabric. I've edited it and re uploaded the correct one.

**Comment by qouteall** [comment]
The solution is to turn off render regions
