### ISSUE TITLE
Cant login with the mod

### ISSUE THREAD

**Issue by Caantie8** [qouteall/ImmersivePortalsMod#372]
When i have the mod enabled, I cant login to any multiplayer servers, When i start a fabric modded server with the same mod on the server [ImmersivePortalsMod] I still cant login.. How do i fix this???????

**Comment by JoelOsler** [comment]
They might not have the newest version, maybe?

**Comment by JoelOsler** [comment]
I added a new feature to the mod recently, and you might have that new version, and they don't yet.

**Comment by qouteall** [comment]
If you want to login tge server, the server should also have this mod. But fixing this is being planned

**Comment by qouteall** [comment]
Show the log
