### ISSUE TITLE
Unable to load into new or old worlds after removing immersive portals mod

### ISSUE THREAD

**Issue by MrKashew** [qouteall/ImmersivePortalsMod#373]
After removing immersive-portals-0.24-mc1.16.1-fabric
Works fine when I add the mod back into the mods folder
When removing the mod I am able to start minecraft and create a world but hang on post a 100% blank background screen
No crash and nothing weird on [the log](https://gist.github.com/MrKashew/de54db2fbb025d303342ccd801b5977c)

**Comment by qouteall** [comment]
Try to uninstall optifine and try again?

**Comment by MrKashew** [comment]
will try sec

**Comment by MrKashew** [comment]
Wait Im an idiot I tried it wrong ignore if you read this before the edit

**Comment by MrKashew** [comment]
Seems to work as long as I have shaders off after removing Immersive Portals strangely. I tried a clean install with fabric and the mods minus IP but it still stops on loading a world. Weird. I guess it can be chalked up to optifine and shaders somehow though. Thanks for the help, I'm just going to keep Immersive Portals in the pack for the time being haha - I love the mod but am a bit worried about distributing the pack to people with lower end specs

**Comment by MrKashew** [comment]
I've figured out what the issue was:

Crimson moon strangely enough has [an issue](https://github.com/Draylar/crimson-moon/issues/6) loading worlds with shaders, but this problem is no longer present when Immersive Portals is installed for some reason.

I don't know how it's possible but perhaps your mod somehow patches this issue for this other mod?
Is there a way I can config lower spec clients that have Immersive Portals installed to not render them (this would be a counter-intuitive config option to have obviously so probably not).
Otherwise just going to remove Crimson Moon or keep Immersive Portals

**Comment by qouteall** [comment]
Immersive Portals has a lot of mixins to OptiFine. But none of them aim in the compatibility between other mods and OptiFine. It could be some weird interactions.
