### ISSUE TITLE
[Enhancement] Keep nether portal texture option

### ISSUE THREAD

**Issue by MrKashew** [qouteall/ImmersivePortalsMod#375]
Not sure how it'd look but could be an interesting look with the other dimension one side of the pane blocks and your world on the other. This could also provide the option of lower spec pcs to use portal rendering 0 with this option to get seemless teleportation still, lmk ur thoughts!

**Comment by qouteall** [comment]
Implemented https://qouteall.fun/immptl/wiki/Config-Options#enable-nether-portal-overlay
