### ISSUE TITLE
Compatibility issue with BSL shaders.

### ISSUE THREAD

**Issue by SnazzyJovialWyrm** [qouteall/ImmersivePortalsMod#378]
There seems to be a compatibility issue with in regards to rendering the world with BSL shaders activated.
![2020-08-07_12 44 34](https://user-images.githubusercontent.com/36800919/89670120-a6a59500-d8ae-11ea-8fe4-ceead2f9af31.png)

**Comment by qouteall** [comment]
Fixed. Will be in the next version
