### ISSUE TITLE
Sometimes the player is unable to get through the portal in survival mode

### ISSUE THREAD

**Issue by ImSpaceLover** [qouteall/ImmersivePortalsMod#380]
https://www.youtube.com/watch?v=bth2S42gws8

**Comment by Ornamus** [comment]
I've experienced this too. Portals work smoothly in creative (regardless of flying, running, or walking), but in survival, most portals either don't teleport me, or kill me from fall damage.

From what I can gather, more "complicated" portals tend to do this more often - i.e., portals that are rotated 90 degrees, or portals with dramatically different y-levels. I've still experienced this on a couple straightforward "shift x" portals though.

**Comment by qouteall** [comment]
Fixed in 0.27
