### ISSUE TITLE
Black entities in nether with sildurs shaders

### ISSUE THREAD

**Issue by LoftyGrove** [qouteall/ImmersivePortalsMod#39]
When using sildurs vibrant shaders, all entities (Mobs, dropped items and xp) are completely black, including the arm/item I am holding.

Tested with multiple different versions of sildurs shaders. High and medium, older and newer versions.

Gonna test older versions of immersive portals.

**Comment by qouteall** [comment]
Restart the game and try again and see whether entities are black. The shader compatibility is very hacky and sometimes problems get fixed by restarting the game.

**Comment by qouteall** [comment]
Ok I can reproduce this issue now. You can use sildurs shader 1.22 which does not have this problem.

**Comment by xamareik** [comment]
I'm using 1.22, and restarted. Still black

**Comment by LoftyGrove** [comment]
Already tried using sildurs 1.22 (medium), and restarting.
Nothing works.

**Comment by qouteall** [comment]
what's your optifine version? And show the log

**Comment by qouteall** [comment]
Possibly fixed.

**Comment by qouteall** [comment]
Fixing this also leads to the fix of chocapic shader compatibility and beyond belief shader compatibility

**Comment by qouteall** [comment]
I will release the new version possibly tomorrow

**Comment by qouteall** [comment]
fixed in 0.26
