### ISSUE TITLE
Incompatibility with Sodium (Fabric)

### ISSUE THREAD

**Issue by ZaneDragonBorn** [qouteall/ImmersivePortalsMod#391]
**The Mod will crash with this error:**

[PasteBin](https://pastebin.com/3Rf56WzL)

**Comment by SnaveSutit** [comment]
https://hasteb.in/akucezah.yaml

Another crash report for the same conflict, In case you need it.

I would assume this won't get fixed because sodium completely replaces the vanilla rendering engine

**Comment by qouteall** [comment]
@SnaveSutit you can use the sodium fork for now, see the mod page.
