### ISSUE TITLE
(Low Importance) Longer Hand Reach Potion Effect

### ISSUE THREAD

**Issue by VexianEmpire** [qouteall/ImmersivePortalsMod#398]
![image](https://user-images.githubusercontent.com/64798986/91224692-1b1e6780-e6e8-11ea-9185-38c4ecf43f68.png)
![image](https://user-images.githubusercontent.com/64798986/91224941-718ba600-e6e8-11ea-84b3-daed0bfd1da7.png)
![image](https://user-images.githubusercontent.com/64798986/91225192-cd562f00-e6e8-11ea-9d64-4fbb202e7824.png)
![image](https://user-images.githubusercontent.com/64798986/91225257-f2e33880-e6e8-11ea-9bb5-fdfa01774ad6.png)
item.minecraft.tipped_arrow.effect.longer_reach_potion
imm_ptl.hand_reach_multiplier

**Comment by qouteall** [comment]
I am going to remove that potion

**Comment by VexianEmpire** [comment]
The potion itself is not the problem

**Comment by VexianEmpire** [comment]
Also, I thought it was part of the loot in alternate4 so why remove it?

**Comment by qouteall** [comment]
Because that potion does not fit the topic of this mod

**Comment by qouteall** [comment]
Maybe I won't remove the potion. I am going to split the core into a separate mod and the potion is in the peripheral mod

**Comment by qouteall** [comment]
Can be done by pehkui
