### ISSUE TITLE
Longer Hand Reach Incompatible With Other Mods (Pehkui,Campanion)

### ISSUE THREAD

**Issue by VexianEmpire** [qouteall/ImmersivePortalsMod#399]
I think Pehkui or Campanion is causing this issue. Pehkui changes your hand reach when you change size, and Campanion increases your hand reach with spears.
[https://www.curseforge.com/minecraft/mc-mods/pehkui](url)
[https://www.curseforge.com/minecraft/mc-mods/campanion](url)

**Comment by VexianEmpire** [comment]
The spear works even when the player is scaled, although it seems that the extended spear reach does not grow with the player size.

**Comment by VexianEmpire** [comment]
Campanion also has longer hand reach for entities, so you can borrow the code from there if needed.

**Comment by qouteall** [comment]
The reach code has been removed
