### ISSUE TITLE
Going through portals with scale transformation changes your current speed

### ISSUE THREAD

**Issue by VexianEmpire** [qouteall/ImmersivePortalsMod#400]
When going through portals that make you smaller, you get slowed down.
When going through portals that make you bigger, you get sped up.

NOTE: Speed does NOT refer to the value that determines how fast you walk. It refers to the value that determines how fast you are going at a particular instance in time. Similar to how drinking a speed potion only changes how fast you can run away from a creeper, not how fast you get flung when a creeper murders you.

**Comment by VexianEmpire** [comment]
"changes your current speed" refers to relative speed. Your actual speed is changed more than the size you are changed by

**Comment by qouteall** [comment]
Probably fixed
