### ISSUE TITLE
(Feature) Shorter Hand Reach

### ISSUE THREAD

**Issue by VexianEmpire** [qouteall/ImmersivePortalsMod#403]
> Maybe I won't remove the potion. I am going to split the core into a separate mod and the potion is in the peripheral mod

-qouteall #398

I just thought it would be a cool idea ¯\\\_(ツ)\_/¯

Useful for:
- Realistic Hand Reach
- Maybe used in PvP

**Comment by VexianEmpire** [comment]
Also could be used for when you are huge but don't want to be able to reach long distances

**Comment by qouteall** [comment]
Can be done by pehkui
