### ISSUE TITLE
Portals are not rendering the other side

### ISSUE THREAD

**Issue by rullinoiz** [qouteall/ImmersivePortalsMod#404]
I have the latest version of fabric and the fabric api, and i have the latest version of your mod. I go into one of my worlds and make a portal, and this is what I see:

![image](https://user-images.githubusercontent.com/46585763/91497227-72504380-e872-11ea-8372-71e7cff3b161.png)

here are my settings:
![image](https://user-images.githubusercontent.com/46585763/91497280-96ac2000-e872-11ea-8240-7ec3f4accd27.png)
![image](https://user-images.githubusercontent.com/46585763/91497308-a461a580-e872-11ea-869f-0c459caf5385.png)

**Comment by rullinoiz** [comment]
i found the problem, compatibility render mode breaks it. if you toggle it on you don't get the portals rendered

**Comment by qouteall** [comment]
The issue of compatibility renderer fixed in the next version
