### ISSUE TITLE
Missing end portal spawn point causes a drop into the void when returning from a gateway

### ISSUE THREAD

**Issue by andwn** [qouteall/ImmersivePortalsMod#41]
Setup:
1.14.4 with Fabric Loader, Immersive Portals v0.27 as the only mod

To reproduce:
1. Create a new world with seed "angus" (all lowercase) and enable cheats
2. Spawn the needed items, and set the difficulty to peaceful to get rid of silverfish and endermen
`/difficulty peaceful`
`/give @a ender_eye 12`
`/give @a ender_pearl 12`
3. Warp to the end portal 
`/teleport @a -993 37 -1205`
4. Light the end portal, take a note that underneath the end portal is the exit portal at the dead center of the boss arena
5. Enter it and quickly warp to a gateway, one is located here
`/teleport @a 949 62 -1878`
6. Throw an ender pearl in
![2019-12-01_16 33 09](https://user-images.githubusercontent.com/8164394/69920658-7c1a5700-1458-11ea-8791-74c71eb2db10.png)
![2019-12-01_16 33 17](https://user-images.githubusercontent.com/8164394/69920659-7d4b8400-1458-11ea-8014-7f8d3a047dc9.png)

Why does this happen?
Because during step 4, the spawn point in the end was supposed to be over the void (100, 49, 0), and the gateway warps you back to where that was. Had Immersive Portals not been installed a platform of obsidian would have generated underneath this spot.

You can verify this by attempting to reproduce the issue a second time without the mod installed.
![2019-12-01_15 54 35](https://user-images.githubusercontent.com/8164394/69920249-7a01c980-1453-11ea-9b79-1192310ed36b.png)
![2019-12-01_15 57 45](https://user-images.githubusercontent.com/8164394/69920240-5e96be80-1453-11ea-8aa7-6695e4e43b73.png)

**Comment by qouteall** [comment]
Do you mean that the obsidian platform in end spawnpoint is not generated? It seems that this issue is not correlated with a special seed or position.

**Comment by qouteall** [comment]
The vanilla end gateway portal destination selection is not simple.

**Comment by qouteall** [comment]
I added the obsidian platform generation and it works fine in your seed. The platform will be generated every time a player enters the end portal.

**Comment by qouteall** [comment]
Please check 0.28 version.

**Comment by andwn** [comment]
Yeah it was the platform, just a bit hard to explain. I'll check it out later tonight, thanks!
