### ISSUE TITLE
After updating to 1.16.2 - all portals unlinked

### ISSUE THREAD

**Issue by GiggySmalls** [qouteall/ImmersivePortalsMod#410]
We have just updated to 1.16.2 on our server and all portals appear unlinked now. We have quite a few portals so restoring them all is a massive undertaking.

Is this normal and is there anything we can do?

**Comment by qouteall** [comment]
Type command /execute in  Do you see the nether and the end? If the nether and the end is missing, then the issue is probably caused by other dimension mods

**Comment by GiggySmalls** [comment]
I think it happened because the mods were not loaded correctly upon first launch (all mods). I have restored the old server save and all portals have returned to normal! :D

Sorry to waste your time :)
