### ISSUE TITLE
Incompatibility with Towelette when on a server.

### ISSUE THREAD

**Issue by BNTFryingPan** [qouteall/ImmersivePortalsMod#413]
On a test server and client instance with the following mods, and no other mods on both the client and server, waterlogged blocks show up as the wrong block and sometimes the wrong liquid

mods:
Fabric API [fabric-api-0.19.0+build.398-1.16]
Immersive Portals [immersive-portals-0.30-mc1.16.2-fabric]
Lithium [lithium-fabric-mc1.16.2-0.5.4]
Towelette [Towelette-4.1.6+1.16.2]

image:
un-waterlogged
![image](https://user-images.githubusercontent.com/7706960/92146086-2d368f00-ede7-11ea-92b3-ad7f296bc879.png)
waterlogged
![image](https://user-images.githubusercontent.com/7706960/92146121-3fb0c880-ede7-11ea-97e8-aa6a12bb96c7.png)

un-waterlogged
![image](https://user-images.githubusercontent.com/7706960/92146261-72f35780-ede7-11ea-930d-ff837ec23bce.png)
waterlogged
![image](https://user-images.githubusercontent.com/7706960/92146293-80a8dd00-ede7-11ea-971b-6fb9db7f660b.png)

This issue does not occur in Singleplayer, only Multiplayer.

I'm not sure if this is something that needs to be fixed in Towelette or in Immersive Portals.

**Comment by qouteall** [comment]
This could be a registry id sync issue. Is other mod blocks abnormal?

**Comment by BNTFryingPan** [comment]
When using other mods, modded blocks that are not waterlogged are perfectly fine, I haven't tested waterlogging them, but this issue still occurs with just Towelette and Immersive Portals installed, although (assuming I understand what you mean by registry sync) when I have certain other mods (probably ones that add blocks) the "randomness" of what block/liquid is shown to the client is different, so that is probably the issue, however, considering that the issue occurs while have no other mods besides Towelette and Immersive portals installed, it has to be an issue either on your end with Immersive Portals, or on Towelettes end. With my (admittedly minimal) testing and knowledge of how fabric works, its probably an issue with Immersive Portals on the client side, as just having it installed on the client and joining a server with only Towelette will cause this issue to occur (although yes there is a warning saying issues may occur because the server doesn't also have Immersive Portals, putting Immersive Portals on the server does not fix the issue).

**Comment by qouteall** [comment]
Create a new fresh world on server and make sure that the client mod list is consistent to the servers, does the issue still occur?

**Comment by BNTFryingPan** [comment]
On a client with only Immersive Portals, Towelette, and Fabric API, and having only Immersive Portals, Towelette, and Fabric API on the server, after deleting the .fabric, .mixin.out, logs, and world folders, the issue still occurs. When the server loaded however, I noticed a bunch of errors that appear to just be fabric creating a mapped jar or something, but ill leave it here just in case it is useful to fixing this iissue https://gist.github.com/LeotomasMC/496d6e6b1dcfdc210a9d9fff5685a87a (note that it wasnt logged using the logger, it was directly printed to the console, and not in logs/latest.txt)

**Comment by qouteall** [comment]
Close because outdated.
