### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by Repties** [qouteall/ImmersivePortalsMod#42]
I am a newbie with fabric and not sure why it isnt working. Here is the crash report:
Could not find required mod: immersive_portals requires {fabric @ [*]}
  Creatitng Empty clause ?

**Comment by qouteall** [comment]
did you install https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by Repties** [comment]
Oop- I installed just Fabric, thinking it was the same. Thank you! Case closed.
