### ISSUE TITLE
[SUGGESTION] New Nether portal mode : `semi_normal`

### ISSUE THREAD

**Issue by zowepsilon** [qouteall/ImmersivePortalsMod#426]
This new portal mode would be like in `normal` mode, but there is a semi-transparent portal texture like a light filter. It would define limits of the portal without completly removing the seamless transition (+it would be beautiful !)

**Comment by ghost** [comment]
Yeah this is something I thought of as well. Have the default nether portal "portal animation" (the particle effects as well) be there but also render the world behind it. This could also go well with the end portal. The end portal would have to be made to be transparent tho, as it isn't in vanilla like the nether portal is.

**Comment by qouteall** [comment]
Implemented https://qouteall.fun/immptl/wiki/Config-Options#enable-nether-portal-overlay

**Comment by zowepsilon** [comment]
Wow thanks 🙏
