### ISSUE TITLE
Immursive Portals Mod crashes upon start of game

### ISSUE THREAD

**Issue by tytder** [qouteall/ImmersivePortalsMod#43]
Hi 

When I have the ImmersivePotralsMod in my mods folder and I start up my game it crashes 
I have the latest download and i have the Optifine U F3, not the F4 which I had before.

Crashlog is attached and I hope you can help.

[crash-2019-12-09_13.40.47-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/3939673/crash-2019-12-09_13.40.47-client.txt)

**Comment by tytder** [comment]
don't know what I changed but it started :P

**Comment by qouteall** [comment]
Did you install optifine and optifabric correctly
