### ISSUE TITLE
Crash when used in conjunction with optifine.

### ISSUE THREAD

**Issue by catweaselirl** [qouteall/ImmersivePortalsMod#433]
I am using **immersive-portals-0.36-mc1.16.3-fabric** and **preview_OptiFine_1.16.3_HD_U_G4_pre1** (using optifabric-1.6.4 to run optifine with fabric (the stable build of optifine has the same issue)) and the game crashes upon loading a world. World loads just fine with either on their own. It may also be important to note that the same issue occurs when using the forge version of the mod.

Log: https://pastebin.com/fWmzMivt

**Comment by qouteall** [comment]
Try to turn off render regions

**Comment by catweaselirl** [comment]
You know, I actually feared that might be the issue, because it just so happens that my game lags if I turn quickly without that setting so I need it to play. I will try it out and get back to you. Thanks for the quick response.

**Comment by catweaselirl** [comment]
Disabling render regions does fix it, however like i said, i need this setting to play. Is there any fix you plan on implementing?

**Comment by qouteall** [comment]
I tested using optifine g3 and worked fine. Try to use g3. If it doesn't work then try to reset optifine settings

**Comment by catweaselirl** [comment]
I said before that G3 doesn't work either, but I tried it again with the settings reset like you said. Doesn't crash until I turn on render regions, at which point the world unloads and the game crashes.

**Comment by tony1boss16** [comment]
i've had the same issue with the forge version, however turning off render regions didn't fix it. is there something else i'm missing?

**Comment by qouteall** [comment]
The latest version works
