### ISSUE TITLE
Portals in the nether get created floating in weird spots.

### ISSUE THREAD

**Issue by meza** [qouteall/ImmersivePortalsMod#436]
At first I thought I was just unlucky but 4/5 portals I've created have put me either in the air or right above lava lakes with no supporting structures generating.

Is that normal or am I doing something wrong?

This is my average experience 
![image](https://user-images.githubusercontent.com/211977/94403414-4d970680-0165-11eb-99d6-1951b6aefe51.png)

**Comment by qouteall** [comment]
If the corresponding nether position is close to a lava lake then it has a high probability to generate above the lava lake. It's normal.

**Comment by meza** [comment]
I'm going to do some comparisions from the same block on vanilla and modded and test what happens. I can't recall ever landing in such a situation in vanilla

**Comment by meza** [comment]
So I'm using `-857414580999580583` as the seed for the tests with 
This modded setup:
Minecraft 1.16.3
Fabric Loader: 0.10.0+build.208
Phosphor: 0.6.0+build.7
Immersive Portals 0.36

And pure vanilla 1.16.3.

All portals are full portals with corners, 4 obsidian on the bottom, 5 on the sides, making a 2x3 portal.
All coordinates correspond to the bottom right corner while facing south, and entering the portal facing south.

### Here are my results:

#### Test1:
Overworld coords:
222, 97, 1164

Modded nether exit coords: 37, 32, 140
![](https://cdn.discordapp.com/attachments/387985347235282944/760156736820215849/unknown.png)

Vanilla nether exit coords: 15, 73, 140
![](https://cdn.discordapp.com/attachments/387985347235282944/760157623499882496/unknown.png)

#### Test 2

Overworld coords: 313, 113, 1790

Modded nether exit: 34, 58, 218
![](https://cdn.discordapp.com/attachments/387985347235282944/760157384458371132/unknown.png)

Vanilla nether exit: 40, 99, 215
![](https://cdn.discordapp.com/attachments/387985347235282944/760157940799504404/unknown.png)


I could keep on going but this is the majority of the cases. In conclusion, I don't think the valid portal location detection works the way it does with vanilla.

**Comment by PoolloverNathan** [comment]
Maybe it could run the vanilla check then use that as the portal location?

**Comment by meza** [comment]
That would be awesome. Right now I have to decide whether to include it in a server and see this as a hard challenge or jus go with vanilla. :/

**Comment by qouteall** [comment]
The vanilla algorithm only generated 2x3 simple nether portal so that cannot be used. I changed the portal generation to decrease the possibility of generating portal above lava lake. Will be in the next version

**Comment by meza** [comment]
Sounds good! I don't mind a challenge once every so often but lava lake/mid air generation should definitely be the minority of cases.
