### ISSUE TITLE
crash au démarrage 

### ISSUE THREAD

**Issue by taureau29** [qouteall/ImmersivePortalsMod#44]
quand je démarre mon jeux ca ma fiche failed to launch 
log minecraft MultiMC version: 0.6.7-1375

Minecraft folder is:
C:/Users/Utilisateur/Desktop/les truc/MultiMC/instances/1.14.4 cool/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_221, using 64-bit architecture.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/instances/1.14.4 cool/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/net/fabricmc/intermediary/1.14.4/intermediary-1.14.4.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.0.11/tiny-mappings-parser-0.2.0.11.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.16/sponge-mixin-0.8+build.16.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/net/fabricmc/tiny-remapper/0.2.0.52/tiny-remapper-0.2.0.52.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/ow2/asm/asm/7.2/asm-7.2.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/ow2/asm/asm-analysis/7.2/asm-analysis-7.2.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/ow2/asm/asm-commons/7.2/asm-commons-7.2.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/ow2/asm/asm-tree/7.2/asm-tree-7.2.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/ow2/asm/asm-util/7.2/asm-util-7.2.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/net/fabricmc/fabric-loader/0.7.2+build.174/fabric-loader-0.7.2+build.174.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/com/mojang/minecraft/1.14.4/minecraft-1.14.4-client.jar

Native libraries:
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/Utilisateur/Desktop/les truc/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [❌] immersive-portals-0.10.jar (disabled)
  [✔️] immersive-portals-0.28 (2)
  [❌] immersive-portals-0.28.jar (disabled)

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Utilisateur/Desktop/les truc/MultiMC/instances/1.14.4 cool/.minecraft --assetsDir C:/Users/Utilisateur/Desktop/les truc/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 8092

Using onesix launcher.

[19:22:20] [main/INFO]: Loading for game Minecraft 1.14.4
net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Mod immersive_portals depends on mod {fabric @ [*]}, which is missing!
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:309)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:603)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:176)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:166)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Process exited with code 1.

**Comment by qouteall** [comment]
install this https://www.curseforge.com/minecraft/mc-mods/fabric-api
And there should not be multiple files of this mod in "mods" folder
