### ISSUE TITLE
Alternative dimension 5 isn't a void but a flat world instead.

### ISSUE THREAD

**Issue by noap123** [qouteall/ImmersivePortalsMod#442]
In the newest version of immersive portals 1.16.3 on both fabric and forge the alternative dimension 5 doesnt create a void.
![2020-10-05_20 17 03](https://user-images.githubusercontent.com/72410346/95117691-482f5280-0749-11eb-8bd7-c814fdd6d825.png)
Above is a picture with the 5 dimension above the overworld

**Comment by qouteall** [comment]
Fixed. Will be in the next version

**Comment by noap123** [comment]
Thank you very much!
