### ISSUE TITLE
Particles from other dimensions appear in overworld

### ISSUE THREAD

**Issue by VexianEmpire** [qouteall/ImmersivePortalsMod#443]
In this example, torch particles from alternate5 appear in the overworld
![image](https://user-images.githubusercontent.com/64798986/95504141-f7e70900-0971-11eb-9543-bb039ee3d2fc.png)
(taken in the immersive portals server)

**Comment by eesanta** [comment]
The same happens for me but the Nether Biome particles

**Comment by qouteall** [comment]
Fixed in the next version
