### ISSUE TITLE
Crashes using custom sodium build from FlashyReese

### ISSUE THREAD

**Issue by Jarfeh** [qouteall/ImmersivePortalsMod#444]
Fabric API: 0.23.0+build.410-1.16
Fabric: 0.10.1+build.209
FlashyReese Sodium Build: 0.1.0
ImmersivePortals: 0.36

MC crashes before the window can appear.
[crash-2020-10-09_20.49.07-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/5358416/crash-2020-10-09_20.49.07-client.txt)

**Comment by qouteall** [comment]
Use this https://github.com/qouteall/sodium-fabric/releases/tag/ipc1161_1

**Comment by Jarfeh** [comment]
The reason I used FlashyReese's version was because the build you linked says "(Merged with FlashyReese's 1.16.2 sodium fork)"
