### ISSUE TITLE
How could I remove an end portal completely in creative please.. 

### ISSUE THREAD

**Issue by KrLite** [qouteall/ImmersivePortalsMod#445]
![image](https://user-images.githubusercontent.com/68179735/95678791-7a392c80-0c01-11eb-9dd6-796a4d2c0f29.png)
**_Seems the portal always exists. I can't break it even with command_**

**Comment by qouteall** [comment]
What do you mean "can't break it even with command"? https://github.com/qouteall/ImmersivePortalsMod/wiki/Portal-Customization

**Comment by qouteall** [comment]
use `/portal delete_portal`
