### ISSUE TITLE
[1.16.3] Weather does not properly sync with overworld

### ISSUE THREAD

**Issue by Jarfeh** [qouteall/ImmersivePortalsMod#446]
When using the /weather clear command, or waiting until the weather clears up in the overworld, does nothing in the 'alternate2' sky dimension. 
![2020-10-10_21 10 18](https://user-images.githubusercontent.com/58902941/95696448-fa569680-0bef-11eb-93a9-7690c988e4f7.png)
![2020-10-10_21 10 21](https://user-images.githubusercontent.com/58902941/95696452-fc205a00-0bef-11eb-8943-8b67548c00f4.png)
![2020-10-11_18 30 33](https://user-images.githubusercontent.com/58902941/95696454-fdea1d80-0bef-11eb-8c3b-4bb51f1cd2ba.png)

I had commented about this on an issue about this, but it was closed, so I decided to create a new one.

**Comment by qouteall** [comment]
Probably fixed in the latest version
