### ISSUE TITLE
[1.15.2]connect world on server

### ISSUE THREAD

**Issue by twjk83** [qouteall/ImmersivePortalsMod#447]
Sorry for my poor English first
I try to connect the three worlds on the server,and it works
But there is a problem
The connection between the two worlds is still bedrock
Is there a way to connect the two worlds before generating the map
Or replace the bedrock by setting?

**Comment by qouteall** [comment]
You need to firstly create a dimension stack world on client and then copy the world to the server

https://github.com/qouteall/ImmersivePortalsMod/wiki/Dimension-Stack

(Note that the ipDimensionStack gamerule only exists in 1.16)

**Comment by Jarfeh** [comment]
Bedrock will still generate, even after loading the world locally then moving to the server.
