### ISSUE TITLE
Issue where Age of Exile projectiles from wands are not visible

### ISSUE THREAD

**Issue by duncy** [qouteall/ImmersivePortalsMod#449]
I'm not really sure if this is the place for it, but the entities that spawn from the wand as projectiles can't be seen when used with this mod. 

There are no errors in the console.

Has anyone else encountered this?
Let me know if you want me to share anything else.

**Comment by qouteall** [comment]
This issue happens without any portal nearby right?

**Comment by duncy** [comment]
With the starting wand on a new world, any world, any wand, with any spell I have tried so far.
Without any portal being built or nearby.

**Comment by qouteall** [comment]
What does the projectile look like normally?

**Comment by duncy** [comment]
It depends on the projectile, but depending on the spell, it could look like a slime ball, ender pearl, fire charge etc. The AoE spells have a non-interactable block that spawns in the center. They're a mix of particles from vanilla with sprites from items and occasionally blocks. 

It's kinda hard to explain. :/

**Comment by ProsperCraft** [comment]
We are having this same issue on my The Adventures of Halk pack on a dedicated server.

You can't see the projectiles from the wands 95% of the time.

**Comment by kissedbytherains** [comment]
Experiencing this as well. The only wand projectile spell I've seen work from Age of Exile in combination with Immersive Portals so far is the lightning trident projectile. Area of effect spells are also invisible of the ones I've tested.

I have had a similar issue with the throwable torches from this mod of the same name not rendering properly alongside Immersive Portals: https://www.curseforge.com/minecraft/mc-mods/throwabletorch-fabric. The thrown torches don't show up or have a weird falling animation until the torches appear on the wall. Sometimes throwing them very far, the projectile might eventually render at a certain distance.

**Comment by qouteall** [comment]
Age of exile 's code is large and I cannot search where does the projectile gets rendered or spawned

**Comment by qouteall** [comment]
@mheps throwable torch is not open source so I cannot check

**Comment by kissedbytherains** [comment]
@qouteall Hi, I'm sorry that I missed this, I think thankfully the [throwable torch repository](https://github.com/DanikingMC/ThrowableTorch)  has been created in the meantime since then. As for Age of Exile I'm sorry, I don't know - https://github.com/RobertSkalko would be the person to ask I think

**Comment by kissedbytherains** [comment]
Testing this with the latest Age of Exile and Immersive Portals I didn't have any problems with the two spells I was able to try - the fireball and poison ball spells rendered properly where I'm pretty sure they didn't before. I don't wanna say it's definitively fixed but it seems like it might be.

Modlist:
![image](https://user-images.githubusercontent.com/29741016/115627613-53a13000-a2cd-11eb-8701-97b589df2926.png)
tested with Optifine after as well and still worked the same
