### ISSUE TITLE
Lighting/Torches

### ISSUE THREAD

**Issue by BLysholm** [qouteall/ImmersivePortalsMod#45]
Upon journeying through the nether a bit, upon return torches are not dispersing light. Attached screenshots of the problem
![2019-12-15_19 57 05](https://user-images.githubusercontent.com/58924574/70876015-4192dd00-1f75-11ea-824e-a5c970a7a2f7.png)
![2019-12-15_19 57 16](https://user-images.githubusercontent.com/58924574/70876018-42c40a00-1f75-11ea-9c1f-9794a7aebfd5.png)

**Comment by qouteall** [comment]
in 1.14 or 1.15? is the environment completely dark or the light does not update? does lava flow at that area? do pigmen move on their own? does relogging fix this issue? does this issue always happen or randomly happen?

**Comment by BLysholm** [comment]
1.15. Nether seems to be completely fine with lava flowing and pigmen behaving normally, just overworld. It seems to be consistently happening everytime I move a decent area away from portal. Going to main menu and then reloading solves the bug

**Comment by qouteall** [comment]
I haven't tested 1.15 throughly. I will check it later today.

**Comment by qouteall** [comment]
I can reproduce this issue now.

**Comment by BLysholm** [comment]
Yeah, with 1.15 being a new release I was under the assumption that it was a new bug that hasn't been discovered yet

**Comment by qouteall** [comment]
I probably fixed this issue. (I'm not sure because it's quite random)
And I reduced some lag spikes caused by client light info update.

**Comment by qouteall** [comment]
And I found more rendering bugs.

**Comment by qouteall** [comment]
And 1.15 changed chunk rebuild schedule policy, It builds more chunk on render thread and results in more lag spikes when the player crosses a lot of portals quickly. I am going to change it a little bit.

**Comment by qouteall** [comment]
This lighting issue is more complex than I thought. I didn't fix it from the root cause. So I update it every 5 seconds. You may still see this issue in the new version but it will be fine after 5 seconds.

**Comment by BLysholm** [comment]
Ok, sounds great. I was going to say waiting 5 seconds gets me to a playable stage, but I am currently unable to recreate that bug. Thank you, it is a great mod
