### ISSUE TITLE
Issues with the collision for rotated portals

### ISSUE THREAD

**Issue by ImSpaceLover** [qouteall/ImmersivePortalsMod#451]
I made a [video](https://www.youtube.com/watch?v=HO4Vbkpcicw) about them. And here's an explanation of what happened in it: I made two examples of the rotated portals. A - a portal rotated along the Z axis by 90 degrees. B - a portal rotated along the Z axis by 180 degrees. (Note: It doesn't matter if the portal rotated along the Z or X  axis. The result are the same.) As you can see at the example A, the player almost instantly falling through the portal after starting walking. The example B is a bit better. The player can walk in the portal for about a second but then he teleports.
Also the players can't crouch in the portals that has non upside-down rotation. (<180 degrees)

**Comment by qouteall** [comment]
Probably fixed in 0.39
