### ISSUE TITLE
Weird bug with scaled portals

### ISSUE THREAD

**Issue by ImSpaceLover** [qouteall/ImmersivePortalsMod#453]
https://youtu.be/PgC43bvovOg

**Comment by qouteall** [comment]
try to turn off `adjustPositionAfterTeleport`

**Comment by qouteall** [comment]
The adjust position thing needs to be changed

**Comment by ImSpaceLover** [comment]
It was off
![image](https://user-images.githubusercontent.com/64267797/96338941-02a04d00-109a-11eb-9db1-5a45504b1a0f.png)

**Comment by qouteall** [comment]
Close because outdated.
