### ISSUE TITLE
[1.16.3] Portals not rendering blocks on linux when using sodium fork

### ISSUE THREAD

**Issue by Mattery** [qouteall/ImmersivePortalsMod#454]
OS: Arch Linux x86_64 on kernel 5.8.14-zen1-1-zen
Java: OpenJDK 1.8.0_265
Fabric: 0.10.1+build.209
ImmersivePortals: 0.39
Sodium: 0.1.0 (qouteall)

Portals link as intended and are traversable, blocks aren't getting rendered even though entities and particles are.

![image](https://user-images.githubusercontent.com/8432976/96349602-341c1700-10a0-11eb-96a0-8bb004b19413.png)
![image](https://user-images.githubusercontent.com/8432976/96349612-3ed6ac00-10a0-11eb-8b3e-842ec2d037ce.png)
![image](https://user-images.githubusercontent.com/8432976/96349621-48601400-10a0-11eb-8457-3e680a7da877.png)

**Comment by qouteall** [comment]
It's related to my sodium fork's shader clipping. Try to use  command`/immersive_portals_debug front_culling_disable`

**Comment by Mattery** [comment]
> It's related to my sodium fork's shader clipping. Try to use command`/immersive_portals_debug front_culling_disable`

That did the trick, thanks!
