### ISSUE TITLE
Fall through floor after teleportation

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#457]
https://www.youtube.com/watch?v=qZzCEQrb1Kc&feature=youtu.be

**Comment by Dual-Iron** [comment]
Can confirm, this happens all the time for me. It's awful.

https://user-images.githubusercontent.com/31146412/118417949-6e748380-b684-11eb-9c77-20b601fda537.mp4

**Comment by Dual-Iron** [comment]
Seems to be that you simply lose collision entirely after intersecting with the portal.

https://user-images.githubusercontent.com/31146412/118418090-fd819b80-b684-11eb-9575-0905081fd465.mp4

**Comment by qouteall** [comment]
Should be fixed.
