### ISSUE TITLE
Infitine world loading screen 1.16.2 (Bug)

### ISSUE THREAD

**Issue by Gomez96** [qouteall/ImmersivePortalsMod#459]
When I'm creating a new world in singleplayer, go to **Dimension Stack** enable everything, then add The End dimension and then I'm trying to load a new world, then it happens this: https://i.imgur.com/oy4skLv.jpg

Not sure, if this has been fixed in 1.16.3 version before, but I'm using 1.16.2 minecraft version and the version of this mod is immersive-portals-0.32-mc1.16.2-fabric

If this was already fixed, then could you please make a backport for 1.16.2? Because some of other mods I use don't work for 1.16.3

**Comment by qouteall** [comment]
Close because outdated.
