### ISSUE TITLE
Fabric, Minecraft Version 1.16.3 

### ISSUE THREAD

**Issue by Emptypng** [qouteall/ImmersivePortalsMod#468]
When I go through the portal I seem to phase through the floor see [here](https://gyazo.com/46f421cb4b9f5f41e6da741cd2949aec)

**Comment by qouteall** [comment]
I cannot reproduce. Uploading the world would help.

**Comment by qouteall** [comment]
Are you using Forge? If so try the latest Fabric version

**Comment by qouteall** [comment]
Close because outdated.
