### ISSUE TITLE
Crash after updating to 0.49

### ISSUE THREAD

**Issue by vico93** [qouteall/ImmersivePortalsMod#476]
[Crash log](https://gist.github.com/vico93/9dba92d98ac1cd068707a38c8d502dd3)

Crash happened right after updating the mod from 0.43 to 0.49.

* Immersive Portals version - `immersive-portals-0.49-mc1.16.4-fabric`
* Minecraft version - `1.16.4`
* Loader - `Fabric (Loader v0.10.8-1.16.4 / API v0.26.1+1.16)`

**Comment by qouteall** [comment]
You need to use my fork of sodium https://github.com/qouteall/sodium-fabric/releases

**Comment by vico93** [comment]
Thanks for the info!
