### ISSUE TITLE
java.lang.IllegalArgumentException: bound must be positive server crash

### ISSUE THREAD

**Issue by tacogerbil** [qouteall/ImmersivePortalsMod#481]
MC 1.16.4
Fabric 0.10.6B.214
Fabric API 0.26.1+1.16
Just playing.. Running around.  Nothing special.  Only when this new version replaces the older version 0.43

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2020-11-23 16:27:37 PST
Description: Exception generating new chunk

java.lang.IllegalArgumentException: bound must be positive
    at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.47)
    at java.util.Random.nextInt(Random.java:388)
    at net.minecraft.world.gen.feature.StructureFeature.getStartChunk(StructureFeature:234)
    at net.minecraft.world.gen.feature.StructureFeature.tryPlaceStart(StructureFeature:256)
    at net.minecraft.world.gen.feature.ConfiguredStructureFeature.tryPlaceStart(ConfiguredStructureFeature:35)
    at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStart(ChunkGenerator:278)
    at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStarts(ChunkGenerator:267)
    at net.minecraft.world.chunk.ChunkStatus.method_16556(ChunkStatus:51)
    at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:219)
    at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:568)
    at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
    at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:562)
    at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
    at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
    at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
    at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58)
    at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:94)
    at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:137)
    at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Chunk to be generated --
  Location: -24,-36
  Position hash: -150323855384
  Generator: net.minecraft.class_3754@756c512b

-- Affected level --
  All players: 2 total; [class_3222['TacoGerbil'/179, l='ServerWorld minecraft:overworld HammyVille', x=-78.16, y=95.86, z=-286.69], class_3222['Can_Ye_help_me'/1017, l='ServerWorld minecraft:overworld HammyVille', x=156.10, y=79.00, z=-91.50]]
  Chunk stats: ServerChunkCache: 3148
  Level dimension: minecraft:overworld
  Level spawn location: World: (219,77,-55), Chunk: (at 11,4,9 in 13,-4; contains blocks 208,0,-64 to 223,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Level time: 3827537 game time, 1346654 day time
  Level name: HammyVille
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Level weather: Rain time: 48340 (now: false), thunder time: 77108 (now: false)
  Known server brands: fabric
  Level was modded: true
  Level storage version: 0x04ABD - Anvil

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Linux (amd64) version 5.4.0-53-generic
  Java Version: 1.8.0_131, Oracle Corporation
  Java VM Version: Java HotSpot™ 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 6408725704 bytes (6111 MB) / 8087142400 bytes (7712 MB) up to 11453595648 bytes (10923 MB)
  CPUs: 4
  JVM Flags: 2 total; -Xms2G -Xmx12G
  Suspected Mods: Unknown
  Fabric Mods: achaybales: Achaybales 1.3-1.16.4
               adorn: Adorn 1.12.1+1.16.4
               adventurez: AdventureZ 1.1.4
               amecs: Amecs 1.3.2+mc.1.16.3
               amecsapi: Amecs API 1.1.1+mc1.16-rc1
               angerable-patch: Angerable Patch 1.0.0-1.16.1
               appleskin: AppleSkin 1.0.11
               appliedenergistics2: Applied Energistics 2 8.1.0-alpha.13
               artifice: Artifice 0.13.2+1.16.3
               autoconfig1u: Auto Config v1 Updated 3.3.1
               backslot: BackSlot 1.1.7
               backslotaddon: BackSlot Addon 1.0.2
               balance_of_exile: Balance of Exile 1.0.3
               battletowers: Battle Towers 3.2.0-beta-1.16.4
               bedspreads: Bedspreads 1.3.1-1.16.4
               beenfo: Beenfo 1.16.4-fabric0.25.1-1.3
               better_wandering_trader: Better Wandering Trader 1.6.1
               bettercaves: YUNG's Better Caves 1.16.2-1.0.3
               betterend: Better End 0.6.2-beta
               betternether: Better Nether 5.0.3
               blackstonetools: Blackstone Tools 1.2.0+1.16.1
               blue_endless_jankson: jankson 1.2.0
               bowinfinityfix: Bow Infinity Fix rv9
               buildersblocks: Builders' Blocks 1.16.3-beta.8
               byg: BYG 1.1.3
               caelus: Caelus API 0.0.12-1.16.4
               camp_fires_cook_mobs: Camp Fires Cook Mobs 1.1.4+MC1.16.2-1.16.4
               cardinal-components-base: Cardinal Components API (base) 2.7.2
               cardinal-components-chunk: Cardinal Components API (chunks) 2.6.0
               cardinal-components-entity: Cardinal Components API (entities) 2.7.2
               cardinal-components-item: Cardinal Components API (items) 2.7.2
               cardinal-components-world: Cardinal Components API (worlds) 2.6.0
               carrier: Carrier 1.4.0
               carvepump: Carve My Pumpkin 1.0.3
               cavebiomes: Cave Biomes 0.5.1
               ce_foodstuffs: Common Expansion: Foodstuffs 1.1.1
               chainmail: Chainmail 0.5.0
               chains: Chains-Link 1.16.2-2.0.1
               chunkpregen: Fabric Chunk Pregenerator 0.3.3
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.5
               cloth-config2: Cloth Config v4 4.8.3
               cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.2.1
               cloth-utils-v1: Cloth Utils v1 1.4.5
               colytra: Colytra 1.3.0-1.16.4
               com_electronwill_night-config_core: core 3.6.0
               com_electronwill_night-config_toml: toml 3.6.0
               com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.1
               com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.1
               com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.1
               com_github_shevek_parallelgzip: parallelgzip master-SNAPSHOT
               com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
               com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
               com_google_code_findbugs_jsr305: jsr305 3.0.2
               com_mashape_unirest_unirest-java: unirest-java 1.4.9
               com_neovisionaries_nv-websocket-client: nv-websocket-client 2.10
               com_squareup_okhttp3_okhttp: okhttp 3.13.0
               com_squareup_okio_okio: okio 1.17.2
               commons-codec_commons-codec: commons-codec 1.9
               commons-logging_commons-logging: commons-logging 1.2
               computercraft: CC:T for Fabric 1.91.2
               cotton-config: Cotton Config 1.0.0-rc.7
               cotton-logging: Cotton Logging 1.0.0-rc.4
               couplings: Couplings 1.3.3
               crawl: Crawl 0.8.0
               crowdin-translate: CrowdinTranslate 1.2
               crumbs: Crumbs 1.0.2+1.16.4-fabric
               curioofundying: Curio of Undying 1.1.0-1.16.3
               curios: Curios API 0.0.10-1.16.3
               curiouselytra: Curious Elytra 1.1.0-1.16.3
               cursed_enchanting: Cursed Enchanting 0.1.3+1.16.1
               curses: Curses 1.5.0
               dankstorage: Dank Storage 1.9-1.16.3
               darkpaintings: Dark Paintings 1.0.0
               dawn: Dawn API 1.5.4
               decorative: Decorative 3.0.0
               disfabric: DisFabric 1.2.0
               dungeons_of_exile: Dungeons of Exile 1.1.1
               earthtojavamobs: Earth2Java 1.2.2+1.16.4
               economical_villager_trading: Economical Villager Trading 1.0.2+MC1.16.4
               edit_sign: Edit Sign 2.1.3
               eer: Erroring Entity Remover 1.0.0
               eldritch_mobs: Eldritch Mobs 1.5.1
               emotecraft: Emotecraft 1.2.2
               expandedstorage: ExpandedStorage 5.6.31
               extraorigins: Extra Origins 1.16.4-3
               ezpas: Ezpas 1.2.3-1.16.2
               fabric: Fabric API 0.26.1+1.16
               fabric-api-base: Fabric API Base 0.2.0+9f0fb4b83a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+6a2618f53a
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+6a2618f53a
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5ba7
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
               fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
               fabric-language-scala: Fabric Language Scala 0.3.2.12
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+6a2618f53a
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b3a
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5fa7
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
               fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.0+6d328b5e3a
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db23a
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+6a2618f53a
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
               fabricloader: Fabric Loader 0.10.6+build.214
               fabrictailor: Fabric Tailor 1.3.2-1.16.4
               fallflyinglib: FallFlyingLib 1.1.0
               falling_tree: FallingTree 2.7.0
               fastfurnace: FastFurnace 2.3
               fiber: fiber 0.23.0-1
               fluidtank: Fluid Tank 16.0.7-fabric
               fullbellysheep: Full Belly Sheep 1.1.0
               gamblers_curse: Curse of The Gambler 0.1.1+1.16.1
               glassdoor: Glass Doors 1.5.0-1.16
               glowcase: Glowcase 0.0.10
               golemsgalore: Golems Galore 0.2.0+mc.1.16.2
               harmfulstonecutters: Harmful Stonecutters 1.0.1
               hellish-materials: Hellish Materials 0.12.2
               hookshot: Hookshot 10.0
               hotfurnace: Hot Furnace 1.1.1
               hypnos: Hypnos 0.1.1
               images: Images 0.4.0+1.16.4
               imm_ptl_core: Immersive Portals Core 0.49
               immersive_portals: Immersive Portals 0.49
               improved-stations: Improved Stations 2.0.3
               indrev: Industrial Revolution 1.7.12-BETA
               inmis: Inmis 1.3.1-1.16.2
               invtrashslot: InvTrashSlot 1.0.2
               itemflexer: ItemFlexer 1.0.1
               jankson: Jankson 3.0.1+j1.2.0
               javax_vecmath_vecmath: vecmath 1.5.2
               kibe: Kibe 1.5.2-BETA
               kirin: Kirin UI 1.7-1.16.2
               kubejs: KubeJS 1.6.0
               lapisreserve: Lapis Reserve 1.0.6
               libblockattributes: LibBlockAttributes 0.8.4
               libblockattributes_core: LibBlockAttributes (Core) 0.8.4
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.4
               libblockattributes_items: LibBlockAttributes (Items) 0.8.4
               libcd: LibCapableData 3.0.3+1.16.3
               libgui: LibGui 3.2.0+1.16.3
               library_of_exile: Library of Exile 1.0.6
               libstructure: LibStructure 1.5
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               llamasteeds: Llama Steeds 2020.2.8
               magna: Magna 1.4.3-1.16.2
               mcdw: MC Dungeons Weapons 1.1.8
               medievalweapons: Medieval Weapons 1.0.2
               megane: megane 3.0.5+1.16.4
               megane-api: megane-api 3.0.5+1.16.4
               megane-impl: megane-impl 3.0.5+1.16.4
               megane-runtime: megane-runtime 3.0.5+1.16.4
               minecraft: Minecraft 1.16.4
               minecraftcapes: MinecraftCapes Mod 10
               mm: Manningham Mills 2.1
               mmorpg: Age of Exile 1.7.6
               mo_glass: Mo Glass 1.5-MC1.16.4
               modify-drops-api: Modify Drops API 0.3.1
               mooblooms: Mooblooms 1.3.2
               morebookshelves: Bookshelving 0.0.1
               morecraftingtables: Oh, How the Crafting Has Tabled! 0.1.3-1.16.3
               moretotems: More Totems 2.7.0
               mostructures: Mo' Structures 1.0.0-pre3+mc.1.16.2
               mousewheelie: Mouse Wheelie 1.5.10+mc1.16.4
               mubble: Mubble 4.0-pre6
               nbtcrafting: NBT Crafting 2.0.0-rc.7+mc1.16.2-pre1
               net_dv8tion_jda: JDA 4.2.0_182
               net_sf_trove4j_trove4j: trove4j 3.0.3
               nicetohave: Nice to Have 1.3.5
               no_sneaking_over_magma: No Sneaking Over Magma! 1.0.5+MC1.16.2-1.16.4
               notenoughbreeding: Not Enough Breeding 1.16.4-1.0.0-fabric
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.4
               oaktree: Oak Tree 0.4.2-beta
               obsidiplates: Obsidiplates 0.1.1
               olifantenpad: Olifantenpad 1.0.0
               org_apache_commons_commons-collections4: commons-collections4 4.1
               org_apache_commons_commons-compress: commons-compress 1.19
               org_apache_httpcomponents_httpasyncclient: httpasyncclient 4.1.1
               org_apache_httpcomponents_httpclient: httpclient 4.5.10
               org_apache_httpcomponents_httpcore: httpcore 4.4.12
               org_apache_httpcomponents_httpcore-nio: httpcore-nio 4.4.4
               org_apache_httpcomponents_httpmime: httpmime 4.5.10
               org_apache_logging_log4j_log4j-slf4j-impl: log4j-slf4j-impl 2.8.1
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
               org_json_json: json 20160212
               org_slf4j_slf4j-api: slf4j-api 1.7.25
               org_tukaani_xz: xz 1.8
               origins: Origins 0.4.5
               origins-classes: Origins: Classes 1.1.0
               paintingcycle: Painting Cycle 1.0.0
               parakeetmod: The Parakeet Mod 1.16.3-1.0.6
               parchment: Parchment 1.0.2+1.15.2
               passable-leaves: Passable Leaves 1.2.3
               patchouli: Patchouli 1.16.2-44-FABRIC
               pconfig: Paradox Config 0.3.6-alpha
               pehkui: Pehkui 1.6.2+1.16.3
               phonos: Phonos 0.1.0-beta
               phosphor: Phosphor 0.6.0+build.7
               pigpoop: Pig Poop 1.1.3
               pinesbarrels: Better Barrels 1.0.1
               plantable_pots: Plantable Flower Pots 0.0.2-SNAPSHOT
               playerabilitylib: Pal 1.2.1
               polymorph: Polymorph 0.0.5-1.16.3
               randompatches: RandomPatches 1.16.1-0.0.0.5-fabric
               rare-ice: Rare Ice 0.2.2
               reach-entity-attributes: Reach Entity Attribute 1.0.1
               reborncore: Reborn Core 4.6.1+build.97
               repurposed_structures: Repurposed Structures 1.16.4-1.7.0
               respawnablepets: Respawnable Pets 1.16.4-1
               rhino: Rhino 1.7.13
               rotten: FleshZ 1.2.2
               roughlyenoughitems: Roughly Enough Items 5.8.7
               roughlyenoughitems-api: REI (API) 5.8.7
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.7
               roughlyenoughitems-runtime: REI (Runtime) 5.8.7
               sandwichable: Sandwichable 1.1.2
               seasons: Fabric Seasons 1.0.3-BETA
               skinswapper: Minecraft Skin Change Mod 2.0.1
               spongesplus: Sponges Plus 1.0.1
               static-content: Static Content 1.0.1-1.16.2
               staticdata: Static Data 1.1.2
               structure-helpers: Structure Helpers 3.0.0
               structurized: Structurized 1.1.0
               suitablystackablestew: Suitably Stackable Stew 1.1.1
               tacobell: Taco Bell 1.1.1
               team_reborn_energy: Energy 0.1.1
               techreborn: Tech Reborn 3.7.1+build.162
               terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.3
               terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.3
               textile_backup: Textile Backup 2.0.1-1.16.3
               the_loved_ones: The Loved Ones 1.0.0+1.16.1
               tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
               trade: Trade 1.1.1
               trinkets: Trinkets 2.6.7
               tweed: Tweed API 3.0.0-beta.20
               universalcomponents: Universal Components 0.7.3+1.16.2
               vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
               varied-mobs: Varied Mobs 1.0.0
               villagerhats: Villager Hats fabric-1.16.4-1.0.1
               villagernames: Villager Names 1.2.5
               voyager: Voyager 1.0.0
               waila: Hwyla 1.9.22
               wands: Wands Mod 1.3.1
               whereisit: Where Is It 1.9.1
               winged: Winged Mod 1.16.2-1.4.1
               wither_cage_fix: Mod Name 1.0.3+MC1.16.1-1.16.4
               wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
               worldedit: WorldEdit 7.2.0+a51fa43
               xaerominimapfair: Xaero's Minimap Fair-Play 20.27.3
  Player Count: 2 / 20; [class_3222['TacoGerbil'/179, l='ServerWorld minecraft:overworld HammyVille', x=-78.16, y=95.86, z=-286.69], class_3222['Can_Ye_help_me'/1017, l='ServerWorld minecraft:overworld HammyVille', x=156.10, y=79.00, z=-91.50]]
  Data Packs: vanilla (incompatible), fabric/achaybales, fabric/adorn, fabric/adventurez, fabric/appliedenergistics2, fabric/balance_of_exile (incompatible), fabric/battletowers, fabric/bedspreads, fabric/betterend, fabric/betternether, fabric/blackstonetools, fabric/buildersblocks, fabric/byg, fabric/carvepump, fabric/cavebiomes, fabric/ce_foodstuffs, fabric/colytra, fabric/computercraft (incompatible), fabric/crumbs, fabric/curioofundying, fabric/curios, fabric/curiouselytra, fabric/cursed_enchanting, fabric/dankstorage, fabric/decorative, fabric/dungeons_of_exile (incompatible), fabric/eldritch_mobs, fabric/expandedstorage, fabric/extraorigins, fabric/ezpas, fabric/fabric-tool-attribute-api-v1, fabric/fluidtank, fabric/glassdoor, fabric/golemsgalore, fabric/hellish-materials (incompatible), fabric/hookshot, fabric/improved-stations, fabric/indrev, fabric/inmis, fabric/kibe, fabric/kubejs (incompatible), fabric/libcd, fabric/mcdw, fabric/medievalweapons, fabric/mmorpg, fabric/mo_glass, fabric/mooblooms, fabric/morebookshelves, fabric/morecraftingtables, fabric/moretotems, fabric/mostructures, fabric/mubble, fabric/nicetohave, fabric/obsidiplates, fabric/origins, fabric/origins-classes, fabric/parakeetmod, fabric/pconfig, fabric/pinesbarrels, fabric/plantable_pots, fabric/rare-ice (incompatible), fabric/repurposed_structures, fabric/respawnablepets, fabric/rotten, fabric/sandwichable, fabric/seasons, fabric/spongesplus, fabric/structure-helpers, fabric/tacobell, fabric/techreborn, fabric/villagerhats, fabric/winged, fabric/wolveswitharmor, fabric/earthtojavamobs, fabric/wands, fabric/phonos, phonos:data_pack, fabric/images
  Is Modded: Definitely; Server brand changed to 'fabric'
  Type: Dedicated Server (map_server.txt)

**Comment by qouteall** [comment]
It may be an incompatibility with byg mod. Test whether it crashes without byg mod

**Comment by qouteall** [comment]
Fixed
