### ISSUE TITLE
Intense lagg when looking at the portal or entities in 1.16.4

### ISSUE THREAD

**Issue by MultiChipModule** [qouteall/ImmersivePortalsMod#482]
After some amounr of time random players will get gamebreaming lagg when looking at dropped items, entities and portals. When you break the portal and re-light it it's fixed for the player who lit the portal.

**Comment by qouteall** [comment]
When it's lagging press F3 and take a screenshot. And post the log. Do you have optifine or sodium installed?

**Comment by MultiChipModule** [comment]
I'll have to try and recreate it, which could take some time as it seems to happen randomly, do you want the client log or the server log?

edit:

I don't have sodium or optifine installed, I do have phosphor and lithium, to try and cancel out the lag which didn't work.

**Comment by qouteall** [comment]
Client log.
And try to remove phosphor because it may be an incompatibility

**Comment by froyo4u** [comment]
> Client log.
> And try to remove phosphor because it may be an incompatibility

This is off topic for this issue but I usually use phosphor and I'm fine so I don't think it's an incompatibility.

**Comment by qouteall** [comment]
Close due to not having complete information to diagnose the issue.
