### ISSUE TITLE
[1.17 - 20w48a] Snapshot release

### ISSUE THREAD

**Issue by AuracleTech** [qouteall/ImmersivePortalsMod#483]
Is there a way to get the snapshot release somewhere?
This mod is incredible we really want it on the server!

**Comment by MCSuperplayer** [comment]
The Snapshot Version is in the Minecraft Launcher
I dont believe there are mod version for Snapshots (could be though)

**Comment by AuracleTech** [comment]
There's a lot I mostly make servers up to date, lots of mods are up to latest snapshot, not all tho
