### ISSUE TITLE
Broken Achievement "We Need to Go Deeper"

### ISSUE THREAD

**Issue by AuracleTech** [qouteall/ImmersivePortalsMod#484]
Hardcore in 1.16.4
Tried to make a portal and enter multiple times
Used "/advancement grant _Auracle_ only minecraft:story/enter_the_nether" in waiting
![image](https://user-images.githubusercontent.com/40531871/100533035-d5cd7280-31cd-11eb-87c2-0db23dd9128c.png)

**Comment by qouteall** [comment]
What do you mean by "in waiting"? Going through a nether portal doesn't trigger the advancement?

**Comment by AuracleTech** [comment]
> What do you mean by "in waiting"? Going through a nether portal doesn't trigger the advancement?

Yeah no the advancement doesn't work, so I used a command until it's fixed.
We were in multiplayer with my friend, I tried breaking his nether portal and make my own, but that doesn't change anything, we just can't get the achievement by any way shape or form.

**Comment by qouteall** [comment]
Fixed in the next version
