### ISSUE TITLE
Crashing with immersive portals version (immersive-portals-0.41-mc1.16.3-fabric)

### ISSUE THREAD

**Issue by SamKotBrown** [qouteall/ImmersivePortalsMod#489]
The game crashes. There must be some incompatibility with my other mods.
[crash-2020-12-07_10.35.39-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/5651800/crash-2020-12-07_10.35.39-client.txt)

**Comment by qouteall** [comment]
https://github.com/qouteall/sodium-fabric/releases
