### ISSUE TITLE
just an idea for this mod.

### ISSUE THREAD

**Issue by maketor** [qouteall/ImmersivePortalsMod#49]
![2019-12-24_02 20 09](https://user-images.githubusercontent.com/13091317/71389844-c49edd80-25dc-11ea-84a1-a4106f44820b.png)

**Comment by qouteall** [comment]
You mean put redstone or rails through portal? It's hard to implement. It required deeply hack into redstone system which I am not familar with. I won't implement this in the near future. To send redstone signal through portal you can use slimeblock to push an entity through portal

**Comment by MolikoDeveloper** [comment]
🤔  uhh, i dont think that, entity. nice idea... i have to learn the fabric api to create mods...
