### ISSUE TITLE
any sort of scaled box portal crashes

### ISSUE THREAD

**Issue by Phantom912** [qouteall/ImmersivePortalsMod#491]
The title really covers it. any sort of scaled portal crashes the game immediately. this includes the scaled portal option for the end portal.
[crash-2020-12-07_17.21.31-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/5656248/crash-2020-12-07_17.21.31-client.txt)

I'm always told every time I post a crash report that I needed to include a full crash report. not entirely sure what this means but I think I did it with the link above if not sorry for the inconvenience normally I would just copy and paste the crash report

**Comment by qouteall** [comment]
You need to disable "Merge portal rendering" option. This option is experimental and mostly does not have optimization effect now.

**Comment by Phantom912** [comment]
oh, thank you I completely forgot and I turn that on. I literally turned it on to see what it did. forgot I did it. sorry for wasting your time
