### ISSUE TITLE
suggestion sky can act like a green screen

### ISSUE THREAD

**Issue by Phantom912** [qouteall/ImmersivePortalsMod#492]
I feel like it would be pretty cool if we had an option in the config to make the sky rendered through a portal not actually render and the sky instead just showing what's ever behind the portal. it would not affect the nether, but like when you have scaled portal View for the End Portal instead of showing the black sky it would just show whatever is below the portal so if it was in the stronghold it would look like the end Island was just floating above lava instead of it looking like a weird box of black sky

**Comment by qouteall** [comment]
When you use command to create the scale box there is a parameter <isBiWay>, make it to true then the box will be "transparent".

It's not really transparent it just places the portals from inner box to outer world.

The scale box rendering can be optimized by introducing the "no sky rendering" feature as you said and the merge portal rendering feature

**Comment by qouteall** [comment]
Implemented https://qouteall.fun/immptl/wiki/Portal-Attributes#fuse-view
