### ISSUE TITLE
1.16.4 CTD, single player, no other mods

### ISSUE THREAD

**Issue by CHollman822** [qouteall/ImmersivePortalsMod#495]
Crash report attached. Crash to desktop in single player with brand new world (creative). No mods other than Fabric and Fabric API. Game works correctly with many other mods installed, just not this one.

[crash-2020-12-10_15.27.17-server.txt](https://github.com/qouteall/ImmersivePortalsMod/files/5675477/crash-2020-12-10_15.27.17-server.txt)

**Comment by qouteall** [comment]
It has issue with the newest fabric api. I am trying to fix it. You can use fabric API 0.25 for now
