### ISSUE TITLE
1.16.4 End Portal on a bedrock roof

### ISSUE THREAD

**Issue by Archesr** [qouteall/ImmersivePortalsMod#497]
Using the normal end portal type on the mod, the portal works you can teleport into the end, however the end dragon structure also generated on 0,134,0 on a bedrock roof for some reason, could this be part of the end portal generation?

**Comment by qouteall** [comment]
Which mod generates which structure?
And you can set the end portal mode in the config. But if the end portal already generates it cannot be changed in normal survival

**Comment by Moleculor** [comment]
> Using the normal end portal type on the mod, the portal works you can teleport into the end, however the end dragon structure also generated on 0,134,0 on a bedrock roof for some reason, could this be part of the end portal generation?

Possibly this?

https://github.com/nevoka-be/Issues/issues/3

**Comment by Archesr** [comment]
> > Using the normal end portal type on the mod, the portal works you can teleport into the end, however the end dragon structure also generated on 0,134,0 on a bedrock roof for some reason, could this be part of the end portal generation?
> 
> 
> 
> Possibly this?
> 
> 
> 
> https://github.com/nevoka-be/Issues/issues/3

Believe so thank you
