### ISSUE TITLE
Wants fabric ">=0.28.1", possible mistake for fabric-api??

### ISSUE THREAD

**Issue by Merith-TK** [qouteall/ImmersivePortalsMod#498]
![image](https://user-images.githubusercontent.com/10422110/102021354-1b448080-3d34-11eb-8bdc-7ea7fc16b9ac.png)
https://mclo.gs/ReLM3km

using multiMC with latest fabric loader 10.8

**Comment by froyo4u** [comment]
latest API is 0.28.1. Might have to download the newest version of it

**Comment by Merith-TK** [comment]
Yeah i just noticed this,
