### ISSUE TITLE
Optifabric & immersive portals Bootcrash [mc-1.16.4]

### ISSUE THREAD

**Issue by SylisMC** [qouteall/ImmersivePortalsMod#499]
Crash on bootup with immersive portals  & optifabric 

Mods : Jumploader, Optifabric, Fabric API Immersive Portals

optifabric-**1.8.13**.jar + IP **0.51**-mc1.16.4-fabric.ja = Crash
optifabric-**1.8.10**.jar + IP **0.51**-mc1.16.4-fabric.ja = Crash
optifabric-**1.8.9**.jar + IP **0.51**-mc1.16.4-fabric.ja = Crash
optifabric-**1.8.7**.jar + IP **0.51**-mc1.16.4-fabric.ja = Crash

optifabric **1.8.7**/**1.8.9**/**1.8.10**/**1.8.17** + immersive-portals-**0.49**-mc1.16.4-fabric.ja = successful boot

Here is my crash log with the latest version of both mods!

[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/5685976/latest.log)

As always, thank you so much for your hard work. it is appreciated

**Comment by qouteall** [comment]
Fixed in 0.52 https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.52-1.16

**Comment by SylisMC** [comment]
Thanks for being so professional about it! good work too
