### ISSUE TITLE
Crash on world load: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16

### ISSUE THREAD

**Issue by andresmarver1** [qouteall/ImmersivePortalsMod#508]
Seems to be an incompatibility with Immersive Portals and Simplex Terrain generation, perhaps.

Things to note:

Generating a world with a generator other than 'Simplex' yields no CTD, at least not in the same conditions as it would with it (need more testing).
Removing Immersive Portals fixes the issue, and lets terrain generate; adding it back in yields a crash on world load.
BYG is installed on the instance.

...
...Immersive portals seems to be, too, incompatible with World Edit; though that's a different issue entirely.

Appreciate very much the attention and work you put on this mod.

Append: crashlog

`---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 12/18/20, 4:59 PM
Description: Exception generating new chunk

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
	at net.minecraft.class_2791.method_12026(class_2791.java:137)
	at net.minecraft.class_2850.method_8675(class_2850.java:59)
	at net.minecraft.class_1951.method_8676(class_1951.java:9)
	at corgiaoc.byg.common.world.surfacebuilder.CanyonSB.generate(CanyonSB.java:114)
	at corgiaoc.byg.common.world.surfacebuilder.CanyonSB.method_15305(CanyonSB.java:17)
	at net.minecraft.class_3504.method_15198(class_3504.java:27)
	at net.minecraft.class_1959.method_8703(class_1959.java:418)
	at com.qouteall.imm_ptl_peripheral.alternate_dimension.ErrorTerrainGenerator.method_12110(ErrorTerrainGenerator.java:218)
	at net.minecraft.class_2806.method_16567(class_2806.java:75)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:263)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1429)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2791.method_12026(class_2791.java:137)
	at net.minecraft.class_2850.method_8675(class_2850.java:59)
	at net.minecraft.class_1951.method_8676(class_1951.java:9)
	at corgiaoc.byg.common.world.surfacebuilder.CanyonSB.generate(CanyonSB.java:114)
	at corgiaoc.byg.common.world.surfacebuilder.CanyonSB.method_15305(CanyonSB.java:17)
	at net.minecraft.class_3504.method_15198(class_3504.java:27)
	at net.minecraft.class_1959.method_8703(class_1959.java:418)
	at com.qouteall.imm_ptl_peripheral.alternate_dimension.ErrorTerrainGenerator.method_12110(ErrorTerrainGenerator.java:218)
	at net.minecraft.class_2806.method_16567(class_2806.java:75)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:263)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)

-- Chunk to be generated --
Details:
	Location: -10,27
	Position hash: 120259084278
	Generator: com.qouteall.imm_ptl_peripheral.alternate_dimension.ErrorTerrainGenerator@1e745b6e
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 529
	Level dimension: immersive_portals:alternate3
	Derived: true
	Level spawn location: World: (-176,147,176), Chunk: (at 0,9,0 in -11,11; contains blocks -176,0,176 to -161,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 62 game time, 62 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 87895 (now: false), thunder time: 95474 (now: false)
	Known server brands: Fabric/Gunpowder
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:874)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.handler$dll000$modifiedRunLoop(MinecraftServer.java:12810)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:832)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 14.0.2, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 2952446112 bytes (2815 MB) / 5905580032 bytes (5632 MB) up to 5905580032 bytes (5632 MB)
	CPUs: 12
	JVM Flags: 21 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5632m -Xms5632m -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		adventurez: AdventureZ 1.1.5
		aopalliance_aopalliance: aopalliance 1.0
		appleskin: AppleSkin 1.0.11
		architectury: Architectury 1.1.55
		artifacts: Artifacts 2.0.2+1.16.4-fabric
		artifice: Artifice 0.13.1+1.16.2-rc1
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		betterend: Better End 0.8.0-beta
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		betternether: Better Nether 5.0.4
		betterweather: Better Weather 1.0.0
		biomemakeover: Biome Makeover 1.16.4-1.1.5
		blockcoins: Block-Coins 1.0.0
		blockus: Blockus 2.0.0+1.16.4
		blue_endless_jankson: jankson 1.1.2
		blur: Blur (Fabric) 2.0.0
		byg: BYG 1.1.3
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
		canvas: Canvas Renderer 1.0.1241
		cardinal-components-base: Cardinal Components API (base) 2.7.9
		cardinal-components-entity: Cardinal Components API (entities) 2.7.9
		cardinal-components-item: Cardinal Components API (items) 2.7.9
		carpet: Carpet Mod in Fabric 1.4.20
		carpet-tis-addition: Carpet TIS Addition 1.11.2
		carrier: Carrier 1.6.1
		charm: Charm 2.1.9
		charmonium: Charmonium 2.1.9
		cinderscapes: Cinderscapes 1.3.0+build.51
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-config2: Cloth Config v4 4.8.3
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.9.0
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.9.0
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.9.0
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.9.0
		com_fasterxml_jackson_module_jackson-module-kotlin: jackson-module-kotlin 2.9.0
		com_google_inject_guice: guice 4.2.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		couplings: Couplings 1.3.3
		croptopia: Croptopia 1.0.6-1.16.4-FABRIC
		cullleaves: Cull Leaves 1.0.0
		curios: Curios API 0.0.10-1.16.3
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		doorknockmod: Door Knocker 1.0
		fabric: Fabric API 0.28.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		fallingleaves: Falling Leaves 1.2
		fast_leaves: Fast Leaves! 1.0.2
		fermion: Fermion 2.8.215
		fermion-gui: Fermion GUI 2.5.215
		fermion-modkeys: Fermion Modifier Keys 1.9.206
		fermion-orientation: Fermion Orientation 1.1.205
		fermion-simulator: Fermion Simulator 1.8.215
		fermion-varia: Fermion Varia 2.6.215
		fiber: fiber 0.23.0-2
		flan: Flan 1.16.2-1.2.1
		frex: FREX 4.2.183
		frex-events: FREX Events 1.1.11
		gateofbabylon: Gate Of Babylon 1.2.0-1.16.2
		glassential: Glassential 1.16.4-1.1.5
		gunpowder-base: Gunpowder 0.3.3+1.16.4
		gunpowder-currency: Gunpowder Currency 1.0.2+gunpowder.0.3.1.mc.1.16.4
		gunpowder-market: Gunpowder Market 1.0.1+gunpowder.0.3.2.mc.1.16.4
		gunpowder-teleport: Gunpowder Teleport 1.0.2+gunpowder.0.3.1.mc.1.16.4
		gunpowder-utilities: Gunpowder Utilities 1.0.2+gunpowder.0.3.1.mc.1.16.4
		healthoverlay: Health Overlay 3.6.13
		illuminations: Illuminations 1.3.1
		imm_ptl_core: Immersive Portals Core 0.52
		immersive_portals: Immersive Portals 0.52
		inventorysorter: Inventory Sorter 1.7.4-1.16
		inventorytabs: Inventory Tabs 0.3.0-1.16.4
		itemflexer: ItemFlexer 1.0.2
		itemscroller: Item Scroller 0.15.0-dev.20201103.183933
		jankson: Jankson 3.0.1+j1.2.0
		javax_inject_javax_inject: javax.inject 1
		json-model-extensions: JSON Model Extensions 1.19.166
		kibe: Kibe 1.5.2-BETA
		kubejs: KubeJS 1.5.3
		kyrptconfig: Kytpt Config 1.1.2-1.16
		lakeside: Lakeside 1.0.3+1.16.4
		lambdynlights: LambDynamicLights 1.3.2+1.16.4
		lchunkloader: Literally Chunk Loader 1.3.3
		libblockattributes_core: LibBlockAttributes (Core) 0.8.3-pre.3
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.3-pre.3
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		megane: megane 3.0.7+1.16.4
		megane-api: megane-api 3.0.7+1.16.4
		megane-impl: megane-impl 3.0.7+1.16.4
		megane-runtime: megane-runtime 3.0.7+1.16.4
		minecraft: Minecraft 1.16.4
		mm: Manningham Mills 2.1
		modid: Damage Tilt 1.16-fabric-0.1.0
		modmenu: Mod Menu 1.14.13+build.19
		moretotems: More Totems 2.7.1
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		multishot: Multishot Infinity 1.1.0
		mysql_mysql-connector-java: mysql-connector-java 5.1.46
		namepain: Name Pain 1.3.1
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_exposed_exposed-core: exposed-core 0.27.1
		org_jetbrains_exposed_exposed-java-time: exposed-java-time 0.27.1
		org_jetbrains_exposed_exposed-jdbc: exposed-jdbc 0.27.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_postgresql_postgresql: postgresql 42.2.2
		org_slf4j_slf4j-api: slf4j-api 1.8.0-beta1
		org_xerial_sqlite-jdbc: sqlite-jdbc 3.32.3.2
		org_yaml_snakeyaml: snakeyaml 1.26
		patchouli: Patchouli 1.16.4-48-FABRIC
		phosphor: Phosphor 0.7.0+build.10
		player-roles: Player Roles 1.2.0
		player_events: Player Events 2.0.0
		player_events_api: Player Events API 2.0.0
		playerabilitylib: Pal 1.2.1
		polymorph: Polymorph 0.0.5-1.16.3
		reauth: ReAuth 3.9.3
		respawnablepets: Respawnable Pets 1.16.4-1
		riverredux: River Redux 0.1.5
		roughlyenoughitems: Roughly Enough Items 5.8.10
		roughlyenoughitems-api: REI (API) 5.8.10
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.10
		roughlyenoughitems-runtime: REI (Runtime) 5.8.10
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		sandwichable: Sandwichable 1.1.2
		satin: Satin 1.5.1
		seasons: Fabric Seasons 1.0.3-BETA
		shulkerboxtooltip: Shulker Box Tooltip 2.3.3+1.16.4
		simplexterrain: Simplex Terrain 0.7.2
		slight-gui-modifications: 'Slight' GUI Modifications 1.6.1
		slotlink: slotlink 2.2.0+1.16.4
		smooth-chunks: Smooth Chunks 1.0.0
		smoothboot: Smooth Boot 1.16-1.3.1
		smoothcoasters: SmoothCoasters 1.16.4-17
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		special-circumstances: Special Circumstances 1.8.215
		spruceui: SpruceUI 1.6.4
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
		terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.1
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.2
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
		terrestria: Terrestria 2.1.5+build.28
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		trade: Trade 1.1.2
		traverse: Traverse 3.0.3+build.13
		trinkets: Trinkets 2.6.7
		truerooms: True Secret Rooms 1.1.2-hotfix
		varied-mobs: Varied Mobs 1.0.0
		waila: Hwyla 1.9.22
		waystones: Waystones 1.0.10
		xaerominimapfair: Xaero's Minimap Fair-Play 20.29.0
		yungsapi: YUNG's API 1.16.4-Fabric-1
		zoob: Monster Of The Ocean Depths 2.5.0
	Patchouli open book context: n/a
	Player Count: 1 / 8; [class_3222['andresmarver'/97, l='ServerWorld minecraft:overworld New World', x=0.66, y=149.74, z=179.59]]
	Data Packs: vanilla (incompatible), fabric/kubejs (incompatible), fabric/trinkets, fabric/kibe, fabric/betternether, fabric/adventurez, fabric/moretotems, fabric/mostructures, fabric/curios, fabric/charm (incompatible), fabric/terrestria, fabric/seasons, fabric/lchunkloader, fabric/player-roles, fabric/croptopia, fabric/gateofbabylon, fabric/byg, fabric/cinderscapes, fabric/betterend, fabric/glassential, fabric/respawnablepets, fabric/fabric-tool-attribute-api-v1, fabric/blockus, fabric/truerooms, fabric/biomemakeover, fabric/waystones, fabric/artifacts, fabric/sandwichable, fabric/traverse, fabric/slotlink, fabric/zoob, fabric/carrier
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'`

**Comment by qouteall** [comment]
Does it crash without byg?

**Comment by qouteall** [comment]
According to bitdefender IP is compatible with world edit.
