### ISSUE TITLE
Projectiles only travel once through portals

### ISSUE THREAD

**Issue by element-119** [qouteall/ImmersivePortalsMod#509]
A projectile thrown/fired by the player will not go through portals multiple times during its flight, whether that be the same portal again, or a different portal. Instead, it treats the second portal as nonexistent.

I tested this with eggs, snowballs, tridents, and arrows (both bow and crossbow). I did not test whether the same happens to projectiles fired by entities.

**Comment by qouteall** [comment]
Similar to https://github.com/qouteall/ImmersivePortalsMod/issues/83

**Comment by qouteall** [comment]
Probably fixed in the next version
