### ISSUE TITLE
I crash on world entry with optifine

### ISSUE THREAD

**Issue by Rannulfus** [qouteall/ImmersivePortalsMod#51]
I'm running just immersive portals 1.14-29 and Optifine 1.14.4_HD_U_F3 and whenever I try to enter a world I just crash to the launcher and then it gives me this as a crash report. It mentions sponge for whatever reason even though it's just a single player game.
[crash-2019-12-28_13.07.34-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/4007298/crash-2019-12-28_13.07.34-client.txt)

**Comment by qouteall** [comment]
try to use older version of optifabric or fabric api? does this issue happen without thismod?

**Comment by Rannulfus** [comment]
It happens whenever I have both of them installed together. I haven't tried older versions of optifabric or the fabric api, but will in the morning tomorrow. Hopefully it'll just be because of that since this mod is really cool. I did however try Optifine 1.14.4_HD_U_F2 with no luck. Shame vanilla MC doesn't have this implemented.

**Comment by qouteall** [comment]
I tested the latest version of fabric loader, fabric api, optifabric and optifine with this mod and it worked fine. So you should use the latest version of all of them.
