### ISSUE TITLE
Incompatibility with The Aether Portal/Custom Portal API

### ISSUE THREAD

**Issue by Snivine** [qouteall/ImmersivePortalsMod#510]
This seems to be that Immersive Portals doesn't implement Custom Portal API, or the other way arround, anywho The Aether Reborn's developers told me that it was Immersive Portals so I'm posting the issue here

devs-immortal/The-Aether#46

[Custom Portal API](https://github.com/kyrptonaught/customportalapi)

[Crash Log](https://paste.ee/p/WodUb)

**Comment by qouteall** [comment]
The crash with aether is probably fixed in the next version.
About the custom portal API, I am not going to integrate with custom portal API. I am designing this mod's own portal API.
