### ISSUE TITLE
Portal view disappears when to close

### ISSUE THREAD

**Issue by Mitigy** [qouteall/ImmersivePortalsMod#511]
When the player moves too close to a portal located on the block grid the portal view disappears but the portal remains functional.

**Comment by qouteall** [comment]
Are you using the latest version of this mod? Does this issue happen with only this mod?

When the portal is not in view, press F3 and see the "Rendered Portal Num" on the right. Is the rendered portal num 0 or 1?

Did you enable compatibility render mode? Try to reset all configurations.

**Comment by Mitigy** [comment]
It just started working after I began the tests you recommended.
