### ISSUE TITLE
[1.15.1] Incompatibility with Lithium

### ISSUE THREAD

**Issue by Fogrits** [qouteall/ImmersivePortalsMod#52]
[Crash Report](https://pastebin.com/Y48d1QqQ)

Seems like something is conflicting between the two regarding something named "AreaContainsFireSource"

Tested with only IP and Lithium

IP version: 1.15-4
Lithium version: 0.2.2

**Comment by qouteall** [comment]
lithium and this mod both redirect this call site. i want the player not to catch fire from the lava below end portal when jumping into end portal. lithium does some optimizations. maybe i can make my mixin have a higher priority.

**Comment by qouteall** [comment]
https://github.com/jellysquid3/Lithium

**Comment by qouteall** [comment]
my mixin made that a player that is close to a portal cannot catch fire in all circumstances. to radically solve it i have to do more hacks on collision stuff.

**Comment by LuminescentMoon** [comment]
Is it possible to fallback gracefully to using a fire immunity potion effect or disabling the entire "prevent player on fire near end portals" functionality?

**Comment by qouteall** [comment]
maybe i can use fire immune potion effect
