### ISSUE TITLE
The Immersive Portals mod crashes Minecraft.

### ISSUE THREAD

**Issue by StatusConnected** [qouteall/ImmersivePortalsMod#522]
The Immersive Portals mod crashes Minecraft when I join a server. A crash log is written and says it's a fatal error. When I removed the mod, everything worked fine. Unrelated, but I used to have performance issues as well.

**Comment by Hearlex** [comment]
Last time i checked it was hostile mobs at fault. For example a creeper exploding or a skeletons arrow approaching the portal. But never the mob itself going through the portal. Maybe it connects to your crashes as well?

**Comment by qouteall** [comment]
show the crash report

**Comment by StatusConnected** [comment]
I tried to replicate the crash, but then I noticed a message I had to record Minecraft in order to read it and it said that IP doesn't work on vanilla servers very well.
