### ISSUE TITLE
breaks fabritone

### ISSUE THREAD

**Issue by astommy** [qouteall/ImmersivePortalsMod#524]
When enabled, fabritone will not do anything, walk, build, etc.  
https://gitlab.com/CDAGaming/fabritone

**Comment by Ardabaskaya55** [comment]
Hi

**Comment by qouteall** [comment]
Show the log

**Comment by astommy** [comment]
[log.txt](https://github.com/qouteall/ImmersivePortalsMod/files/5756653/log.txt)

**Comment by astommy** [comment]
There is nothing in the log, as far as I can tell.

**Comment by astommy** [comment]
@qouteall I enabled debug logging and found out that fabritone was stuck in this loop
https://gitlab.com/CDAGaming/fabritone/-/blob/master/src/main/java/baritone/pathing/path/PathExecutor.java#L190

**Comment by astommy** [comment]
According to my testing, movement is only possible in the current chunk, anything beyond that just spams that line of log.

**Comment by qouteall** [comment]
I am investigating this.

**Comment by qouteall** [comment]
Seems that Fabritone copies the chunk map. But this mod replaces the chunk array because the vanilla chunk array does not allow loading chunks beyond render distance.

**Comment by qouteall** [comment]
Vanilla's ClientChunkManager is thread-safe so there is no need to copy the chunk map. It may be the heritage code from 1.12 version of baritone

**Comment by astommy** [comment]
@qouteall Thank you. I'll report this to baritone
