### ISSUE TITLE
Portal doesn't appear and i can't get it to work.

### ISSUE THREAD

**Issue by pratmagicgander** [qouteall/ImmersivePortalsMod#530]
https://youtu.be/C6q8JYMEps8
I didn't have any texture pack on.

**Comment by qouteall** [comment]
This mod is not better portals. If you encounter the issue with better portals, open the issue elsewhere.
If you are using fabric, upgrade to 1.16.4 and use the latest version of this mod and fabric api

**Comment by pratmagicgander** [comment]
I used impressive portals, i just wrote it wrong in the title.

**Comment by pratmagicgander** [comment]
It worked!
Than you!
