### ISSUE TITLE
Can additional dimensions be customized?

### ISSUE THREAD

**Issue by KuangYang452** [qouteall/ImmersivePortalsMod#534]
I tried to create a 64 grid underground mineral world between the main world and nether
But when creating the world, I can't use my preset to stack it.
I've also tried to name the default "immediate."_ portals:alternate1 Then put alternate1 on top of nether, but it doesn't change the way it works.
Is there any way?

**Comment by qouteall** [comment]
What do you mean? The custom datapack dimension does not show in dimension stack?

**Comment by KuangYang452** [comment]
> What do you mean? The custom datapack dimension does not show in dimension stack?

Excuse me, I don't know how to use data pack to add dimensions.
Now I create the world by exporting the preset, modifying it, and importing it again
However, it seems that the dimensions preset by immediate cannot be modified in this way

**Comment by qouteall** [comment]
You are using custom dimension of "immediate" mod?

**Comment by KuangYang452** [comment]
> You are using custom dimension of "immediate" mod?
Immersive Portals

**Comment by KuangYang452** [comment]
OK, I've solved the problem
I'm sorry I may have wasted your time
