### ISSUE TITLE
When rendering too many portals... this... happens

### ISSUE THREAD

**Issue by Ookidablobida** [qouteall/ImmersivePortalsMod#538]
I'm not sure how to describe it, but this is what it looks like. I'm only running immersive portals (0.52 because it seems any newer version won't run, no crash report or anything) and fabric api. (The screenshots were taken with other mods, but when done in just those two I had the same result.)
![2021-01-05_11 50 58](https://user-images.githubusercontent.com/69689724/103687163-10ed5f00-4f4d-11eb-8979-613bcecf0866.png)
![2021-01-05_11 51 12](https://user-images.githubusercontent.com/69689724/103687179-177bd680-4f4d-11eb-8ca1-62d737271151.png)
![2021-01-05_11 51 32](https://user-images.githubusercontent.com/69689724/103687195-1e0a4e00-4f4d-11eb-81f6-9c5b0c038e8f.png)

**Comment by qouteall** [comment]
Firstly, use the latest version. If the latest version does not work, upgrade the fabric api and fabric loader

**Comment by Ookidablobida** [comment]
Ok, when I first tried it, I only updated Fabric API so I'll try out updating Fabric loader.

**Comment by Ookidablobida** [comment]
Oddly enough, even after uninstalling and reinstalling fabric entirely, and updating both immersive portals and fabric api, this still happens. Changing the client config doesn't seem to do anything either.

**Comment by qouteall** [comment]
Enable "check gl error" in config, then trigger this issue, then upload the log.

**Comment by qouteall** [comment]
Issue closed because the issue opener haven't provided requested information for a long time.
