### ISSUE TITLE
Sodium fork incompatible with lambdadynamiclight?

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#545]

**Comment by Sparktion** [comment]
I seem to also have this error. For a more accurate description, the mod, "Chlorine" (Which is a Sodium Fork, for Forge.) Is incompatible with ImmersivePortals. I have attached a log.
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/6033016/latest.log)

**Comment by DragonEggBedrockBreaking** [comment]
I use sodium and LambDynamicLights fine, and have done before this bug was closed, so what is this about?
