### ISSUE TITLE
Motion Affinity affects ground movement near vertical portal

### ISSUE THREAD

**Issue by epicRedHot** [qouteall/ImmersivePortalsMod#552]
(motionAffinity set to 1 in this example)
In the attached image, walking/standing near the portal causes the player's momentum to slowly increase, provided there is at least a slight amount of motion to begin with.
![image](https://user-images.githubusercontent.com/76829489/105795248-1c331980-5f52-11eb-92b9-26494db33c73.png)

**Comment by qouteall** [comment]
Should already be fixed.
