### ISSUE TITLE
Bug compability with related mod of Pehkui, WhiteRabbit

### ISSUE THREAD

**Issue by GamyGamer** [qouteall/ImmersivePortalsMod#555]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* If you find an issue, check whether this issue happens with only this mod. If not, check which mod it's incompatible with. 
* The Forge version is not being supported. If you find an issue of the Forge version, check whether the same issue exists for the Fabric version. Forge-version-specific issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues

WhiteRabbit is a mod that has been created by same developer of Pehkui, it adds 2 consumables to change player size. It appears that being scaled by consumable first and going throught scalable portal makes wrong math while scaling First scaling to be slower makes output smaller even on increasing portal and scaling to be bigger makes you always bigger while traversing any scalable portal. This mod add new variable "white_rabbit:food" that scales player by consumable.

**Comment by qouteall** [comment]
https://www.curseforge.com/minecraft/mc-mods/white-rabbit

**Comment by GamyGamer** [comment]
Yeah, that's the mod that I was talking about, sorry that I forgot to link it here

**Comment by qouteall** [comment]
Probably fixed.

**Comment by GamyGamer** [comment]
It was partially fixed, right now using version 0.74 from experimental website, Original bug was fixed but another emerged. I am using this chamber for testing: 
![image](https://user-images.githubusercontent.com/49346764/108052409-62a8ff00-704c-11eb-9abd-6bbd5bc365a1.png)
Scale of portals is 1:2. Getting to scale 0.0625 (base scale) and going again gives error "Scale out of range" and resets base scale to one

**Comment by GamyGamer** [comment]
Nevermind, I have found in .json config option "scaleLimit", not related to that but I have a question, is there a way to disable this completly? (By completly I mean setting option to false, not very high numbers) You can now close this issue, I can also but I want to hear last answer.

**Comment by qouteall** [comment]
The scale limit was added because some big entities lag the server a lot. Changing the scale limit to a high number is equivalent to disabling the scale limit

**Comment by qouteall** [comment]
The scale limit was added because some big entities lag the server a lot. Changing the scale limit to a high number is equivalent to disabling the scale limit
