### ISSUE TITLE
Convert conventional portal does not work with custom portal api?

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#556]
https://www.curseforge.com/minecraft/mc-mods/gobber-fabric

**Comment by ChaosContrl** [comment]
So I tried this portal converter feature, but I really can't seem to make it work. It's either a bug or my own fault, but here's my procedure.

First, I picked out a dimension portal I want to convert. I decided to convert the Hunting World portal from the Gobber [FABRIC] mod. So I took note of the dimension's name: **gobber2:hunting**

Second, I took note of the portal's block name: **customportals:customportalblock**
![2021-03-05_16 37 51](https://user-images.githubusercontent.com/45300040/110176378-2ce87200-7dd1-11eb-8bfe-033ded814beb.png)

Third, using the given JSON example that I copied and renamed to **convert_hunting_portal.json** (and placed the file in the same directory as all the other templates: **custom_portal_generation**), I modified the file like the following:
`{
  "schema_version": "imm_ptl:v1",
  "from": [
    "minecraft:overworld"
  ],
  "to": "gobber2:hunting",
  "form": {
    "type": "imm_ptl:convert_conventional_portal",
    "portal_block": "customportals:customportalblock"
  },
  "trigger": {
    "type": "imm_ptl:conventional_dimension_change"
  }
}`

Fourth, I entered **/reload** and then Save&Quit my game entirely, before launching it again and opening the save with the new JSON file I created in step 3.

Fifth, I destroyed the existing portal (that I built to get the portal block's name) and rebuilt a new one:
![2021-03-05_16 34 34](https://user-images.githubusercontent.com/45300040/110176071-c5cabd80-7dd0-11eb-82a1-b27c5ae0a262.png)

Which I then activated with a Flint&Steel:
![2021-03-05_16 34 39](https://user-images.githubusercontent.com/45300040/110176084-cb280800-7dd0-11eb-90b6-990385fccc39.png)

Sixth, while in Creative mode, I passed through the portal and had a small loading screen, before I was in the Hunting Dimension. However, the portal looked like this:
![2021-03-05_16 34 48](https://user-images.githubusercontent.com/45300040/110176093-cd8a6200-7dd0-11eb-9be5-b852b0ff5e56.png)

And when I try to go back, I am stuck in this sort of unloaded void for minutes. The only way out of it is to either teleport to another dimension, or exit and come back to the save. Though even after teleporting (via /execute) and coming back to the portal in the overworld (again via /execute), the portal is not converted at all.
![2021-03-05_16 55 31](https://user-images.githubusercontent.com/45300040/110178044-e1839300-7dd3-11eb-9c67-02be31445ee6.png)

Besides the weird loading behavior when coming back to the overworld via portal (which is its own issue), am I doing something wrong or is it a bug?

**Comment by qouteall** [comment]
The overworld chunk not being loaded seems to be a serious issue

**Comment by qouteall** [comment]
https://www.curseforge.com/minecraft/mc-mods/gobber-fabric

**Comment by qouteall** [comment]
https://github.com/kyrptonaught/customportalapi/issues/14

**Comment by qouteall** [comment]
The new custom portal api should have it fixed.

**Comment by ChaosContrl** [comment]
Nice, cannot wait to test it out! Thanks for the support! 👍
