### ISSUE TITLE
Carpet Compat

### ISSUE THREAD

**Issue by ApposModding** [qouteall/ImmersivePortalsMod#557]
The carpet mod is incompatible with immersive portals fabric
This is NOT Fixed

**Comment by qouteall** [comment]
show the crash report

**Comment by lucotuco** [comment]
https://ihaveaissue.blogspot.com/2021/02/the-carpet-mod-is-incompatible-with.html

**Comment by qouteall** [comment]
@lucotuco post the crash report. the screenshot shows no useful information

**Comment by qouteall** [comment]
Close due to not having complete information to diagnose the issue.
