### ISSUE TITLE
Game crashed when using 1.16.3 version

### ISSUE THREAD

**Issue by b-5k1** [qouteall/ImmersivePortalsMod#559]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* If you find an issue, check whether this issue happens with only this mod. If not, check which mod it's incompatible with.
* The Forge version is not being supported. If you find an issue of the Forge version, check whether the same issue exists for the Fabric version. Forge-version-specific issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues

Im using the 1.16.3 version of Immersive Portals, and I get this crash screen why I try load the game. (https://gyazo.com/2efe4ca032f4e582b7877bc3c17a6e68)

I dont really know what is causing this, can somebody help me figure this out?
It says "provided by imm_ptl_core" and it says "Could not execute entrypoint stage 'client' due to errors,"
Can someone help?

**Comment by qouteall** [comment]
Firstly, it's recommended to use 1.16.5. Most 1.16.3 mods should work in 1.16.5.

If it still crashes in 1.16.5 latest version, post the crash report

**Comment by b-5k1** [comment]
> Firstly, it's recommended to use 1.16.5. Most 1.16.3 mods should work in 1.16.5.
> 
> If it still crashes in 1.16.5 latest version, post the crash report

Ah ok, I'll try doing that.

**Comment by b-5k1** [comment]
> Firstly, it's recommended to use 1.16.5. Most 1.16.3 mods should work in 1.16.5.
> 
> If it still crashes in 1.16.5 latest version, post the crash report

![image](https://user-images.githubusercontent.com/78498219/106959772-092eff00-6733-11eb-8cc3-90d4c70ab9ca.png)
Nope, I still get this, I'm litreally using  the 1.16.5 version and i still get this crash screen, what the heck?

**Comment by b-5k1** [comment]
Oh wait, I see now, I'm using an outdated version of the Fabric API,  Or something.

**Comment by b-5k1** [comment]
Oh wait, I see now, I'm using an outdated version of the Fabric API,  Or something.

**Comment by b-5k1** [comment]
Nope, I just didnt have the API installed. bruh momento
