### ISSUE TITLE
Portals with unusual shapes allow for partially invisible portals

### ISSUE THREAD

**Issue by RogerGodzilla** [qouteall/ImmersivePortalsMod#56]
It's probably easier to explain through the video below, but I'll try to explain the circumstances.

See the video [here](https://youtu.be/N93y0ThhWtk).

When the player's head is between the topmost, bottom most, right most, and left most portal blocks, they will teleport as if there is a portal in the location that they are standing in, regardless of whether or not there is one.

**Comment by qouteall** [comment]
nice catch

**Comment by qouteall** [comment]
It may be fixed in the newest version.
