### ISSUE TITLE
Portal Isn't See-Through

### ISSUE THREAD

**Issue by MaskedToxinYT** [qouteall/ImmersivePortalsMod#563]
I got on my Survival World using 1.16.5 Fabric and the nether portal isn't see-through

**Comment by qouteall** [comment]
You need to break the nether portal and relight it.

**Comment by SparkStone01** [comment]
I have the same problem and have been trying everything to solve it, nothing works.

**Comment by qouteall** [comment]
Show a screenshot. If you only see the fog color it may be the videocard driver's fault. Then try to enable "compatibility render mode"

**Comment by SparkStone01** [comment]
![2021-02-12_19 04 13](https://user-images.githubusercontent.com/78862969/107805444-a7d7e300-6d65-11eb-8dd4-6e80887970f3.png)
![2021-02-12_19 04 28](https://user-images.githubusercontent.com/78862969/107805473-b1614b00-6d65-11eb-8fd3-e52026d29301.png)

The first screenshot is without "compatibility render mode" and the second one is with "compatibility render mode".

**Comment by qouteall** [comment]
Try to use command `/immersive_portals_debug front_clipping_disable`

**Comment by SparkStone01** [comment]
That didn't work but thanks for trying to help

**Comment by qouteall** [comment]
Close because outdated.
