### ISSUE TITLE
You can't see entities when you're inside the scaled box and entities are outside of it

### ISSUE THREAD

**Issue by ImSpaceLover** [qouteall/ImmersivePortalsMod#568]
![image](https://user-images.githubusercontent.com/64267797/107637450-332a7900-6c7f-11eb-9c79-5170be508d61.png)
![image](https://user-images.githubusercontent.com/64267797/107637460-36be0000-6c7f-11eb-9e7f-3046e5b49359.png)
![image](https://user-images.githubusercontent.com/64267797/107637574-61a85400-6c7f-11eb-86cb-b6f050286d06.png)

**Comment by qouteall** [comment]
Probably fixed
