### ISSUE TITLE
Bug with other dimensions mods

### ISSUE THREAD

**Issue by Kiryonn** [qouteall/ImmersivePortalsMod#569]
I'm using the 1.16.5 version with the minning dimension mod.

The problem is that if i enter a dimension other than the nether (i tried only with the cobblestone one yet), when i go back i can't get into the nether portal (nor do i see what happen inside) unless i break the portal (mirror not bloc) and light it again. and i need to do that for all the portals in the overworld. All the portals within the nether are ok wich make still possible to redo the first portal, walk in, go through the 2nd, and then need to redo the 2nd.

Which brings me to make me do the suggestion : why not make it compatible with every dimension portals ? This way the bug disapear and we could have a great experience with multiple dimensions mods.

**Comment by qouteall** [comment]
How did you "enter a dimension other than the nether"? With or without loading screen?
What do you mean by "i can't get into the nether portal (nor do i see what happen inside)"? You walk through portal but does not teleport? Does the portal show black or fog color?

**Comment by qouteall** [comment]
Close due to not having complete information to diagnose the issue.
