### ISSUE TITLE
Is it possible to disable the functionality of the mod for nether portals?

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#570]
Hello. I want to use this mod for some custom dimensions that I do with datapacks. But I want to keep the nether portal functionality completely vanilla. Is it possible to do this? Perhaps there is some sort of dimension blacklist to make the mod ignore the nether portals... I found this parameter in the config, set it to vanilla, but it doesn't seem to work as it should. When I activate a portal, it is created as vanilla, but after entering it, the purple overlay breaks and the portals become immersive. 
`#Allowed Values: normal, vanilla, adaptive, disabled 
nether_portal_mode = "vanilla"`

I am using the latest version of the mod for Forge, Minecraft 1.16.5

**Comment by qouteall** [comment]
The example datapack has one to convert vanilla nether portals. You need to delete that one https://github.com/qouteall/ImmersivePortalsMod/wiki/Datapack-Based-Custom-Portal-Generation#convert_vanilla_nether_portaljson-convent-vanilla-nether-portals-into-see-through-portals-if-the-shapes-are-compatible
