### ISSUE TITLE
Glitched Textures and craziness

### ISSUE THREAD

**Issue by saythrt** [qouteall/ImmersivePortalsMod#572]
i really dont know whats happening , i am just using immersive portals + pehkui + optfine and these things are communly happening now , these weird visual glitches , i really dont know if is because of compatibility issues with optifine but this is happening
![image](https://user-images.githubusercontent.com/79027783/107864121-3fa60180-6e38-11eb-8714-f16726807854.png)
![image](https://user-images.githubusercontent.com/79027783/107864124-47fe3c80-6e38-11eb-8d0d-93ab172d97bf.png)

**Comment by choalover** [comment]
Try getting rid of Optifine to see if it fixes the issue cause it is the likely cause if I read correctly I think Optifine does not like Immersive Portals at all.

**Comment by qouteall** [comment]
Does this happen when render regions is turned off?

**Comment by saythrt** [comment]
> Does this happen when render regions is turned off?

yes , thanks , now i can play the game without having a seizure ,and yes when its off this happens
