### ISSUE TITLE
1.15.2 pre 1 Server Crash

### ISSUE THREAD

**Issue by AltimusX** [qouteall/ImmersivePortalsMod#58]
Works fine single player except for the bug where fences vanish and where requiem possession bugs out until relog when players move from ceiling and floor dimensions. It seems to be okay when it is just going up and down between 2 dimensions, like simple void world and overwolrd but when you decide to go up to the end then back to void then to over world from there the game stops recognizing your entity, you have to kill the vessel and restart the game to possess again after that.

And here is the server crash logs for trying to start the server with your new version, note that the old version works on the server.

https://pastebin.com/0ePJMNJM
 We rolled back to start the server.

**Comment by qouteall** [comment]
fixed in 0.8

**Comment by AltimusX** [comment]
Thanks! The crash has been fixed!

**Comment by qouteall** [comment]
What do you mean "fence"? Which mod provides it?

**Comment by qouteall** [comment]
The compatibility issue with requiem is fixed in 0.9 version
