### ISSUE TITLE
Portals are glitched and connect to each other

### ISSUE THREAD

**Issue by Findzi** [qouteall/ImmersivePortalsMod#585]
When I tried to build a portal from a portal to another, the portal glitched and connected to an already used portal.
I tried to remove the portal by setting it with air but nothing changed. When I removed the portal blocks and made another portal, the portal in there connected to the portal I wanted to, but when I walk through it teleports me into the original portal. This works when I go from the portal that is not glitched to the portal that is glitched, but does not when I go into the glitched portal. Weird than that, that connected portal went into another connected portal that was connected to another portal that was sideways, so whenever I walked into that portal I would turn sideways. It's hard to explain, but I have images or videos of it.

![Minecraft_ 1 16 5 - Singleplayer 2_18_2021 9_04_29 PM](https://user-images.githubusercontent.com/79298572/108460856-58465b00-722e-11eb-8a43-a9d76d74beb7.png)
In this image, the portal looks good and is connected.
![Minecraft_ 1 16 5 - Singleplayer 2_18_2021 9_04_34 PM](https://user-images.githubusercontent.com/79298572/108460889-698f6780-722e-11eb-9991-c409290143d1.png)
When I walk into it, I go into this area. It looks weird when I look down because the portal is blocked with nether blocks.
![Minecraft_ 1 16 5 - Singleplayer 2_18_2021 9_04_40 PM (1)](https://user-images.githubusercontent.com/79298572/108460927-8330af00-722e-11eb-89fa-87a9a0045324.png)
There is a portal connected to the portal I just went through. Going in that portal leads me here.
![Minecraft_ 1 16 5 - Singleplayer 2_18_2021 9_05_02 PM](https://user-images.githubusercontent.com/79298572/108460993-a3f90480-722e-11eb-8d01-ada4f733c54f.png)
That portal is glitched because it connects to a turned portal. I cannot go back to the second portal, or the previous portal. Only the portal that is shown I will walk through. That portal is also blocked by blocks.
![Minecraft_ 1 16 5 - Singleplayer 2_18_2021 9_05_10 PM](https://user-images.githubusercontent.com/79298572/108461124-f0444480-722e-11eb-9469-2aabd90a2944.png)
When I walk out it looks like that.
I cannot remove the portals too, so those portals are stuck there forever unless I find a way to remove them.
![Minecraft_ 1 16 5 - Singleplayer 2_18_2021 9_23_49 PM](https://user-images.githubusercontent.com/79298572/108461553-c5a6bb80-722f-11eb-8a06-80c65ecdffd2.png)
When I go the other way, it looks fine.
![Minecraft_ 1 16 5 - Singleplayer 2_18_2021 9_23_53 PM](https://user-images.githubusercontent.com/79298572/108461579-cf302380-722f-11eb-9988-6c4b99febef4.png)
The portal works too.

**Comment by qouteall** [comment]
You can delete portal helper made portals by `/portal eradicate_portal_clutter`

Does nether portal connect to an existing nether portal?

**Comment by qouteall** [comment]
Close because outdated.
