### ISSUE TITLE
Unable to break end portals 

### ISSUE THREAD

**Issue by Alvin-And-The-Chipmunks** [qouteall/ImmersivePortalsMod#586]
My issue is that I am unable to break end portals I tried water but that only removed the blocking placement thing pls help.

**Comment by ItsAlvinThePro** [comment]
I also lag most of the times I go in a nether portal

**Comment by qouteall** [comment]
Use `/portal delete_portal` to remove the end portal

**Comment by qouteall** [comment]
About the lag, are you using other mods?

**Comment by ItsAlvinThePro** [comment]
> About the lag, are you using other mods?

no I am not 
Im just using the mod and now every 1-2 seconds i get 0 fps 

these are my specs https://prnt.sc/100yle6 https://prnt.sc/100ylpi

**Comment by ItsAlvinThePro** [comment]
I usually get 300 something fps

**Comment by ItsAlvinThePro** [comment]
> > About the lag, are you using other mods?
> 
> no I am not
> Im just using the mod and now every 1-2 seconds i get 0 fps
> 
> these are my specs https://prnt.sc/100yle6 https://prnt.sc/100ylpi

this is fixed now but the nether portal lag is still there

**Comment by ItsAlvinThePro** [comment]
and this usually happens https://prnt.sc/100ywnr

**Comment by ItsAlvinThePro** [comment]
random question no relation to the problem you made this??? https://prnt.sc/100z0xk
that's epic

**Comment by qouteall** [comment]
It's very weird that it lags. To debug this, I need you to 1. only install IP and uninstall other mods 2. Enter game, press shift+F3  3. experience lag  4. post the log (logs/latest.log)

**Comment by ItsAlvinThePro** [comment]
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/6015974/latest.log)

**Comment by ItsAlvinThePro** [comment]
here this is maybe better 
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/6015988/latest.log)

**Comment by qouteall** [comment]
It mainly lags in root.gameRenderer.level.render_portal_total.render_portal_content.terrain which contains the solid block rendering(CPU side), 
IP cross portal entity rendering and IP render list prune.
The performance is affected by many factors. Does it lag after playing the game for 5 minutes? Does it lag with my sodium fork?

And you can try disabling the cross portal entity rendering in the config. And try command `/immersive_portals_debug cull_sections_behind_disable` to disable the render list prune but I doubt that these two things cause the lag

**Comment by ItsAlvinThePro** [comment]
im a bit confused but sure i will try the 5 min thing and your fork. any tips on uninstalling normal fabric?

**Comment by ItsAlvinThePro** [comment]
also sorry for the late responses i think we are on completely different timezones...

**Comment by qouteall** [comment]
Why do you want to uninstall faric
