### ISSUE TITLE
Game Crashes upon lighting portal with latest Sodium compatibility version

### ISSUE THREAD

**Issue by LoneWolfNick** [qouteall/ImmersivePortalsMod#589]
So I'm using the Fabric version of both mods for 1.16.5, I'm quite new to bug reporting however I do know you might want the crash report so I'll post it down below

The game runs perfectly but as soon as I light a portal and the chunks start loading it freezes for a moment and after that the game outright crashes
The mod doesn't seem to work with optifabric (and thus optifine) either, but instead of the game loading it just crashes without a crash report at all

> ---- Minecraft Crash Report ----
> // Oh - I know what I did wrong!
> 
> Time: 2/20/21 12:02 PM
> Description: Unexpected error
> 
> java.lang.NoClassDefFoundError: me/jellysquid/mods/sodium/client/IWorldRenderer
> 	at com.qouteall.hiding_in_the_bushes.sodium_compatibility.SodiumInterfaceInitializer.lambda$init$0(SodiumInterfaceInitializer.java:18)
> 	at com.qouteall.hiding_in_the_bushes.sodium_compatibility.SodiumInterfaceInitializer$$Lambda$2580/526417334.apply(Unknown Source)
> 	at com.qouteall.immersive_portals.render.MyGameRenderer.switchAndRenderTheWorld(MyGameRenderer.java:179)
> 	at com.qouteall.immersive_portals.render.MyGameRenderer.renderWorldNew(MyGameRenderer.java:75)
> 	at com.qouteall.immersive_portals.render.PortalRenderer.invokeWorldRendering(PortalRenderer.java:223)
> 	at com.qouteall.immersive_portals.render.PortalRenderer.renderPortalContent(PortalRenderer.java:188)
> 	at com.qouteall.immersive_portals.render.RendererUsingStencil.doRenderPortal(RendererUsingStencil.java:140)
> 	at com.qouteall.immersive_portals.render.PortalRenderer.renderPortals(PortalRenderer.java:110)
> 	at com.qouteall.immersive_portals.render.RendererUsingStencil.doPortalRendering(RendererUsingStencil.java:53)
> 	at com.qouteall.immersive_portals.render.RendererUsingStencil.onBeforeTranslucentRendering(RendererUsingStencil.java:48)
> 	at net.minecraft.class_761.handler$zlm000$onBeforeTranslucentRendering(class_761.java:7724)
> 	at net.minecraft.class_761.method_22710(class_761.java:1360)
> 	at net.minecraft.class_757.method_3188(class_757.java:727)
> 	at net.minecraft.class_757.redirect$zli000$redirectRenderingWorld(class_757.java:2051)
> 	at net.minecraft.class_757.method_3192(class_757.java:546)
> 	at net.minecraft.class_310.method_1523(class_310.java:1048)
> 	at net.minecraft.class_310.method_1514(class_310.java:681)
> 	at net.minecraft.client.main.Main.main(Main.java:215)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
> Caused by: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.IWorldRenderer
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 25 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at com.qouteall.hiding_in_the_bushes.sodium_compatibility.SodiumInterfaceInitializer.lambda$init$0(SodiumInterfaceInitializer.java:18)
> 	at com.qouteall.hiding_in_the_bushes.sodium_compatibility.SodiumInterfaceInitializer$$Lambda$2580/526417334.apply(Unknown Source)
> 	at com.qouteall.immersive_portals.render.MyGameRenderer.switchAndRenderTheWorld(MyGameRenderer.java:179)
> 	at com.qouteall.immersive_portals.render.MyGameRenderer.renderWorldNew(MyGameRenderer.java:75)
> 	at com.qouteall.immersive_portals.render.PortalRenderer.invokeWorldRendering(PortalRenderer.java:223)
> 	at com.qouteall.immersive_portals.render.PortalRenderer.renderPortalContent(PortalRenderer.java:188)
> 	at com.qouteall.immersive_portals.render.RendererUsingStencil.doRenderPortal(RendererUsingStencil.java:140)
> 	at com.qouteall.immersive_portals.render.PortalRenderer.renderPortals(PortalRenderer.java:110)
> 	at com.qouteall.immersive_portals.render.RendererUsingStencil.doPortalRendering(RendererUsingStencil.java:53)
> 	at com.qouteall.immersive_portals.render.RendererUsingStencil.onBeforeTranslucentRendering(RendererUsingStencil.java:48)
> 	at net.minecraft.class_761.handler$zlm000$onBeforeTranslucentRendering(class_761.java:7724)
> 	at net.minecraft.class_761.method_22710(class_761.java:1360)
> 	at net.minecraft.class_757.method_3188(class_757.java:727)
> 	at net.minecraft.class_757.redirect$zli000$redirectRenderingWorld(class_757.java:2051)
> 
> -- Affected level --
> Details:
> 	All players: 0 total; []
> 	Chunk stats: Client Chunks (ImmPtl) 0
> 	Level dimension: minecraft:the_nether
> 	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> 	Level time: 1 game time, 1 day time
> 	Server brand: fabric
> 	Server type: Integrated singleplayer server
> Stacktrace:
> 	at net.minecraft.class_638.method_8538(class_638.java:449)
> 	at net.minecraft.class_310.method_1587(class_310.java:2239)
> 	at net.minecraft.class_310.method_1514(class_310.java:704)
> 	at net.minecraft.client.main.Main.main(Main.java:215)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.16.5
> 	Minecraft Version ID: 1.16.5
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_51, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 547816848 bytes (522 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
> 	CPUs: 4
> 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	Fabric Mods: 
> 		cloth-basic-math: Cloth Basic Math 0.5.1
> 		cloth-config2: Cloth Config v4 4.8.2
> 		fabric: Fabric API 0.30.3+1.16
> 		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
> 		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
> 		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
> 		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
> 		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
> 		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
> 		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
> 		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
> 		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
> 		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
> 		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
> 		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
> 		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
> 		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
> 		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
> 		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
> 		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
> 		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
> 		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
> 		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
> 		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
> 		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
> 		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
> 		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
> 		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
> 		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
> 		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
> 		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
> 		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
> 		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
> 		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
> 		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
> 		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
> 		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
> 		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
> 		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
> 		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
> 		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
> 		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
> 		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
> 		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
> 		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
> 		fabricloader: Fabric Loader 0.11.1
> 		imm_ptl_core: Immersive Portals Core 0.68
> 		immersive_portals: Immersive Portals 0.68
> 		java: Java HotSpot(TM) 64-Bit Server VM 8
> 		minecraft: Minecraft 1.16.5
> 		modmenu: Mod Menu 1.14.6+build.31
> 		sodium: Sodium 0.1.1
> 	Launched Version: fabric-loader-0.11.1-1.16.5
> 	Backend library: LWJGL version 3.2.2 build 10
> 	Backend API: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.40, NVIDIA Corporation
> 	GL Caps: Using framebuffer using OpenGL 3.0
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fabric'
> 	Type: Client (map_client.txt)
> 	Graphics mode: fast
> 	Resource Packs: vanilla
> 	Current Language: English (US)
> 	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
>

**Comment by DragonEggBedrockBreaking** [comment]
> 
> 
> So I'm using the Fabric version of both mods for 1.16.5, I'm quite new to bug reporting however I do know you might want the crash report so I'll post it down below
> 
> The game runs perfectly but as soon as I light a portal and the chunks start loading it freezes for a moment and after that the game outright crashes
> The mod doesn't seem to work with optifabric (and thus optifine) either, but instead of the game loading it just crashes without a crash report at all
> 
> > imm_ptl_core: Immersive Portals Core 0.68
> > immersive_portals: Immersive Portals 0.68
> > java: Java HotSpot(TM) 64-Bit Server VM 8
> > minecraft: Minecraft 1.16.5
> > modmenu: Mod Menu 1.14.6+build.31
> > sodium: Sodium 0.1.1

You are using Immersive Portals 0.68, and the fork of 0.1.1. You either need to [upgrade Immersive Portals](https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.78-1.16), or you need to [downgrade your Sodium fork version](https://github.com/qouteall/sodium-fabric/releases/tag/ipc1164_1). The first option is more recommended. 

For Optifine compatibility, you need to upgrade Immersive Portals to [a newer version](https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.78-1.16).
