### ISSUE TITLE
imm_ptl_core issues?

### ISSUE THREAD

**Issue by jumpy72red** [qouteall/ImmersivePortalsMod#594]
Not sure what this error is about, but here ya go:
[https://pastebin.com/wZ0AnpZD](https://pastebin.com/wZ0AnpZD)

I'm using Kali Linux, and for some reason, I have to give Minecraft its own java so I use the java 8 runtime, which works for everything else but thought it might cause some issues so worth mentioning.

Yes, I have the latest version of the mod (I downloaded it 2 days ago)
Yes, I have the latest Fabric and Fabric API
No, I am not using the Forge version.

**Comment by froyo4u** [comment]
You aren't using the latest version, the latest version was released yesterday, go download the new one and the newest compatible Sodium fork and you should be good to go!

**Comment by jumpy72red** [comment]
> You aren't using the latest version, the latest version was released yesterday, go download the new one and the newest compatible Sodium fork and you should be good to go!

ah I didn't realise! Sorry for the trouble

**Comment by jumpy72red** [comment]
Closing now
