### ISSUE TITLE
Not working on server

### ISSUE THREAD

**Issue by masonVZ** [qouteall/ImmersivePortalsMod#596]
I have an SMP with my friends and I think I did everything right (downloaded it installed it on the server and in my mods folder)
but it just wont work. It works if I load up a single player and use the mod in that world just not in the server.

**Comment by EnderTheCoder** [comment]
same problem to be solved

**Comment by qouteall** [comment]
Both client and server needs to install this mod

**Comment by EnderTheCoder** [comment]
not this problem, the server cant even launch normally, it would stuck at world loading when this mod is added

**Comment by qouteall** [comment]
@EnderTheCoder post the server log. Does the stuck happen randomly?

**Comment by qouteall** [comment]
And if you are using bukkit4fabric, IP is incompatible with bukkit4fabric

**Comment by qouteall** [comment]
Close due to not having complete information to diagnose the issue.
