### ISSUE TITLE
Particles appear in more than one dimension

### ISSUE THREAD

**Issue by detective-wraith** [qouteall/ImmersivePortalsMod#597]
I made an issue on this a while back but didn't realize what it was. I am now making an issue on it again because I actually realize what is happening. 
////
Extra Required Mods: Optifine
////
Description: When particles are generated in one dimension, They also appear in all other dimensions!
////
Steps to Reproduce:
1. Grab yourself a copy of Optifine, drop it in the mods folder with Optifabric so that it works, then load a minecraft world (A creative world works best)
2. Make a Portal. Any portal will work, but a portal between 2 dimensions that lead to the same coordinates works best.
3. Enable all particles for maximum effect.
4. Place a block that emits particles. I found that Campfires work best due to them constantly emitting smoke.
5. Go through the portal and observe the same coordinates on the other side.
////
Result: Particles from the block are in other dimensions. 
Expected Result: Particles should not randomly appear.
////
Some Screenshots I took of it in action. I promise, despite what the screenshots show, that each particle appeared in each dimension. Yes, I tested it out in every dimension.
![image](https://user-images.githubusercontent.com/56732629/108764675-88387b80-7518-11eb-949a-75f8cd530e2c.png)
![image](https://user-images.githubusercontent.com/56732629/108764822-b28a3900-7518-11eb-818d-4d046d1449e3.png)
![image](https://user-images.githubusercontent.com/56732629/108765303-3a704300-7519-11eb-8dfc-c3a9e82d20bb.png)
![image](https://user-images.githubusercontent.com/56732629/108765467-6ee3ff00-7519-11eb-9727-db8a7dc5a0cb.png)
////
Tester's Notes: You can't just see the particles in all dimensions, each block actually makes different particles in each dimension. This could cause massive amounts of lag when in areas with lots of portals and lots of particles. Also, you're welcome for gathering as much data on this bug as I reasonably could, and then putting it into this format. Should make it easier to read.

**Comment by froyo4u** [comment]
This only happens because the particle fix currently does not work when OptiFine is present, so therefore is disabled.

**Comment by detective-wraith** [comment]
Still needs to be fixed

**Comment by froyo4u** [comment]
To be fair, you are given a warning in chat

**Comment by detective-wraith** [comment]
What do you mean?

**Comment by froyo4u** [comment]
You get a warning in chat saying there may be portal rendering artifacts because optifine is present, if you aren't using one of the newest versions(including preview versions) you will not see that message.

**Comment by detective-wraith** [comment]
I suppose that is fair, but like I said, it's still a bug that will eventually need to be fixed. Might as well report it now rather than later.

**Comment by qouteall** [comment]
Should be fixed
