### ISSUE TITLE
Map items appearing grey with grids of dots

### ISSUE THREAD

**Issue by Dooglesmile** [qouteall/ImmersivePortalsMod#599]
Just installed Fabric 0.6.1.51 and Immersive Portals 0.78-mc1.16.5 to see how they work.

While using stacked dimensions, making a map, the image comes out just grey with a grid of coloured dots.
This happens in all dimensions, though in The End, it does first map the End islands before over writing with the grey and dots.

No other mods installed other than fabric api 0.30.3.

**Comment by qouteall** [comment]
What do you mean by "just grey with a grid of coloured dots"? Show a screenshot

**Comment by qouteall** [comment]
I cannot reproduce this issue

**Comment by Dooglesmile** [comment]
> What do you mean by "just grey with a grid of coloured dots"? Show a screenshot

Here is a screenshot of the maps how they turn out...

https://imgur.com/a/Xqy2HHI

It does the same thing in the Overworld, The Void world layered on top, and The End on top of the Void world.

I just tested the same seed but without the stacking dimensions, and the map rendered correctly.

[Video clip of what is happening](https://youtu.be/rGjHShqbS7Q)

**Comment by qouteall** [comment]
Close because outdated.
