### ISSUE TITLE
Incompatible with Fabric Carpet

### ISSUE THREAD

**Issue by briansemrau** [qouteall/ImmersivePortalsMod#6]
This mod has a conflicting mixin into PortalBlock. Briefly analyzing your code, I believe this could be solved by replacing the following method in MixinPortalBlock:
```java
@Overwrite
public boolean createPortalAt(...) {
    return false;
}
```
with:
```java
@Inject(method = "createPortalAt", at = @At("HEAD"), cancellable = true)
public boolean createPortalAt(...,k CallbackInfoReturnable<Boolean> cir) {
    cir.setReturnValue(false);
}
```

In your mod I see several instances of using @Overwrite. This is bound to cause compatibility issues with mods in the future and generally not recommended. The above replacement should allow the mixins to properly load, at a minimum.

Using version 0.2.
Log: https://paste.ee/p/zwu3x

**Comment by qouteall** [comment]
Thank for your help. I removed this overwrite.

**Comment by Decrepitdoors** [comment]
I'm playing with carpet and immersive portals in the new snapshots (20w16a) and they seem to be conflicting again

`[Warn] @ModifyConstant conflict. Skipping immersive_portals.mixins_ma.json:block_manipulation/MixinServerPlayerInteractionManager->@ModifyConstant::modifyBreakBlockRangeSquare(D)D with priority 1000, already redirected by carpet.mixins.json:ServerPlayerInteractionManager_antiCheatMixin->@ModifyConstant::addDistance(D)D with priority 69420.`

Not sure which mod would need to be changed so I've made an issue on both.
