### ISSUE TITLE
Visual Artifact/Glitch (Zooming)

### ISSUE THREAD

**Issue by Galaxtone** [qouteall/ImmersivePortalsMod#60]
There appears to be some sort of invisible hitbox which when entered causes a visual zoom distortion to occur.

https://dl.dropboxusercontent.com/s/s093b8alr8d7f7n/Immersive%20Portals%20Glitch.mp4

Minecraft 1.15.1, `immersive-portals-0.8(for mc 1.15 with fabric).jar`

**Comment by qouteall** [comment]
How to reproduce it? Upload the world file?

**Comment by qouteall** [comment]
probably fixed

**Comment by qouteall** [comment]
check 0.9 version
