### ISSUE TITLE
Not rendering half of world when moving through portal

### ISSUE THREAD

**Issue by Serphorus1** [qouteall/ImmersivePortalsMod#600]
whenever i go through a portal, it only renders on half of the current world and all of the other world.
![2021-02-23_21 29 08](https://user-images.githubusercontent.com/79512821/108831703-9bce0a00-761e-11eb-9102-8be4e62e2d2e.png)

**Comment by Serphorus1** [comment]
i'm using sodium oneshot 3.0 (I.P. fork), integrated gpu (powerful enough), no fps drops.
this effect stops after i reset the rendering engine but as soon as i pass through a portal, it happens again and does not stop after i go back through.

**Comment by qouteall** [comment]
Is the missing region aligned to chunk border

**Comment by TrentsPC** [comment]
I'm in the same situation as them, it is aligned to the block you're standing on, though can be offset by a few blocks if you go through one portal and out another nearby

The problem only occurs when using the sodium immersive portals fork (sodium-fabric-mc1.16.4-0.1.1-ipc2.jar)
