### ISSUE TITLE
Portal Reflections?

### ISSUE THREAD

**Issue by yeldarbnivot** [qouteall/ImmersivePortalsMod#603]
This mod is great. I love it. Apart from lithe shads of light not transferring through them (witch is pretty simple to combat), for some reason, only for one set of two portals, when I enter the first one, I can see myself from the second one. Not sure what is happening, as I am making a non-Euclidean tunnel (I need two portals)

**Comment by K0-RR** [comment]
Where is the issue? Have you ever played the Portal game? Your body is being transferred in real-time to another location (second portal). There is a transition moment when only a part of your body is transferred and the rest is still in the old location. What you see is the part that is already teleported. That being said I'm not entirely it's not just a bug but for me, it seems like a feature and it's logical to work like this.

**Comment by qouteall** [comment]
Does this issue happen without other mods?

**Comment by yeldarbnivot** [comment]
Yes. Am I able to send a screenshot/video somehow?

**Comment by qouteall** [comment]
yes

**Comment by qouteall** [comment]
Close because outdated.
