### ISSUE TITLE
Wrong teleport + other

### ISSUE THREAD

**Issue by omarr321** [qouteall/ImmersivePortalsMod#61]
# Wrong teleport + other

## First the other:
The portal does not show up in mirrors. I do not know if this is internally or not.

## Second:
Sometimes when you move the thought the portals fast enough and move into a new one it does not put you through it and instead skips it.

## Update:
Also, I found if you try to light the same portal multiple times it will create multiple all linked to the same base one which causes problems when trying to go through them. I found that I could do it with a mirror present and only when a mirror is present.

**Comment by qouteall** [comment]
If a portal is nearby then the loading indicator will vanish then the player thinks that something is wrong and constantly try to light the portal then the bug occurred.

**Comment by qouteall** [comment]
About mirror rendering https://github.com/qouteall/ImmersivePortalsModForForge/issues/14

**Comment by qouteall** [comment]
check 0.9 version, the portal generation issue should be fixed

**Comment by omarr321** [comment]
I am using the fabric version of the mod.

**Comment by qouteall** [comment]
it's being fixed in 0.9 version in fabric 1.15

**Comment by omarr321** [comment]
> If a portal is nearby then the loading indicator will vanish then the player thinks that something is wrong and constantly try to light the portal then the bug occurred.

I found tho that if the mirror is not there and the loading thing shows and you try multiple times. it does not create multiple portals.
