### ISSUE TITLE
Allow arbitrarily sized end portals

### ISSUE THREAD

**Issue by muzikbike** [qouteall/ImmersivePortalsMod#610]
![2021-02-25_19 18 34](https://user-images.githubusercontent.com/52297970/109205475-8b449d80-779e-11eb-8046-5fc45b1de160.png)

**Comment by qouteall** [comment]
You can set the portal width height using commands https://qouteall.fun/immptl/wiki/Portal-Attributes#command-examples
I don't think that it's a feature worth implementing
