### ISSUE TITLE
Player model can intersect mirrors, causing disturbing effects in first person

### ISSUE THREAD

**Issue by muzikbike** [qouteall/ImmersivePortalsMod#613]
![2021-02-25_18 44 01](https://user-images.githubusercontent.com/52297970/109355489-2e68e600-7877-11eb-9065-10e0bab1c9c7.png)
![2021-02-26_21 09 24](https://user-images.githubusercontent.com/52297970/109355492-2f017c80-7877-11eb-9d22-609c9a21793f.png)
![2021-02-26_21 09 32](https://user-images.githubusercontent.com/52297970/109355493-2f9a1300-7877-11eb-98c6-f971149f0061.png)

**Comment by qouteall** [comment]
This is now fixed by not displaying player when touching the mirror.
