### ISSUE TITLE
Not working properly, It says something about Imm_ptl_core and idk what that even means

### ISSUE THREAD

**Issue by FIREBALL-Z42** [qouteall/ImmersivePortalsMod#617]
So basically It just doesn't work.
[crash-2021-02-27_12.30.31-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/6055004/crash-2021-02-27_12.30.31-client.txt)

**Comment by froyo4u** [comment]
you are using sodium, sodium is not compatible

**Comment by froyo4u** [comment]
qouteall does however have a version that is compatible

**Comment by froyo4u** [comment]
[https://github.com/qouteall/sodium-fabric](url)

**Comment by FIREBALL-Z42** [comment]
ok thanks
