### ISSUE TITLE
[1.15.2] Weather Bug

### ISSUE THREAD

**Issue by Diamondman121314** [qouteall/ImmersivePortalsMod#62]
When leaving the Nether, it appears to be raining, in which it actually isn't. After doing /weather clear, it continues to rain. After actually setting it to rain (/weather rain) then back, it went back to normal. Using Immersive Portals 0.8.

**Comment by qouteall** [comment]
check 0.9 version

**Comment by qouteall** [comment]
This issue was fixed in forge version. I synced it to fabric version easily.
