### ISSUE TITLE
1x1 portals

### ISSUE THREAD

**Issue by detective-wraith** [qouteall/ImmersivePortalsMod#622]
Description: You can go through vertical 1x1 portals
///
Steps to reproduce:
1. Make a 1 block wide by 1 block wide portal. Make sure it's horizontal. 
2. Break the frame around it without breaking the portal. 
3. Try walking through the portal while its at eye level
///
Results: You pass through the portal when its at eye level
Expected Result: You don't pass through the portal because it is too small

**Comment by qouteall** [comment]
If I forbid entering too small portals, then the player cannot enter the scale box from the near edge position.
To avoid that, you can simply put frame blocks around the portal

**Comment by GamyGamer** [comment]
Also it is possible to pass 1x1 portals normally while in prone state (for example using trapdoors)

**Comment by detective-wraith** [comment]
Well quoteall, I don't know what to say to that, but it is still a bug.

**Comment by froyo4u** [comment]
> 
> 
> Well quoteall, I don't know what to say to that, but it is still a bug.

it's only a bug the way you're thinking about it

**Comment by detective-wraith** [comment]
Its a bug. If you went through a portal like this irl, you would bump into a wall.

**Comment by froyo4u** [comment]
since when do we have portals IRL, and why are we comparing Minecraft to real life

**Comment by detective-wraith** [comment]
Well, we don't have portals IRL, but you know that's what would happen. Also, I'm comparing IP to real life because, in my opinion, the goal of games is to be immersive and fun, and weird portal physics ruins the immersion. Physics still applies as far as portal physics are concerned.

**Comment by froyo4u** [comment]
ok

**Comment by detective-wraith** [comment]
And I can guarantee that IP's goal is immersion, because... It's literally called Immersive portals.

**Comment by qouteall** [comment]
Normally portals should have frame blocks to wrap it so it's not a serious issue.
If I fix this, then player can pass through scale box without entering the scale box which ruins scale box effect so I won't fix it
