### ISSUE TITLE
Migrating from Forge to Fabric broke nether portals created with Immersive Portal Mod

### ISSUE THREAD

**Issue by Zxurian** [qouteall/ImmersivePortalsMod#623]
Verisons in use
Fabric: `fabric-api-0.31.0+1.16.jar`
Immersive Portals: `immersive-portals-0.80-mc1.16.5-fabric.jar`

I'm trying to transfer a world from Forge based to Fabric based, and one of the mods in use are Immersive Portals. The world folder is copied to the new server folder, and running the new Fabric server starts without issues.

Portals created manually from point to point in the overworld are the same, however any nether portal created via natural generation _after_ Immersive Portals was enabled on the Forge server (ie, should be an immersive portal now to the nether), do not appear within the world. I've tested two different portals that were previously connected to the Nether, and neither one shows up on the Fabric world.

Any ideas on what to look at to make sure all existing portals stay when coping world from Forge to Fabric server?

**Comment by qouteall** [comment]
I guess that it's because the portal placeholder blocks vanished. The world saving saves block using integer id. Fabric and Forge both store the record of every integer block id for block name but Fabric does not recognize Forge's record and give portal placeholder a different integer id so that portal placeholder blocks vanished. If the placeholder block vanishes, the nether portal is deemed broken and will vanish.

**Comment by Zxurian** [comment]
meh... that's gonna be a pain. As a workaround, if Fabric can't read Forge's information for cross-realm portals, could we just re-light the nether portals and reconnect them?

If Fabric can't read Forge's IDs and just removes them from the database, then that would be a clean way to recreate them. I'm just concerned about having a bunch of garbage data in the portal database.

Also noticed the following log entries when I restated the server
```
[14:15:27] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:15:27] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:15:27] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:15:27] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:15:27] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
```

not sure if that has to do with fabric vs forge IDs or not.

**Comment by qouteall** [comment]
It's theoretically possible to migrate the block id. You can use nbt editor to check `level.dat`.

> could we just re-light the nether portals and reconnect them?

yes

The teleport command ambiguity is vanilla's issue.

**Comment by qouteall** [comment]
Close because outdated.
