### ISSUE TITLE
When going between global portals, players sometimes become invisible

### ISSUE THREAD

**Issue by InvaderHawk** [qouteall/ImmersivePortalsMod#626]
I believe this is caused by the game thinking that you're still in the other chunk, but I'm not sure.

**Comment by qouteall** [comment]
Showing a video could help

**Comment by qouteall** [comment]
I cannot reproduce this issue

**Comment by Wolfstar1010** [comment]
I'm having the same issue on a server with friends. We have around 100 mods in total and I believe it could be a mod conflict but I'm not sure. It happens at times when passing between dimensions or even rarely when just looking at a portal. It's not consistent and I can't currently reproduce it consistently. But on our end the player becomes invisible and/or all entities disappear to the player.

**Comment by Darkwolf6180** [comment]
Issue happens with me as well;
~4-6 player server and it's only started happening recently.
Approximately 89 mods total, can append a full mod list and crash report if needed.
The modpack is on curseforge, Tomatoland 3.

It occurs at random, looking at or going through portals.

**Comment by qouteall** [comment]
Close because outdated.
