### ISSUE TITLE
Lighting issue with portals

### ISSUE THREAD

**Issue by KewlDude2005** [qouteall/ImmersivePortalsMod#633]
![2021-03-12 (1)](https://user-images.githubusercontent.com/71187763/111014680-eb2c6e00-8372-11eb-9d4f-2a224339da0b.png)

I'm not sure if this has been fixed, or if this issue is fixable, but the lighting is inconsistent through portals.

**Comment by qouteall** [comment]
Minecraft lights different facings with different lighting. You can choose darker block or lighter blocks to make the lighting less noticable.
