### ISSUE TITLE
Portals Won't Link

### ISSUE THREAD

**Issue by BlackAcidZombie** [qouteall/ImmersivePortalsMod#637]
When I make two portal frames that are not in the same chunk and try to link them I end up getting a third half created portal that the one I tried to activate links itself to. I can't get portal to connect unless they are located in the same chunk.

I am using the most recent version, 1.16.5, with Fabric.

![2021-03-19_16 13 50](https://user-images.githubusercontent.com/80985340/111837447-44922100-88ce-11eb-9684-cc0ea1d1c81c.png)

EDIT: I did a little experimenting and I found that it doesn't have to be in the same chunk, but there is a pretty strict distance limit. You can actually see where the portal it was supposed to link to is located in the background.

![2021-03-19_16 18 50](https://user-images.githubusercontent.com/80985340/111837951-047f6e00-88cf-11eb-9ebc-3fa67d137c68.png)

**Comment by froyo4u** [comment]
try turning up your `Nether Portal Searching Range` in the Server-side configuration of Immersive Portals

**Comment by BlackAcidZombie** [comment]
> try turning up your `Nether Portal Searching Range` in the Server-side configuration of Immersive Portals

How do I do that?

**Comment by froyo4u** [comment]
Several ways, check this out: [Immersive Portals Wiki](https://qouteall.fun/immptl/wiki/Config-Options)

**Comment by BlackAcidZombie** [comment]
> Several ways, check this out: [Immersive Portals Wiki](https://qouteall.fun/immptl/wiki/Config-Options)

Thank you!

**Comment by BlackAcidZombie** [comment]
Well, it would help, but I don't  know how to get to the config file and it doesn't tell me how...

**Comment by froyo4u** [comment]
if you are on Windows hit `Windows Key + R` and type in `%appdata%\.minecraft\config` and search for the config file that says something like immersive portals fabric

**Comment by BlackAcidZombie** [comment]
Yeah, I actually deleted the reply since I figured out what it meant. But, I increased the distance and it didn't help. I may have used too large a value so I will try something smaller and see if it works.

**Comment by BlackAcidZombie** [comment]
The first time I tried to change it, the change wasn't saved. I tried again and it did save this time. I kept it as a 3 digit value just in case but this did not help.

**Comment by squendan998** [comment]
that happend to me

**Comment by qouteall** [comment]
@squendan998 Explain it in detail

**Comment by qouteall** [comment]
Close because outdated.
