### ISSUE TITLE
Maintaining velocity through portals oriented differently?

### ISSUE THREAD

**Issue by Alurium** [qouteall/ImmersivePortalsMod#641]
Not really an issue per se; just wondering if it would be at all feasible to implement a conservation-of-momentum system similar to how the portals in Portal work?

**Comment by qouteall** [comment]
The momentum should be conserved. On which occasion does the momentum not conserved?

**Comment by Fusion-Flux** [comment]
any instance where the player exits a portal at a different angle then when they go in the only exceptions to this rule are portals on the celling / ground this issue is not noticeable at low speeds and you really need to focus to see it happening but at higher speeds its extremely noticeable and jarring.

**Comment by froyo4u** [comment]
I can confirm

**Comment by Alurium** [comment]
> The momentum should be conserved. On which occasion does the momentum not conserved?

Try falling into a portal facing up, with the exit portal also facing up. Instead of being launched upwards into the air out of the exit portal, you'll come to an abrupt halt between portals, as you're still moving objectively downward. 

If relative velocity was to be maintained, you would need to come out of the exit portal moving downward _relative_ to the entry portal, which would now be _up_.

**Comment by Fusion-Flux** [comment]
> > The momentum should be conserved. On which occasion does the momentum not conserved?
> 
> Try falling into a portal facing up, with the exit portal also facing up. Instead of being launched upwards into the air out of the exit portal, you'll come to an abrupt halt between portals, as you're still moving objectively downward.
> 
> If relative velocity was to be maintained, you would need to come out of the exit portal moving downward _relative_ to the entry portal, which would now be _up_.

oh this issue is a collision issue in IP

**Comment by qouteall** [comment]
The collision system is being improved. It's probably fixed.
