### ISSUE TITLE
Incompatible with both Dropz and Cavebiomes together. 1.16.5.

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#643]
https://www.curseforge.com/minecraft/mc-mods/dropz
https://www.curseforge.com/minecraft/mc-mods/cave-biomes

When using all three mods together, nothing else (Except rayon of course for dropz {Rayon itself doesn't cause the crash}, and also the fabric API), there is a chance that the world crashes after a minute.

The seeds I used are 2630427862233096394 / 998660511143954696 / and -4266022823465279949 

When deleting a world and making a new world with those seeds (Sometimes you have to do it multiple times, go between them, and also exit minecraft and load again), the game crashes. Most of the time, typing in chat before the world loads can fix it, or even just loading into the world several times may get it to fix itself.

I am using Multi MC, I disabled all other mods, and I also cleared out the config folder.
[hs_err_pid1076.log](https://github.com/qouteall/ImmersivePortalsMod/files/6178372/hs_err_pid1076.log)

**Comment by qouteall** [comment]
The JVM crashes inside rayon's physics calculation code in its physics thread
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 23306  com.jme3.bullet.PhysicsSpace.stepSimulation(JFIF)V (0 bytes) @ 0x000001f31a8ed650 [0x000001f31a8ed600+0x50]
J 25294 C2 dev.lazurite.rayon.impl.bullet.thread.PhysicsThread$$Lambda$3316.accept(Ljava/lang/Object;)V (8 bytes) @ 0x000001f31acda0a4 [0x000001f31acd9be0+0x4c4]
J 27614 C2 java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Ljava/util/function/Consumer;)V (63 bytes) @ 0x000001f31b8f29d4 [0x000001f31b8f2700+0x2d4]
J 28952% C2 dev.lazurite.rayon.impl.bullet.thread.PhysicsThread.run()V (89 bytes) @ 0x000001f319c90730 [0x000001f319c90420+0x310]
v  ~StubRoutines::call_stub
```

**Comment by qouteall** [comment]
Rayon has one-client-world assumption (https://github.com/LazuriteMC/Rayon/blob/490196aa45b1eae9f214f2cac5c019b20fdc9781/rayon-core/src/main/java/dev/lazurite/rayon/core/impl/RayonCoreClient.java#L59) but IP maintains multiple client worlds at the same time. This issue cannot be solved on IP's side

**Comment by ghost** [comment]
> 
> 
> Rayon has one-client-world assumption (https://github.com/LazuriteMC/Rayon/blob/490196aa45b1eae9f214f2cac5c019b20fdc9781/rayon-core/src/main/java/dev/lazurite/rayon/core/impl/RayonCoreClient.java#L59) but IP maintains multiple client worlds at the same time. This issue cannot be solved on IP's side

Oh sorry, my bad.
