### ISSUE TITLE
Lighting issues with linked portals facing different directions

### ISSUE THREAD

**Issue by tobrick** [qouteall/ImmersivePortalsMod#644]
![Immersive Portals bug](https://user-images.githubusercontent.com/81130752/111933792-2f63f080-8a8e-11eb-9b9b-327e783a190a.png)

**Comment by froyo4u** [comment]
This is not an issue, it's how lighting in Minecraft works and how portals work, light does not go through portals

**Comment by qouteall** [comment]
Minecraft renders different light on different faces, this is normal behavior. You can use a darker block or use different materials to make it less visible.
