### ISSUE TITLE
Render issues

### ISSUE THREAD

**Issue by GavinKacprowicz** [qouteall/ImmersivePortalsMod#645]
I have tried fabric and forge, and both versions of the mod are rendering the portal red in the nether and blue in the overworld. Is there something I'm doing wrong? Could it be because I'm using a third party launcher?

**Comment by qouteall** [comment]
Maybe your videocard does not support some GL features. Try using command `/immersive_portals_debug front_clipping_disable`

**Comment by GavinKacprowicz** [comment]
> Maybe your videocard does not support some GL features. Try using command `/immersive_portals_debug front_clipping_disable` 

This didn't seem to help. Is there anything else I can do?

**Comment by qouteall** [comment]
Probably nothing. The critical GL feature is not supported there and the portal cannot be rendered.

**Comment by GavinKacprowicz** [comment]
> Probably nothing. The critical GL feature is not supported there and the portal cannot be rendered.

If I use a launcher that uses a different renderer could that help? One such as zinc or osmesa?

**Comment by qouteall** [comment]
I don't know
