### ISSUE TITLE
Incompatible with Iris

### ISSUE THREAD

**Issue by machinesmith42** [qouteall/ImmersivePortalsMod#648]
https://paste.gg/p/anonymous/6eecb2fc634b43a787eec9c42d4af4a0

**Comment by machinesmith42** [comment]
what causes this issue @qouteall

**Comment by Razboy20** [comment]
I think there is a issue within the Iris GitHub currently referencing this; I remember looking it up earlier as I had this same issue previously.

**Comment by machinesmith42** [comment]
https://github.com/IrisShaders/Iris/issues/190

**Comment by SirPytan** [comment]
I don't have a crash when using this mod with Iris(+Sodium) but I have the issue that my FPS drops to 1 Frame per second, when using this mod and  looking at the portal.

**Comment by qouteall** [comment]
@SirPytan use this https://github.com/qouteall/Iris/releases/tag/ipc1.1.1_1

**Comment by DragonEggBedrockBreaking** [comment]
Th pr was merged 31 minutes after you posted this command, iris development versions are fully compatible with immersive portals.

**Comment by SirPytan** [comment]
I am using the latest Version from HyperCubeMC:
https://github.com/HyperCubeMC/Iris/actions/runs/1178473993
https://github.com/HyperCubeMC/sodium-fabric/actions/runs/1178189673

Just download the Actions folder unzip it and use the .jar (without source, dev and so on) and it works.
I know have more stable FPS with Immersive Portals mod.
