### ISSUE TITLE
Chunks disapearing with Framed

### ISSUE THREAD

**Issue by nullified33** [qouteall/ImmersivePortalsMod#651]
![image](https://user-images.githubusercontent.com/70713233/112664849-a7784080-8e17-11eb-8c73-5f33a3844af4.png)

**Comment by nullified33** [comment]
![image](https://user-images.githubusercontent.com/70713233/112665001-d0003a80-8e17-11eb-9778-702d429026f0.png)

**Comment by qouteall** [comment]
Are you using other rendering related mods?

**Comment by nullified33** [comment]
> Are you using other rendering related mods?

sodium and framed

**Comment by nullified33** [comment]
> > Are you using other rendering related mods?
> 
> sodium and framed

https://github.com/alex5nader/Framed

**Comment by qouteall** [comment]
Does this issue happen without sodium?

**Comment by nullified33** [comment]
> Does this issue happen without sodium?

no, it happens with framed

**Comment by nullified33** [comment]
> > Does this issue happen without sodium?
> 
> no, it happens with framed

like when you go up blocks dissapear

**Comment by nullified33** [comment]
> > > Does this issue happen without sodium?
> > 
> > 
> > no, it happens with framed
> 
> like when you go up blocks dissapear

apparently Framed depends on Fabric API, LibGui, JMX, and FREX

**Comment by nullified33** [comment]
> > > > Does this issue happen without sodium?
> > > 
> > > 
> > > no, it happens with framed
> > 
> > 
> > like when you go up blocks dissapear
> 
> apparently Framed depends on Fabric API, LibGui, JMX, and FREX

Does immersive portals use any of these?

**Comment by froyo4u** [comment]
it uses Fabric API but like almost every mod does

**Comment by nullified33** [comment]
> it uses Fabric API but like almost every mod does

I dont mean fabric api

**Comment by nullified33** [comment]
> > it uses Fabric API but like almost every mod does
> 
> I dont mean fabric api

I misworded

**Comment by nullified33** [comment]
> it uses Fabric API but like almost every mod does

I meant LibGui, JMX, and FREX

**Comment by nullified33** [comment]
I updated my drivers and the bug seems to have gone
