### ISSUE TITLE
Far Audio isn't rendered at all

### ISSUE THREAD

**Issue by SleepyCardia** [qouteall/ImmersivePortalsMod#654]
I was using fabric for this one, I first noticed it when i couldn't hear ghasts shooting at me or distant fireworks/noteblocks
I am 100% its immersive portals I tested it.

https://user-images.githubusercontent.com/81494543/112737936-e0c7c200-8f77-11eb-8ea7-4136576139b0.mp4

**Comment by froyo4u** [comment]
what version are you using?

**Comment by SleepyCardia** [comment]
the latest 1.16.5 one

immersive-portals-0.88-mc1.16.5-fabric.jar



> what version are you using?

**Comment by froyo4u** [comment]
weird

**Comment by qouteall** [comment]
It's probably related to cross-portal audio

**Comment by qouteall** [comment]
I set that if the sound is more than 30 blocks far from player then handle it as cross portal sound. Now I changed 30 to 50

**Comment by SleepyCardia** [comment]
> I set that if the sound is more than 30 blocks far from player then handle it as cross portal sound. Now I changed 30 to 50

I mean fireworks can be heard from up to 64 blocks

**Comment by qouteall** [comment]
Changed to 64

**Comment by qouteall** [comment]
Probably fixed in this https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.89-1.16

**Comment by SleepyCardia** [comment]
Imma test it.

**Comment by SleepyCardia** [comment]
Yeah its fixed.
