### ISSUE TITLE
Unique "barrier block" for each dimension stack

### ISSUE THREAD

**Issue by CalaMariGold** [qouteall/ImmersivePortalsMod#656]
**Is your feature request related to a problem? Please describe.**
Currently, the only barrier for every dimension is obsidian. I'd love for this to be configurable for progression-based modpacks with multiple dimensions.

**Describe the solution you'd like**
Add a config option (see my previous issue about dim stack config) for each dimension that determines what block should be at the bottom of that dimension.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by qouteall** [comment]
Already implemented.
