### ISSUE TITLE
Config option to enable dimension stack

### ISSUE THREAD

**Issue by CalaMariGold** [qouteall/ImmersivePortalsMod#657]
**Is your feature request related to a problem? Please describe.**
I'd like to make a modpack where dimension stack is enabled by default with specific dimensions in it. Currently, if I make a modpack based around dimension stack, the player would have to manually add all the dimensions.

**Describe the solution you'd like**
A config option to enable dimension stack and all the dimensions included.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by CalaMariGold** [comment]
As a temporary alternative, is there a file that is created in the world folder that creates the dimension stack? I would be able to copy those file(s) into each new world using the CopyPaste mod.

**Comment by qouteall** [comment]
no

**Comment by CalaMariGold** [comment]
@qouteall Heya, I know you probably are a little busy, but is it possible that I can have a confirmation that this will be worked on? If so, do you have a time frame for release?

Sorry to bother, thank you!

**Comment by qouteall** [comment]
Unfortunately, it's in low priority

**Comment by qouteall** [comment]
This is being reconsidered now.

**Comment by qouteall** [comment]
Already implemented
