### ISSUE TITLE
Obsidian farm breaks

### ISSUE THREAD

**Issue by JustinPlayzz** [qouteall/ImmersivePortalsMod#659]
When you throw a item into end portal the obsidian platform does not regenerate.

**Comment by qouteall** [comment]
I remember that in old vanilla versions only player can trigger obsidian frame generation

**Comment by qouteall** [comment]
I changed it so that every entity crossing end portal can trigger obsidian platform generation

**Comment by JustinPlayzz** [comment]
That would be great.
