### ISSUE TITLE
Fabric crashes even without Immersive Portals

### ISSUE THREAD

**Issue by MoltenxCrystal** [qouteall/ImmersivePortalsMod#661]
I uninstalled immersive portals bc it was crashing my game with fabric and now its crashing without it, is there a way to fix this? Using the latest version of fabric btw.

**Comment by MoltenxCrystal** [comment]
Here's a crash log 
[crash-2021-04-03_10.14.49-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/6252683/crash-2021-04-03_10.14.49-client.txt)

**Comment by K0-RR** [comment]
[Just a user here] From the log I can see you **are** using IP and Sodium together, seems like you didn't read IP description "This mod is currently incompatible with the officially released version of sodium. However, there is [a version of sodium that's compatible with this mod](https://github.com/qouteall/sodium-fabric/releases)."

Btw @qouteall there is a little misspelling in the description - "offically"

**Comment by MoltenxCrystal** [comment]
> [Just a user here] From the log I can see you **are** using IP and Sodium together, seems like you didn't read IP description "This mod is currently incompatible with the officially released version of sodium. However, there is [a version of sodium that's compatible with this mod](https://github.com/qouteall/sodium-fabric/releases)."
> 
> Btw @qouteall there is a little misspelling in the description - "offically"
![Capture](https://user-images.githubusercontent.com/69010619/113511017-af2c9900-952b-11eb-8f28-e9ff24a2fe47.PNG)
???
Its literally not there I removed it bc it conflicts with sodium i knew that going in. 
 Idk why it gave me that error even though it wasn't in the mod folder,

**Comment by K0-RR** [comment]
Then you shared the wrong log file (the one from where you had IP installed). If you want IP with Sodium then use the fork. You can send a proper log if it's crashing without IP but then it's not IP fault.

**Comment by MoltenxCrystal** [comment]
> Then you shared the wrong log file (the one from where you had IP installed). If you want IP with Sodium then use the fork. You can send a proper log if it's crashing without IP but then it's not IP fault.

[crash-2021-04-04_10.22.07-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/6254715/crash-2021-04-04_10.22.07-client.txt)
try this
its the latest, i updated the wrong one lol
So get this you saw the mod wasn't in the mods folder right? now sodium is gone and the game is working idk whats going on. IP isn't there yet its causing sodium to conflict with it and crash the game.
And its showing in mod menu even though the mod isn't there
![image](https://user-images.githubusercontent.com/69010619/113512575-45b08880-9533-11eb-9968-e4e817749bc7.png)

So either A: it doesn't fully remove itself when I delete it, or b it forces itself to stay there.
The question is how do I delete the core file because that's whats causing it to crash.
Let's see if deleting the modmenu config file helps at all, nope still there lol

**Comment by qouteall** [comment]
@RDKRACZ Thanks for informing the typo. Typo fixed.

**Comment by qouteall** [comment]
A mod that you use contains Immersive Portals Core so you need the fork of sodium even without Immersive Portals

**Comment by froyo4u** [comment]
My Portal Gun mod contains Immersive Portals

**Comment by qouteall** [comment]
Close because outdated.
