### ISSUE TITLE
SEUS Renewed is giving a weird visual glitch in 0.88

### ISSUE THREAD

**Issue by Prodabic** [qouteall/ImmersivePortalsMod#664]
I don't know how to fix this and why it's happening.
First pic is me not looking at the portal and second pic is me looking at the portal.

![2021-04-07_21 03 34](https://user-images.githubusercontent.com/26947025/113957514-f85b4200-97e4-11eb-81a3-e89027ab3ee4.png)
![2021-04-07_21 03 43](https://user-images.githubusercontent.com/26947025/113957550-0c9f3f00-97e5-11eb-9b9f-47ab1754982b.png)

**Comment by qouteall** [comment]
Go to the shader's option, turn off motion blur
