### ISSUE TITLE
tag update doesn't work with /execute store result (I might be doing it wrong)

### ISSUE THREAD

**Issue by Pinty220** [qouteall/ImmersivePortalsMod#665]
I want to control where the portal goes with command blocks, and input a scoreboard into this so I can type in coordinates (making a tardis). I am an armature at using these mechanics, but i think this is a bug. When I try to edit the tags using the following command: (with coords being a scoreboard value)

/execute as @e[type=immersive_portals:portal,sort=nearest,limit=1] store result entity @s destinationY double 1 run scoreboard players get @p coords

It updates the tag as shown by /data get, but the actual portal does not change where it leads. 
I tested this out on a new world and made sure there was only 1 portal entity. 

When I use the function set_portal_nbt it works but I do not know how to input scoreboard values it works. 
/execute as @e[type=immersive_portals:portal,limit=1] run portal set_portal_nbt {destinationY:10}   (works)
I also don't want to use armor stands because I want to portal to places that arn't chunkloaded

**Comment by qouteall** [comment]
Because that the change was not synced to the client side. You can use `/portal set_portal_nbt {whatever...}` to make it synchronize
