### ISSUE TITLE
Crashing game when scaling player

### ISSUE THREAD

**Issue by Woomulous** [qouteall/ImmersivePortalsMod#666]
Whenever I try to go into a portal that changes my size, the game crashes. I think it might be something to do with pehkui, which I do in fact have in the mods folder, but I don't know how to fix it.

**Comment by qouteall** [comment]
Post the crash report

**Comment by qouteall** [comment]
Seems that it's due to pehkui has an incompatible update

**Comment by qouteall** [comment]
Does it crash with 0.90? https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.90-1.16
