### ISSUE TITLE
Portals doesn't scale down player properly

### ISSUE THREAD

**Issue by CubeMath** [qouteall/ImmersivePortalsMod#667]
I have two huge portals (8x16 and 16x32).

The problem:
If I have scale **16** and go through the bigger portal to scale me down,
then it looks like I am scaled down to **8**, but `/scale get` still returns **16**.
If I go through the bigger portal again, I get scaled to **8** again with `/scale get` **8**.
If I go through the smaller portal instead to scale me back up again, my scale would be **32** (which would cause an Out of scale warning).

What I expected:
When I go through the bigger portal with scale **16**, then I should have scale **8** with `/scale get` **8**.

Tested with:
fabric-api-0.32.5+1.16.jar
immersive-portals-0.88-mc1.16.5-fabric.jar
Pehkui-1.10.0+21w14a.jar

**Comment by ImSpaceLover** [comment]
It may be a Pehkui's issue, not Immersive Portals' one

**Comment by qouteall** [comment]
Are you playing multiplayer? This could happen if the client has pehkui but server doesn't.

**Comment by CubeMath** [comment]
No, I played on singleplayer.

**Comment by qouteall** [comment]
Cannot reproduce with the latest IP and pehkui
