### ISSUE TITLE
Fabric World generation freezes everytime i load Immersive Portals

### ISSUE THREAD

**Issue by cobalt-ink-12** [qouteall/ImmersivePortalsMod#668]
Everytime I load Immersive protals with a single player world, it freezes.

**Comment by K0-RR** [comment]
You should post a log. Do you have Sodium installed? Any other mods?

**Comment by cobalt-ink-12** [comment]
no i do not have any other mods installed.
and its kind of weird, it doesn't properly crash, it just freezes infinitely and says "not responding" i should have elaborated on that.

**Comment by qouteall** [comment]
Post the log, it's `logs/latest.log`

**Comment by Jmulder08** [comment]
same for me, i have the compatible sodium release installed (and mod menu) 
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/6373174/latest.log)
(this is what i get when creating a new world, when trying to load an existing one it just freezes without any error msgs)

**Comment by qouteall** [comment]
@Jmulder08 Your computer does not support OpenGL 1.3 which the sodium fork uses

**Comment by MoonlightSystem** [comment]
not sure if this is the same issue, but..
[latest.zip](https://github.com/qouteall/ImmersivePortalsMod/files/6389553/latest.zip)

It's a zip because log spam made the file too big

**Comment by qouteall** [comment]
@SkyladySelena It crashes inside MTapeMod: `at com.retrixe.mtape.MTapeMod.lambda$onInitializeClient$0(MTapeMod.java:48)`

**Comment by MoonlightSystem** [comment]
still freezes

[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/6394854/latest.log)

**Comment by qouteall** [comment]
@SkyladySelena 
```
[10:48:51] [main/WARN]: Program link log for sodium:chunk_shader: The fragment shader uses varying v_FadeInProgress, but previous shader does not write to it.
Out of resource error.
```
try uninstalling sodium

**Comment by qouteall** [comment]
Close because outdated.
