### ISSUE TITLE
both the forge and fabric versions don't load

### ISSUE THREAD

**Issue by obaid911** [qouteall/ImmersivePortalsMod#671]
<img width="425" alt="dfdfsfgshsyjgxjfsfgs" src="https://user-images.githubusercontent.com/82478557/114629264-539ba180-9cc9-11eb-8147-e7909162634a.PNG">

**Comment by froyo4u** [comment]
I know this sounds like a stupid question but are they actually in your mods folder lol

**Comment by obaid911** [comment]
> I know this sounds like a stupid question but are they actually in your mods folder lol

yes it is

**Comment by obaid911** [comment]
![Uploading dvdshsysgsgfgs.PNG…]()

**Comment by defsil** [comment]
Both Forge and Fabric versions certainly load for me (**immersive-portals-0.16-mc1.16.5-forge.jar** and **immersive-portals-0.90-mc1.16.5-fabric.jar**).

**Comment by creeperkidking** [comment]
it also wont load  for me either

**Comment by qouteall** [comment]
Close because outdated.

**Comment by creeperkidking** [comment]
lol
