### ISSUE TITLE
When i try and move the portals it doesnt work

### ISSUE THREAD

**Issue by Blakechez** [qouteall/ImmersivePortalsMod#678]
Video link
also its low quality because i had to reduce size

https://user-images.githubusercontent.com/71154884/115162464-43891680-a069-11eb-819d-2545c548c08c.mp4

**Comment by qouteall** [comment]
Use /portal remove_connected_portals before moving the portal
check https://qouteall.fun/immptl/wiki/Portal-Customization#1-nether-portal--4-portal-entities

**Comment by Blakechez** [comment]
i did it and it still didnt work

**Comment by Blakechez** [comment]
I dont wanna be rude but this is really pissing me off and im getting really frustrated

**Comment by qouteall** [comment]
If you want to edit the portal use the stick of "making the portal one way and one faced" first and then move the portal and then use the stick of "make portal bi way and bi faced"
