### ISSUE TITLE
Immersive Portals Crashing with Sodium/Phosphor/Lithum.

### ISSUE THREAD

**Issue by OmarUVX** [qouteall/ImmersivePortalsMod#679]
Why can't i start minecraft without sodium while it is the only optimizing tool in my mods folder ;-;

**Comment by froyo4u** [comment]
because it is not compatible with sodium lmao

**Comment by humematt190** [comment]
use this version of sodium that is compatible with immersive portals https://github.com/qouteall/sodium-fabric/releases/tag/ipc1165_2

**Comment by joshcangit** [comment]
In **1.17**, with these mods.
- Immersive Portals 0.20
- Sodium 0.3.0+build.5
- ~Indium 1.0.0+mc1.17.1~

~I think it's the Fabric Rendering API in **Indium** that allows compatibility between **Immersive Portals** and **Sodium**.~

~Hopefully when **Sodium** and **Indium** merge, this and a lot of other mods would be compatible.~

Sorry, my bad. 😅

**Comment by froyo4u** [comment]
That's not what makes it work lol. 1.17 sodium is compatible by itself
