### ISSUE TITLE
Command Sticks not available in creative inventory or /give

### ISSUE THREAD

**Issue by TheAwesome98-Real** [qouteall/ImmersivePortalsMod#682]

**Comment by qouteall** [comment]
The command stick is only in fabric version currently

**Comment by TheAwesome98-Real** [comment]
Sorry for not providing any information, I am using fabric, but if I scroll down the Miscellaneous tab only the portal helper is there, and the item ID is missing.

**Comment by qouteall** [comment]
Are you using the latest 1.16.5 version?

**Comment by TheAwesome98-Real** [comment]
Oh, sorry, I didn't realise I had an outdated version. I had 0.65, updating to 0.90 fixed it.

**Comment by froyo4u** [comment]
DAMN THAT'S OLD 😂

**Comment by TheAwesome98-Real** [comment]
I got the mod before all the "non euclidean" stuff happened (only for the actual portals) and only recently realised you can make your own portals
