### ISSUE TITLE
portals dissapeared entirely?

### ISSUE THREAD

**Issue by derpyboi123** [qouteall/ImmersivePortalsMod#686]
ok so i had a world and i ONLY SWITCHED THE END PORTALS to the little model and it did not work so i went in and did /kill @e and now my portals are gone

**Comment by saythrt** [comment]
portals are entities , they die with /kill , so be careful when trying to clear lag on your creations

**Comment by qouteall** [comment]
The scale box type end portal takes time to load and it does not work with low render distance(<5)

**Comment by qouteall** [comment]
Close because outdated.
