### ISSUE TITLE
"True" mirrors

### ISSUE THREAD

**Issue by muzikbike** [qouteall/ImmersivePortalsMod#689]
Basically, mirrors that also reflect the output view left to right such that the scene is how someone else would actually see it.

**Comment by ImSpaceLover** [comment]
From what I've read I think you're describing common mirrors that already exist in Immersive Portals. I advise you to close this issue.

**Comment by qouteall** [comment]
https://qouteall.fun/immptl/wiki/Portals#mirrors

**Comment by muzikbike** [comment]
? why was this closed? the linked page mentions nothing about what this proposes.

**Comment by qouteall** [comment]
This mod already have "true" mirrors. What do you mean by "reflect the output view left to right such that the scene is how someone else would actually see it"? Try `/portal set_portal_rotation_along y 180`

**Comment by muzikbike** [comment]
Like this: https://youtu.be/ZSxCZCy5Wsk

I'll have to try that later

**Comment by qouteall** [comment]
The true mirror in that video can be made by a non-mirror portal rotating 180
