### ISSUE TITLE
Error on server entry

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#69]
https://gyazo.com/942369aaa775823b4af9a6d9538ff136

**Comment by qouteall** [comment]
The server and client should both install this mod

**Comment by ghost** [comment]
I am running spigot how should I do that

**Comment by qouteall** [comment]
Is spigot compatible with Forge? I don't know.

**Comment by qouteall** [comment]
And this mod is not a normal Forge mod. It uses Mixin.
