### ISSUE TITLE
immersive portals requires a newer version than the current one.

### ISSUE THREAD

**Issue by StillOutOfOrder** [qouteall/ImmersivePortalsMod#691]
![image](https://user-images.githubusercontent.com/83432130/116624315-f62c6500-a904-11eb-99a5-542820da5fce.png)

![image](https://user-images.githubusercontent.com/83432130/116624445-24aa4000-a905-11eb-972c-fc4c3fb14add.png)

![image](https://user-images.githubusercontent.com/83432130/116624522-499eb300-a905-11eb-9e2c-2b4d4b3c9fd6.png)

![image](https://user-images.githubusercontent.com/83432130/116624542-51f6ee00-a905-11eb-8f83-a9821e06479c.png)

**Comment by saythrt** [comment]
you need fabric API , its says just fabric , but u need to download fabric API

**Comment by StillOutOfOrder** [comment]
> 
> 
> you need fabric API , its says just fabric , but u need to download fabric API

oh crap your right im an idiot
