### ISSUE TITLE
знаете в ютубе выходят видео с этим модом и тама делают маленькие постройки примерно тоже самое как с эндор миром

### ISSUE THREAD

**Issue by rolmem** [qouteall/ImmersivePortalsMod#694]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* If you find an issue, check whether this issue happens with only this mod. If not, check which mod it's incompatible with. And include that mod's link in the issue.
* The Forge version is not being supported. If you find an issue of the Forge version, check whether the same issue exists for the Fabric version. Forge-version-specific issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues

**Comment by ImSpaceLover** [comment]
what

**Comment by rolmem** [comment]
![2020-09-15-21-13-34](https://user-images.githubusercontent.com/83511419/116790129-32f68880-aacc-11eb-9439-b0752cb642fb.png)

**Comment by rolmem** [comment]
можно ли как то мне сделать так токо с воё

**Comment by rolmem** [comment]
you know in youtube there are videos with this mod and tama make small buildings about the same as with endor world

**Comment by rolmem** [comment]
can I somehow make this toko my own

**Comment by qouteall** [comment]
Change the end portal mode to `scaledView` https://qouteall.fun/immptl/wiki/Config-Options
