### ISSUE TITLE
Rendering issues with OptiFine shaders

### ISSUE THREAD

**Issue by VoxelCreatesStuff** [qouteall/ImmersivePortalsMod#697]
Immersive Portals still hates Shaders, huh?
Im Using the Chocapic13's on high and when im standing in the overworld, the portal desides to not render certain parts.
And in the ther all my items suddenly become RGB rainbows.
Help. I would realy like to keep the shader

**Comment by VoxelCreatesStuff** [comment]
![2021-05-03_17 08 39](https://user-images.githubusercontent.com/63454846/116895317-5c7df400-ac33-11eb-8252-c0ec8120365d.png)
![2021-05-03_17 09 15](https://user-images.githubusercontent.com/63454846/116895344-66075c00-ac33-11eb-8538-8201e2e396a2.png)
![2021-05-03_17 09 32](https://user-images.githubusercontent.com/63454846/116895379-6ef82d80-ac33-11eb-91c5-7159843061da.png)
![2021-05-03_17 09 50](https://user-images.githubusercontent.com/63454846/116895406-77e8ff00-ac33-11eb-9cf1-3c8621f525b5.png)

**Comment by qouteall** [comment]
It's recommended to use BSL shader.

**Comment by qouteall** [comment]
Close because outdated.
