### ISSUE TITLE
Obsidian platform does not generate fast enough

### ISSUE THREAD

**Issue by squishycat92** [qouteall/ImmersivePortalsMod#698]
It seems as if the obsidian platform in The End does not generate quickly in order to accommodate the player, which can lead to the player falling out of the world (depending on the seed).

Steps to reproduce:
- Make a new world with seed `590375946522069433` (any seed without land under the obsidian platform should work) and verify that the end portal is set to point to the obsidian platform
- Go to The End, make sure the obsidian platform is generated
- Teleport back to the stronghold and break the obsidian
- Jump in, the obsidian should generate right after you fall past it, leading for you to fall into the void

Died to this bug in my hardcore world today, rip o7
![image](https://user-images.githubusercontent.com/62223616/116936051-19fced00-ac1c-11eb-98e6-ad6bcedceb5d.png)

**Comment by qouteall** [comment]
That was very unfortunate. I am going to fix this issue

**Comment by qouteall** [comment]
As I tested the obsidian generates quick enough for the player to stand onto it. Maybe it doesn't generate quickly on your side because of some packet delay or server lag.

**Comment by qouteall** [comment]
I made it to generate the obsidian platform earlier. This issue is probably fixed in the next version.

**Comment by squishycat92** [comment]
Alrighty, great to hear! Thank you!
