### ISSUE TITLE
Crash on Pairing

### ISSUE THREAD

**Issue by CaptainKyros** [qouteall/ImmersivePortalsMod#7]
Every time I try to light a nether portal with this mod, It gives me this crash

https://paste.ee/p/kZnd9

Mods list
![image](https://user-images.githubusercontent.com/8211402/62083608-34669300-b20c-11e9-9a78-cab1576b780b.png)
cosmetic-armor-slots-1.1.3.jar
![image](https://user-images.githubusercontent.com/8211402/62083473-dcc82780-b20b-11e9-95f4-29038fca5ecf.png)

**Comment by qouteall** [comment]
check 0.4 version of this mod and see is this issue fixed.

**Comment by CaptainKyros** [comment]
now I'm getting this crash: https://paste.ee/p/oIcoe

**Comment by qouteall** [comment]
check 0.5 version and see does it crash
