### ISSUE TITLE
Latest Verisons of the mod crash my game on loading screen except for 0.68 verison

### ISSUE THREAD

**Issue by ayzick** [qouteall/ImmersivePortalsMod#700]
I don't know what I'm doing wrong but the game crashes on the loading screen with any newer verison of the mod except for the 0.68 mod that dosen't crash on the loading screen

**Comment by froyo4u** [comment]
Are you using OptiFine?

**Comment by ayzick** [comment]
yes

**Comment by froyo4u** [comment]
You need to use G7 for anything above 0.68

**Comment by ayzick** [comment]
Oh
