### ISSUE TITLE
(server) I get disconnected when I left click anything.

### ISSUE THREAD

**Issue by LordDnds** [qouteall/ImmersivePortalsMod#704]
I am making a server for some friends and am having problems with disconnecting
Line 270 Is where the error is
https://pastebin.com/RjTK4icz

First time using Fabric
Made java modpacks for years and wanted to try fabric

**Comment by LordDnds** [comment]
Sorry if this isn't caused by Immersive portals but the error is from it so I though this would be my best bet

**Comment by froyo4u** [comment]
Yo my portal gun mod uses the preview versions of Immersive Portals, which you can get at this github repo

**Comment by LordDnds** [comment]
Oh ok thx
