### ISSUE TITLE
sticks do not work

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#707]
My sticks do not appear in the menu via creative mode I do not know why I have all the modes and do not show me please help

**Comment by froyo4u** [comment]
are you on the Fabric version?

**Comment by ghost** [comment]
I'm sorry I went to sleep. Yes I'm on fabric version

**Comment by ghost** [comment]
Yes I'm on fabric version

**Comment by froyo4u** [comment]
They should be in the misc tab(lava bucket) of the creative inventory. If they aren't there make sure you're on the latest version

**Comment by ghost** [comment]
Ok thanks uh in need to instal new version BRUH
