### ISSUE TITLE
Texture bug help pls

### ISSUE THREAD

**Issue by dharder123** [qouteall/ImmersivePortalsMod#708]
What the hell why block broke
![texture bug](https://user-images.githubusercontent.com/84148131/118167375-4b04cb00-b42f-11eb-9075-05189efd2bd3.png)

**Comment by qouteall** [comment]
remove the bottom inner portal. I am going to make a new mod called MiniScaled and won't have this issue

**Comment by qouteall** [comment]
Or you can remove the grass blocks under the "inner region"
