### ISSUE TITLE
Updating The Mod crashes you unless you de-update

### ISSUE THREAD

**Issue by Fishtoes** [qouteall/ImmersivePortalsMod#709]
It just won't work

**Comment by froyo4u** [comment]
Need more info than that

**Comment by qouteall** [comment]
Post the crash report

**Comment by StupidRepo** [comment]
Ok. This is such a stupid question. It should be closed because there is...

* 1: NO info
* 2: NO confirms
* 3: NO logs
* 4: NO DESCRIPTIVE TITLE or DESCRIPTION, same(?) as NO info
* 5: STUPIDNESS spread throughout this "issue" (literally!)
