### ISSUE TITLE
[Feature (that we need)] Add a stick that links 2 specific portals.

### ISSUE THREAD

**Issue by StupidRepo** [qouteall/ImmersivePortalsMod#711]
I am TIRED of it making new crappy portals that don't link up. Add a command stick that allows one portal [block] (when right clicked with the/a stick) to link with another portal [block] (when right clicked again with the/a stick).

## How are you so dumb to not think of something like this? I have gone through actual pain getting my portals to link up (they aren't linked still)

If you close this and don't add something like this, I don't think anyone would seriously appreciate this mod that much.

(This post is now in the [2+ total comments][1] list)

[1]: https://github.com/qouteall/ImmersivePortalsMod/issues?q=is:issue+is:open+comments:>=2

**Comment by froyo4u** [comment]
seeing as no one else has said anything like this, I really don't think that this is needed that much

**Comment by StupidRepo** [comment]
Please though, it's so annoying when TRYING to connect portals (or at least for me).

**Comment by StupidRepo** [comment]
Oh my fking (sorry for the swear, I can't handle this anymore) god:
<img width="1440" alt="fug me >:(" src="https://user-images.githubusercontent.com/69256931/118375688-33f2e400-b5bb-11eb-87c4-33f681616ce2.png">
JUST FKING LINK AND STOP MAKING A NEW PORTAL!

**Comment by StupidRepo** [comment]
So, you see what I mean? 

# [If your that type of person who literally scans comments and posts too fast to see key details and don't know what I mean please USE YOUR EYES to look at the above screenshot :)]

**Comment by qouteall** [comment]
@StupidRepo In your screenshot, you are trying to link a 1x1 with 10x8. 1x1 can link to 10x10 not 10x8

**Comment by qouteall** [comment]
Use this datapack https://github.com/Pinaz993/ImmersiveTransit

**Comment by StupidRepo** [comment]
Oh I am SOOO dumb.

**Comment by StupidRepo** [comment]
> Use this datapack https://github.com/Pinaz993/ImmersiveTransit

That [datapack](https://github.com/Pinaz993/ImmersiveTransit
) doesn't help but at least I know what I was doing wrong....

**Comment by L1lith** [comment]
I would really like this feature because portal linking can be a pain when trying to do it across dimensions, or when trying to link two portals that are extremely far away
