### ISSUE TITLE
minecraft wont load

### ISSUE THREAD

**Issue by Looygi** [qouteall/ImmersivePortalsMod#712]
https://gist.githubusercontent.com/natanfudge/1cbb32c70f3ee8d43ec7acef2f0bac29/raw/354595ddf5f55735fcb847f77c1e8435173457a8/crash.txt

**Comment by StupidRepo** [comment]
Try allocating more ram to Minecraft whilst I try and find a solution here...

**Comment by StupidRepo** [comment]
Solution: Look in the error log at about lines 5-10, it says (on one of the lines):

```
The sodium version that you use is incompatible with Immersive Portals.
Check https://github.com/qouteall/sodium-fabric/releases
```
