### ISSUE TITLE
There is no portal block

### ISSUE THREAD

**Issue by monsieurmelon** [qouteall/ImmersivePortalsMod#714]
Im using 1.16.5 mod version with biome O'plenty ,create mod ,just enough items and omni
and when I whant to use your mod there is no items and when im creating the world its saying that im using experimental settings. Please respnd soon !

**Comment by monsieurmelon** [comment]
maybe i gonna remove my issue because i cant use this mod because its a fabric and i dont know how to use fabric mod :C

**Comment by qouteall** [comment]
Do you see this mod in the mod list? If not you didn't install it correctly

**Comment by qouteall** [comment]
Close because outdated.
