### ISSUE TITLE
One-to-many and many-to-one portal relationships?

### ISSUE THREAD

**Issue by muzikbike** [qouteall/ImmersivePortalsMod#718]
This would allow for situations much like Sam Hogan's game within a game, where an entity can enter one portal and two copies of it would come out of two other portals, or two (confirmed to be through checking NBT and such) identical entities enter two portals within a reasonable time frame and one entity comes out of a third linked portal.

I doubt this would be an easy feat to implement, but it's something that came to mind I wanted to put out there.

**Comment by qouteall** [comment]
One-to-many: https://qouteall.fun/immptl/wiki/Portal-Customization#create-the-portal-that-points-to-different-destinations-for-different-players
Many-to-one: one way portals

**Comment by muzikbike** [comment]
That doesn't allow for entity cloning.
