### ISSUE TITLE
servers with immersive portals?

### ISSUE THREAD

**Issue by gooblorshks** [qouteall/ImmersivePortalsMod#719]
are there any servers with immersive portals mod? if anyone knows one please tell me

**Comment by StupidRepo** [comment]
Hello @gooblorshks. I am not a moderator/contributor here and really don't want to mini-mod:

Please close your post as this is not related to an issue to Immersive Portals.

*To other people that aren't @gooblorshks: Do not reply unless you really want to.*

**Comment by qouteall** [comment]
I opened a test server, check the #servers channel in the discord https://discord.gg/BZxgURK

**Comment by StupidRepo** [comment]
Thank you @qouteall.
