### ISSUE TITLE
New portal spawning above portal when linked to another portal that's a different size.

### ISSUE THREAD

**Issue by Moewperson5** [qouteall/ImmersivePortalsMod#720]
I have the Pehkui Mod installed and when I link a portal to another portal that's a different size a new portal spawns above it even though I have the Pehkui Mod.

**Comment by qouteall** [comment]
set nether portal mode to "adaptive"

**Comment by Moewperson5** [comment]
how?

**Comment by qouteall** [comment]
https://qouteall.fun/immptl/wiki/Config-Options

**Comment by Moewperson5** [comment]
Okay, I did it but its still doing the same thing!

**Comment by Moewperson5** [comment]
I'm in the overworld using a portal helper.

**Comment by Moewperson5** [comment]
Making different sized portals and its still doing it.

**Comment by Moewperson5** [comment]
But I have the Pehkui Mod!

**Comment by Moewperson5** [comment]
I'm using fabric to.

**Comment by Moewperson5** [comment]
With fabric api.

**Comment by Mjam-0** [comment]
i have been having this problem aswell

**Comment by MenacingPerson** [comment]
Stop spamming.
If you have the forge version it won't work.
They also need to be the same proportions.

**Comment by qouteall** [comment]
Close because outdated.
