### ISSUE TITLE
Command-generated particle invisible in portal

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#723]

**Comment by StupidRepo** [comment]
What is going on here? I just saw this after I commented on a post just like this. What the hell are you doing lol?

If you want to know what this comment here was originally going to say, it'd be the same as [the comment on a post that you made this is just like this][, you idiot].

[, you idiot]: https://github.com/qouteall/ImmersivePortalsMod/issues/725#issuecomment-851559240
