### ISSUE TITLE
Trying to first time load, getting errors that I am not in 1.17

### ISSUE THREAD

**Issue by MLRSFDC** [qouteall/ImmersivePortalsMod#724]
I Saw Mombo use this, so I'm trying to add it to my current use of Fabric. Kept getting updated file errors. Tracked all of them down, loaded all the new API's and updates. I am trying to use Minecraft 1.16.5. The version of Immersive Portals that I downloaded says it is for 1.16.5, however, I am getting errors saying that I need to be in 1.17, which isn't out yet. I tried using an older version of Immersive Portals, and it told me that I was using the wrong API, so I shifted them. I have included screenshots including my mods folder and 2 of the errors that I keep getting. All of my older files are in the New Folder that way I can shift back and forth if I need to.
![SharedScreenshot](https://user-images.githubusercontent.com/84738056/119390966-607dbe80-bc93-11eb-9731-a6462bff0a65.jpg)
![SharedScreenshot1](https://user-images.githubusercontent.com/84738056/119390969-61165500-bc93-11eb-98e2-f0c21aab47c6.jpg)

**Comment by froyo4u** [comment]
use [this version](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3304636) of Fabric API. You are trying to use the 1.17 version of Fabric API

**Comment by MLRSFDC** [comment]
You make it seem so easy. LOL. I went through about 6 of the old API's and kept choosing the wrong one. PEBKAC. I appreciate it, this fixed the issue.
