### ISSUE TITLE
Map in item frame does not load through portal

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#725]

**Comment by StupidRepo** [comment]
Uhh, @qouteall, you're a/the developer of this mod, if you know about this issue, don't report it on your own GitHub.

Instead try to fix it than open an issue on your own GitHub addressing an issue about your OWN MOD.

Sorry if I sound rude here but this is a really stupid thing to do lol.

**Comment by qouteall** [comment]
Should be fixed.
