### ISSUE TITLE
all of my progress got deleted 

### ISSUE THREAD

**Issue by turtleigg** [qouteall/ImmersivePortalsMod#726]
so I wanted to troll my friend with this mod but he dose not have discord and we have to use zoom so we hoped on hypixel for me to send him the zoom and I had to switch to Minecraft 1.16.5 for it to work and his wifi was not working so we were going to do it the next day and I went on the world to make 1 adjustment and I switched to fabric to use it but then when it said it was at 100% I waited for 5 mins and thought this will take a while and I tried to close out Minecraft so open it again I clicked the red x but nothing happened and I restarted my computer again it did not do anything and now all the progress in my world is gone and I have a forever Minecraft tab at 100% what the hell happened???

**Comment by froyo4u** [comment]
You were originally on Forge?

**Comment by turtleigg** [comment]
no

**Comment by froyo4u** [comment]
so what did you mean by switched to Fabric?

**Comment by turtleigg** [comment]
when you first load up Minecraft you have the choice to load up Minecraft forge the new snapshot or fabric

**Comment by froyo4u** [comment]
oh that's what you meant, ok.

**Comment by turtleigg** [comment]
I'm trying to send a picture

**Comment by qouteall** [comment]
Are you sure that this issue is related to Immersive Portals?

**Comment by TheAwesome98-Real** [comment]
I think they accidentally loaded a forge world in fabric which removes chunks that have invalid tiles(?) in it (which is all of them)

**Comment by turtleigg** [comment]
ok thank you so much
