### ISSUE TITLE
Terrible lag with pretty good specs 

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#728]
This mod looks great, and I'd love to use it, though even without having a single portal open I am experiencing INTENSE frame rate problems. I can barely play at 2 chunks with this mod enabled. Even with a 3700x, 1050TI, and 16GB allocated to minecraft the problem remains.

Disabling the mod fixes the issue, but what's the point in that?

**Comment by qouteall** [comment]
Are you using the latest 1.16.5 Fabric version? Do you get this issue with only this mod and fabric api? Is your render distance larger than 16? Does it lag after playing the game for 5 minutes?

**Comment by ghost** [comment]
lag with 2 chunks
I have the latest fabric version
does not lag in the nether
lags even after 10 minutes
issue persists even if I isolate this only running immersive portals and fabric api

**Comment by qouteall** [comment]
Does it constantly lag or lag perodically? To debug this, I need you to press shift+F3 in game, run 1 minutes, close the game and then upload the log `/logs/latest.log`

**Comment by TheAwesome98-Real** [comment]
I have this same issue. It might be because Sodium isn't installed, but it's not compatible with Immersive Portals.

**Comment by qouteall** [comment]
@TheAwesome98-Real To debug this, I need you to press shift+F3 in game, run 1 minutes, close the game and then upload the log `/logs/latest.log` .
And there is a compatible sodium https://github.com/qouteall/sodium-fabric/releases

**Comment by TheAwesome98-Real** [comment]
I forgot to mention that it's only if there's a portal in my render distance.

**Comment by qouteall** [comment]
Close because outdated.
