### ISSUE TITLE
portal helper problem with pehkui mod

### ISSUE THREAD

**Issue by Mjam-0** [qouteall/ImmersivePortalsMod#731]
the portal helper will create a new portal when lit the same size as the original  portal if tried to connect with a bigger portal.

**Comment by froyo4u** [comment]
How far away is the other portal?

**Comment by Mjam-0** [comment]
just around 2-4 blocks away

**Comment by froyo4u** [comment]
Odd

**Comment by Mjam-0** [comment]
nevermind i played with the config and it worked
