### ISSUE TITLE
More Command Sticks

### ISSUE THREAD

**Issue by PortalPuzzleMan** [qouteall/ImmersivePortalsMod#735]
Can we have some way to set a portal end and entrance areas with the command sticks insted of having to note the commands? i think it would make it a lot easier for some people. Also, can we have singular bi-face, one-face. and one-way sticks?

**Comment by qouteall** [comment]
1. I am considering changing the portal helper. If no linkable frame is not found, the player will be given an item that when used creates a portal to that position.
2. About one-way portals, see this https://qouteall.fun/immptl/wiki/Portal-Customization#1-nether-portal--4-portal-entities

**Comment by qouteall** [comment]
Close because outdated.
