### ISSUE TITLE
1.17 version of immersive portals gives me an infinite loading screen

### ISSUE THREAD

**Issue by narpouo** [qouteall/ImmersivePortalsMod#737]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* If you find an issue, check whether this issue happens with only this mod. If not, check which mod it's incompatible with. And include that mod's link in the issue.
* The Forge version is not being supported. If you find an issue of the Forge version, check whether the same issue exists for the Fabric version. Forge-version-specific issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues
The red MOJANG screen will load and then go instantly back to loading. It does this infinitely.

**Comment by qouteall** [comment]
Post the log, it's gameDirectory/logs/latest.log

**Comment by qouteall** [comment]
Are you using Mac?

**Comment by narpouo** [comment]
> Are you using Mac?

No I'm on Windows.

**Comment by narpouo** [comment]
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/6632048/latest.log)

**Comment by qouteall** [comment]
Does this version work? https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.04-1.17

**Comment by narpouo** [comment]
> Does this version work? https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.04-1.17

Yes. Thank you.
