### ISSUE TITLE
Portal spawns above other portal even though I have a portal to link it with, I have pehkui installed.

### ISSUE THREAD

**Issue by Duckhasascended** [qouteall/ImmersivePortalsMod#738]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* If you find an issue, check whether this issue happens with only this mod. If not, check which mod it's incompatible with. And include that mod's link in the issue.
* The Forge version is not being supported. If you find an issue of the Forge version, check whether the same issue exists for the Fabric version. Forge-version-specific issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues

**Comment by Duckhasascended** [comment]
I am using fabric, with adaptive on, and the portals never link. I made the bigger one exactly 2x the size of the smaller one, but it still doesn't work. Any help?

**Comment by qouteall** [comment]
Is the other side frame close to the corresponding position? And show screenshots.

**Comment by qouteall** [comment]
Close because outdated.
