### ISSUE TITLE
GUI interface in 1.17 removes images and item textures

### ISSUE THREAD

**Issue by IrrelevantCube** [qouteall/ImmersivePortalsMod#744]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* If you find an issue, check whether this issue happens with only this mod. If not, check which mod it's incompatible with. And include that mod's link in the issue.
* The Forge version is not being supported. If you find an issue of the Forge version, check whether the same issue exists for the Fabric version. Forge-version-specific issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues

**Comment by qouteall** [comment]
Which and where image and item texture is being removed? Does this issue happen with only this mod and fabric api?

**Comment by IrrelevantCube** [comment]
Most items in the creative GUI

**Comment by qouteall** [comment]
Does this issue happen with only this mod and fabric api?

**Comment by qouteall** [comment]
Issue closed because the issue opener haven't provided requested information for a long time.
