### ISSUE TITLE
portal appears black through other portals

### ISSUE THREAD

**Issue by baconlover209** [qouteall/ImmersivePortalsMod#745]
when looking through a portal into a different portal the portal renders only black
![2021-06-17_10 12 07](https://user-images.githubusercontent.com/69828483/122424700-8de91f80-cf54-11eb-81c1-9a4add0a67df.png)

**Comment by qouteall** [comment]
Did you enabled "compatibility renderer"? Does this issue happen with only Immersive portals and fabric api?

**Comment by Tranquanto** [comment]
It could be due to your max portal stack limit. Check in config; if it's too low the portals will render as black through other portals to reduce lag.

**Comment by qouteall** [comment]
Close because outdated.
