### ISSUE TITLE
when aproaching portal it turns black

### ISSUE THREAD

**Issue by baconlover209** [qouteall/ImmersivePortalsMod#746]
when within ~1-2 blocks the portal flashes black
![2021-06-17_10 44 12](https://user-images.githubusercontent.com/69828483/122430248-0eaa1a80-cf59-11eb-974b-d62ddb2261c9.png)

**Comment by qouteall** [comment]
Does it happen in 1.17 or 1.16? Does it happen with only Immersive portals and fabric api?

**Comment by qouteall** [comment]
edit the config file to turn off compatibility render mode.
