### ISSUE TITLE
When I turn on the portal it renders like the sky with nothing

### ISSUE THREAD

**Issue by Trapszinho** [qouteall/ImmersivePortalsMod#748]
When I turn on the portal, both global and inferior, the image of the local sky is always
![Screenshot_2021-06-21-13-22-23-722_net kdt pojavlaunch](https://user-images.githubusercontent.com/86251969/122797653-14c03400-d296-11eb-8654-552dff0b03f1.jpg)
![Screenshot_2021-06-21-13-30-50-726_net kdt pojavlaunch](https://user-images.githubusercontent.com/86251969/122797661-17bb2480-d296-11eb-8d45-ece94120bdea.jpg)
![Screenshot_2021-06-21-13-31-07-324_net kdt pojavlaunch](https://user-images.githubusercontent.com/86251969/122797675-1b4eab80-d296-11eb-8d5a-4caa1df8281a.jpg)
![Screenshot_2021-06-21-13-32-53-923_net kdt pojavlaunch](https://user-images.githubusercontent.com/86251969/122797688-1db10580-d296-11eb-8cb9-4fc72339db0e.jpg)
![Screenshot_2021-06-21-13-33-03-728_net kdt pojavlaunch](https://user-images.githubusercontent.com/86251969/122797695-20135f80-d296-11eb-937d-615ae5f3e235.jpg)

**Comment by RemagOfficial** [comment]
thats a pojav issue

**Comment by qouteall** [comment]
Probably because the phone does not support some OpenGL functionality
