### ISSUE TITLE
Weird things

### ISSUE THREAD

**Issue by ArtemSolo23** [qouteall/ImmersivePortalsMod#750]
Portal Helper texture is now a smile thing.....And portal not working
![javaw_BUa8CZcne8](https://user-images.githubusercontent.com/86269587/122837480-d3af3a80-d2fc-11eb-8b20-554f5b1852c7.png)

**Comment by RemagOfficial** [comment]
that's a pack issue not an IP issue

**Comment by ArtemSolo23** [comment]
And what me need to do to fix it?

**Comment by RemagOfficial** [comment]
ask the pack author

**Comment by ArtemSolo23** [comment]
Ok thx

**Comment by qouteall** [comment]
Use 1.16 or 1.17 versions
