### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Ameliaplayz** [qouteall/ImmersivePortalsMod#751]
So my game crashes whenever i use this mod, here are the mods, this is on 1.17 btw

*iris-mc1.17-1.0.2
latest version of immersive portals
latest version of fabric api*

**Comment by Ameliaplayz** [comment]
well pretty much 1.17 is unstable so let's see if you guys can fix issues with it

**Comment by qouteall** [comment]
post the crash report

**Comment by qouteall** [comment]
Incompatible with iris
