### ISSUE TITLE
I am unable to light the end portal

### ISSUE THREAD

**Issue by AtaraXY-MNM** [qouteall/ImmersivePortalsMod#752]
No matter what I do, I am unable to light the end portal.

**Comment by qouteall** [comment]
Naturally generated end portal or manually placed end portal?

**Comment by AtaraXY-MNM** [comment]
Manual

**Comment by qouteall** [comment]
Maybe you placed the end portal blocks wrongly. That block is directional. Stay in the center and don't move your position and place the end portal blocks.

**Comment by qouteall** [comment]
Close because outdated.
