### ISSUE TITLE
mirror 

### ISSUE THREAD

**Issue by cool243** [qouteall/ImmersivePortalsMod#753]
If you hold an item in a mirror it will not show. (I do not no if this is because i have pure mirror on)
![screenshot](https://user-images.githubusercontent.com/83677820/123170306-37d21b80-d42f-11eb-9fd7-83d656bf5f85.png)

**Comment by qouteall** [comment]
1.17?

**Comment by qouteall** [comment]
Close due to not having complete information to diagnose the issue.
