### ISSUE TITLE
Direct Incompatibility with Seasons for Fabric 1.17

### ISSUE THREAD

**Issue by MorganRO8** [qouteall/ImmersivePortalsMod#757]
![2021-06-27_18 31 59](https://user-images.githubusercontent.com/47795945/123561408-244beb00-d776-11eb-8b0a-38657615e9d3.png)

Basically the story goes you load in just these two mods (Seasons for Fabric and Immersive Portals), go to a creative world, put down a portal and then /set time 672000t and the game will suddenly only be able to render about 2 chunks at a time and keep a stable framerate. Not sure who's end this is on but I figured I'd at least make you aware that modpack authors are having to make a tough choice. Love the work so much and thank you for doing it.

**Comment by qouteall** [comment]
Post the link of "Seasons" mod

**Comment by MorganRO8** [comment]
no problem https://www.curseforge.com/minecraft/mc-mods/fabric-seasons

**Comment by Moocow9m** [comment]
just to add some more info, when this happens, I noticed this in the logs: 
`[11:57:59] [Render thread/INFO]: WorldRenderer reloaded minecraft:overworld
[11:57:59] [Render thread/INFO]: WorldRenderer reloaded minecraft:the_nether
[11:57:59] [Render thread/INFO]: WorldRenderer reloaded minecraft:the_nether
[11:57:59] [Render thread/INFO]: WorldRenderer reloaded minecraft:overworld
[11:57:59] [Render thread/INFO]: WorldRenderer reloaded minecraft:overworld`
Over and over till disconnect, several times a second

**Comment by qouteall** [comment]
The Seasons mod reloads the world renderer when the last rendered season is different than the current season during world ticking. However with immersive portals, there could be multiple client worlds existing at the same time, if the two client worlds have different seasons it will constantly reload the world renderer.
https://github.com/lucaargolo/fabric-seasons/blob/1.17/src/main/java/io/github/lucaargolo/seasons/FabricSeasonsClient.java#L44

This can only be fixed by Seasons. Seasons can only track the season for the overworld dimension, or track different season data for different dimensions. You can open an issue to Seasons'.

**Comment by deadspidervenom** [comment]
Had same issue, removed immersive portals and it prevents people from logging in via "[Disconnect] _______ has disconnected, reason Invalid player data"

**Comment by qouteall** [comment]
@deadspidervenom Are you sure that this issue relates to Seasons mod? Does the server have the same mod list as the client?

**Comment by deadspidervenom** [comment]
yes, i am not dumb, removal of season but leaving in immersive portals worked just fine, but when we remove immersive portals it wont let anyone join

**Comment by qouteall** [comment]
@deadspidervenom Does the client also remove Immersive Portals?

**Comment by MorganRO8** [comment]
@deadspidervenom From the server console try running '/time set 0' and '/kill @e' to make sure that the season is set back to before the issue and the portal entities are removed. If that doesn't work, try deleting your level.dat and then rename the level.dat_old to level.dat to slightly revert the server.

**Comment by lucaargolo** [comment]
Hii, I'm the dev of the Fabric Seasons mod. Sorry for taking too long to fix this, but version 1.3-BETA should be fully compatible with Immersive Portals.
