### ISSUE TITLE
[Issue] Dimensional Stacking fails to replace bedrock layer if using the 1.18 Preview Pack for cave generation

### ISSUE THREAD

**Issue by BathToast** [qouteall/ImmersivePortalsMod#758]
Issue occurs on the latest version of Immersive Portals and _DOES NOT_ occur if you generate terrain normally. However, should you use the 1.18 generation data pack preview available from Mojang [here](https://feedback.minecraft.net/hc/en-us/articles/4402614709389-Caves-Cliffs-Prototype-Data-Pack-for-Minecraft-Java-Edition) then bedrock generation does not get replaced with obsidian as shown in the image below:

![2021-06-28_10 46 24](https://user-images.githubusercontent.com/66298508/123658352-a502f980-d7ff-11eb-9516-a647bfa6c825.png)

Currently, no other issues have been encountered. Other than the unstable build warning upon world start being a tad annoying as it cant be suppressed in the config it seems.

**Comment by qouteall** [comment]
This is because that the bedrock replacement code hardcoded the y range. Now fixed
