### ISSUE TITLE
Minecart w/Player doesn't pass through Nether Portal (1.17)

### ISSUE THREAD

**Issue by MindForged** [qouteall/ImmersivePortalsMod#760]
As the title says. Whether the portal is vertical or flat/horizontal on the ground, a minecart with a player in it stops completely. It works without a player inside, but it'd be really nice if one could ride straight through on a minecart.
![image](https://user-images.githubusercontent.com/33333985/123830796-443ff380-d8c9-11eb-9261-c18835b92819.png)

**Comment by qouteall** [comment]
Fixed.

**Comment by MindForged** [comment]
> Fixed.

Thanks!
