### ISSUE TITLE
Game constantly crashing with mod installed

### ISSUE THREAD

**Issue by zander999** [qouteall/ImmersivePortalsMod#763]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* If you find an issue, check whether this issue happens with only this mod. If not, check which mod it's incompatible with. And include that mod's link in the issue.
* The Forge version is not being supported. If you find an issue of the Forge version, check whether the same issue exists for the Fabric version. Forge-version-specific issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues

My game will constantly crash, showing a blank screen with only the sky and the player's hand visible.
I have attached the latest.log file, I have tried different versions and have removed all other mods, and the crash still occurs.

I happen to have many portals in the world, not sure if that would make a difference.
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/6747926/latest.log)

**Comment by RemagOfficial** [comment]
your username is just "Player"?

**Comment by qouteall** [comment]
It seems to be a compatibility issue. The rendering kept reloading. Try to remove half mods until you find which exact mod it's incompatible with

**Comment by that-named-guy-named-diamond** [comment]
I checked it does not work, deleted it the reinstalled it, it did not work

**Comment by zander999** [comment]
It seems to break with just fabric API and the immersive portals installed.
I will try reinstalling everything.

**Comment by zander999** [comment]
Update: A total reinstall of everything, along with only running both the latest fabric API and the immersive portals mod, the crashes still occur. The latest log has been included.
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/6752238/latest.log)

**Comment by qouteall** [comment]
@zander999 You installed pehkui. Does it crash without pehkui?

**Comment by zander999** [comment]
It still crashes when only immersive portals and fabric API are installed.
In some sessions, it works fine, but it usually crashes. I'd say there is a 1 in 10 chance of it working.

**Comment by qouteall** [comment]
The log does not provide useful information other than `java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!`
Does it crash when entering a newly created world?

**Comment by zander999** [comment]
Yeah, thanks.
It seems like my current world is not working quite right with the mod.
I'll just have to start over in a new world, thanks for the help.

**Comment by qouteall** [comment]
Does it crash with that world and without immersive portals?
