### ISSUE TITLE
Crashing with Iris Shaders

### ISSUE THREAD

**Issue by SaltSouls** [qouteall/ImmersivePortalsMod#766]
[Iris Shaders](https://www.curseforge.com/minecraft/mc-mods/irisshaders)
The game crashes the instant you try to open a portal to the nether when using Iris.

Crash Report:
- [Portality.zs](https://github.com/qouteall/ImmersivePortalsMod/files/6763173/crash-2021-07-05_02.10.33-client.txt)

**Comment by qouteall** [comment]
Because the Iris compatibility PR hasn't been merged https://github.com/IrisShaders/Iris/pull/425
