### ISSUE TITLE
Lag when rain starts

### ISSUE THREAD

**Issue by ravensniper72** [qouteall/ImmersivePortalsMod#767]
on the 1.17 version when the rain starts in single player I get a harsh lag spike. when I have it on a server it doesn't stop lagging until the rain stops.

**Comment by qouteall** [comment]
Client lag or server lag?

**Comment by gustasmarcinkevicius** [comment]
Same thing for me. Rain = Lag

**Comment by qouteall** [comment]
Did you try installing sodium? (in 1.17.1)

**Comment by gustasmarcinkevicius** [comment]
Me, no. I don't use Sodium. If @ravensniper72 has Sodium, then he should.

**Comment by qouteall** [comment]
Close because outdated.
