### ISSUE TITLE
Textures 

### ISSUE THREAD

**Issue by ClosedTheDor** [qouteall/ImmersivePortalsMod#769]
The blocks are appering and dissappear
It's all

**Comment by qouteall** [comment]
Does this issue happen with only Immersive portals and fabric api installed?

**Comment by ClosedTheDor** [comment]
Yes

**Comment by qouteall** [comment]
1.17? Does this happen without any portal nearby? Which video card do you use?

**Comment by qouteall** [comment]
Close because outdated.
