### ISSUE TITLE
(crash) org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError

### ISSUE THREAD

**Issue by cootshk** [qouteall/ImmersivePortalsMod#772]
Game crashes upon loading a creative world with datapacks. When I remove immersive ptls, the world loads fine (mod list at the bottom of the crash report)

crash log: 
---- Minecraft Crash Report ----
// Don't do that.

Time: _________
Description: Exception in server tick loop

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.server.world.ServerChunkManager.<init>(ServerChunkManager:87)
	at net.minecraft.server.world.ServerWorld.<init>(ServerWorld:200)
	at net.minecraft.server.MinecraftServer.createWorlds(MinecraftServer:383)
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer:350)
	at net.minecraft.server.integrated.IntegratedServer.setupServer(IntegratedServer:71)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:831)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [imm_ptl.mixins.json:common.chunk_sync.MixinThreadedAnvilChunkStorage_C] from phase [DEFAULT] in config [imm_ptl.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_17707 was not located in the target class net.minecraft.class_3898. Using refmap imm_ptl_core-refmap.json
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:610)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:289)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 576019584 bytes (549 MiB) / 1677721600 bytes (1600 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-1607 v2 @ 3.00GHz
	Identifier: Intel64 Family 6 Model 62 Stepping 4
	Microarchitecture: Ivy Bridge (Server)
	Frequency (GHz): 2.99
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA NVS 510
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x0ffd
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6231
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 1.87
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 1.87
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 2048.00
	Memory slot #2 clockSpeed (GHz): 1.87
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 2048.00
	Memory slot #3 clockSpeed (GHz): 1.87
	Memory slot #3 type: DDR3
	Memory slot #4 capacity (MB): 2048.00
	Memory slot #4 clockSpeed (GHz): 1.87
	Memory slot #4 type: DDR3
	Memory slot #5 capacity (MB): 2048.00
	Memory slot #5 clockSpeed (GHz): 1.87
	Memory slot #5 type: DDR3
	Memory slot #6 capacity (MB): 2048.00
	Memory slot #6 clockSpeed (GHz): 1.87
	Memory slot #6 type: DDR3
	Memory slot #7 capacity (MB): 2048.00
	Memory slot #7 clockSpeed (GHz): 1.87
	Memory slot #7 type: DDR3
	Virtual memory max (MB): 41804.43
	Virtual memory used (MB): 35043.82
	Swap memory total (MB): 25496.58
	Swap memory used (MB): 1774.93
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin mc1.17-2.0.0
		architectury: Architectury 2.1.20
		authme: Auth Me 1.5.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		automated_crafting: Automated Crafting 1.3.24+MC1.17-1.17.1
		bclib: BCLib 0.2.0
		betterend: Better End 0.10.2-pre
		betternether: Better Nether 5.1.3
		blue_endless_jankson: jankson 1.2.1
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		couplings: Couplings 1.5.0+1.17
		crowdin-translate: CrowdinTranslate 1.3+1.17
		diggusmaximus: Diggus Maximus 1.4.5-1.17
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dynamicfps: Dynamic FPS 2.0.4
		fabric: Fabric API 0.36.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d013
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea813
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446313
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57713
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa13
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446313
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446313
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31013
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57713
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446313
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c013
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa13
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57713
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446313
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612113
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446313
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e13
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463d5
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446313
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa13
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446313
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57713
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446313
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612113
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446313
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446313
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee13
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96913
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446313
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446313
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446313
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa13
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446313
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446313
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57713
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446313
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446313
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612113
		fabric-tpa: FabricTPA 3.0.1
		fabricloader: Fabric Loader 0.11.6
		fallingtree: FallingTree 2.12.1
		fiber: fiber 0.23.0-2
		flycommand: FlyCommandMod 1.1
		imm_ptl_core: Immersive Portals Core 0.10
		immersive_portals: Immersive Portals 0.10
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kyrptconfig: Kytpt Config 1.1.10-1.17
		libgui: LibGui 4.1.2+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.2.1+1.17
		lithium: Lithium 0.7.3
		minecraft: Minecraft 1.17.1
		modmenu: Mod Menu 2.0.2
		naturescompass: Nature's Compass 1.17.1-2.0.0-fabric
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		pehkui: Pehkui 2.2.1+1.14.4-1.17
		q_misc_util: A Miscellaneous Utility Library from qouteall 0.10
		roughlyenoughitems: Roughly Enough Items 6.0.264-alpha
		spark: spark ${pluginVersion}
		spruceui: SpruceUI 3.2.0+1.17
		truerooms: True Secret Rooms 1.1.4
		worldedit: WorldEdit 7.2.6-beta-01+1415e6f
		wthit: wthit 3.7.0
		xaerominimap: Xaero's Minimap 21.12.5.1
	Player Count: 0 / 8; []
	Data Packs: vanilla (incompatible), file/armored elytra v1.0.3, file/cauldron concrete v2.0.3, file/chunk loaders v1.0.1, file/coordinates hud v1.2.0, file/double shulker shells v1.3.0, file/dragon drops v1.3.0, file/elevators v1.0.1, file/more mob heads v2.9.2, file/player head drops v1.1.0, file/real time clock v1.1.0, file/redstone rotation wrench v1.1.1, file/spectator conduit power v1.1.0, file/spectator night vision v1.1.0, file/terracotta rotation wrench v1.1.1, file/thunder shrine v1.1.0, file/track statistics v1.1.0, file/villager workstation highlights v1.1.0, Fabric Mods, file/unlock all recipes v2.0.1
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
	Suspected Mods: Fabric Loader (fabricloader)

**Comment by qouteall** [comment]
Use 1.17 for now. I am going to upgrade to 1.17.1
