### ISSUE TITLE
Issue with certain seeds when paired with Castle Dungeons

### ISSUE THREAD

**Issue by Baggytrousers27** [qouteall/ImmersivePortalsMod#783]
Fabric loader 0.11.6 - 1.17.1

1. Fabric-Api 0.37.0+ 1.17
2. immersive portals 0.12 - 1.17.1-fabric 
2. [castle_dungeons-2.5-1.17-fabric](https://www.curseforge.com/minecraft/mc-mods/castle-dungeons#c78)

Certain seeds that generate Castle structures near spawn (Example seed: 3102493044798757045) will load to 100% and freeze on that screen forevermore, requiring forcible ending of the process in task manager.

Log usually counts up to a number between 90-97, then no further output.

**Comment by qouteall** [comment]
Does the issue happen in this version? https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.13-1.17

**Comment by Baggytrousers27** [comment]
That seems to have fixed it. Cheers.
