### ISSUE TITLE
[1.17.1] Some Game Elements Appear Through Mirrors

### ISSUE THREAD

**Issue by SaberShip** [qouteall/ImmersivePortalsMod#786]
### Issues
**Particles:**
Particles appear through all mirrors while also being reflected by mirrors:
![2021-07-17_21 15 01](https://user-images.githubusercontent.com/6741766/126053607-10830a28-b8d5-4852-aca5-4a7fa35c6189.png)

**Water:**
Water (Still and Flowing) appears through all mirrors:
![2021-07-17_20 36 34](https://user-images.githubusercontent.com/6741766/126053428-35e4c75b-06fc-45f0-aaa5-87a7bb19c139.png)

Lava however, does not appear through mirrors:
![2021-07-17_21 05 20](https://user-images.githubusercontent.com/6741766/126053444-0c95505c-058d-41b4-b27c-7da0b975347d.png)

**Stacked Dimensions:**
Blocks from stacked dimensions below the overworld can be seen through mirrors.  This only appears to appy to mirrors activated on the tops of glass blocks:
![2021-07-17_20 34 04](https://user-images.githubusercontent.com/6741766/126053489-9cf4927a-43ce-4588-aadd-206bb2e1f03f.png)
You can see Steve's head appears to "clip" through the non-existing obsidian blocks.

**Clouds:**
While difficult to demonstrate in a screenshot, clouds appear through and are reflected by mirrors:
![2021-07-17_21 13 36](https://user-images.githubusercontent.com/6741766/126053581-bdd6915f-af1c-4c01-a833-0d6c96a8d0fd.png)

### Versions:
- Minecraft: 1.17.1
- IP: 0.12
- Fabric API: 0.37
- All screenshots were taken with Optifabric, however I have verified these issues still exist without Optifabric installed. 
- No other mods present

**Comment by qouteall** [comment]
Probably fixed https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.14-1.17

**Comment by SaberShip** [comment]
Verified the issue is gone.
