### ISSUE TITLE
IP messing when WWOO datapack and Mo'Structure mod together

### ISSUE THREAD

**Issue by schuberty** [qouteall/ImmersivePortalsMod#788]
I have a server with [William Wythers' Overhauled Overworld](https://www.planetminecraft.com/data-pack/william-wythers-overhauled-overworld/) datapack, [Mo' Structures](https://www.google.com/search?client=firefox-b-d&q=mo+structures) and ImmersivePortals on the latest release by now.

If I have IP and WWOO on the server, no Mo'S structures generate.
If I have IP without WWOO, Mo'S structures generate.
In both cases IP works.

I don't know what could be causing it. I have a lot of other mods but I tested in all the cases (with only these mods and only other, with and without datapacks) and looks like **IP is causing the Mo'S structures not being generated when WWOO datapack is on the map**.

No errors appears on the logs altought. Nothing different from the usual.

**Comment by schuberty** [comment]
Now I added Repurposed Structures for testing, and when I try to locate any RS Mod structure it crashes the server.
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/6844185/latest.log)
[crash-2021-07-19_19.13.56-server.txt](https://github.com/qouteall/ImmersivePortalsMod/files/6844187/crash-2021-07-19_19.13.56-server.txt)

**Comment by svenhjol** [comment]
See #787.  I think we have the same issue here.

**Comment by qouteall** [comment]
Close because outdated.
