### ISSUE TITLE
crashing when using shaders

### ISSUE THREAD

**Issue by Sjskyler27** [qouteall/ImmersivePortalsMod#793]
crashing when using shaders

**Comment by MenacingPerson** [comment]
Optifabric or iris?

**Comment by N-U-M-B-A-T** [comment]
I have the same issue on Iris

**Comment by N-U-M-B-A-T** [comment]
Just learnt that iris is incompatible with Immersive Portals but they are working on fixing this.

**Comment by MenacingPerson** [comment]
actually, there is a branch of sodium compatible with both immptl and iris.

**Comment by N-U-M-B-A-T** [comment]
ok. could you send link please?

**Comment by DragonEggBedrockBreaking** [comment]
The pr was merged into iris a few hrs ago
