### ISSUE TITLE
Unable to see through portals

### ISSUE THREAD

**Issue by Daedalus112** [qouteall/ImmersivePortalsMod#8]
Unable to view through portals when they are activated, Can only see the color of the sky. Only the 0.5 version of the mod and fabric api are installed. Game running on MacOS using the latest build of Fabric.
![2019-08-06_14 32 10](https://user-images.githubusercontent.com/15059498/62566469-05c56980-b857-11e9-982b-d998f5e4059d.png)
![2019-08-06_14 32 03](https://user-images.githubusercontent.com/15059498/62566478-0a8a1d80-b857-11e9-94da-0303a53eb645.png)

**Comment by qouteall** [comment]
I can't reproduce this issue.(I don't have a mac) Maybe the internal server is lagging. Try to reduce render distance?

**Comment by qouteall** [comment]
Try to go into the portal and go back

**Comment by qouteall** [comment]
Try to run command /immersive_portals_debug multithreaded_chunk_loading_disable

**Comment by qouteall** [comment]
Can you see sun, moon or star from portal?

**Comment by Daedalus112** [comment]
Ok so I updated to the 0.6 version of the mod and the issue is still there. I cannot see the sun, moon, or stars through the portal, and i set my render distance to 2. After running all of those commands this was the output:

Client Chunk:
minecraft:the_nether 9
minecraft:overworld 49

**Comment by qouteall** [comment]
Please give me the log

**Comment by Daedalus112** [comment]
[Log.txt](https://github.com/qouteall/ImmersivePortalsMod/files/3501577/Log.txt)

I'm assuming you mean this but if you meant something else please let me know

**Comment by qouteall** [comment]
It seems that OpenGL does not support stencil buffer. Try to upgrade Graphics driver?
I made another rendering system. Try 0.7 version and use this command:
/immersive_portals_debug switch_to_compatibility_renderer
In compatibility mode, it can't render the portal inside portal

**Comment by Daedalus112** [comment]
Ok so I updated to the 0.7 version of the mod and my graphics drivers are up to date. I ran the command and the only thing that changed was I was able to see transparent blocks like water through the portal.
![2019-08-14_11 03 09](https://user-images.githubusercontent.com/15059498/63032284-843b9000-be83-11e9-9086-ae80c7adfb70.png)

**Comment by qouteall** [comment]
So strange. I have no idea how to fix it.

**Comment by Daedalus112** [comment]
Its possible that it may be a mac issue. Tomorrow I'm going to try to test it on another mac to see if it carries over.

**Comment by juliand665** [comment]
I just ran into this issue too, with the exact same symptoms (including being able to see transparent blocks through portals in compatibility mode). Tested on 0.10 and 0.11 with no other mods loaded. I'm on macOS too, so it seems that is actually the cause.

**Comment by qouteall** [comment]
Check 0.14 version and see whether this issue still exists

**Comment by juliand665** [comment]
Can confirm it works for me now!
