### ISSUE TITLE
visual bug

### ISSUE THREAD

**Issue by lostopkk** [qouteall/ImmersivePortalsMod#800]
mods:
fabric api v0.37.1
sodium v0.3.0 build.529
immersive portals v0.16

images:
![2021-07-26_15 16 43](https://user-images.githubusercontent.com/50776714/127039646-17cb2d50-d55c-4b21-b56d-88d0f595f898.png)

when you get away, there's no such bug, but when you look, it looks buggy with game particles

**Comment by qouteall** [comment]
Does it occur without sodium? Did you turn on fabulous graphics?

**Comment by Baelein** [comment]
I'm having this issue 2 and I don't have sodium. I also noticed it immediately when I set up dimensional stacking. And same version 0.16.

**Comment by lostopkk** [comment]
> Does it occur without sodium? Did you turn on fabulous graphics?

I haven't tested yet if this bug only occurs with sodium, and no, it's not with the fabulous graphics

**Comment by lostopkk** [comment]
merged to #801
