### ISSUE TITLE
video report

### ISSUE THREAD

**Issue by lostopkk** [qouteall/ImmersivePortalsMod#801]
https://drive.google.com/file/d/1cPqWK9DxtB0OVjUUOsBrHmXq27kfUtsy/view?usp=sharing

notes:
I had already made an issue but here is a more general overview of the visual bugs, a video showing several strange bugs like:
- when you light up the portal, one of the blocks of the helper portal becomes practically transparent, and ends up bugging a lot of times.
- particles are above the portals and end up hindering the portal's visibility.
- sometimes at different points the portal is over blocks like the particle.
(google translate brazilian to english)
mods:
- adorn@2.1.3+1.17.1
	- advanced_runtime_resource_pack@0.4.3
	- amecsapi@1.1.5+mc21w16a
	- appleskin@mc1.17-2.1.1
	- appletreesrev@1.3
	- architectury@2.2.21
	- artofalchemy@1.2.0+1.17.1
	- backslot@1.2.0
	- biome_locator@1.1.3
	- bitsandchisels@2.5.3
	- blockus@2.2.7+1.17.1
	- cardinal-components-base@3.0.0
	- cardinal-components-entity@3.0.0
	- charm@3.3.2
	- cherishedworlds@2.0.1-1.17.1
	- cloth-api@2.0.54
	- clumps@fabric-1.17.1-7.0.4
	- croptopia@1.6.0
	- ctm@0.5.0+1.17
	- customskinloader@14.13-SNAPSHOT-282
	- deathlog@0.1.3
	- dml-refabricated@0.4.4-beta
	- dmlsimulacrum@1.0.2
	- enhancedblockentities@0.4.1+1.17
	- expandedstorage@7.0.0-alpha.37
	- fabric@0.37.1+1.17
	- fasttransferlib@0.5.6
	- fiber@0.23.0-2
	- flytre_lib@0.2.21
	- imm_ptl_core@0.17
	- imm_ptl_surv_adapt@0.4.0
	- immersive_portals@0.17
	- improved-stations@2.0.7
	- indium@1.0.0+mc1.17.1
	- indrev@1.10.0-alpha.12
	- jankson@3.0.1+j1.2.0
	- java@16
	- kibe@1.8-BETA+1.17
	- ktdatataglib@1.5.4
	- libblockattributes_core@0.9.0
	- libblockattributes_fluids@0.9.0
	- libblockattributes_items@0.9.0
	- libcd@3.0.3+1.16.3
	- libgui@4.1.5+1.17.1
	- libninepatch@1.1.0
	- lithium@0.7.3
	- magna@1.5.5-1.17-pre4
	- megane@5.1.1
	- minecraft@1.17.1
	- mm@2.1
	- mocolors@1.2.2
	- modern_industrialization@0.5.3
	- modmenu@2.0.4
	- mousewheelie@1.7.3+mc1.17.1-pre1
	- namepain@1.4.0
	- nbtcrafting@2.0.19+mc1.17
	- omega-config@1.0.8
	- patchouli@1.17-54-FABRIC
	- playerabilitylib@1.3.0-nightly.1.17-rc1
	- q_misc_util@0.17
	- quarryplus@17.0.334
	- repurposed_structures@2.1.8+1.17.1
	- roughlyenoughitems@6.0.264-alpha
	- slight-gui-modifications@2.0.1
	- sodium@0.3.0+build.529
	- stacc@1.2.3
	- team_reborn_energy@0.1.1
	- trinkets@3.0.2
	- tweed@3.0.0-beta.26
	- wthit@3.8.1
	- xaerominimap@21.14.0
	- xaeroworldmap@1.15.0.1

**Comment by qouteall** [comment]
Does it occur without sodium?

**Comment by lostopkk** [comment]
> Does it occur without sodium?

https://drive.google.com/file/d/1tlYhdcupo0REpIS5RgrKlH1yG2b0Dabk/view?usp=sharing
without sodium video

**Comment by qouteall** [comment]
Does this issue occur with only immersive portals and fabric API? If so it may be a hardware issue. If not it's a mod compatibility issue with another mod. Then try to remove half of the mods until you find which mod it's incompatible with.

**Comment by lostopkk** [comment]
sorry for the delay in answering about this issue, but the incompatibility rolls with Modern industrial, some feature should bug the game's particles.

**Comment by lostopkk** [comment]
![image](https://user-images.githubusercontent.com/50776714/128605078-27b473c6-00ae-48ec-a049-db13fcaa1205.png)
more taking advantage of it, and this black bug that happens?
