### ISSUE TITLE
Nether portal won't link except in vanilla mod

### ISSUE THREAD

**Issue by Chucky2401** [qouteall/ImmersivePortalsMod#803]
Hi,
I just discover this mod, and it seems amazing!

But, I need some help, even if it's possible to solve.

I have a world in 1.16.5 with some nether portals, I duplicate this world to make some test. I have my overworld portal at the coordinate -54 / 8 / 280. And the portal in the Nether at -4 / 110 / 41. Everything link correctly if I set to vanilla mod.
But, If I try the others mods (normal or adaptive) the portals don't link to each other.
I try to change the range to find the other portal, but nothing change.

Is it possible to link my portals in normal or adaptive mod? Both portal are 3x3 size.

Thank you in advance.
Regards

EDIT : My bad... My portal in overworld was 3x4... I change his size to 3x3 and it works... Now I have to found how to "mirror" the portal. Because in the overworld I enter in it from the east side, and I need to go to the west side in the nether.

**Comment by qouteall** [comment]
With `adaptive` mode, lighting the nether portal in overworld and in nether may generate portals with different rotations. You can try to mirror it by lighting it on another side.
