### ISSUE TITLE
[Bug] Incompatible with Carpet

### ISSUE THREAD

**Issue by ImSpaceLover** [qouteall/ImmersivePortalsMod#807]
[crash-2021-08-02_18.57.53-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/6918148/crash-2021-08-02_18.57.53-client.txt)
(https://www.curseforge.com/minecraft/mc-mods/carpet)

**Comment by qouteall** [comment]
https://github.com/gnembon/fabric-carpet/blob/db157447379a487608bbd8e03e3232f1fc5285a6/src/main/java/carpet/mixins/WorldRenderer_creativeNoClipMixin.java#L14

**Comment by qouteall** [comment]
probably fixed in the next version

**Comment by endigma** [comment]
is this fixed?

**Comment by qouteall** [comment]
@endigma you can test it

**Comment by qouteall** [comment]
Close because outdated.
