### ISSUE TITLE
[Bug] [IP:0.90] [MC:1.16.5] Breaks Tron Cycles Datapack

### ISSUE THREAD

**Issue by Merith-TK** [qouteall/ImmersivePortalsMod#808]
```yaml
Minecraft: 1.16.5
Fabric:    0.11.6
FabricAPI: 0.37
Immersive: 0.90
```

https://mclo.gs/0VGCiXj What happens WITH immersive portals, 
https://mclo.gs/FQTAyWu What happens WITHOUT immersive portals

```md
# Actions Taken on World Gen
1. Create Superflat world
2. Put Datapack in world/datapacks
3. /datapack list
4. /datapack enable (the datapack)
5. /difficulty peaceful
6. /function lj:rez/batons/4
7. Attempt to use baton to fly with 4th Gen Light Jet
```

[Tron Light Cycles Datapack](https://github.com/Flubberschnub/light-cycles)
[Tron Light Cycles ResourcePack](https://github.com/Flubberschnub/Light-Cycle-Resources)

Without Immersive portals, the Datapack allows me to spawn in a Light Jet and fly around, 

With Immersive portals the jet does not even attempt to load, it will play load sound, and entities will start to spawn, but then it just dies

**Comment by qouteall** [comment]
Does this issue occur in the latest 1.17.1 version?

**Comment by Merith-TK** [comment]
Unknown, As I do not have access to the 1.17 datapack for the Tron Cycles.

**Comment by qouteall** [comment]
1.16 datapacks probably work in 1.17

**Comment by qouteall** [comment]
Maybe related with some edge case entity tracking mechanics that IP changed

**Comment by Merith-TK** [comment]
Potentially, but its odd that it doesnt break Light Cycles as well as Jets. It only breaks jets and `lc:the_grid` dimension.

**Comment by qouteall** [comment]
Close because outdated.
