### ISSUE TITLE
portal linking 

### ISSUE THREAD

**Issue by Dionvs** [qouteall/ImmersivePortalsMod#809]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* Provide instructions for how to reproduce the issue. Include the minecraft version and mod version.
* Forge version issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues
* If it's a mod compatibility issue, post that mod's link and open another issue on that mod
v0.10 minecraft 1.17:

when I link the portal to the correct coörds, it creats a new portal at a random place in the world, I create a portal in the overworld.
then break the one in the nether, move it to the coörds devided by 8 and light it. it should connect, but it creates a new portal in the overworld.

**Comment by qouteall** [comment]
Are you sure that the two obsidian frames have the same shape and orientation?

**Comment by joshcangit** [comment]
This mod can cause breaking the portal to also break linkage.

If I relight the same portal, it will link to a new portal unless `netherPortalMode` value to `vanilla`.

**Comment by qouteall** [comment]
@joshcangit an see-through nether portal cannot link to a vanilla portal. an see-through nether portal can link to an empty obsidian frame

**Comment by joshcangit** [comment]
I don't mean linking portals made under different modes.

I mean when I light a **see-through** portal, a 2<sup>nd</sup> portal is made in the Nether. If I deactivated the 1<sup>st</sup> portal, the 2<sup>nd</sup> portal won't link back anymore. If I relight the 1<sup>st</sup> portal, a 3<sup>rd</sup> portal spawns and if I light the 2<sup>nd</sup> as well, I get 4 portals. All under the same mode e.g. `normal`.

When I light a `vanilla` portal, a 2<sup>nd</sup> portal is made. If I deactivate then relight the 1<sup>st</sup> portal, it links back to the 2<sup>nd</sup> portal. No extra portals. No matter how many times I relight the same 1<sup>st</sup> portal.

**Comment by qouteall** [comment]
@joshcangit I see. Upload the world for me to debug it. Are you using any datapack to change world height?

**Comment by joshcangit** [comment]
I can't upload it but I have a link to my folder of 2 world saves.
[Google Drive folder](https://drive.google.com/drive/folders/1kQVhI8iD7eUxkRdxwR8F4qZMLly_YFPE?usp=sharing)
They don't have any datapacks. Also I'm thinking of removing that link some time soon.

Anyway, I think I know the problem. It seems that disabling `activeLoading` also stops portals from reconnecting.
The wiki did warn about this.
> (If this is disabled, nether portal linking may not work normally.)

I think it should be that nether portal linking **will** not work normally. Although it still works with `activeLoading` disabled albeit only for active portals.

**Comment by qouteall** [comment]
@joshcangit If you does not experience server lag you don't need to disable activeloading

**Comment by qouteall** [comment]
Close because outdated.
