### ISSUE TITLE
Crashed while enter a dim stack enabled world, so i disable dim stack but crashed after open nether portol.

### ISSUE THREAD

**Issue by leon7104** [qouteall/ImmersivePortalsMod#812]
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/6932541/latest.log)

**Comment by qouteall** [comment]
First, this mod is not yet compatible with Iris. Another issue is that adventurez mod is trying to spawn entity in world gen thread. Spawning entity in non-server thread is illegal in vanilla but vanilla does not detect this issue.

**Comment by leon7104** [comment]
i see..
