### ISSUE TITLE
i cant see through portals

### ISSUE THREAD

**Issue by MinecraftFabricEnjoyer** [qouteall/ImmersivePortalsMod#814]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* Provide instructions for how to reproduce the issue. Include the minecraft version and mod version.
* Forge version issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues
* If it's a mod compatibility issue, post that mod's link and open another issue on that mod

**Comment by qouteall** [comment]
1. Make sure that you installed the mod.
2. After installing this mod vanilla portals won't be changed, you need to light new portals

**Comment by RobinYH** [comment]
Are you using shaders? If so, that's the problem.

**Comment by MinecraftFabricEnjoyer** [comment]
Im not

**Comment by qouteall** [comment]
Close because outdated.
