### ISSUE TITLE
Immersive Portals crashing

### ISSUE THREAD

**Issue by Kenn-Guilstorf-Jr** [qouteall/ImmersivePortalsMod#816]
I updated Immersive Portals this morning to the latest build and it continues to crash. I'm using the CurseForge Loader so I can STOP the crash by disabling Immersive Portals.

Immersive portals worked in the last patch (not sure the version) flawlessly. I thought this might be an issue with Lithium (I read about the possible memory leak) but disabling Lithium didn't resolve the issue.

I've copied the crash log to https://pastebin.com/Jhd1Pg5T. I hope this helps. Obviously, this could be an issue with my installation - but I've not modified anything from the CurseForge install.

Thank you.

**Comment by Kenn-Guilstorf-Jr** [comment]
Further information: I went and disabled all add-ins and turned them on one by one. The problem appears to be a compatibility issue with gnembon's Carpet or Carpet Extra. Not sure it's worth fixing the incompatibility - I don't know how many people use gnembon's add-in but I can swap it on (and Immersive Portals off) when I'm doing testing of farms and so on.

**Comment by qouteall** [comment]
Does this version crash with carpet? https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.20-1.17

**Comment by qouteall** [comment]
Close because outdated.
