### ISSUE TITLE
Failed Mixin Apply With Iris's Sodium (1.17)

### ISSUE THREAD

**Issue by MindForged** [qouteall/ImmersivePortalsMod#817]
Crashes the instant i try to connect with server. Works perfectly if I disable Iris (the most recent release). Seems to be this bit:
`Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [imm_ptl_sodium.mixins.json:MixinSodiumChunkProgram] from phase [DEFAULT] in config [imm_ptl_sodium.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)`

[crash-2021-08-07_12.27.08-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/6949604/crash-2021-08-07_12.27.08-client.txt)

**Comment by qouteall** [comment]
Use this version of iris and iris sodium https://github.com/qouteall/Iris/releases/tag/ipc1.1.1_1

**Comment by MindForged** [comment]
Oh dang, I cant since the newest IP release is 1.17.1, but the server is minecraft 1.17 :(
