### ISSUE TITLE
i cant join single player worlds

### ISSUE THREAD

**Issue by Yoreni** [qouteall/ImmersivePortalsMod#823]
when i open a single player world it loads then i get the disconnected screen and then i get taken to the server lists.
when its run on a server it doesnt happen
lithim is not installed.
my log file is attached i could not put it in paste bin cos it was too big
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/7012652/latest.log)

**Comment by qouteall** [comment]
Does this issue occur with this version? https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.21-1.17

**Comment by Yoreni** [comment]
thank you the new version has made your error go away
