### ISSUE TITLE
Small and big portals won't link

### ISSUE THREAD

**Issue by ninjaKATTguy** [qouteall/ImmersivePortalsMod#829]
Whenever I try to make a big portal link to a small one, it just creates a new portal.

**Comment by ImSpaceLover** [comment]
the portals should have the same aspect ratio to connect

**Comment by ninjaKATTguy** [comment]
what does that mean?

**Comment by qouteall** [comment]
first make sure that you are using mc 1.16.x or 1.17.x. Then you need to make two compatible shapes. A 2x2 can connect to 3x3 but not 2x3

**Comment by ninjaKATTguy** [comment]
Oh. I was using a 2x1 and a 3x2.
