### ISSUE TITLE
Nether appearing under Overworld

### ISSUE THREAD

**Issue by gustasmarcinkevicius** [qouteall/ImmersivePortalsMod#835]
Version: 1.17
Launcher: Official
Mod version: 0.10
OS: macOS High Sierra

So, I was playing with the Immersive Portals mod and I made a cave. I dig down, I see obsidian. I get the achievement Ice Bucket Challenge. I dig down more, my Y level goes from -1 to 128 instantly. I get the achievement We Need To Go Deeper, I freak out. I dig down deeper and I fall into the Nether.

**Comment by CaitlynMainer** [comment]
That sounds like you have Dimension stacking turned on.
https://github.com/qouteall/ImmersivePortalsMod/wiki/Dimension-Stack

**Comment by qouteall** [comment]
Did you enable dimension stack during world creation? If not it may be a bug.
