### ISSUE TITLE
Rendering broken with Iris&Sodium

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#837]
Front clipping, multi portal rendering

**Comment by Zxurian** [comment]
let me know if this isn't related, and I'll open a new issue.

Just tried latest ImmersivePortalsMod v0.24-1.17 and while in use, chests/signs dissappearing when a portal frame is in line of sight, then reappearing when back in sight.

**Comment by DragonEggBedrockBreaking** [comment]
Latest commits of iris + sodium fork + immersive portals crashes. All three mods need to be present and a shader needs to be loaded (tested with complementary and sildur’s). Crash report: https://gist.github.com/DragonEggBedrockBreaking/b7cf9c768627d7ef89c0ffb5de01cb32

**Comment by DragonEggBedrockBreaking** [comment]
> Latest commits of iris + sodium fork + immersive portals crashes. All three mods need to be present and a shader needs to be loaded (tested with complementary and sildur’s). Crash report: https://gist.github.com/DragonEggBedrockBreaking/b7cf9c768627d7ef89c0ffb5de01cb32

Update:  new commit attempting to fix the crash on iris’ 1.16 branch: 
https://github.com/IrisShaders/Iris/commit/2cce055d90f17402f41ec5514e55aac965ac47a8

**Comment by AlsoSylv** [comment]
Crash was fixed already, commited to 1.16 and merged up for safety
