### ISSUE TITLE
Fabric version on curseforge doesn't have fabric category

### ISSUE THREAD

**Issue by 1point7point4** [qouteall/ImmersivePortalsMod#838]
The mod's [fabric version](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod) doesn't have the _Fabric_ and _Server Utility_ categories. Adding it will make it easier for users to find the mod. Phanlash brought this up [here](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod?comment=1526).

**Comment by 1point7point4** [comment]
(It can also go in _Server Utility_).

**Comment by qouteall** [comment]
I didn't find the Fabric category in CurseForge. And this mod is not a server utility, both the client and the server should install the mod to work.

**Comment by froyo4u** [comment]
I think to get the Fabric category you have to mark the files as using Fabric in the mod loader part

**Comment by K0-RR** [comment]
@1point7point4 @MeowMC Fabric category was removed by CursedForge a few days ago. Just look at other Fabric mods.
