### ISSUE TITLE
Significant FPS Drop

### ISSUE THREAD

**Issue by StealthMeister1** [qouteall/ImmersivePortalsMod#842]
The portal will drop my FPS from 300+ in a superflat world to 3 or less in a heartbeat. This only happens when I look at it though. Once I look away, my FPS goes back to normal.

EDIT: So it seems as though the problem is the shaders. I removed it and the FPS is normal again. However, it's a great shame since shaders is such a nice thing to have. I'd rather not disable it if I don't have to.
![2021-09-04_11 15 59](https://user-images.githubusercontent.com/12484573/132101355-36c6d621-eb2c-4638-bb46-e5a15d69c3a3.png)
![2021-09-04_11 16 11](https://user-images.githubusercontent.com/12484573/132101356-2688a377-4831-4016-8f7a-00296ae3765a.png)

**Comment by qouteall** [comment]
The current version of Iris is incompatible and the next version of Iris will be compatible. You can use https://github.com/qouteall/Iris/releases/tag/ipc1.1.1_1 for now
