### ISSUE TITLE
Crash loading portal

### ISSUE THREAD

**Issue by cootshk** [qouteall/ImmersivePortalsMod#844]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* Provide instructions for how to reproduce the issue. Include the minecraft version and mod version.
* Forge version issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues
* If it's a mod compatibility issue, post that mod's link and open another issue on that mod

minecraft version: 1.17.1
type: fabric
mods:  
        - appleskin@mc1.17-2.0.0
        - architectury@2.1.20
        - authme@1.5.0
        - autoconfig1u@3.3.1
        - automated_crafting@1.3.24+MC1.17-1.17.1
        - bclib@0.2.0
        - betterend@0.10.2-pre
        - betternether@5.1.3
        - blue_endless_jankson@1.2.1
        - cleancut@1.17-4.0-fabric
        - cloth-basic-math@0.5.1
        - cloth-config2@5.0.34
        - com_electronwill_night-config_core@3.6.3
        - com_electronwill_night-config_toml@3.6.3
        - com_moandjiezana_toml_toml4j@0.7.2
        - couplings@1.5.0+1.17
        - crowdin-translate@1.3+1.17
        - diggusmaximus@1.4.5-1.17
        - disable_custom_worlds_advice@1.3
        - dynamicfps@2.0.4
        - fabric@0.36.1+1.17
        - fabric-api-base@0.3.0+a02b446313
        - fabric-api-lookup-api-v1@1.2.0+2b5c62d013
        - fabric-biome-api-v1@3.1.11+c345aea813
        - fabric-blockrenderlayer-v1@1.1.5+a02b446313
        - fabric-command-api-v1@1.1.2+6cefd57713
        - fabric-commands-v0@0.2.2+92519afa13
        - fabric-containers-v0@0.1.12+a02b446313
        - fabric-content-registries-v0@0.2.2+a02b446313
        - fabric-crash-report-info-v1@0.1.5+be9da31013
        - fabric-dimensions-v1@2.0.11+6cefd57713
        - fabric-entity-events-v1@1.1.0+a02b446313
        - fabric-events-interaction-v0@0.4.9+a722d8c013
        - fabric-events-lifecycle-v0@0.2.1+92519afa13
        - fabric-game-rule-api-v1@1.0.7+6cefd57713
        - fabric-item-api-v1@1.2.4+a02b446313
        - fabric-item-groups-v0@0.2.10+b7ab612113
        - fabric-key-binding-api-v1@1.0.4+a02b446313
        - fabric-keybindings-v0@0.2.2+36b77c3e13
        - fabric-lifecycle-events-v1@1.4.4+a02b446313
        - fabric-loot-tables-v1@1.0.4+a02b446313
        - fabric-mining-levels-v0@0.1.3+92519afa13
        - fabric-models-v0@0.3.0+a02b446313
        - fabric-networking-api-v1@1.0.12+6cefd57713
        - fabric-networking-blockentity-v0@0.2.11+a02b446313
        - fabric-networking-v0@0.3.2+92519afa13
        - fabric-object-builder-api-v1@1.10.9+b7ab612113
        - fabric-object-builders-v0@0.7.3+a02b446313
        - fabric-particles-v1@0.2.4+a02b446313
        - fabric-permissions-api-v0@0.1-SNAPSHOT
        - fabric-registry-sync-v0@0.7.10+e2961fee13
        - fabric-renderer-api-v1@0.4.4+5f02c96913
        - fabric-renderer-indigo@0.4.8+a02b446313
        - fabric-renderer-registries-v1@3.2.0+a02b446313
        - fabric-rendering-data-attachment-v1@0.1.5+a02b446313
        - fabric-rendering-fluids-v1@0.1.13+a02b446313
        - fabric-rendering-v0@1.1.2+92519afa13
        - fabric-rendering-v1@1.6.0+a02b446313
        - fabric-resource-loader-v0@0.4.7+b7ab61213d
        - fabric-screen-api-v1@1.0.4+198a96213d
        - fabric-screen-handler-api-v1@1.1.8+a02b446313
        - fabric-structure-api-v1@1.1.12+6cefd57713
        - fabric-tag-extensions-v0@1.1.4+a02b446313
        - fabric-textures-v0@1.0.6+a02b446313
        - fabric-tool-attribute-api-v1@1.2.12+b7ab612113
        - fabric-tpa@3.0.1
        - fabricloader@0.11.6
        - fallingtree@2.12.1
        - fiber@0.23.0-2
        - flycommand@1.1
        - imm_ptl_core@0.24
        - immersive_portals@0.24
        - inmis@2.3.1-1.17
        - jankson@3.0.1+j1.2.0
        - java@16
        - kyrptconfig@1.1.10-1.17
        - libgui@4.1.2+1.17.1
        - libninepatch@1.1.0
        - libzoomer@0.2.1+1.17
        - lithium@0.7.3
        - minecraft@1.17.1
        - modmenu@2.0.2
        - naturescompass@1.17.1-2.0.0-fabric
        - notenoughcrashes@3.3.1+1.17
        - okzoomer@5.0.0-beta.2+1.17
        - omega-config@1.0.4
        - org_aperlambda_lambdajcommon@1.8.1
        - pehkui@2.2.1+1.14.4-1.17
        - q_misc_util@0.24
        - roughlyenoughitems@6.0.264-alpha
        - sodium@0.3.0+build.5
        - spark@${pluginVersion}
        - spruceui@3.2.0+1.17
        - terraform-biome-builder-api-v1@2.0.0
        - terraform-config-api-v1@2.0.0
        - terraform-overworld-biome-extensions-api-v1@2.0.0
        - terraform-surfaces-api-v1@2.0.0
        - terraform-tree-api-v1@2.0.0
        - terraform-wood-api-v1@2.0.2
        - traverse@4.0.0-beta.2
        - truerooms@1.1.4
        - vanish@1.2.6
        - worldedit@7.2.6+4b2d1e7
        - wthit@3.7.0
        - xaerominimap@21.12.5.1

crashes on loading an end portal (on a server, that mod list is the server and client mod list). The server is still running, and it just says "______ Disconnected". Using the entity loading time, you can type "/kill @e[type=immersiveportals:nether_portal]" to stop your game from crashing on the loading time. Minecraft does not generate a crash report, and notenoughcrashes does not stop the crash.

**Comment by cootshk** [comment]
nevermind, this was an issue with better end and bclib.

**Comment by Ynaught** [comment]
Can you go into more detail on this and how to fix? I think I am having a similar issue.
