### ISSUE TITLE
Chests, signs, banners, shulker boxes etc appearing and disappearing

### ISSUE THREAD

**Issue by ELRATO313** [qouteall/ImmersivePortalsMod#846]
Running 1.17.1 with only Immersive Portals and Fabric  installed and whenever im somewhat near a portal things like chests and signs start to appear and disappear as I move like I could stand on one block and see them clearly and when I move to another one the textures just don't appear at all.

**Comment by qouteall** [comment]
Probably fixed in this version https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.28-1.17

**Comment by ELRATO313** [comment]
> Probably fixed in this version https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.28-1.17

Worked like a charm, cheers!
