### ISSUE TITLE
idk what to title this...

### ISSUE THREAD

**Issue by akselbuch** [qouteall/ImmersivePortalsMod#849]
portals made with this mod active are completely nonfunctional they dont provide a window into the nether and dont even transport you... it spawns the associated blocks but they are just invisible and nothing happens
![2021-09-16_22 22 53](https://user-images.githubusercontent.com/57223619/133682437-a9cdf8d9-223e-4938-bb08-40784dfb2936.png)

**Comment by qouteall** [comment]
Does this issue occur with only immersive portals mod installed?

**Comment by akselbuch** [comment]
i have no clue... but i will check on it now

**Comment by akselbuch** [comment]
it works with only this mod installed but i have no clue what would conflict with this mod in such a way

**Comment by qouteall** [comment]
Close because outdated.
