### ISSUE TITLE
Incompatibility with AdventureZ

### ISSUE THREAD

**Issue by T3CHNERD** [qouteall/ImmersivePortalsMod#853]
Globox1997/AdventureZ#58 https://pastebin.com/iWtNJDBm
Seems to crash on attempting to spawn a secondary entity in the nether while in the overworld with the nether loaded as a global portal. Works fine if I'm already in the nether

**Comment by qouteall** [comment]
AdventureZ is trying to directly spawn an entity to the ServerWorld in a world generation thread which is illegal. Without IP this may cause data race. IP jsut detected it and crash early.
