### ISSUE TITLE
Chests and bed

### ISSUE THREAD

**Issue by brisingr01** [qouteall/ImmersivePortalsMod#854]
When looking in a nether portal the chests and beds in the whichever world your in go invisible. Can still open them and can see the ones on the other side of the portal though
![2021-09-24_19 50 17](https://user-images.githubusercontent.com/91355683/134753913-c4755db9-53ab-4bd7-a2cd-c4b645fc04be.png)
.

**Comment by qouteall** [comment]
are you using the latest version of the mod (0.28)?

**Comment by brisingr01** [comment]
I am using .40.1

**Comment by qouteall** [comment]
This mod does not have 0.20.1 version.

**Comment by brisingr01** [comment]
My bad, it's 0.26

**Comment by brisingr01** [comment]
Just updated to 0.28 and it's better :)
