### ISSUE TITLE
Having multiple portals (3-4+) in FOV causes significant drop in framerate.

### ISSUE THREAD

**Issue by Hurrikane-Nexus** [qouteall/ImmersivePortalsMod#858]
I have a hallway lined with doors (8 of which are portals) and a connector portal (1) to extend the length of the hallway. When I'm looking a just one or no portal(s), framerate is around 60 fps. When looking at 3 the framerate drops to about 40 fps. Looking down the hallway at all 9 portals causes a noticeable drop to 30 fps. Portal density also seems to affect framerate slightly.
(Hallway in question for reference)
![2021-10-08_12 18 13](https://user-images.githubusercontent.com/92169592/136577662-95e97376-fed1-48b3-854e-187ebe48afa5.png)

**Comment by qouteall** [comment]
The text shows that it's rendering 10 portals. Portal-in-portal is also accounted for.
