### ISSUE TITLE
Most Recent Imm Ptl version crashes stand alone on 16.5

### ISSUE THREAD

**Issue by ranenvious** [qouteall/ImmersivePortalsMod#864]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* Provide instructions for how to reproduce the issue. Include the minecraft version and mod version.
* Forge version issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues
* If it's a mod compatibility issue, post that mod's link and open another issue on that mod

MC : 1.16.5
Fabric : 0.12.1
ModLoader : Gdlauncher

Mods : 
    fabric-api-0.40.6+1.16
    immersive-portals-0.99-mc1.16.5-fabric

tested with blank instance : 
 
![image](https://user-images.githubusercontent.com/39103942/136704492-1da4efd2-ba91-4a64-aef9-3e0ecb36ee7f.png)

screen shots of GDlauncher crash pop up : 
 (I tried copying and resizing, nothing worked. Aside from going letter by letter and retyping it this was the best I could do) 
 Images are backwards due to how I exported them
 
[screenshot.zip](https://github.com/qouteall/ImmersivePortalsMod/files/7317803/screenshot.zip)

extra notes : This crash does not have a CR and the log gives minimal information. I have it attached anyway but like I said I don't think it will help.
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/7317805/latest.log)

System details 
[system details.txt](https://github.com/qouteall/ImmersivePortalsMod/files/7317811/system.details.txt)
:

**Comment by qouteall** [comment]
Does it crash with fabric loader 0.11.3 (not fabric api)?

**Comment by qouteall** [comment]
Fixed in 0.101
