### ISSUE TITLE
Any text gets deleted

### ISSUE THREAD

**Issue by Hobo-Ex** [qouteall/ImmersivePortalsMod#867]
no text shows when i have optifabric in the mod folder

**Comment by qouteall** [comment]
Are you using Intel graphics card? Does the issue appear after removing optifine?

**Comment by qouteall** [comment]
To debug this, I need you to find `options.txt` and change `glDebugVerbosity` to 3, then reproduce the bug, then upload `logs/latest.log`

**Comment by qouteall** [comment]
merged to https://github.com/qouteall/ImmersivePortalsMod/issues/916
