### ISSUE TITLE
[suggestion] make nether portal overlay client-side

### ISSUE THREAD

**Issue by wouu** [qouteall/ImmersivePortalsMod#868]
instead of using the nether portal block model, the nether portal overlay texture should be a client-side thing, because it seems to be mainly cosmetic and not affecting the functionality of the portals. this would allow existing portals to get the overlay, allow horizontal portals to have the overlay, and would possibly allow for a slider to change the overlay's transparency, much akin to https://www.curseforge.com/minecraft/mc-mods/betterportals.

**Comment by qouteall** [comment]
The reason for this design is to allow customizing the overlay. For example, using command `/portal set_portal_nbt {overlayBlockState:{Name:"minecraft:diamond_block"},overlayOpacity:0.6,overlayOffset:-0.3}` to a nether portal will give it diamond block overlay.
About the horizontal portal overlay issue: this mod uses existing block models to render the overlay. Vanilla does not have horizontal nether portal block. I am considering fixing it by allowing rotation of block models.

**Comment by wouu** [comment]
> The reason for this design is to allow customizing the overlay. For example, using command `/portal set_portal_nbt {overlayBlockState:{Name:"minecraft:diamond_block"},overlayOpacity:0.6,overlayOffset:-0.3}` to a nether portal will give it diamond block overlay. About the horizontal portal overlay issue: this mod uses existing block models to render the overlay. Vanilla does not have horizontal nether portal block. I am considering fixing it by allowing rotation of block models.

i think the concept of block states as overlays is rather interesting, but would it make more sense for overlays to be textures instead? that way you wouldn't need to worry about horizontal portal block states, and if you wanted a diamond block overlay, you wouldn't have to create a custom block, or even do some hacky stuff with data packs, just to give it the same shape as a nether portal overlay. also, yeah custom portals should still be able to have an nbt tag that specifies their texture overlay, but in my opinion clients should also be able to also specify a "default" overlay which appears if a portal doesn't have an overlay specified, which possibly could be different for separate portal types, for example nether portals have the nether portal overlay, end portals have the end portal overlay, and data driven portals have their own custom overlay? again that would make it so portals don't require being rebuilt just to get their overlay updated, which i imagine would be rather frustrating in singleplayer.

**Comment by qouteall** [comment]
It's being considered.

**Comment by qouteall** [comment]
Already implemented
