### ISSUE TITLE
[minor_change] Use "fuseView" for stacked dimension portal in nether.

### ISSUE THREAD

**Issue by SaberShip** [qouteall/ImmersivePortalsMod#878]
### Tested On
Minecraft: 1.17.1 (Fabric)
immptl: 0.29
With and without Sodium 0.3.2 (No change)

### Behavior
With dimension stack enabled, (Overworld <-> Nether) the overworld sky is visible through unloaded chunks in the nether.

Day:
![Day](https://user-images.githubusercontent.com/6741766/141596339-a075cc3b-898f-4a12-b3cf-020edb834191.PNG)

Night:
![Night](https://user-images.githubusercontent.com/6741766/141596344-424bf3f1-6602-44c3-8812-a227442620fe.PNG)

### Possible Fix:
If fuseView is enabled for the vertical connecting portal, then the sky is not rendered through unloaded chunks.  I used NBTExplorer to quickly modify the test world by enabling fuseView in the global portal data:
![NBT](https://user-images.githubusercontent.com/6741766/141596618-db9e30e4-cd7e-4df1-bb54-befb257114d7.PNG)

After that, the portal is much harder to see through the unloaded chunks:
![Day_Fuze](https://user-images.githubusercontent.com/6741766/141596650-57ea8f4d-27ee-4d6a-9636-ab91981d4306.PNG)

Only when flying and generating new chunks quickly does the portal appear as the dark obsidian at the bottom overworld of chunks:
![Fuze](https://user-images.githubusercontent.com/6741766/141596816-2bcf47d5-8a69-45d4-977f-42c71ec29df0.PNG)

Looking at the code, AltiusInfo.java only sets fuzeView to true if the portal entity's world has skyLight:
```java
public static void initializeFuseViewProperty(Portal portal) {
    if (portal.world.getDimension().hasSkyLight()) {
        if (portal.getNormal().y < 0) {
            portal.fuseView = true;
        }
    }
}
```

It may be good to consider the skylight of the world for both sides of the portal.  I did not want to create a PR for this as I'm not entirely sure of the other purposes for fuseView and if there are any side effects I'm not seeing.

**Comment by qouteall** [comment]
ok I am going to change that.

**Comment by qouteall** [comment]
Fixed, will be in the next version.
