### ISSUE TITLE
Minimum camera depth doesn't scale in scaled portals causing see-through-blocks glitch 

### ISSUE THREAD

**Issue by ImSpaceLover** [qouteall/ImmersivePortalsMod#883]
This is a view near the portal with scale 0.03125 (1/32)
![image](https://user-images.githubusercontent.com/64267797/142758031-ac698839-98a0-41f2-891b-3e02b9cb7803.png)

This is a view after entering the portal. It looks normal because minimum camera depth is set to 0.
![image](https://user-images.githubusercontent.com/64267797/142758055-2cb51f0a-157d-4cde-ac8e-0db340e60959.png)

In-portal camera should have 0 depth or its depth should scale with portal scale because as I can see 0 camera depth causes other unrelated issues.

**Comment by qouteall** [comment]
I made a switch that enable depth clamp but that is only enabled when MiniScaled is presend. Try installing MiniScaled.

**Comment by ImSpaceLover** [comment]
I refactored my building to make it work with bigger scales, so this glitch doesn't occur anymore. But in my opinion fixing this issue in the base mod would be good, because I can't download more mods in my type of projects

**Comment by qouteall** [comment]
Fixed
