### ISSUE TITLE
[Fabric][1.17.1] Crash with Iris-starline when shader is disabled

### ISSUE THREAD

**Issue by DerLeole** [qouteall/ImmersivePortalsMod#884]
This happens in likely all versions released right now (tested up to 0.31) for fabric 1.17.1.

Issue and Reproduction:
Game crashes whenever no shader pack is selected or shaders are turned off. The game works fine when any shader pack is loaded and active. Game crashes only when either a world is loaded without any shader pack, or the shader pack is turned off while playing.

Environment:
This only happens when used in a mod constellation that includes at least:
Immersive Portals 1.17.1 (0.31-)
Sodium 1.17.1 (0.3.2)
Iris-starline (1.1.3 - build 639) ([Link](https://github.com/HyperCubeMC/Iris/actions/runs/1488680406))
Fabric Loader 0.12.5

Detailed Crash Report:
[https://crashy.net/1sisi2lc4kDITwlTQeKw](https://crashy.net/1sisi2lc4kDITwlTQeKw)

Link to issue on Iris-starline page:
[https://github.com/HyperCubeMC/Iris/issues/37](https://github.com/HyperCubeMC/Iris/issues/37)

**Comment by Justsnoopy30** [comment]
This is because iris now uses mixin-based sodium compat, and immersive portals will need changes to work with it.
This shouldn't be specific to starline and should happen on the latest upstream Iris commits too.

**Comment by qouteall** [comment]
only official iris is being considered
