### ISSUE TITLE
incompatible with optifine g8

### ISSUE THREAD

**Issue by yeete183** [qouteall/ImmersivePortalsMod#887]
plz help the mod isnt compatible with optifine hd g8
it just crashes with a blank error
heres the crash log
[crash-2021-11-25_17.44.10-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/7610872/crash-2021-11-25_17.44.10-client.txt)

**Comment by froyo4u** [comment]
This is a known issue and it states on the curseforge page that it only works with G7
