### ISSUE TITLE
Not compatible with Sodium 0.3.3

### ISSUE THREAD

**Issue by coderbot16** [qouteall/ImmersivePortalsMod#889]
https://github.com/qouteall/ImmersivePortalsMod/blob/1.18/imm_ptl_core/src/main/resources/fabric.mod.json#L46

Also, because of how Fabric handles dependency errors with JIJ, this causes `imm_ptl_core` to not be loaded, causing a seemingly unrelated game crash with IESimpleRegistry not being found. To fix this issue and make errors more clear, must ensure that if a JIJ module is required, then an explicit dependency must be specified in the `fabric.mod.json` of the mod using it.

**Comment by qouteall** [comment]
Thanks for informing

**Comment by qouteall** [comment]
Probably fixed in this version https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.32-1.17

**Comment by coderbot16** [comment]
Thanks! A related issue, however, is that IP no longer appear to work properly with Iris 1.1.3 (which is getting released soon). Perhaps this was due to buffer management / clear color changes? Note that the screen appears to be filled with the fog color / clear color of the nether:

![image](https://user-images.githubusercontent.com/22420959/144102467-7d5bad91-af3d-4bed-9d30-bb8bb1632642.png)

![image](https://user-images.githubusercontent.com/22420959/144102487-70401ac2-4efe-4a36-9600-8f90cf382792.png)

If these are issues on my side, please let me know.

**Comment by qouteall** [comment]
~
 @coderbot16 Can you explain briefly how did you change the framebuffer? 
My debugging shows that one of my framebuffer gets cleared somewhere, but other code should not be able to access my framebuffer
Which OpenGL debug tool do you use? ~

nevermind, fixed. I didn't bind to mc framebuffer before invoking world rendering. Then the vanilla clearing will clear my framebuffer.

**Comment by coderbot16** [comment]
Sorry for not responding in time, but yeah, Iris reworked the rendering logic so that we begin shader rendering after all MC frambuffers have been cleared, which must have revealed that issue. Before, the way the code was laid out, we bound the main MC framebuffers after clearing the shader framebuffers, which would hide that issue.
