### ISSUE TITLE
crash when I enter an portal with size difference and on F5 mode

### ISSUE THREAD

**Issue by kenzo11t** [qouteall/ImmersivePortalsMod#891]
I am on 1.17.1 and my minecraft crashes when I enter an portal with size difference and on F5 mode, idk why and my computer is not the problem. on the forge one its can do it, but on the fabric on i dosen´t work. i want to continue playing in fabric but when i do something that uses those problems it just crash.

**Comment by qouteall** [comment]
Use Pehkui 2.2.1 for now

**Comment by qouteall** [comment]
https://github.com/Virtuoel/Pehkui/issues/218
