### ISSUE TITLE
Game crashes when I enter different scaled portals

### ISSUE THREAD

**Issue by HappyAlexRomania** [qouteall/ImmersivePortalsMod#892]
So I made a portal  that should make the player bigger, but when I enter the portal, Minecraft crashes and gives me this error 

The game crashed whilst exception in world tick
Error: java.lang.NoSuchFieldError: BASE
Exit Code: -1

I have:
Pehkui 3.0.0
Fabric API 0.43.1
Immersive Portals 0.33
WorldEdit 7.2.7

Fabric for 1.17.1

**Comment by qouteall** [comment]
Use Pehkui 2.2.1 for now

**Comment by qouteall** [comment]
https://github.com/Virtuoel/Pehkui/issues/218
