### ISSUE TITLE
[v0.33-1.17] Snow renders through mirrors when it should be blocked off

### ISSUE THREAD

**Issue by EeveeEuphoria** [qouteall/ImmersivePortalsMod#895]
Minecraft v1.18, mod version v0.33-1.17
Placing a mirror that uses glass panes, up against a wall (in which the backside is connected with blocks) shows weather effects such as snow in the mirror, when there should not be weather effects present. 
It is occuring when weather is present, it's just that blocks should be blocking the effect.

If you walk right up to the mirror, the weather effect is no longer visible.

![image](https://user-images.githubusercontent.com/8446547/144385853-cad1658e-cc32-4925-bcc1-d43117ca8949.png)
![image](https://user-images.githubusercontent.com/8446547/144385350-f547e45f-53dc-40f8-80ae-3454d1b4ecfb.png)

**Comment by qouteall** [comment]
Seems a weather rendering clipping issue

**Comment by EeveeEuphoria** [comment]
Latest update provided seems to fix it!
