### ISSUE TITLE
1.18 with Pehkui

### ISSUE THREAD

**Issue by BirBop** [qouteall/ImmersivePortalsMod#898]
Linking a 1x3 and 2x6 portal leads to crashing upon entry into either portal. Immersive Portals version 1.0.1 and Pehkui version 3.0.1 for MC version 1.18. Fabric api 0.44.0 for 1.18 also installed. crash occurs both singleplayer or multi.

The game crashed whilst exception in world tick
Error: java.lang.NoClassDefFoundError: net/minecraftforge/fml/config/IConfigSpec
Exit Code: -1

**Comment by BirBop** [comment]
[crash-2021-12-04_03.48.38-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/7653628/crash-2021-12-04_03.48.38-client.txt)

**Comment by qouteall** [comment]
You are using the forge version of Pehkui. Use the Fabric version.
