### ISSUE TITLE
chest visible in front of portal in other dimension

### ISSUE THREAD

**Issue by KingDirp** [qouteall/ImmersivePortalsMod#9]
![2019-08-13_18 45 15](https://user-images.githubusercontent.com/54087347/62987086-73dfd280-bdfb-11e9-8750-1a2ed0e53d2b.png)
![2019-08-13_18 45 35](https://user-images.githubusercontent.com/54087347/62987090-76422c80-bdfb-11e9-847f-64090aad0618.png)

**Comment by qouteall** [comment]
check 0.7 version and see whether this fixed
