### ISSUE TITLE
Instant Crash

### ISSUE THREAD

**Issue by AccursedBird** [qouteall/ImmersivePortalsMod#900]
On 1.16.5, 0.7.3, 0.12.8 Immersive Portals on my Aternos Server, went I went through a Portal my server & game instantly Crashed. My Server Stopped it's self but how did Immersive Portals cause this? (Plus, I have pekuhi on the server.
Here's the crash report (I don't know what any of this means plz simplify it.)
[16:25:01] [Server thread/INFO]: [AccursedBird: Set own game mode to Survival Mode]
256 | [16:29:42] [Server thread/INFO]: [AccursedBird: Applied effect Jump Boost to AccursedBird]
257 | [16:30:01] [Server thread/INFO]: [AccursedBird: Gave 2 [block.immersive_portals.portal_helper] to AccursedBird]
258 | [16:30:13] [Server thread/INFO]: Portal Generation Attempted minecraft:overworld 111 72 -131
259 | [16:30:14] [Server thread/INFO]: Cannot Find Portal Placement on Ground with 3 Spacing
260 | [16:30:14] [Server thread/INFO]: Generated Portal On Ground
261 | [16:30:47] [Server thread/INFO]: [AccursedBird: Gave 2 [block.immersive_portals.portal_helper] to AccursedBird]
262 | [16:30:58] [Server thread/INFO]: Portal Generation Attempted minecraft:overworld 111 72 -131
263 | [16:30:59] [Server thread/INFO]: Cannot Find Portal Placement on Ground with 3 Spacing
264 | [16:30:59] [Server thread/INFO]: Generated Portal On Ground
265 | [16:31:23] [Server thread/INFO]: [AccursedBird: Set own game mode to Creative Mode]
[16:31:48] [Server thread/INFO]: Portal Generation Attempted minecraft:overworld 111 72 -132
267 | [16:31:49] [Server thread/INFO]: Cannot Find Portal Placement on Ground with 3 Spacing
268 | [16:31:49] [Server thread/INFO]: Generated Portal On Ground
269 | [16:32:41] [Server thread/INFO]: Portal Generation Attempted minecraft:overworld 111 72 -132
(Next line is where Game & Server Crashed.)
270 | [16:32:46] [Server thread/ERROR]: Encountered an unexpected exception
271 | java.lang.NoClassDefFoundError: virtuoel/pehkui/api/ScaleTypes
272 | at com.qouteall.hiding_in_the_bushes.PehkuiInterfaceInitializer.doScalingForEntity(PehkuiInterfaceInitializer.java:84) ~[imm_ptl_core-0.102-cf245e0bd4f7d06d.jar:?]
273 | at com.qouteall.hiding_in_the_bushes.PehkuiInterfaceInitializer.onEntityTeleportedServer(PehkuiInterfaceInitializer.java:72) ~[imm_ptl_core-0.102-cf245e0bd4f7d06d.jar:?]
274 | at com.qouteall.immersive_portals.teleportation.ServerTeleportationManager.onPlayerTeleportedInClient(ServerTeleportationManager.java:148) ~[imm_ptl_core-0.102-cf245e0bd4f7d06d.jar:?]
275 | at com.qouteall.hiding_in_the_bushes.MyNetwork.lambda$processCtsTeleport$4(MyNetwork.java:191) ~[imm_ptl_core-0.102-cf245e0bd4f7d06d.jar:?]
276 | at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
277 | at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
278 | at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
279 | at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
280 | at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
281 | at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
282 | at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
283 | at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
284 | at net.minecraft.class_1255.method_5383(class_1255.java:103) ~[intermediary-server.jar:?]
285 | at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:721) ~[intermediary-server.jar:?]
286 | at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
287 | at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
288 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
289 | Caused by: java.lang.ClassNotFoundException: virtuoel.pehkui.api.ScaleTypes
290 | at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_292]
291 | at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
292 | at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_292]
293 | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
294 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.8.jar:?]
295 | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
296 | ... 17 more
297 | [16:32:46] [Server thread/ERROR]: This crash report has been saved to: /server/./crash-reports/crash-2021-12-06_16.32.46-server.txt
(Rest is for Server but you can look at it if you can find what made it crash.)
298 | [16:32:46] [Server thread/INFO]: Stopping server
299 | [16:32:46] [Server thread/INFO]: Saving players
300 | [16:32:46] [Server thread/INFO]: AccursedBird lost connection: Internal Exception: java.lang.StackOverflowError
301 | [16:32:46] [Server thread/INFO]: AccursedBird left the game
302 | [16:32:46] [Server thread/INFO]: Saving worlds
303 | [16:32:46] [Server thread/INFO]: Saving chunks for level 'ServerWorld minecraft:overworld world'/minecraft:overworld
304 | [16:32:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
305 | [16:32:48] [Server thread/INFO]: Saving chunks for level 'ServerWorld minecraft:the_nether world'/minecraft:the_nether
306 | [16:32:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
307 | [16:32:48] [Server thread/INFO]: Saving chunks for level 'ServerWorld minecraft:the_end world'/minecraft:the_end
308 | [16:32:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
309 | [16:32:48] [Server thread/INFO]: Saving chunks for level 'ServerWorld immersive_portals:alternate1 world'/immersive_portals:alternate1
310 | [16:32:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate1): All chunks are saved
311 | [16:32:48] [Server thread/INFO]: Saving chunks for level 'ServerWorld immersive_portals:alternate2 world'/immersive_portals:alternate2
312 | [16:32:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate2): All chunks are saved
313 | [16:32:48] [Server thread/INFO]: Saving chunks for level 'ServerWorld immersive_portals:alternate3 world'/immersive_portals:alternate3
314 | [16:32:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate3): All chunks are saved
315 | [16:32:48] [Server thread/INFO]: Saving chunks for level 'ServerWorld immersive_portals:alternate4 world'/immersive_portals:alternate4
316 | [16:32:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate4): All chunks are saved
317 | [16:32:48] [Server thread/INFO]: Saving chunks for level 'ServerWorld immersive_portals:alternate5 world'/immersive_portals:alternate5
318 | [16:32:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate5): All chunks are saved
319 | [16:32:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
320 | [16:32:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
321 | [16:32:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
322 | [16:32:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate1): All chunks are saved
323 | [16:32:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate2): All chunks are saved
324 | [16:32:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate3): All chunks are saved
325 | [16:32:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate4): All chunks are saved
326 | [16:32:48] [Server thread/INFO]: ThreadedAnvilChunkStorage (alternate5): All chunks are saved
327 | [16:32:48] [Server thread/INFO]: Thread Query Listener stopped

**Comment by qouteall** [comment]
use pehkui 3.0.0. This is due to Pehkui made breaking changes.
