### ISSUE TITLE
Dimension stack incompatibile with Amplified nether.

### ISSUE THREAD

**Issue by Stevekk11** [qouteall/ImmersivePortalsMod#903]
When using dim. stack, the amplified nether is cut off at y128 instead of y256.

**Comment by qouteall** [comment]
Can you provide a link of amplified nether?

**Comment by Stevekk11** [comment]
Here it is https://www.curseforge.com/minecraft/mc-mods/amplified-nether

Dne čt 9. 12. 2021 3:23 uživatel qouteall ***@***.***> napsal:

**Comment by qouteall** [comment]
I didn't find that mod's source code. If that mod is not open-source, I won't fix the compatibility issue.

**Comment by qouteall** [comment]
I am planning to add the ability to control dimension stack y level. That may help this issue

**Comment by Stevekk11** [comment]
The source code is here: [Source](https://discord.gg/zweCAdd)

**Comment by qouteall** [comment]
@Stevekk11 Post the exact link, I don't want to search the whole discord

**Comment by Stevekk11** [comment]
Here, its in the pack
[amplified-nether-e3360.zip](https://github.com/qouteall/ImmersivePortalsMod/files/7705108/amplified-nether-e3360.zip)
:

**Comment by qouteall** [comment]
The first link you provided is a mod, and the second link you provided is a datapack. I assume that you mean that datapack.
This mod reads the dimesion type's `logical_height` field, but that datapack does not change the dimension type (data/minecraft/dimension/the_nether.json has `"type":"minecraft:the_nether"` so it's using the vanilla dimension type). It's that datapack's issue, not IP's issue.
The latest version of IP already supports customizing dimension stack y level so it can work without fixing that datapack
