### ISSUE TITLE
Not working with some mods.

### ISSUE THREAD

**Issue by yodaluca23** [qouteall/ImmersivePortalsMod#911]
I have created a custom mod pack using the CurseForge app but its not working.
I get this error:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'imm_ptl_core'!
Exit Code: -1
I have also attached the crash log

[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/7697797/latest.log)
[crash-2021-12-11_15.39.14-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/7697796/crash-2021-12-11_15.39.14-client.txt)

I have the following mods in the pack:

Carpet
gnembon
fabric-carpet-1.16.5-1.4.44+v210714.jar

Dynamic FPS
juliand665
dynamic-fps-2.0.2.jar

Fabric API
modmuss50
fabric-api-0.42.0+1.16.jar

Immersive Portals
qouteall
immersive-portals-0.102-mc1.16.5-fabric.jar

Lithium (Fabric)
jellysquid3_
lithium-fabric-mc1.16.5-0.6.6.jar

Pehkui
Virtuoel
Pehkui-3.0.0+1.14.4-1.18.jar

Sodium
jellysquid3_
sodium-fabric-mc1.16.5-0.2.0+build.4.jar

**Comment by qouteall** [comment]
Use this sodium https://github.com/qouteall/sodium-fabric/releases
