### ISSUE TITLE
Add way to convert vanilla nether and end portals

### ISSUE THREAD

**Issue by Tachytaenius** [qouteall/ImmersivePortalsMod#92]

**Comment by Tachytaenius** [comment]
I was doing this in the style of your todos, but it's quite impolite. I would understand if this feature wasn't interesting to you.

**Comment by qouteall** [comment]
I am going to make a system to convert vanilla and all other mod's portals automatically

**Comment by qouteall** [comment]
The automatic conversion feature is already implemented. https://github.com/qouteall/ImmersivePortalsMod/wiki/Datapack-Based-Custom-Portal-Generation#convert_vanilla_nether_portaljson-convent-vanilla-nether-portals-into-see-through-portals-if-the-shapes-are-compatible

However, that does not support converting end portals. Automatic end portal conversion is not being planned.

**Comment by ghost** [comment]
Hi qouteall, sorry to necro this old issue but I was curious as to the reasoning behind not supporting end portal conversion? It would certainly be helpful for mods like End Remastered that add their own end portal.

**Comment by qouteall** [comment]
@Brittank88 You can use `imm_ptl:one_way`, see https://qouteall.fun/immptl/wiki/Datapack-Based-Custom-Portal-Generation#other-examples

**Comment by ghost** [comment]
@qouteall I appreciate this but I'm not sure I can.

* The new portal is made out of multiple different blocks.
* Each block needs to be filled with a different item.

I'm not sure if the parameters present allow for me to check for that.

**Comment by qouteall** [comment]
@Brittank88  Unfortunately the custom portal system does not allow that.

**Comment by ghost** [comment]
I'm just surprised there's no way to tell IP to check if there are actual portal blocks at the location where somebody was, right before they changed dimensions, and then just replace them.

**Comment by ghost** [comment]
Apologies, that came off a bit rude. I appreciate features take time - it was a genuine expression of surprise, not an expectation that it exists. This mod is lovely regardless.
