### ISSUE TITLE
Immersive Portals - Crash on Launch

### ISSUE THREAD

**Issue by Kagenokami** [qouteall/ImmersivePortalsMod#921]
Immersive Portals appears to cause a cascade of errors when installed in a modded client, but instead of throwing its own error, it will hide behind other mods. This one says it was caused by balm, but if I remove that it goes to Besmirchment and then continues down the list until most of my mods are deactivated. I only finally realized it was immersive portals when I did a 1 by 1 enable run.

https://pastebin.com/G01DvDBk

**Comment by janIpen** [comment]
Uhhhhh
Shady af

**Comment by Kagenokami** [comment]
> Uhhhhh Shady af

???

**Comment by froyo4u** [comment]
What's shady??

**Comment by janIpen** [comment]
immptl is hiding its errors behind other mods

**Comment by Kagenokami** [comment]
It's more likely that the situation is the presence of Immersive Portals is causing some error that makes the other mods throw errors before it hits Immersive in load-order. So Minecraft thinks it's the other mods and not specifically Immersive Portals. Or something similar.

**Comment by qouteall** [comment]
@TJCgames This is not ImmPtl intentionally hiding errors.

**Comment by qouteall** [comment]
@Kagenokami Firstly use the latest 1.18.1 version and test again.
It's a mixin conflict but the log does not show which mixin ImmPtl is conflicting with, this is weird (maybe the conflicting mod uses asm?)
If the log does not tell which mod it's conflicting with, you need to do a binary search to see which mod ImmPtl is conflicting with. (binary search means removing half of the mods per test)
