### ISSUE TITLE
Broken dimension stack rendering

### ISSUE THREAD

**Issue by Stevekk11** [qouteall/ImmersivePortalsMod#922]
Step 1: turn on dim. stack
Step 2: dig to the bottom of the world
Bug: you can see trough the floor. Image below:
![2021-12-15_20 27 55](https://user-images.githubusercontent.com/77753228/146252806-eb84cffe-3abf-4530-b8bb-96b1237774af.png)

**Comment by Stevekk11** [comment]
Graphic settings do not affect this.

**Comment by qouteall** [comment]
Are you using amplified nether? If so, use command `/portal dimension_stack` and set nether's top y to 256. (This is amplified nether's issue)

**Comment by Stevekk11** [comment]
I will try it.

**Comment by Stevekk11** [comment]
Fixed. Thanks
