### ISSUE TITLE
Rendering issues with the next version of Sodium

### ISSUE THREAD

**Issue by Nitjsefnie** [qouteall/ImmersivePortalsMod#926]
Immersive Portals version: 1.1.4
Minecraft version: 1.18.1
Sodium version: 0.4.0-alpha5
What happens:
![image](https://user-images.githubusercontent.com/75166987/146416380-2332746f-f202-4de9-8491-d050f3a04ee1.png)
![2021-12-16_18 06 49](https://user-images.githubusercontent.com/75166987/146416698-50b95a7e-0141-4bf2-af42-b0249880391b.png)

After a while of testing different debug options, I found out /imm_ptl_client_debug front_clipping_disable nearly fixed it:
![2021-12-16_18 08 35](https://user-images.githubusercontent.com/75166987/146416931-911ecf1b-f9fa-4783-9be2-aed272b5f216.png)
![2021-12-16_18 09 09](https://user-images.githubusercontent.com/75166987/146417035-fe20fd33-cbdc-450e-ac00-48170f22c15d.png)

**Comment by qouteall** [comment]
Are you using intel or AMD vidoecard? Are you using other mods? Does this issue occur without sodium?

**Comment by Nitjsefnie** [comment]
I'm using nVidia GPU. No other mods. Issue doesn't occur without sodium.

**Comment by qouteall** [comment]
I cannot reproduce the issue.

**Comment by qouteall** [comment]
Does this issue occur in a newly created superflat world with only one nether portal? And try to exit the game, delete the config file (reset the config) and re-launch the game.

**Comment by octalide** [comment]
I'll add that with my own testing of this issue, the camera direction seems to be inverted on the other side of the portal, hence the incorrect culling. Should be an easy fix if someone is able to find the source of the bad math.

I'll note that this issue is significantly more visible on larger portals. I ran into it while making a 9x9 portal.

**Comment by octalide** [comment]
Here's a link to a video of the problem in action: https://youtu.be/-aioNnBIua4

**Comment by DaimeneX** [comment]
Can confirm that this issue happens with 1.18.1 Sodium rc1 0.4.0 build as presented in octalide's video.
Got an NVIDIA GTX 1050 Ti

**Comment by qouteall** [comment]
@octalide @DaimeneX It's not recommended to use the version from GitHub actions because they are deemed unstable. I will update ImmPtl to accommodate new sodium only when sodium has a new release

**Comment by DaimeneX** [comment]
@qouteall here's the issue, the last release that is **out on CurseForge** crashes with Immersive Portals installed. The experimental built does not. Even Iris downloads the experimental built since it's made for 1.18.1 :T

**Comment by qouteall** [comment]
@DaimeneX I only checked modrinth so I missed that. Ok I will update it

**Comment by qouteall** [comment]
@DaimeneX I see that the latest sodium on curseforge is still 0.4.0alpha5. The crash is probably not caused by this incompatibility

**Comment by octalide** [comment]
@quoteall Bump what @DaimeneX said, the version I'm using is the only version that I was able to get running with 1.18.1, especially since I'm using replaymod.
