### ISSUE TITLE
Cross-portal collision doesn't work for players with non-downwards gravity

### ISSUE THREAD

**Issue by ImSpaceLover** [qouteall/ImmersivePortalsMod#928]
When you use this mod and gravity changer together, cross-portal collision doesn't always work on players whose gravity is not "down"

**Comment by qouteall** [comment]
Is the issue still persist in the latest version 1.1.7?

**Comment by ImSpaceLover** [comment]
Yes, this issue still occurs

**Comment by qouteall** [comment]
https://discord.com/channels/662271867431682058/671895714527182920/926660144127934474

**Comment by qouteall** [comment]
already fixed
