### ISSUE TITLE
Add bedrock support

### ISSUE THREAD

**Issue by UniqueName12345** [qouteall/ImmersivePortalsMod#929]
Add support for Bedrock 1.17/1.18.

**Comment by DaimeneX** [comment]
Did you just ask for a port of this mod **to a completely different platform?** 🥴 
Mods like this ain't possible on Bedrock! Correct me if I'm wrong.

**Comment by froyo4u** [comment]
> Add support for Bedrock 1.17/1.18.

Literally not even possible

**Comment by qouteall** [comment]
Bedrock version does not support modding.

**Comment by UniqueName12345** [comment]
I mean Addons. Addons are possible.

**Comment by froyo4u** [comment]
> I mean Addons. Addons are possible. 

Addons are just a combination of behavior packs and resource packs. Which do not have the capability of what this mod does

**Comment by UniqueName12345** [comment]
Except? You can jailbreak IOS and possibly get Minecraft Java mods to work on Bedrock edition.

**Comment by IMS212** [comment]
No, bedrock is a completely different game with similar content. The code is completely different.

**Comment by UniqueName12345** [comment]
With some effort, another GitHub repo, and a lot of hard work, you could make a Java mod loader for Bedrock.

**Comment by bravely-beep** [comment]
With some effort, another GitHub repo, and a lot of hard work, you could make a clone of Minecraft from scratch that has Immersive Portals native support, runs on your microwave and is controlled entirely by your brainwaves.

**Comment by qouteall** [comment]
@UniqueName12345 By modding I mean changing Minecraft code. Addons and datapacks can only use limited interfaces provided by vanilla Minecraft and cannot change Minecraft code to do spectacular internal mechanic changes.

**Comment by UniqueName12345** [comment]
> With some effort, another GitHub repo, and a lot of hard work, you could make a clone of Minecraft from scratch that has Immersive Portals native support, runs on your microwave and is controlled entirely by your brainwaves.

Good joke, but that is nearly impossible, if not impossible to do in actuality. Microwaves do not have RAM, where as phones do have ram, so making a Java modloader for bedrock might be closer to reality than making Minecraft from scratch with IP support and all that. Nice joke though.

**Comment by UniqueName12345** [comment]
> @UniqueName12345 By modding I mean changing Minecraft code. Addons and datapacks can only use limited interfaces provided by vanilla Minecraft and cannot change Minecraft code to do spectacular internal mechanic changes.

You can still unload the .apk or .ipa file, modify the code itself to add IP support, then reload the .apk or .ipa file onto Android or IOS. Android is even quicker as you can just put the apk on some apk site and a few people would download it.

**Comment by froyo4u** [comment]
I can't tell if this guy is trolling rn or not

**Comment by UniqueName12345** [comment]
I am not. I am being 100% serious. It might take a long time, but (**nearly**) nothing’s impossible. You might feel like giving up, but it is **almost always** not impossible.

**Comment by qouteall** [comment]
@UniqueName12345 ImmPtl is just a hobby project. I refuse to do this kind of impossible thing.
