### ISSUE TITLE
Chests and shields (at least) display wrong in mirrors

### ISSUE THREAD

**Issue by Tachytaenius** [qouteall/ImmersivePortalsMod#93]
I think it's to do with culling. The wrong faces are being drawn, so chest bottoms z-fight with the floor etc etc.

**Comment by Tachytaenius** [comment]
https://i.imgur.com/1TVhwdk.png screenie

**Comment by qouteall** [comment]
Are you using 1.14?

**Comment by Tachytaenius** [comment]
No, 1.15.2.
The bug appears w/ and w/o optifine.
It's the fabric version btw.
Also render distances are bugged too, walking slightly far away from a mirror on a low render distance causes chunks close to the mirror to not be drawn (within the mirror), and w/o any fog, too.

**Comment by Tachytaenius** [comment]
Also, I just noticed sign text ~~is vampiric~~ doesn't get drawn either.

**Comment by qouteall** [comment]
should be fixed in the newest version
