### ISSUE TITLE
Normal entity sometimes fall through floor after teleporting

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#931]

**Comment by y2k04** [comment]
I experience this too

**Comment by FreqNegative** [comment]
Frequently, cats, dogs, and villagers attempting to pathfind through a portal will cross the threshold and then fall into the floor. Cats and dogs will instantly begin taking suffocation damage. Villagers will either remain stuck in the ground with their head one block above ground, but if touched by the player, they will move and fall again, and then begin suffocating.
