### ISSUE TITLE
Invisible block when deleting end portal

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#939]
Hi when I was messing around I found a bug! (minecraft 1.18.1 mod version 1.1.6) when you use the "delete the portal entity" stick on an end portal a 3x3 area of invisible blocks are spawned! in the F3 menu they are Immersive_portals:nether_portal_block
![Minecraft_ 1 18 1 - Singleplayer 12_22_2021 12_01_09 PM_LI](https://user-images.githubusercontent.com/96546098/147142016-e5276b4e-3ad8-4f29-8840-960e9d6ef8a7.jpg)
k

**Comment by qouteall** [comment]
Well, this is normal behavior. These blocks are used for avoiding players from placing blocks inside.
