### ISSUE TITLE
我的IP崩溃了/My IP is Crashed

### ISSUE THREAD

**Issue by ffffffffawd** [qouteall/ImmersivePortalsMod#943]
在我打开一个传送门的时候，游戏黑屏了(强调：是游戏黑屏)。当我重启游戏再次尝试进入存档时，它崩溃了😭。
以下是崩溃日志/In my activating a portal the game is black. I'm restart the game try to rejoin my save, he Crashed😭. Below is Crash Report 
`---- Minecraft Crash Report ----
// You're mean.

Time: 2021/12/25 下午8:11
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_29470" because "shader" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.65)
	at qouteall.imm_ptl.core.render.ViewAreaRenderer.renderPortalArea(ViewAreaRenderer.java:74)
	at qouteall.imm_ptl.core.render.RendererUsingFrameBuffer.lambda$testShouldRenderPortal$0(RendererUsingFrameBuffer.java:110)
	at qouteall.imm_ptl.core.render.QueryManager.renderAndGetDoesAnySamplePass(QueryManager.java:31)
	at qouteall.imm_ptl.core.render.RendererUsingFrameBuffer.testShouldRenderPortal(RendererUsingFrameBuffer.java:109)
	at qouteall.imm_ptl.core.render.RendererUsingFrameBuffer.doRenderPortal(RendererUsingFrameBuffer.java:61)
	at qouteall.imm_ptl.core.render.PortalRenderer.renderPortals(PortalRenderer.java:111)
	at qouteall.imm_ptl.core.render.RendererUsingFrameBuffer.onBeforeTranslucentRendering(RendererUsingFrameBuffer.java:22)
	at net.minecraft.client.render.WorldRenderer.handler$bml000$onBeforeTranslucentRendering(WorldRenderer:7402)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1378)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1026)
	at net.minecraft.client.render.GameRenderer.redirect$bme000$redirectRenderingWorld(GameRenderer:4622)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:810)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at qouteall.imm_ptl.core.render.ViewAreaRenderer.renderPortalArea(ViewAreaRenderer.java:74)
	at qouteall.imm_ptl.core.render.RendererUsingFrameBuffer.lambda$testShouldRenderPortal$0(RendererUsingFrameBuffer.java:110)
	at qouteall.imm_ptl.core.render.QueryManager.renderAndGetDoesAnySamplePass(QueryManager.java:31)
	at qouteall.imm_ptl.core.render.RendererUsingFrameBuffer.testShouldRenderPortal(RendererUsingFrameBuffer.java:109)
	at qouteall.imm_ptl.core.render.RendererUsingFrameBuffer.doRenderPortal(RendererUsingFrameBuffer.java:61)
	at qouteall.imm_ptl.core.render.PortalRenderer.renderPortals(PortalRenderer.java:111)
	at qouteall.imm_ptl.core.render.RendererUsingFrameBuffer.onBeforeTranslucentRendering(RendererUsingFrameBuffer.java:22)
	at net.minecraft.class_761.handler$bml000$onBeforeTranslucentRendering(class_761.java:7402)
	at net.minecraft.class_761.method_22710(class_761.java:1378)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.redirect$bme000$redirectRenderingWorld(class_757.java:4622)

-- Affected level --
Details:
	All players: 1 total; [class_746['114514'/100, l='ClientWorld minecraft:overworld', x=124.79, y=72.00, z=-321.90]]
	Chunk stats: Client Chunks (ImmPtl) 250
	Level dimension: minecraft:overworld
	Level spawn location: World: (208,66,-240), Section: (at 0,2,0 in 13,4,-15; chunk contains blocks 208,0,-240 to 223,255,-225), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 2475675 game time, 1095262 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1343433560 bytes (1281 MiB) / 2457862144 bytes (2344 MiB) up to 9663676416 bytes (9216 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.42
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8853
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18615.30
	Virtual memory used (MB): 11205.09
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 13.03
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx9216m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.17.1-fabric0.36.1-1.3
		altoclef: Alto Clef ${version}
		appleskin: AppleSkin mc1.17.1-2.2.0
		architectury: Architectury 2.8.46
		baritone: Baritone 1.7.0
		betterdroppeditems: Better Dropped Items 1.3.0-1.17
		betterpingdisplay: Better Ping Display 1.1
		betterthanmending: BetterThanMending 1.3.0
		blue_endless_jankson: jankson 1.2.1
		breakprogress: Break Progress 1.0.1
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.5.0
		caelus: Caelus API 0.0.16-1.17
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cherishedworlds: Cherished Worlds 2.0.1-1.17.1
		chesttracker: Chest Tracker 1.1.1
		clearview: Lava Clear View 2.0.0
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.1.40
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		colytra: Colytra 2.0.0-1.17
		comforts: Comforts 0.0.7-1.17.1
		croparia: Croapria 1.17.1-0.0.4
		dashloader: DashLoader 3.0-rc.11-1.17
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.1
		dev_quantumfusion_hyphen: hyphen 0.1
		diggusmaximus: Diggus Maximus 1.5.1-1.17
		dimores: DimensionalOres 1.0.1
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.17.1
		enchantmentdescriptions: Enchantment Descriptions 4.0.3
		enchlevel-langpatch: Enchantment Level Language Patch 0.2.0
		fabric: Fabric API 0.44.0+1.17
		fabric-api-base: Fabric API Base 0.4.0+cf39a74318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+cb9053d118
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+cf39a74318
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+cf39a74318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+cf39a74318
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+cf39a74318
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+cf39a74318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.1+3447790d18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+cf39a74318
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+cf39a74318
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.1+377137cc18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.12+e99fbe1218
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.4+cf39a74318
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+cf39a74318
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+6617390918
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.2+cf39a74318
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.6+2a2bb57318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.4+cf39a74318
		fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.6+0392f3a618
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+cf39a74318
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+cf39a74318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.6+cf39a74318
		fabric-models-v0: Fabric Models (v0) 0.3.1+cf39a74318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+cf39a74318
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+cf39a74318
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+cf39a74318
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+f907116918
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.7+cf39a74318
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+cf39a74318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+cf39a74318
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+cf39a74318
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+cf39a74318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+cf39a74318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+cf39a74318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+cf39a74318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+cf39a74318
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+377137cc18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.10+f09604ce18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+cf39a74318
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+cf39a74318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.15+cf39a74318
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.3+cf39a74318
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+cf39a74318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.2+cf39a74318
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.3+cf39a74318
		fabricloader: Fabric Loader 0.12.11
		fancymenu: FancyMenu 2.4.2
		fastfurnace: FastFurnace 1.17-3.0
		ferritecore: FerriteCore 3.1.0
		gildedarmor: Gilded Armor 1.3.1+fabric-1.17.1
		gravestones: Simple Gravestones 0.5
		hlandbukkit_c2me-fabric_ver_1_17_libs_: libs 0.2.0+alpha.5.0
		hydrogen: Hydrogen 0.3
		imblocker: IMBlockerFabric 1.0.16
		imm_ptl_core: Immersive Portals Core 0.36
		immersive_portals: Immersive Portals 0.36
		inventoryhud: Inventory HUD + 3.4.1
		inventoryprofilesnext: Inventory Profiles Next 1.2.1
		invmove: InvMove 1.17-0.1.0
		io_airlift_aircompressor: aircompressor 0.21
		iris: Iris 1.1.3
		ironchest: Iron Chests 1.2.0+fabric-1.17.1
		ironfurnaces: Iron Furnaces 1.17.1-2.7.1-fabric
		itemmodelfix: Item Model Fix 1.0.2+1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		konkrete: Konkrete 1.3.0
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lambdabettergrass: LambdaBetterGrass 1.2.1+1.17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 4.1.7+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.3.0+1.17.1
		lithium: Lithium 0.7.5
		magiclib: MagicLib 1.0.0+build.undefined
		malilib: MaLiLib 0.10.0-dev.26
		midnightlib: MidnightLib 0.2.9
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		modmanager: Mod Manager 1.2.0-alpha+1.17
		modmenu: Mod Menu 2.0.14
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		noexpensive: NoExpensive 1.17-Fabric-1.2.0
		notenoughcrashes: Not Enough Crashes 4.1.2+1.17.1
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		picturesign: PictureSign 1.2.0
		polymorph: Polymorph 0.0.14-1.17.1
		prefab: Prefab 2.1.6
		pride: Pride Lib 1.1.0+1.17
		q_misc_util: A Miscellaneous Utility Library from qouteall 0.36
		reeses-sodium-options: Reese's Sodium Options 1.2.3
		right-click-harvest: Right-Click-Harvest 1.1.0
		ring_of_attraction: Ring Of Attraction 1.1.15
		roughlyenoughitems: Roughly Enough Items 6.2.347
		roughlyenoughresources: Roughly Enough Resources 2.2.0
		roughlysearchable: Roughly Searchable 2.2.1+1.17.1
		seamless_loading_screen: Seamless Loading Screen 1.3.6+1.17.1
		searchablecontainers: Searchable Containers 1.2
		shulkerboxtooltip: Shulker Box Tooltip 3.0.4+1.17.1
		simple_backpack: SimpleBackpack 1.1.20
		sit: Sit 1.17.1-13
		smoothboot: Smooth Boot 1.16.5-1.6.0
		smoothswapping: Smooth Swapping 0.4.2
		sodium: Sodium 0.3.3+build.8
		sodium-extra: Sodium Extra 0.3.6
		somnus: Somnus API 0.0.13-1.17.1
		spruceui: SpruceUI 3.3.0+1.17
		stacc: Stacc 1.3.0
		stacker: Stacker 2.1.0
		starlight: Starlight 1.0.0+fabric.73f6d37
		taxfreelevels: Tax Free Levels 1.3
		team_reborn_energy: Energy 2.0.0-beta1
		tooltipfix: ToolTip Fix 1.0.4-1.17.1
		torcherino: Torcherino 15.0.0-alpha.3
		torohealth: ToroHealth Damage Indicators 1.17.1-fabric-12
		tweakeroo: Tweakeroo 0.10.0-dev.20211201.002419
		tweakmyclient: TweakMyClient 1.1.11+925a5bd
		whereisit: Where Is It 1.14.3
		wthit: wthit 3.11.2
		xaerominimap: Xaero's Minimap 21.21.0
		xaeroworldmap: Xaero's World Map 1.18.3
	Launched Version: 1.17.1-Fabric 0.12.11
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) Iris(R) Xe Graphics GL version 3.2.0 - Build 27.20.100.8853, Intel
	Window size: 1920x1001
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: 简体中文 (中国)
	CPU: 8x 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
	Player Count: 1 / 8; [class_3222['114514'/100, l='ServerWorld minecraft:overworld DSREFSFA', x=124.79, y=72.00, z=-321.90]]
	Data Packs: vanilla, Fabric Mods
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Immersive Portals Core (imm_ptl_core)`

**Comment by ffffffffawd** [comment]
IP的版本是最新的 immersive-portals-0.36-mc1.17.1-fabric.jar/The IP ver is new immersive-portals-0.36-mc1.17.1-fabric.jar

**Comment by ffffffffawd** [comment]
我在MC百科看到是国创模组，希望有中文答复/I'm in the mcmod.cn looked this mod is Made in China.I hope the reply is chinese

**Comment by qouteall** [comment]
可能是模组兼容性问题。只用这个模组会崩吗

**Comment by ffffffffawd** [comment]
测试过了
只使用这个模组不会崩
可能是Sodium或Iris Shader的问题

**Comment by qouteall** [comment]
可能不是sodium和iris的问题 ，你用的iris和sodium版本是兼容的（https://qouteall.fun/immptl/wiki/Miscellaneous）
可能是其他模组的问题，建议删除一半模组测试直到找到是哪个模组不兼容

**Comment by ffffffffawd** [comment]
[附图 Imgbb](https://i.ibb.co/5M5g4Qy/image.png)
[附图 SM.MS](https://s2.loli.net/2021/12/28/dT7UJDxpCv3hlkA.png)
就是这两货
qswl

**Comment by ffffffffawd** [comment]
希望早日修复
附下载链接
[两个都在Release的zip里](https://github.com/gaucho-matrero/altoclef)
Github官方开源链接

**Comment by ffffffffawd** [comment]
请在解决之后Close The issues

**Comment by qouteall** [comment]
https://github.com/qouteall/ImmersivePortalsMod/issues/933

**Comment by qouteall** [comment]
我加了breaks，下个版本fabric会显示不兼容

**Comment by ffffffffawd** [comment]
有希望修复吗

**Comment by ffffffffawd** [comment]
元旦快乐 作者
还是那句话
有希望修复吗

**Comment by qouteall** [comment]
希望较小。由于与https://github.com/qouteall/ImmersivePortalsMod/issues/933 重复，关闭。
