### ISSUE TITLE
Lags when going to survival/spectator/adventure mode

### ISSUE THREAD

**Issue by Veis2015** [qouteall/ImmersivePortalsMod#945]
I'm making some escape room map with immersive portals mod, everything is fine when im on creative mode, but when i switch to spectator/adventure/survival, minecraft goes 1fps, I don't really know why.

Minecraft version: 1.16.5
Mod version: 0.101

**Comment by Veis2015** [comment]
oh and map has like 100+ portals, but even with 1 portal its laggy, i have good specs

**Comment by qouteall** [comment]
Are you using other mods?

**Comment by Veis2015** [comment]
Only pehkui

**Comment by qouteall** [comment]
Close because outdated.
