### ISSUE TITLE
MC 1.16.5  Iris mod compatibility

### ISSUE THREAD

**Issue by Elcar903** [qouteall/ImmersivePortalsMod#949]
I cant get MC 1.16.5 to launch when running Immersive Portals and Iris at the same time,

It works with MC 1.17+ but not with MC 1.16.5.

I tried running them one at a time and they both seem to work just fine separately
but together MC will fail to launch.

Is there a way to fix this on 1.16.5?

Thanks for any help on this issue.

**Comment by qouteall** [comment]
Which version of iris are you using?

**Comment by qouteall** [comment]
Unfortunately Iris compatibility in 1.16.5 is not being considered.
