### ISSUE TITLE
Character limit on 'Bedrock Replacement' option for Dimension Stack.

### ISSUE THREAD

**Issue by FloodPhobia** [qouteall/ImmersivePortalsMod#950]
At world creation, when modifying the 'Bedrock Replacement' field in the Dimension Stack settings, the character limit is too short for certain block IDs.

Example:

If I wanted to use 'minecraft:chiseled_polished_blackstone', the character limit would only allow for 'minecraft:chiseled_polished_black'

**Comment by qouteall** [comment]
Mojang made text fields limit 32 chars by default.
Will be fixed in version 1.2.0
