### ISSUE TITLE
Fabric 1.18.1 Issue with removing mod.

### ISSUE THREAD

**Issue by Sephoix** [qouteall/ImmersivePortalsMod#951]
Hello, I would first like to say this mod is very cool and neat to be able to seamlessly travel from the overworld to the nether or end.
Unfortunately though I was having some bad performance issues when using the mod and so I decided to break any existing portals utilizing the mod and removed it from my mods folder. The issue I ran into for existing worlds and even recreated ones is that the nether and end dimension themselves seem to be gone. I can make a frame, light the portal and stand in them like before but it wont take me to the end or nether. Had to fully reinstall minecraft and make a brand new world to use the level.dat to fix the problem. If there is a guide for how to properly uninstall the mod to avoid these issues i did not see it, if there isn't a guide I think it would help not only myself but others who wanted to try the mod and had to remove for one issue or another.

**Comment by qouteall** [comment]
Are you using 1.18.1?

**Comment by qouteall** [comment]
Cannot reproduce this issue. Did you uninstall other dimension mods altogether with ImmPtl?

**Comment by Sephoix** [comment]
yes I am using 1.18.1 with the latest version of fabric and fabric api. I had no other dimension related mod and the issue only came up with loaded worlds when i removed the immersive portals mod and only the mod. The issue affected the world which had used the mod and it persisted to worlds using the "recreate" option. Only with a brand new world only using the seed and moving the level.dat and replacing the old world file did it fix the dimensions and clean up the remnants of the uninstalled mod.

**Comment by qouteall** [comment]
I still cannot reproduce this issue with fabric api 0.45.2 and fabric loader 0.12.12.
Some mods that seems unrelated with dimension may change dimension mechanics. Does this issue occur with only ImmPtl and Fabric API on your side?
