### ISSUE TITLE
Immersive Portals Core - Fabric API Crash 1.18.1 

### ISSUE THREAD

**Issue by TheRanker** [qouteall/ImmersivePortalsMod#952]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* Provide instructions for how to reproduce the issue. Include the minecraft version and mod version.
* Forge version issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues
* If it's a mod compatibility issue, post that mod's link and open another issue on that mod

using Fabric Api ;0.45.1
using immersive-portals-1.1.7-mc1.18.1-fabric.jar

cause this crash 
https://crashy.net/kdUHoA2TtCO8kGvBbBMd
also
https://pastebin.ubuntu.com/p/WKVTNJY8KP/

reverting fabric api  to 0.45.0 fixes the issue

fabrics api changelog -

 Bump versions. (modmuss50)
- Preventing END special events with dimensional api (#1938) (kohanis)
- Registry sync packet compression II (#1853) (deirn)
- Fix attribute modifiers inject limiting other mixins. (#1928) (Jared)
- Use the correct information when throwing Exceptions for failed tests. (#1927) (Jared)

guessing somethign got changed with how immersive portals handels the dimensional api ? 

use fabric 0.12.12. on 1.18.1 

edit:    same crash with 0.45.0 api now. :(

this is used in a modpack im developing, and may take time to figure out the interacting mod causing this.. if it is caused by another mod. 

edit: updated all my mods..not fabric api.. .. works fine.... updated fabric api... fails to create a world.

**Comment by TheRanker** [comment]
reverting back the fabric api update... also keeps the same crash happening.   cant update fabric api or crash will continue to happen even if down graded the api mod.

edit: if i dont update the fabric api... everything works as intended. .... update it.. breaks world load.. reverting the update, also breaks world load.

**Comment by octalide** [comment]
Can confirm the same issue. Have been unable to get everything except a local server instance running with 0.45.1 and immp.

**Comment by qouteall** [comment]
Should be fixed in 1.1.8
