### ISSUE TITLE
iris shader not working

### ISSUE THREAD

**Issue by mmmmmmmmmmmmmmmmaly** [qouteall/ImmersivePortalsMod#955]
I use the seus hrr 2.1 shader and this happened
![2022-01-05_19 46 08](https://user-images.githubusercontent.com/68011857/148310586-bad77abe-c3e3-4717-b65d-8271bccffd0b.png)

**Comment by qouteall** [comment]
What do you mean by hrr?

**Comment by mmmmmmmmmmmmmmmmaly** [comment]
no idea the shader is here https://www.patreon.com/posts/45141775

**Comment by IMS212** [comment]
It’s Half Resolution Rendering, aka rendering at half the resolution and upscaling with tricks to make it look good

**Comment by qouteall** [comment]
PTGI shader is not supported
