### ISSUE TITLE
View bobbing gets reduced/"disabled" with this mod installed

### ISSUE THREAD

**Issue by Slooshie1** [qouteall/ImmersivePortalsMod#964]
When I walk in any direction with this mod enabled, my first person view bobbing doesn't exactly show up. Or rather, it ever so slightly shows, but only the rotation of the camera. The hand doesn't sway, and niether does the camera. I have tried it without this mod and it works fine until I put it on.

**Comment by qouteall** [comment]
Firstly if you are near a portal, view bobbing will be reduced. This aims to make the teleportation seamless.
Are you using other mods (such as sodium, iris or camera-related mods)?

**Comment by Slooshie1** [comment]
> Firstly if you are near a portal, view bobbing will be reduced. This aims to make the teleportation seamless. 

Could you perhaps make this an optional feature, toggleable with mod menu/config file?
> Are you using other mods (such as sodium, iris or camera-related mods)?

I use Sodium and Iris, and I also use Camera Overhaul, but I only use the mouse-look camera tilt. I also have better third person, but I don't think that would change the first person camera.

**Comment by qouteall** [comment]
1. the view bobbing only reduce when you are about 1 block close to a portal, it won't affect you when you are not close to a portal.
2. It may be camera overhaul mod compatibility. Does this issue occur without camera overhaul?

**Comment by Slooshie1** [comment]
It's affecting my camera even when I am dozens of blocks away from a portal, even with camera overhaul disabled

**Comment by qouteall** [comment]
Does this issue occur with only ImmPtl?

**Comment by Slooshie1** [comment]
I found the issue. It only happens when I enable shaders. An Iris developer told me that it is a problem on this mod's end, not Iris's

**Comment by qouteall** [comment]
~I tested it with iris 1.2.0 with BSL shader in mc 1.18.1 and cannot reproduce the issue.~
can reproduce now

**Comment by qouteall** [comment]
Should be fixed in this version https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v1.2.2-1.18

**Comment by Slooshie1** [comment]
Thank you, this new version works perfectly!
