### ISSUE TITLE
Incompatible with optifabric

### ISSUE THREAD

**Issue by WinterNemesis734** [qouteall/ImmersivePortalsMod#972]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* Provide instructions for how to reproduce the issue. Include the minecraft version and mod version.
* Forge version issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues
* If it's a mod compatibility issue, post that mod's link and open another issue on that mod

Here's the issue I am having with launching the game with this mod at the moment I hope any fixes can be implemented

net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Immersive Portals' (immersive_portals) 1.2.3 (C:\Users\blaze\AppData\Roaming\.minecraft\instances\1.18 install\mods\immersive-portals-1.2.3-mc1.18.1-fabric.jar) with any version that is compatible with:
		 - optifabric 1.12.10
Unmet dependency listing:
	 - Mod 'Immersive Portals' (immersive_portals) 1.2.3 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
		 - Mod 'OptiFabric' (optifabric) 1.12.10 is being loaded from C:\Users\blaze\AppData\Roaming\.minecraft\instances\1.18 install\mods\optifabric-1.12.10.jar
Inactive mods:
	 - mod 'Immersive Portals' (immersive_portals) 1.2.3, reason: to replace
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cdc8, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.7+3ac43d95c8, reason: newer version active
	 - mod 'Immersive Portals Core' (imm_ptl_core) 1.2.3, reason: inactive parent mod (nested jar)
	 - mod 'QMiscUtil' (q_misc_util) 1.2.3, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Immersive Portals' (immersive_portals) 1.2.3 (C:\Users\blaze\AppData\Roaming\.minecraft\instances\1.18 install\mods\immersive-portals-1.2.3-mc1.18.1-fabric.jar) with any version that is compatible with:
		 - optifabric 1.12.10
Unmet dependency listing:
	 - Mod 'Immersive Portals' (immersive_portals) 1.2.3 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
		 - Mod 'OptiFabric' (optifabric) 1.12.10 is being loaded from C:\Users\blaze\AppData\Roaming\.minecraft\instances\1.18 install\mods\optifabric-1.12.10.jar
Inactive mods:
	 - mod 'Immersive Portals' (immersive_portals) 1.2.3, reason: to replace
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cdc8, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.7+3ac43d95c8, reason: newer version active
	 - mod 'Immersive Portals Core' (imm_ptl_core) 1.2.3, reason: inactive parent mod (nested jar)
	 - mod 'QMiscUtil' (q_misc_util) 1.2.3, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more

**Comment by qouteall** [comment]
https://qouteall.fun/immptl/wiki/Miscellaneous#optifine-compatibility
