### ISSUE TITLE
Im unable to drink and eat

### ISSUE THREAD

**Issue by TheButterbrotMan** [qouteall/ImmersivePortalsMod#978]
https://bytebin.lucko.me/H4mYNlAplw

**Comment by TheButterbrotMan** [comment]
Run server, join try eat and drink
https://www.curseforge.com/minecraft/modpacks/deathdusk

**Comment by TheButterbrotMan** [comment]
Only occuring in Multiplayer

**Comment by froyo4u** [comment]
No idea, 714 mods is a lot

**Comment by TheButterbrotMan** [comment]
I solved it. Not your mod. Sorry.
