### ISSUE TITLE
Crashing minecraft while playing a game with mod

### ISSUE THREAD

**Issue by buddyarctic** [qouteall/ImmersivePortalsMod#988]
My game kicks me when I play a world or creating a new world and the exit code is -1
Proof:

![image](https://user-images.githubusercontent.com/100022528/155305456-0d450d47-4211-4bb5-a6b8-833d54f204a5.png)

**Comment by qouteall** [comment]
Post the crash report here to diagnose the issue

**Comment by OnionSquid1** [comment]
What mod?

**Comment by BuddyArctic** [comment]
I don't have a crash report and the exit code is -1

**Comment by BuddyArctic** [comment]
And the mod is immersive portals
