### ISSUE TITLE
Minecraft crashes when looking at a mirror in F5 mode

### ISSUE THREAD

**Issue by OnionSquid1** [qouteall/ImmersivePortalsMod#990]
Looking at a mirror in F5 mode crashes the game
How to reproduce:
Step 1. Make a mirror lighting up a glass wall
Step 2. Look at the mirror in F5 mode and move the camera a little bit
Crash Report:
[crash-2022-02-20_14.08.39-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/8104650/crash-2022-02-20_14.08.39-client.txt)

**Comment by OnionSquid1** [comment]
wait let me see if I'm in updated version if not I try the issue on the updated version

**Comment by qouteall** [comment]
Use 1.16.5 and the latest version of immptl and the latest version of pehkui
It's recommended to use mc 1.18.1

**Comment by OnionSquid1** [comment]
I'm not using 1.18.1 because I want fabric tickrate changer

**Comment by OnionSquid1** [comment]
it worked
