### ISSUE TITLE
1.18.1fab

### ISSUE THREAD

**Issue by zhongguolaoxiang** [qouteall/ImmersivePortalsMod#991]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* Provide instructions for how to reproduce the issue. Include the minecraft version and mod version.
* Forge version issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues
* If it's a mod compatibility issue, post that mod's link and open another issue on that mod

**Comment by zhongguolaoxiang** [comment]
简单的说，这个模组的fab1.18.1版并不支持光影，我预装的optfabric1.12.9or 1.12.10全都扑街了。
希望能解决一下。如果没有办法就算了。
以下是报错文件。
使用的光影版本是1.18.1最新的opt，和我预装的回放模组没关系。（我知道两个东西不兼容，但是在不开光影的条件下游戏最起码能运行，所以这一定是开光影的锅。）
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Immersive Portals' (immersive_portals) 1.2.5 (C:\Users\Administrator\AppData\Roaming\.minecraft\mods\沉浸式传送门 (2).jar) with any version that is compatible with:
		 - optifabric 1.12.10
Unmet dependency listing:
	 - Mod 'Immersive Portals' (immersive_portals) 1.2.5 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
		 - Mod 'OptiFabric' (optifabric) 1.12.10 is being loaded from C:\Users\Administrator\AppData\Roaming\.minecraft\mods\optifabric-1.12.10.jar
Inactive mods:
	 - mod 'Immersive Portals' (immersive_portals) 1.2.5, reason: to replace
	 - mod 'cloth-basic-math' (cloth-basic-math) 0.6.0, reason: inactive parent mod (nested jar)
	 - mod 'Cloth Config v6' (cloth-config) 6.0.42, reason: inactive parent mod (nested jar)
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cdc8, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.6+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Events Interaction (v0)' (fabric-events-interaction-v0) 0.4.16+bfa23f17c8, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f314, reason: newer version active
	 - mod 'Fabric Key Bindings (v0)' (fabric-keybindings-v0) 0.2.6+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.10+c15ca335c8, reason: newer version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.18+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Networking (v0)' (fabric-networking-v0) 0.3.5+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'Immersive Portals Core' (imm_ptl_core) 1.2.5, reason: inactive parent mod (nested jar)
	 - mod 'QMiscUtil' (q_misc_util) 1.2.5, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Immersive Portals' (immersive_portals) 1.2.5 (C:\Users\Administrator\AppData\Roaming\.minecraft\mods\沉浸式传送门 (2).jar) with any version that is compatible with:
		 - optifabric 1.12.10
Unmet dependency listing:
	 - Mod 'Immersive Portals' (immersive_portals) 1.2.5 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
		 - Mod 'OptiFabric' (optifabric) 1.12.10 is being loaded from C:\Users\Administrator\AppData\Roaming\.minecraft\mods\optifabric-1.12.10.jar
Inactive mods:
	 - mod 'Immersive Portals' (immersive_portals) 1.2.5, reason: to replace
	 - mod 'cloth-basic-math' (cloth-basic-math) 0.6.0, reason: inactive parent mod (nested jar)
	 - mod 'Cloth Config v6' (cloth-config) 6.0.42, reason: inactive parent mod (nested jar)
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cdc8, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.6+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Events Interaction (v0)' (fabric-events-interaction-v0) 0.4.16+bfa23f17c8, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f314, reason: newer version active
	 - mod 'Fabric Key Bindings (v0)' (fabric-keybindings-v0) 0.2.6+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.10+c15ca335c8, reason: newer version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.18+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Networking (v0)' (fabric-networking-v0) 0.3.5+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'Immersive Portals Core' (imm_ptl_core) 1.2.5, reason: inactive parent mod (nested jar)
	 - mod 'QMiscUtil' (q_misc_util) 1.2.5, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more

**Comment by qouteall** [comment]
本模组不兼容optifine，也不兼容回放模组，但是兼容Iris  https://qouteall.fun/immptl/wiki/Miscellaneous
