### ISSUE TITLE
feat: 3D portal helpers

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#993]
Portal helpers but 3D using box portals.

(I don't know how to explain it further lmfao)

**Comment by qouteall** [comment]
There is MiniScaled mod that helps creating scale boxes https://github.com/qouteall/MiniScaledMod/blob/1.18/README.md

**Comment by ghost** [comment]
I was thinking about having more sizes than 1x1 -> yxy

**Comment by qouteall** [comment]
It's being considered

**Comment by qouteall** [comment]
Making scale box is tricky so it's recommended to use MiniScaled mod
