### ISSUE TITLE
feat: Lighting through portals

### ISSUE THREAD

**Issue by ghost** [qouteall/ImmersivePortalsMod#994]
This could be either really simple or really hard depending on how Minecraft's rendering engine works. (no inbetween).

Sorry if this has been suggested before, I haven't seen any issues on it on this repo.

**Comment by qouteall** [comment]
This probably won't be implemented, reason: https://qouteall.fun/immptl/wiki/Miscellaneous.html#can-fluid-redstone-and-light-work-across-a-portal
