### ISSUE TITLE
Crash with Sodium Extra

### ISSUE THREAD

**Issue by TheButterbrotMan** [qouteall/ImmersivePortalsMod#998]
When i am installing the new version of: https://www.curseforge.com/minecraft/mc-mods/sodium-extra

my modpack is crashing at starting.

https://bytebin.lucko.me/EGpu5qDqhh

**Comment by Redd56** [comment]
Current versions of sodium extras with immersive portals seems to be working, 
Will get version numbers here in a bit when im on my pc
Sodium extra

**Comment by FiddleStickers** [comment]
On version 1.18.2, Sodium extra 0.4.3 (Along with Sodium 0.4.1) works with immersive portals 1.3.6, I've only had rendering issues through the portal after saving and reloading, but no crashes.

There must be another mod in your modpack that conflicts with it.
