### ISSUE TITLE
Hybrid nether portal rendering?

### ISSUE THREAD

**Issue by muzikbike** [qouteall/ImmersivePortalsMod#999]
Not sure if this has been suggested before, but a simple request: there should be some ability to create a portal that renders the other side through it, but still has the purple translucent animated texture. This purple texture plane would be completely intangible and wouldn't impart any of the nausea effects usually seen in vanilla portals.

**Comment by qouteall** [comment]
It's already a thing. You only need to enable nether portal overlay in the config.
https://qouteall.fun/immptl/wiki/Config-Options#enable-nether-portal-overlay
You can access the config by installing mod menu or edit the config file
